### ISSUE TITLE
xaxis.range and yaxis.range in Relayout data get removed on performing other interactions (than zoom)

### ISSUE THREAD

**Issue by Kishanrajput** [plotly/dash#1004]
dash                 1.4.0
dash-core-components 1.3.0
dash-html-components 0.16.0

**bug**
When I zoom in/out on graph, attributes xaxis.range and yaxis.range are created/updated in the RelayoutData dictionary which is expected. But upon performing other interactions (like lasso select, clicking on 'show closest data on hover') it adds respective attributes in RelayoutData but removes existing xaxis.range and yaxis.range.

**Expected behavior**
I think it is more helpful to keep the axis range data unchanged when other interactions are performed. I need the axis range data if my plot is updated after performing other interactions; in order to keep the same zoom level.

This issue can be seen at the dash official User Guide for interactive grapphing - [https://dash.plot.ly/interactive-graphing](https://dash.plot.ly/interactive-graphing)

**Comment by alexcjohnson** [comment]
Accumulating changes in these props is an interesting idea, but for other purposes it's important to know what changed in this particular event. So I don't think we can consider this a bug. The solution we have in mind for this is to create a new partial "live" figure prop https://github.com/plotly/dash-core-components/issues/584

**Comment by Kishanrajput** [comment]
This makes sense, Thanks! 
For now I thing the best solution is to store the zoom level in Store and use them while updating graph with some conditional statements. But for long term, I think the idea of "liveFigure" makes more sense.
