### ISSUE TITLE
Reactive Variables

### ISSUE THREAD

**Issue by kitsonswannff** [plotly/dash#101]
Hi There,

I feel like this might be a trivial question, so sorry in advance for that. I'm trying to figure out how to create a reactive variable in plotly dash similar to this kind of thing in R Shiny https://shiny.rstudio.com/reference/shiny/latest/reactive.html

I want to make a reactive expression that updates a pandas dataframe given user interface selections, and then have each plot react to updates to that dataframe. This way I'm only updating the dataframe once and then the plots are just re-drawing based on the updated data.

Currently I'm updating the dataframe in each callback in response to user interface selections like so and I know its brutally inefficient.

```
@app.callback(
    dash.dependencies.Output('some_plot', 'figure'),
    [dash.dependencies.Input(thing_selector', 'value'),
    dash.dependencies.Input('other_thing_selector', 'value')])
def update_figure(selected_thing, other_selected_thing):

    # update the data
    data = get_data(selected_thing)

    # filter the data to only other selected things
    filtered_data = data[data.otherthing.isin(other_selected_thing)]

    return {
        'data': plot_something(filtered_data),
        'layout': plot_layout(filtered_data)
    }
```

Any help on this would be greatly appreciated. Thanks.

**Comment by chriddyp** [comment]
Hey @kitsonswannff - Good question. For now, the best way to do this would be to update the contents of a hidden div. Check out the second example here: https://github.com/plotly/dash/issues/49#issuecomment-311511286

**Comment by kitsonswannff** [comment]
Thanks for the quick response!
