### ISSUE TITLE
[BUG] No key 'row_id' for active_cell in dash_table.DataTable

### ISSUE THREAD

**Issue by Aryalexa** [plotly/dash#1025]
Hello.
I'm working with `dash_table.DataTable` and reading the docs I found `row_id` in the `active_cell `argument. Using it does't work. Is it not incuded yet? Was it excluded in recent versions? Examples on the Dash web are using it (https://dash.plot.ly/datatable/interactivity)

``` 
- active_cell (dict; optional): The row and column indices and IDs of the currently active cell. 
active_cell has the following type: dict containing keys 'row', 'column', 'row_id', 'column_id'.
Those keys have the following types:
  - row (number; optional)
  - column (number; optional)
  - row_id (string | number; optional)
  - column_id (string; optional)
```

**Context**

-  dash libraries
```
dash                               1.4.1
dash-core-components               1.3.1
dash-daq                           0.2.1
dash-html-components               1.0.1
dash-renderer                      1.1.2
dash-table                         4.4.1

```

**The bug**

It seems `active_cell['row_id']` is not supported.
This is what I get exploring the `active_cell` dictionary

```
', '.join(['{}:{}'.format(k, v) for k, v in active_cell.items()])
# result: row:5, column:4, column_id:Company
```
I also have a screenshot where I force the code to get the value and get an error.

![image](https://user-images.githubusercontent.com/12053430/69435118-429e6900-0d3f-11ea-94d6-a23ba514f813.png)

**Comment by Aryalexa** [comment]
I'll wirte this in the dash-table repository. I'm sorry.

**Comment by rdkbruce** [comment]
Hi, @Aryalexa Do you know if this bug was fixed? I still get this error.

**Comment by Aryalexa** [comment]
The issue on its right place:
https://github.com/plotly/dash-table/issues/651
