### ISSUE TITLE
Error while running Dash app - FileNotFoundError No such file or directory: '../lib/python3.7/site-packages/dash_renderer/prod'

### ISSUE THREAD

**Issue by ravi-data-science** [plotly/dash#1038]
FileNotFoundError No such file or directory: '../lib/python3.7/site-packages/dash_renderer/prod'

**Comment by alexcjohnson** [comment]
I've never seen that error, can you say more? App code that leads to this error, dash version & OS you're using?

**Comment by mark-datanaltek** [comment]
I have experienced the same error.  It was generated by running the first part of the dash tutorial 
https://dash.plot.ly/getting-started

The package was installed with:
conda install -c conda-forge dash-renderer

But the package directory does not contain the missing file or directory?
(base) FM-MBP010:dash-tutorial user$ ls /Users/user/anaconda3/lib/python3.7/site-packages/dash_renderer/
__init__.py               dash_renderer.min.js      prop-types@15.7.2.min.js  react@16.8.6.js
__pycache__/              polyfill@7.7.0.min.js     react-dom@16.8.6.js       react@16.8.6.min.js
dash_renderer.dev.js      prop-types@15.7.2.js      react-dom@16.8.6.min.js   
(base) FM-MBP010:dash-tutorial user$ 

Can you advise about how to proceed to complete the tutorial after a conda installation?

Thanks!

**Comment by derlehner** [comment]
I had the same problem.
In my case, there were incompatible version numbers for dash and dash-renderer installed.
Fixed it by re-installing only dash and letting the versions of the dependent modules be determined automatically, as adviced on the Installation page: https://dash.plot.ly/installation (new feature in version 0.37.0). I think there was a mistake in an old version of this page, where incompatible version numbers were advised to install.

In your case, the following commands should fix the issue:
conda uninstall dash
conda uninstall dash-renderer
conda install dash==1.8.0

If that doesn't work, you could try manually adding the missing directory with the following command:
mkdir -p ../lib/python3.7/site-packages/dash_renderer/prod

**Comment by mark-datanaltek** [comment]
conda install -c conda-forge dash==1.8.0 

returns:
PackagesNotFoundError: The following packages are not available from current channels:

  - dash==1.8.0

Is the current version of dash available via conda?

**Comment by derlehner** [comment]
Seems like 1.7.0 is latest: https://anaconda.org/conda-forge/dash

so either use that one, use pip install or maybe install it without explicitly stating the version number (just conda install dash)

**Comment by kiransamudrala** [comment]
In my case, when I was using pyinstaller to create an executable from my dash-app, I encountered this same issue.
And I had to reference the libraries in the specific conda environment in which I was building my executable.

**Comment by GiancarloRizzo** [comment]
I had the same problem with pip. 
First time I installed with `pip install dash` and tried the example from tutorial. It throws an error that flake7.12. ist missing. 
`~/.local/lib/python3.8/site-packages/dash`

I solved it by doing the following steps. 
1.  install flake: `pip install flake8-polyfill` (newest version)
2. uninstall only dash: `pip uninstall dash`
3. reinstall dash: `pip install dash` 

Before uninstalling dash the folderstructure was different than after reinstalling dash.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
