### ISSUE TITLE
[BUG] Long x-labels are cut off

### ISSUE THREAD

**Issue by soerendip** [plotly/dash#1043]
Long x-labels are cut off.

dash                   1.4.1
dash-core-components   1.3.1
dash-html-components   1.0.1
dash-renderer          1.1.2
dash-table             4.4.1
dash-table-experiments 0.6.0
django-plotly-dash     1.0.1

Chrome 78.0.3904.108 

![Annotation 2019-12-09 164715](https://user-images.githubusercontent.com/3391614/70450290-beb8e080-1aa3-11ea-930d-1f4e0917990f.png)

**Comment by chriddyp** [comment]
By default the margins are fixed, but you can have them expand to the width of the labels by setting `automargin=True` - https://plot.ly/python/setting-graph-size/#automatically-adjust-margins

**Comment by SebastianHeslinRees** [comment]
@chriddyp 
I have tried both increasing the bottom margin space (b=70) and also setting automargin=True, but it still cuts off some of the x-axis labels

<img width="954" alt="xaxis cutoff" src="https://user-images.githubusercontent.com/72191580/154510899-b41d07f4-c31c-41a2-8a24-849c5d322c81.PNG">

```python
@app.callback(
    Output('feature-graphic', 'figure'),
    [Input('slct_xaxis', 'value'),
     Input('select_region', 'value'),
     Input('slct_xaxis2','value'),
     Input('slct_v', 'value')])
def update_graph(slct_xaxis, select_region, slct_xaxis2, slct_v):

    region_mirco_census_filtered_test = region_mirco_census.loc[(region_mirco_census['UK region'] == select_region) & (region_mirco_census[slct_xaxis2].isin(slct_v))]
    region_mirco_census_filtered_uk = region_mirco_census[region_mirco_census[slct_xaxis2].isin(slct_v)]
    
    fig = go.Figure()

    fig.add_trace(
        go.Histogram(
            x=region_mirco_census_filtered_test[slct_xaxis], histnorm='percent', 
            opacity=0.8, name="Region" 
        )
    )

    fig.add_trace(
            go.Histogram(
                x=region_mirco_census_filtered_uk[slct_xaxis], histnorm='percent',  marker=dict(color='rgba(0,0,0,0)', line=dict(width=2, color='red')),
                opacity=0.8, name="UK average" 
            )
    )
    fig.update_layout(barmode='overlay',
                     margin=dict(l=20, r=20, t=20, b=70))
    fig.update_xaxes(categoryorder='category ascending', automargin=True)
    fig.update_yaxes(range=[0, 100])

    #fig.show()
    return fig
```

**Comment by alexcjohnson** [comment]
@SebastianHeslinRees it's not clear what more we could do automatically, but manually you can make the graph height larger (`update_layout(height=1000)`) . You can also add line breaks in the labels. There's no way to have the graph do this automatically (it's not a native capabillity in SVG so we'd need to write the algorithm separately), but inserting `<br>` in the x values at the appropriate locations will wrap them onto multiple lines.

**Comment by SebastianHeslinRees** [comment]
@alexcjohnson Thank you so much for your reply. I was also wondering about something unrelated, regarding the hovermode in plotly can it display other/extra information, for example could I display the histogram count as well as the percentage that it already displays automatically? I've read the documentation but there is not an example of this.

**Comment by alexcjohnson** [comment]
Yes - see `customdata` https://plotly.com/python/hover-text-and-formatting/#adding-other-data-to-the-hover-with-customdata-and-a-hovertemplate

**Comment by SebastianHeslinRees** [comment]
@alexcjohnson Thanks Alex! I am using this code to display count but it seems to be difficult to include the percentage as well, for example when I try to place it in the variable in the bracket (" template string can include variables in %{variable} format ")  it breaks
```python
region_mirco_census_filtered_test = region_mirco_census[region_mirco_census['UK region'] == 'South East']

Region = go.Histogram(
    x=region_mirco_census_filtered_test['Characteristic - Ethnicity'], histnorm='percent',
    opacity=0.4, name="Region" 
)
UK_average = go.Histogram(
    x=region_mirco_census['Characteristic - Ethnicity'], histnorm='percent', marker=dict(color='rgba(0,0,0,0)', line=dict(width=2, color='red')),
    opacity=0.6, name="UK average", hovertemplate =  region_mirco_census['Characteristic - Ethnicity'].value_counts()
)

data = [Region, UK_average]
layout = go.Layout(barmode='overlay')
fig1 = go.Figure(data=data, layout=layout)

fig1.show()
```

![image](https://user-images.githubusercontent.com/72191580/154691983-2038217c-3403-4c9d-b319-516d44711604.png)

**Comment by alexcjohnson** [comment]
Getting a little OT - questions like this are better suited to https://community.plotly.com/, would you mind asking this over there?
