### ISSUE TITLE
[Feature Request] Update Outputs in middle of callback.

### ISSUE THREAD

**Issue by toddkarin** [plotly/dash#1052]
**Problem**
It would often be helpful to update an element in the middle of a callback. A great example if during a long calculation one would like to show results before the full callback is finished, or use a dbc.Loading element to show progress. 

**Possible Solution**
In the _middle_ of a callback, it would be great to have a function that could be called that would change some element before the function is finished. Something like the following would be very helpful:

```python
@app.callback(
    Output("calculation_result", "children"),
    [Input("input", "value")],
)
def run_long_calculation(input):
    # Do really long calculation
    input_data = parse_input_data(input)
    dash.dependencies.Update_Output(id='display_input',children=input_data)
    dash.dependencies.Update_Output(id='progress_bar',value=30)

    # And some more long calculation
    result = run_long_calculation(input_data)
    dash.dependencies.Update_Output(id='progress_bar', value=100)

    return result
```

**Alternatives**
A solution could be to use background processes as suggested here: https://github.com/facultyai/dash-bootstrap-components/issues/137

However this is unnecessarily complicated.

**Comment by kelsiuss** [comment]
I'm also encountering the same issue. Have a callback back that will take some time to complete (transferring files) and would like to update a progress bar so I know how far along in the transfer it is.

**Comment by MM-Lehmann** [comment]
I think this should be requested directly in https://github.com/plotly/dash rather than here

**Comment by kelsiuss** [comment]
FYI to those who are curious: I wasn't able to achieve what I wanted in Dash directly, but with using Redis and Celery to run asynchronous tasks and periodically read the file transfer status from a database, I was able to do what I needed. It's not a great solution, as I have to have another periodic task check on the transfer to ensure nothing failed.

**Comment by marsupialtail** [comment]
is there an update on this issue? Is the workaround still the best way to achieve this right now?

**Comment by gvwilson** [comment]
@T4rk1n is this one still relevant?

**Comment by T4rk1n** [comment]
@gvwilson This can now be done with background callbacks. closing.
