### ISSUE TITLE
[BUG] Treemap Doesn't Render in Dash

### ISSUE THREAD

**Issue by KangboLu** [plotly/dash#1058]
Treemap can be rendered fine when I use it alone with Plotly.
**I used the sample code from treemap documentation, but it doesn't render in Dash. All my other charts render fine in Dash.**

**I have no error message in my web browser console and my terminal console.**

**Plotly.py version**: 4.4.1
**Dash version**:  dash-1.7.0, dash-core-components-1.6.0, dash-html-components-1.0.2, dash-renderer-1.2.2, dash-table-4.5.1

**Any help please? I was thrilled with the Treemap finally implemented in plotlt, but I am quite upset that I can't use it in Dash.**

**Screenshots of code and the plot:**
![image](https://user-images.githubusercontent.com/17485959/71599062-205eee80-2b28-11ea-91c1-dc4f7f4578e1.png)

![image](https://user-images.githubusercontent.com/17485959/71599088-34a2eb80-2b28-11ea-9a4b-700e0c5e7509.png)

**Comment by KangboLu** [comment]
It takes longer to render. It worked now.

**Comment by s3630237** [comment]
Hi @KangboLu , did you find a solution to this? Im having the exact same problem. The code works in jupyter notebook. If i use return fig within my function in dash it does not render. If i then add fig.show it will render in a seperate html page. For some reason, it does not render within the dashboard.

**Comment by KangboLu** [comment]
> Hi @KangboLu , did you find a solution to this? Im having the exact same problem. The code works in jupyter notebook. If i use return fig within my function in dash it does not render. If i then add fig.show it will render in a seperate html page. For some reason, it does not render within the dashboard.

It works for me now. It's just took longer to render the Treemap. Can you do a screenshot of your code or include your code so that I might be able to help you with your situation?

**Comment by s3630237** [comment]
Hi @KangboLu<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKangboLu&data=02%7C01%7Cs3630237%40student.rmit.edu.au%7C2517380a40274751b74908d8370302b3%7Cd1323671cdbe4417b4d4bdb24b51316b%7C0%7C0%7C637319833404831370&sdata=qOtG7ckn6MXVUYGHM8PduI%2FRnfFcshVG82ZNfAzAc2c%3D&reserved=0>

Thanks for looking at this form, really appreciate it. Still cant work this out. The last function in the code is the update treemap function. Youll see before the return fig statement I have commented the fig.show() statement out. When I enable this, the treemap renders in a separate HTML, but not in the app/ dashboard for some reason. Here is a snapshot of the bottom half of the dashboard, notice the graph below which has not rendered i.e the treemap.

[cid:image001.jpg@01D6698D.18E4C780]

When I enable fig.show(), the treemap appears in a seperate HTML page – but not in the app as above

[cid:image007.jpg@01D6698D.18E4C780]

Here is the code,

import dash
import dash_auth
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output
import plotly.express as px
import plotly.graph_objs as go
import streamlit as st
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
from plotly.utils import PlotlyJSONEncoder
import pandas as pd
import numpy as np
import math
from plotly.subplots import make_subplots
from datetime import date
from datetime import datetime

app = dash.Dash()
colors = {
    'background': '#032037',
    'text': '#CDD5D5'
}

server = app.server

df = pd.read_csv('C:/…….. /df1.csv')
incidents = pd.read_csv('C:/………. Incidents.csv')
incidents['Date'] = pd.to_datetime(incidents['Date'])
incidents['Incident Time'] = pd.to_datetime(incidents['Incident Time'])
incidents['FY'] = incidents['Date'].apply(lambda x: x.year + 1 if x.month > 6 else x.year)
incidents['Qtr'] = pd.PeriodIndex(incidents['Date'], freq='Q-JUN')
incidents['Qtr'] = incidents['Qtr'].astype(str)
incidents['hour'] = incidents['Incident Time'].dt.hour
incidents['Weekday'] = incidents['Date'].dt.weekday
# dic_to_replace = {"FinMonth": {0:'Mon',
# 1:'Aug',
# 2:'Sep',
# 3:'Oct',
# 5:'Nov',
# 6:'Dec',
# 7:'Jan',
# 8:'Feb',
# 9:'Mar',
# 10:'Apr',
# 11:'May',
# 12:'Jun'
# }}
# incidents.replace(dic_to_replace, inplace=True)
incidents['FinWeek'] = incidents['Date'].apply(lambda x: x.week - 26 if x.week > 26 else x.week + 26)
incidents['FinMonth'] = incidents['Date'].apply(lambda x: x.month - 6 if x.month > 6 else x.month + 6)
# dic_to_replace = {"FinMonth": {1:'Jul',
# 2:'Aug',
# 3:'Sep',
# 4:'Oct',
# 5:'Nov',
# 6:'Dec',
# 7:'Jan',
# 8:'Feb',
# 9:'Mar',
# 10:'Apr',
# 11:'May',
# 12:'Jun'
# }}
# incidents.replace(dic_to_replace, inplace=True)
incidents['Total Incidents']=1
incidents['Serious Incident flag'] = incidents['Serious Incident flag'].apply(lambda x: 1 if x =='Y' else 0)
incidents['Incident Forklift flag'] = incidents['Incident Forklift flag'].apply(lambda x: 1 if x =='Y' else 0)
incidents['Fallstock flag'] = incidents['Fallstock flag'].apply(lambda x: 1 if x =='Y' else 0)
incidents['Onsite Flag'] = incidents['Onsite Flag'].apply(lambda x: 1 if x =='Y' else 0)


workHrs = pd.read_csv('C:/……. Worked_Hours_Dash.csv',
                      parse_dates=['Date'], dayfirst=True)

# features = df.columns
metric_list = ['Total Incidents','TRIFR Flag', 'Injury Ilness Flag', 'Serious Incident flag', 'Incident Forklift flag','Fallstock flag','Onsite Flag']
finYr_list = incidents['FY'].unique().tolist()
all_options = {
    'Body Category Lookup': incidents['Body Category Lookup'].unique().tolist(),
    'Injury Cause Categories': incidents['Injury Cause Categories'].unique().tolist(),
    'Incident category lookup': incidents['Incident category lookup'].unique().tolist(),
    'hour': incidents['hour'].unique().tolist(),
    'Weekday': incidents['Weekday'].unique().tolist(),
    'FinWeek': incidents['FinWeek'].unique().tolist(),
    'FinMonth': incidents['FinMonth'].unique().tolist()
}
cat2 = df['state'].unique().tolist()
cat2.append('National')
grouping_list = ['name', 'country', 'state', 'region', 'operations_area', 'function', 'type', 'Location Type',
                 'Incident Department', 'Category', 'Department', 'Sub Department']

graphStyles = ['Bar', 'Markers', 'Lines', 'Lines+Markers']
app.layout = html.Div(style={'backgroundColor': colors['background']}, children=[
    html.H1(children='Safety Quarterly Pack Visualisations', style={
        'textAlign': 'left',
        'color': colors['text'],
        'background-image': 'url(https://1000logos.net/wp-content/uploads/2019/07/Bunnings-Logo.png)'
    }
            ),

    html.Div(children='Dash: A web application framework for Python.', style={
        'textAlign': 'left',
        'color': colors['text']
    }),


    html.Div([
        html.H3('Financial Years:'),
        dcc.Dropdown(
            id='finyr',
            options=[{'label': i, 'value': i} for i in finYr_list],
            multi=True,
            value=[2020, 2019, 2018]
        )
    ],
        style={'width': '20%', 'display': 'inline-block', 'color': colors['text']}),
    html.Div([
        html.H3('Metric:'),
        dcc.Dropdown(
            id='metric',
            options=[{'label': i.title(), 'value': i} for i in metric_list],
            value='TRIFR Flag'
        )
    ],
        style={'width': '20%', 'display': 'inline-block', 'color': colors['text']}),
    html.Div([
        html.H3('Category 1:'),
        dcc.Dropdown(
            id='category1',
            options=[{'label': k, 'value': k} for k in all_options.keys()],
            value='Body Category Lookup'
        )
    ],
        style={'width': '20%', 'display': 'inline-block', 'color': colors['text']}),

    html.Div([
        html.H3('Category 2:'),
        dcc.Dropdown(
            id='category22',
            options=[{'label': k, 'value': k} for k in all_options.keys()],
            value='Injury Cause Categories'
        )
    ],
        style={'width': '20%', 'display': 'inline-block', 'color': colors['text']}),

    html.Div([
        html.H3('Location:'),
        dcc.Dropdown(
            id='category2',
            options=[{'label': i.title(), 'value': i} for i in cat2],
            value='VIC'
        )
    ],
        style={'width': '20%', 'display': 'inline-block', 'color': colors['text']}),

    html.Div([
        dcc.Graph(id='time-series'),
    ], style={'width': '70%', 'display': 'inline-block', 'padding': '0 20'}),

    html.Div([
        dcc.Graph(id='pie'),
    ], style={'width': '30%', 'display': 'inline-block'}),

    html.Div([
        html.H3('Alternate View:'),
        dcc.RadioItems(
            id='altView',
            options=[{'label': k, 'value': k} for k in ['No', 'Yes']],
            value='No'
        )], style={'width': '100%', 'display': 'inline-block', 'color': colors['text']}),

    html.Div([
        dcc.Graph(id='top10'),
    ], style={'width': '50%', 'display': 'inline-block', 'padding': '0 20'}),

    html.Div([
        dcc.Graph(id='time-series2'),
    ], style={'width': '50%', 'display': 'inline-block', 'padding': '0 20'}),

    html.Div([
        html.H3('Alternate View:'),
        dcc.RadioItems(
            id='altView1',
            options=[{'label': k, 'value': k} for k in ['No', 'Yes']],
            value='No'
        )], style={'width': '50%', 'display': 'inline-block', 'color': colors['text']}),
    html.Div([
        html.H3('Alternate View:'),
        dcc.RadioItems(
            id='altView2',
            options=[{'label': k, 'value': k} for k in ['No', 'Yes']],
            value='No'
        )], style={'width': '10%', 'display': 'inline-block', 'color': colors['text']}),
    html.Div([
        html.H3('Y axis:'),
        dcc.Dropdown(
            id='yaxis',
            options=[{'label': k, 'value': k} for k in metric_list],
            value='Injury Ilness Flag'
        )], style={'width': '10%', 'display': 'inline-block', 'color': colors['text']}),

    html.Div([
        html.H3('Bubble Size:'),
        dcc.Dropdown(
            id='bubbleSize',
            options=[{'label': k, 'value': k} for k in metric_list],
            value='TRIFR Flag'
        )], style={'width': '10%', 'display': 'inline-block', 'color': colors['text']}),

    html.Div([
        html.H3('Grouping Variable:'),
        dcc.Dropdown(
            id='groupingVar',
            options=[{'label': k, 'value': k} for k in grouping_list],
            value='name'
        )], style={'width': '10%', 'display': 'inline-block', 'color': colors['text']}),

    html.Div([
        html.H3('Colour Variable:'),
        dcc.Dropdown(
            id='colour',
            options=[{'label': k, 'value': k} for k in grouping_list],
            value='region'
        )], style={'width': '10%', 'display': 'inline-block', 'color': colors['text']}),

    html.Div([
        dcc.Graph(id='heatmap',
                  style={
                      'height': 600,
                      'width': 900,
                      "display": "block",
                      "margin-left": "auto",
                      "margin-right": "auto",
                  }),
    ], style={'width': '50%', 'display': 'inline-block', 'padding': '0 20'}),

    html.Div([
        dcc.Graph(id='bubble-chart',
                  style={
                      'height': 600,
                      'width': 900,
                      "display": "block",
                      "margin-left": "auto",
                      "margin-right": "auto",
                  }),
    ], style={'width': '50%', 'display': 'inline-block', 'padding': '0 20'}),

    html.Div([
        html.H3('Global Grouping:'),
        dcc.Dropdown(
            id='global',
            options=[{'label': k, 'value': k} for k in grouping_list],
            value='region'
        )], style={'width': '10%', 'display': 'inline-block', 'color': colors['text']}),

    html.Div([
        html.H3('Subset 1:'),
        dcc.Dropdown(
            id='subset1',
            options=[{'label': k, 'value': k} for k in grouping_list],
            value='function'
        )], style={'width': '10%', 'display': 'inline-block', 'color': colors['text']}),


    html.Div([
        html.H3('Subset 2:'),
        dcc.Dropdown(
            id='subset2',
            options=[{'label': k, 'value': k} for k in grouping_list],
            value='Location Type'
        )], style={'width': '10%', 'display': 'inline-block', 'color': colors['text']}),

    html.Div([
        dcc.Graph(id='treemap')
    ], style={'width': '100%', 'display': 'inline-block', 'padding': '0 20'}),

],)


@app.callback(
    Output('bubble-chart', 'figure'),
    [Input('metric', 'value'),
     Input('yaxis', 'value'),
     Input('bubbleSize', 'value'),
     Input('colour', 'value'),
     Input('finyr', 'value'),
     Input('category2', 'value'),
     Input('altView2', 'value'),
     Input('groupingVar', 'value')])
def update_bubble_chart(metric_name, yaxis_name, bubbleSize_name, colour_name, finyr_name, category2_name,altView2_name, groupingVar_name):

    if (category2_name == "National"):
        df_s = incidents[incidents['FY'].isin(finyr_name)]
        df_wh = workHrs[workHrs['FY'].isin(finyr_name)]
    else:
        df_s = incidents[(incidents['state'] == category2_name) & (incidents['FY'].isin(finyr_name))]
        df_wh = workHrs[(workHrs['state'] == category2_name) & (workHrs['FY'].isin(finyr_name))]

    if (altView2_name == "Yes"):

        df_wh = df_wh.groupby(['Cost Centre']).agg(
            {
                'Worked_Hours': sum,
            }).reset_index()

        df_s = pd.merge(df_s,
                        df_wh,
                        left_on='Location Number',
                        right_on='Cost Centre',
                        how='left')

        df7 = df_s.groupby(
            [colour_name, groupingVar_name]).agg(
            {
                metric_name: sum,
                yaxis_name: sum,
                bubbleSize_name: sum,
                'Worked_Hours': 'mean'
            }).reset_index()


        df7['metric_name_ph'] = (df7[metric_name] / df7['Worked_Hours']) * 100
        df7['yaxis_name_ph'] = (df7[yaxis_name] / df7['Worked_Hours']) * 100
        df7['bubbleSize_name_ph'] = (df7[bubbleSize_name] / df7['Worked_Hours']) * 100
        df7.fillna(0, inplace=True)

        fig = px.scatter(df7, x=df7['metric_name_ph'], y=df7['yaxis_name_ph'],
                         size=df7['bubbleSize_name_ph'], color=colour_name,
                         hover_name=groupingVar_name, hover_data=[colour_name], size_max=30)

    else:
        df7 = df_s.groupby(
            [colour_name, groupingVar_name]).agg(
            {
                metric_name: sum,
                yaxis_name: sum,
                bubbleSize_name: sum,
            }).reset_index()
        df7.fillna(0, inplace=True)

        fig = px.scatter(df7, x=metric_name, y=yaxis_name,
                         size=bubbleSize_name, color=colour_name,
                         hover_name=groupingVar_name, hover_data=[bubbleSize_name, colour_name], size_max=20)

    fig.update_layout(legend=dict(
        orientation="v",
        yanchor="top",
        y=1,
        xanchor="right",
        x=1.2,
        font=dict(family="Courier", size=8, color=colors['text'])),
        paper_bgcolor=colors['background'],
        plot_bgcolor=colors['background'],
        # yaxis1=dict(gridcolor = 'rgb(150,150,150)'),
        # xaxis1=dict(gridcolor='rgb(150,150,150)')
    )
    return fig


    # df7 = df7.sort_values([colour_name, groupingVar_name])
    #
    # hover_text = []
    # bubble_size = []
    #
    # for index, row in df7.iterrows():
    #     hover_text.append(('groupingVar_name: {groupingVar_name}<br>' +
    #                        'colour_name: {colour_name}<br>' +
    #                        'metric_name: {metric_name}<br>' +
    #                        'yaxis_name: {yaxis_name}').format(groupingVar_name=row[groupingVar_name],
    #                                                                        colour_name=row[colour_name],
    #                                                                        metric_name=row[metric_name],
    #                                                                        yaxis_name=row[yaxis_name]))
    #     bubble_size.append(math.sqrt(row[bubbleSize_name]))
    #
    # df7['text'] = hover_text
    # df7['size'] = bubble_size
    # sizeref = 2. * max(df7['size']) / (20 ** 2)
    #
    # # Dictionary with dataframes for each continent
    # colour_name_names = df7[colour_name].unique()
    # colour_name_data = {colour_name:df7.query("colour_name == '%s'" %colour_name) for colour_name in colour_name_names}
    # colour_name_data.to_csv('c1.csv')
    # # Create figure
    # fig = go.Figure()
    #
    # for colour_name_name, colour_name in colour_name_data.items():
    #     fig.add_trace(go.Scatter(
    #         x=colour_name[metric_name], y=colour_name[yaxis_name],
    #         name=colour_name_name, text=colour_name['text'],
    #         marker_size=colour_name['size'],
    #     ))
    #
    # # Tune marker appearance and layout
    # fig.update_traces(mode='markers', marker=dict(sizemode='area',sizeref=sizeref, line_width=2))
    #
    # fig.update_layout(
    #     title='Life Expectancy v. Per Capita GDP, 2007',
    #     xaxis=dict(
    #         title='GDP per capita (2000 dollars)',
    #         gridcolor='white',
    #         gridwidth=2,
    #     ),
    #     yaxis=dict(
    #         title='Life Expectancy (years)',
    #         gridcolor='white',
    #         gridwidth=2,
    #     ),
    #     paper_bgcolor=colors['background'],
    #     plot_bgcolor=colors['background'],
    # )

    # fig.update_xaxes(tickangle=45, tickfont=dict(family='Rockwell', color=colors['text'], size=11))
    # fig.update_yaxes(tickfont=dict(family='Rockwell', color=colors['text'], size=11))
    #


@app.callback(
    Output('time-series', 'figure'),
    [Input('metric', 'value'),
     Input('category1', 'value'),
     Input('finyr', 'value'),
     Input('category2', 'value')])
def update_time_series(metric_name, category1_name, finyr_name, category2_name):
    if (category2_name == "National"):
        df_s = incidents[(incidents['FY'].isin(finyr_name))]
    else:
        df_s = incidents[(incidents['state'] == category2_name) & (incidents['FY'].isin(finyr_name))]

    df7 = df_s.groupby(
        ['Qtr', category1_name]).agg(
        {
            metric_name: sum,
        }).reset_index()

    fig = go.Figure()
    for element in df7[category1_name].unique():
        fig.add_trace(go.Scatter(x=df7['Qtr'].unique(),
                                 y=df7[df7[category1_name] == element][metric_name],
                                 mode='lines+markers',
                                 name=element
                                 ))

    fig.update_xaxes(tickangle=45, tickfont=dict(family='Rockwell', color=colors['text'], size=11))
    fig.update_yaxes(tickfont=dict(family='Rockwell', color=colors['text'], size=11))

    fig.update_layout(legend=dict(
        orientation="h",
        yanchor="bottom",
        y=1,
        xanchor="right",
        x=1,
        font=dict(family="Courier", size=12, color=colors['text'])),
        paper_bgcolor=colors['background'],
        plot_bgcolor=colors['background'],
        # yaxis1=dict(gridcolor = 'rgb(150,150,150)'),
        # xaxis1=dict(gridcolor='rgb(150,150,150)')
    )

    return fig


@app.callback(
    Output('top10', 'figure'),
    [Input('metric', 'value'),
     Input('category1', 'value'),
     Input('finyr', 'value'),
     Input('altView', 'value'),
     Input('category2', 'value')])
def update_top10(metric_name, category1_name, finyr_name, altView_name, category2_name):
    workHrs['Date'] = pd.to_datetime(workHrs['Date'])
    workHrs['FY'] = workHrs['Date'].apply(lambda x: x.year + 1 if x.month > 6 else x.year)
    workHrs['Qtr'] = pd.PeriodIndex(workHrs['Date'], freq='Q-JUN')
    workHrs['Qtr'] = workHrs['Qtr'].astype(str)

    if (category2_name == "National"):
        df_b = incidents[(incidents['FY'].isin(finyr_name))]
        df_wh = workHrs[(workHrs['FY'].isin(finyr_name))]
    else:
        df_b = incidents[(incidents['state'] == category2_name) & (incidents['FY'].isin(finyr_name))]
        df_wh = workHrs[(workHrs['state'] == category2_name) & (workHrs['FY'].isin(finyr_name))]

    df9 = df_b.groupby(
        ['Location Number', 'name']).agg(
        {
            metric_name: sum,
        }).reset_index()

    df35 = df_wh.groupby(
        ['Cost Centre']).agg(
        {
            'Worked_Hours': sum,
        }).reset_index()

    df_final = pd.merge(df9,
                        df35,
                        left_on='Location Number',
                        right_on='Cost Centre',
                        how='left')

    df_final['Rate per Hour'] = (df_final[metric_name] / df_final['Worked_Hours']) * 100
    df_final = df_final.nlargest(10, metric_name)

    if (altView_name == "Yes"):
        df_final = df_final.nlargest(10, 'Rate per Hour')

    # fig = make_subplots(specs=[[{"secondary_y": True}]])
    #
    # fig.add_trace(go.Scatter(x=df_final['name'],
    #                          y=df_final[metric_name],
    #                          line=dict(color='royalblue', width=3),
    #                          mode='lines+markers',
    #                          name=metric_name + ", " + category1_name
    #                          ),
    #               )
    #
    # fig.add_trace(go.Bar(x=df_final['name'],
    #                      y=df_final['Rate per Hour'],
    #                      name='Injury Rate (Worked Hours)'),
    #               secondary_y=True,
    #               )
    #
    # fig.update_traces(marker_color='rgb(158,202,225)', marker_line_color='rgb(8,48,107)',
    #                   marker_line_width=1.5, opacity=0.6)
    #
    # fig.update_layout(margin={'l': 40, 'b': 40, 't': 10, 'r': 0}, hovermode='closest')
    # # Set y-axes titles
    # fig.update_yaxes(title_text="<b>primary</b> yaxis title", secondary_y=False)
    # fig.update_yaxes(title_text="<b>secondary</b> yaxis title", secondary_y=True)

    # Creating two subplots
    fig = make_subplots(rows=1, cols=2, specs=[[{}, {}]], shared_xaxes=True,
                        shared_yaxes=False, vertical_spacing=0.001)
    x = df_final['name']
    y_saving = df_final[metric_name]
    y_net_worth = df_final['Rate per Hour']

    # Creating two subplots

    fig.append_trace(go.Bar(
        x=y_saving,
        y=x,
        marker=dict(
            color='rgba(50, 171, 96, 0.6)',
            line=dict(
                color='rgba(50, 171, 96, 1.0)',
                width=1),
        ),
        name='Sites with the highest injury numbers',
        orientation='h',
    ), 1, 1)

    fig.append_trace(go.Scatter(
        x=y_net_worth, y=x,
        mode='lines+markers',
        line_color='rgb(128, 0, 128)',
        name='Top injury rates as a proportion of worked hours, by site',
    ), 1, 2)

    fig.update_layout(
        title='Household savings & net worth for eight OECD countries',
        yaxis=dict(
            showgrid=False,
            showline=False,
            showticklabels=True,
            domain=[0, 0.85],
        ),
        yaxis2=dict(
            showgrid=False,
            showline=True,
            showticklabels=False,
            linecolor='rgba(102, 102, 102, 0.8)',
            linewidth=2,
            domain=[0, 0.85],
        ),
        xaxis=dict(
            zeroline=False,
            showline=False,
            showticklabels=True,
            showgrid=True,
            domain=[0, 0.42],
        ),
        xaxis2=dict(
            zeroline=False,
            showline=False,
            showticklabels=True,
            showgrid=True,
            domain=[0.47, 1],
            side='top',
        ),
        legend=dict(x=0.029, y=1.038, font_size=10),
        margin=dict(l=100, r=20, t=70, b=70),
        paper_bgcolor=colors['background'],
        plot_bgcolor=colors['background'],
    )

    annotations = []

    y_s = y_saving
    y_nw = np.round(y_net_worth, decimals=4)

    # Adding labels
    for ydn, yd, xd in zip(y_nw, y_s, x):
        # labeling the scatter savings
        annotations.append(dict(xref='x2', yref='y2',
                                y=xd, x=ydn - 0.001,
                                text='{:,}'.format(ydn),
                                font=dict(family='Arial', size=12,
                                          color='rgb(128, 0, 128)'),
                                showarrow=False))
        # labeling the bar net worth
        annotations.append(dict(xref='x1', yref='y1',
                                y=xd, x=yd - 5,
                                text=str(yd),
                                font=dict(family='Arial', size=12,
                                          color='rgb(150,150,150)'),
                                showarrow=False))
    # Source
    annotations.append(dict(xref='paper', yref='paper',
                            x=0, y=-0.109,
                            text='"Injury Rates" equal ' +
                                 'Total Injuries for period ' +
                                 'divided by ' +
                                 'Total Worked Hours in period, multiplied by 100',
                            font=dict(family='Arial', size=10, color='rgb(150,150,150)'),
                            showarrow=False))

    fig.update_layout(annotations=annotations)
    fig.update_yaxes(tickangle=45, tickfont=dict(family='Rockwell', color='rgb(150,150,150)', size=11))
    fig.update_xaxes(tickfont=dict(family='Rockwell', color='rgb(150,150,150)', size=11))

    return fig


@app.callback(
    Output('heatmap', 'figure'),
    [Input('metric', 'value'),
     Input('finyr', 'value'),
     Input('category1', 'value'),
     Input('category2', 'value'),
     Input('altView1', 'value'),
     Input('category22', 'value')])
def update_heatmap(metric_name, finyr_name, category1_name, category2_name, altView1_name, category22_name):
    if (category2_name == "National"):
        df_h = incidents[(incidents['FY'].isin(finyr_name))]
    else:
        df_h = incidents[(incidents['state'] == category2_name) & (incidents['FY'].isin(finyr_name))]

    df3 = df_h.groupby(
        [category22_name, category1_name]).agg(
        {
            metric_name: sum,
        }).reset_index()

    df_t1 = df3.pivot(index=category22_name, columns=category1_name, values=metric_name)
    df_t1.fillna(0, inplace=True)
    z = df_t1.values

    fig = go.Figure(data=go.Heatmap(
        z=df3[metric_name],
        x=df3[category1_name],
        y=df3[category22_name],
        hoverongaps=False))

    if (altView1_name == "Yes"):
        fig = go.Figure()
        fig.add_trace(go.Surface(x=df_t1.columns, y=df_t1.index, z=z))
        # fig.update_layout(scene=dict(
        #         xaxis_title='X AXIS TITLE',
        #         yaxis_title='Y AXIS TITLE',
        #         zaxis_title='Z AXIS TITLE'),
        #         width=1200,
        #         height = 800,
        #         margin=dict(r=20, b=10, l=10, t=10))

    fig.update_layout(legend=dict(
        yanchor="bottom",
        y=0,
        xanchor="right",
        x=2,
        font=dict(family="Courier", size=11, color=colors['text'])),
        paper_bgcolor=colors['background'],
        # width=1500,
        # height=800,
        margin=dict(r=10, b=100, l=150, t=50),
        plot_bgcolor=colors['background']
    )
    fig.update_xaxes(tickangle=45, tickfont=dict(family='Rockwell', color=colors['text'], size=11))
    fig.update_yaxes(tickangle=45, tickfont=dict(family='Rockwell', color=colors['text'], size=11))
    # fig.update_zaxes(tickfont=dict(family='Rockwell', color=colors['text'], size=11))

    return fig


# @app.callback(
#          Output('surface', 'figure'),
#         [Input('metric', 'value'),
#          Input('finyr', 'value'),
#          Input('category1', 'value'),
#          Input('category2', 'value'),
#          Input('category22', 'value')])
# def update_3d(metric_name, finyr_name, category1_name, category2_name, category22_name):
#
#     df_t = incidents[(incidents['state'] == category2_name) & (incidents['FY'].isin(finyr_name))]
#     df3 = df_t.groupby(
#         [category22_name,category1_name]).agg(
#         {
#             metric_name: sum,
#         }).reset_index()
#
#     df_t1 = df3.pivot(index=category22_name, columns=category1_name, values=metric_name)
#     df_t1.fillna(0, inplace=True)
#     z=df_t1.values
#
#     fig = go.Figure()
#     fig.add_trace(go.Surface(x=df_t1.columns,
#         y=df_t1.index,
#         z=z
#     ))
#
#     fig.update_layout(scene=dict(
#         xaxis_title='X AXIS TITLE',
#         yaxis_title='Y AXIS TITLE',
#         zaxis_title='Z AXIS TITLE'),
#         width=1200,
#         height = 800,
#         margin=dict(r=20, b=10, l=10, t=10))
#
#
#     return fig


@app.callback(
    Output('time-series2', 'figure'),
    [Input('metric', 'value'),
     Input('finyr', 'value'),
     Input('category1', 'value'),
     Input('category2', 'value')])
def update_graph(metric_name, finyr_name, category1_name, category2_name):
    workHrs['Date'] = pd.to_datetime(workHrs['Date'])
    workHrs['FY'] = workHrs['Date'].apply(lambda x: x.year + 1 if x.month > 6 else x.year)
    workHrs['Qtr'] = pd.PeriodIndex(workHrs['Date'], freq='Q-JUN')
   workHrs['Qtr'] = workHrs['Qtr'].astype(str)

    if (category2_name == "National"):
        df_b = incidents[(incidents['FY'].isin(finyr_name))]
        df_wh = workHrs[(workHrs['FY'].isin(finyr_name))]
    else:
        df_b = incidents[(incidents['state'] == category2_name) & (incidents['FY'].isin(finyr_name))]
        df_wh = workHrs[(workHrs['state'] == category2_name) & (workHrs['FY'].isin(finyr_name))]

    df9 = df_b.groupby(
        ['Qtr']).agg(
        {
            metric_name: sum,
        }).reset_index()

    df35 = df_wh.groupby(
        ['Qtr']).agg(
        {
            'Worked_Hours': sum,
        }).reset_index()

    df_final = pd.merge(df9,
                        df35,
                        left_on='Qtr',
                        right_on='Qtr',
                        how='left')

    df_final['Rate per Hour'] = (df_final[metric_name] / df_final['Worked_Hours']) * 100
    df_final = df_final.fillna(0)

    fig = make_subplots(specs=[[{"secondary_y": True}]])

    fig.add_trace(go.Scatter(x=df_final['Qtr'],
                             y=df_final[metric_name],
                             line=dict(color='royalblue', width=3),
                             mode='lines+markers',
                             name=metric_name + ", " + category1_name
                             ),
                  )

    fig.add_trace(go.Scatter(x=df_final['Qtr'],
                             y=df_final[metric_name].rolling(4).mean(),
                             line=dict(color='firebrick', width=2, dash='dashdot'),
                             name='4Q Rolling Avg'),
                  secondary_y=False,
                  )

    fig.add_trace(go.Bar(x=df_final['Qtr'],
                         y=df_final['Rate per Hour'],
                         name='Injury Rate (Worked Hours)'),
                  secondary_y=True,
                  )

    fig.update_traces(marker_color='rgb(158,202,225)', marker_line_color='rgb(8,48,107)',
                      marker_line_width=1.5, opacity=0.6)

    # fig.update_layout(margin={'l': 40, 'b': 40, 't': 10, 'r': 0}, hovermode='closest')
    # Set y-axes titles
    fig.update_yaxes(title_text="<b>primary</b> yaxis title", secondary_y=False)
    fig.update_yaxes(title_text="<b>secondary</b> yaxis title", secondary_y=True)
    fig.update_xaxes(tickangle=45, tickfont=dict(family='Rockwell', color='grey', size=11))

    fig.update_layout(legend=dict(
        orientation="h",
        yanchor="bottom",
        y=1,
        xanchor="right",
        x=1,
        font=dict(family="Courier", size=12, color=colors['text'])),
        paper_bgcolor=colors['background'],
        plot_bgcolor=colors['background']
    )
    # fig.update_xaxes(rangeslider_visible=True)

    return fig


@app.callback(
    Output('pie', 'figure'),
    [Input('metric', 'value'),
     Input('finyr', 'value'),
     Input('category1', 'value'),
     Input('category2', 'value')])
def update_pie(metric_name, finyr_name, category1_name, category2_name):
    if (category2_name == "National"):
        df_b = incidents[(incidents['FY'].isin(finyr_name))]
    else:
        df_b = incidents[(incidents['state'] == category2_name) & (incidents['FY'].isin(finyr_name))]

    df11 = df_b.groupby(
        [category1_name]).agg(
        {
            metric_name: sum,
       }).reset_index()
    fig = go.Figure(
        data=[go.Pie(labels=df11[category1_name], values=df11[metric_name], textinfo='label+percent+value',
                     insidetextorientation='radial', textfont_size=10
                     )])
    fig.update_layout(legend=dict(
        yanchor="bottom",
        y=0,
        xanchor="right",
        x=2,
        font=dict(family="Courier", size=11, color=colors['text'])),
        paper_bgcolor=colors['background'],
        plot_bgcolor=colors['background']
    )

    return fig

@app.callback(
    Output('treemap', 'figure'),
    [Input('metric', 'value'),
     Input('global', 'value'),
     Input('subset1', 'value'),
     Input('subset2', 'value'),
     Input('yaxis', 'value'),
     Input('finyr', 'value'),
     Input('category2', 'value')])
def update_treemap(metric_name, global_name, subset1_name, subset2_name, yaxis_name, finyr_name, category2_name):

    if (category2_name == "National"):
        df_s = incidents[(incidents['FY'].isin(finyr_name))]
    else:
        df_s = incidents[(incidents['state'] == category2_name) & (incidents['FY'].isin(finyr_name))]

    df7 = df_s.groupby(
        [global_name, subset1_name, subset2_name]).agg(
        {
            metric_name: sum,
            yaxis_name: sum,
        }).reset_index()

    df7['root']=category2_name
    df7=df7[df7[metric_name]>0]

    fig = px.treemap(df7, path=['root', global_name, subset1_name, subset2_name], values=metric_name,
                     color=yaxis_name, #hover_data=df7[subset2_name],
                     color_continuous_scale='RdBu',
                     color_continuous_midpoint=np.average(df7[yaxis_name], weights=df7[metric_name]))

    fig.update_layout(legend=dict(
        orientation="h",
        yanchor="bottom",
        y=1,
        xanchor="right",
        x=1,
        font=dict(family="Courier", size=12, color=colors['text'])),
        paper_bgcolor=colors['background'],
        plot_bgcolor=colors['background'],
        # yaxis1=dict(gridcolor = 'rgb(150,150,150)'),
        # xaxis1=dict(gridcolor='rgb(150,150,150)')
    )
    #fig.show()
    return fig


if __name__ == '__main__':
    app.run_server()
