### ISSUE TITLE
Getting 403 on dash JS files on deployment

### ISSUE THREAD

**Issue by boludo00** [plotly/dash#1067]
I am using the Serverless framework to deploy my dash app with api-gateway + lambda with the serverless-wsgi plugin. I am able to serve my app locally and it works using `serverless wsgi serve` but when I deploy and hit the endpoint all I see is a Loading message. Checking out the debugger I see 
![image](https://user-images.githubusercontent.com/8398241/71841632-bb018500-3074-11ea-8e72-53399e1375db.png)

Has anyone run into this issue or is there something trivial I am missing?

**Comment by boludo00** [comment]
If anyone is following the same route I am, I have fixed this with the following snippet in my app code
`if __name__ != "__main__":
    app.config.update({
        'routes_pathname_prefix': '/',
        'requests_pathname_prefix': '/dev/'
    })
    app.css.config.serve_locally = False
    app.scripts.config.serve_locally = False`

**Comment by kobonyo** [comment]
Saved me after days!!
