### ISSUE TITLE
small typo in docs example

### ISSUE THREAD

**Issue by ras44** [plotly/dash#1072]
At the end of the second example in https://dash.plot.ly/state, it looks like there is an errant ```:

```
if __name__ == '__main__':
    app.run_server(debug=True)```
```

**Comment by kolayne** [comment]
Looks like it's fixed already, isn't it?

**Comment by alexcjohnson** [comment]
I'm not seeing it either - so yeah, closing. Thanks for checking @kolayne 
FWIW docs issues can be opened directly in https://github.com/plotly/dash-docs
