### ISSUE TITLE
[Feature Request] Allow component developers to expose custom errors / warnings in Dash Devtools

### ISSUE THREAD

**Issue by Marc-Andre-Rivet** [plotly/dash#1088]
As encountered in https://github.com/plotly/dash-core-components/pull/729, it would be useful for component developers to expose degradation warnings / errors, etc. in Dash Devtools.

As currently implemented, only front-end errors thrown from within the React Error Boundary components are caught / handled by the Dash Devtools, making it impossible to both expose warning / error information to the user and rendering a component at the same time.

**Comment by wbrgss** [comment]
I think I ran into that problem myself. If it helps (but basically echoing this issue description):

> I would prefer to throw a warning **and** still render the [component], but I can't figure out a way to display a Dev Tools warning without throwing an exception, and any uncaught exceptions will result in the component failing to render. Any caught exceptions (even with React Error Boundaries & `componentDidCatch()`) won't show the warning in Dev Tools. As an escape hatch I added a suppress_layout_exceptions flag to [the parent component]

**Comment by T4rk1n** [comment]
This has been implemented with `set_props({_dash_error: new Error("custom")})`
