### ISSUE TITLE
[BUG] Histogram trims empty bins even when range is explicitly specified

### ISSUE THREAD

**Issue by buuck** [plotly/dash#1090]
**Context**
```
dash                   1.8.0              
dash-core-components   1.7.0              
dash-daq               0.3.1              
dash-html-components   1.0.2              
dash-renderer          1.2.3              
dash-table             4.6.0
```

**Describe the bug**

This might actually be either a bug with plotly.py or my own ignorance, but when I try to produce a histogram the lower and upper bounds of the x-axis are not set correctly. As you can see in the code supplied I am using `autobinx: False` and supplying all values required by `xbins`, but plotly seems to trim empty bins outside the data range, even if I have explicitly asked it to include them. Code to reproduce:

```
import dash
import dash_core_components as dcc
import dash_html_components as html
from random import sample

x = sample(range(250,750), 100)

app = dash.Dash(__name__)
app.layout = html.Div(children=[
    dcc.Graph(
        id='example',
        figure={
            'data': [
                {'type': 'histogram', 'x': x, 'autobinx': False, 'xbins': {'start': 0, 'end': 1000, 'size': 10}}
            ]
        }
    )
])

if __name__ == '__main__':
    app.run_server(debug=True)
```

**Expected behavior**

Histogram spans the range specified, even if there are empty bins above and/or below the data set.

**Screenshots**

This is what I get when I run the above code. The histogram x-axis should extend down to 0 and up to 1000, even though 0-250 and 750-1000 will be empty bins by construction.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/850413/72540368-9da09800-3878-11ea-8903-23b64ed9e255.png">

**Comment by alexcjohnson** [comment]
This is working as expected from our perspective, though I can understand there are cases you want these points included. You can get the behavior you want by including:
`figure={'data': [...], 'layout': {'xaxis': {'range': [0, 1000]}}}`

**Comment by buuck** [comment]
Ah yes, that does what I was looking for. The actual use case I had was for showing a lookback at data bundles transferred in the last 24 hours between two locations, and I want it to always show the full 24 hours, even if the transfers are only happening sporadically during that time. I found the documentation somewhat confusing, so at least maybe some clarification there would be helpful.

Thanks!

**Comment by alexcjohnson** [comment]
OK great - I'll close this issue then, and we'll follow up as a documentation issue https://github.com/plotly/plotly.py/issues/2086
