### ISSUE TITLE
Dash 2.0

### ISSUE THREAD

**Issue by alexandercbooth** [plotly/dash#11]
Hi @chriddyp, 

I saw the PLOTCON talk recently and I cannot wait to start building with/contributing to the new Dash! Will you be releasing soon?

Thanks!

**Comment by prescod** [comment]
I'm curious why it is important that it be designed in private rather than on github?

**Comment by nevion** [comment]
@chriddyp 
I'm interesting doing a somewhat webapp using Dash 2.0.  Pet project but I think it'll go best with Dash - although I'm taking a look at everything.  I hope you guys put your code up on github even if it's not a release so I can see what you have cooking and further find and inform what parts work for me and maybe uncover design flaws, if any.

**Comment by Dan-S** [comment]
I also came here via the PLOTCON talk, nice work! The world needs this library.  This video wasnt far from the top of my search: https://youtu.be/VgRGDzCK5v0

**Comment by dwinston** [comment]
Looks like this will come up in a [workshop](https://github.com/plotly/Plotcon-Python-Workshop-2017) at PLOTCON in Oakland, CA May 4-5, and it looks like there are new [demos](https://github.com/plotly/dash-demos) in development. I'm excited for this project to get un-deprecated. :)

**Comment by tobsecret** [comment]
Two weeks ago the plotly account on youtube mentioned in a comment that the release will be within the next 6 weeks (i.e. within the coming 4 weeks from my comment)
https://www.youtube.com/watch?v=e4ti2fCpXMI

**Comment by tobsecret** [comment]
So any day now? @chriddyp, can you give a release date to the hungry masses?

**Comment by chriddyp** [comment]
Any day now! Just wrapping some loose ends here and there. Thank you all for your patience ❤️

**Comment by rohansb** [comment]
eagerly eagerly waiting! thanks @chriddyp
