### ISSUE TITLE
[BUG] Warnings in first documentation sample

### ISSUE THREAD

**Issue by sabas** [plotly/dash#1101]
Hi!
I think this issue is solvable here more than in the documentation, but I don't know React :-)
I tried the first example from https://dash.plot.ly/getting-started
The page renders correctly as in the screenshot but I noticed this warning repeated two times .

```
Warning: Failed prop type: The prop `isRequired` is marked as required in `<<anonymous>>`, but its value is `undefined`.
    in Unknown (created by t)
    in t (created by CheckedComponent)
    in CheckedComponent (created by TreeContainer)
    in UnconnectedComponentErrorBoundary (created by Connect(UnconnectedComponentErrorBoundary))
    in Connect(UnconnectedComponentErrorBoundary) (created by TreeContainer)
    in TreeContainer (created by Connect(TreeContainer))
    in Connect(TreeContainer) (created by TreeContainer)
    in div (created by u)
    in u (created by CheckedComponent)
    in CheckedComponent (created by TreeContainer)
    in UnconnectedComponentErrorBoundary (created by Connect(UnconnectedComponentErrorBoundary))
    in Connect(UnconnectedComponentErrorBoundary) (created by TreeContainer)
    in TreeContainer (created by Connect(TreeContainer))
    in Connect(TreeContainer) (created by UnconnectedContainer)
    in div (created by UnconnectedGlobalErrorContainer)
    in div (created by GlobalErrorOverlay)
    in div (created by GlobalErrorOverlay)
    in GlobalErrorOverlay (created by DebugMenu)
    in div (created by DebugMenu)
    in DebugMenu (created by UnconnectedGlobalErrorContainer)
    in div (created by UnconnectedGlobalErrorContainer)
    in UnconnectedGlobalErrorContainer (created by Connect(UnconnectedGlobalErrorContainer))
    in Connect(UnconnectedGlobalErrorContainer) (created by UnconnectedContainer)
    in UnconnectedContainer (created by Connect(UnconnectedContainer))
    in Connect(UnconnectedContainer) (created by UnconnectedAppContainer)
    in UnconnectedAppContainer (created by Connect(UnconnectedAppContainer))
    in Connect(UnconnectedAppContainer) (created by AppProvider)
    in Provider (created by AppProvider)
    in AppProvider
```
pip3 list
```
dash (1.8.0)
dash-core-components (1.7.0)
dash-html-components (1.0.2)
dash-renderer (1.2.3)
dash-table (4.6.0)
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: Ubuntu (WSL)
    - Browser Chrome
    - Version 79

**Comment by anders-kiaer** [comment]
I get the same console warnings (https://github.com/plotly/dash-core-components/issues/742). But I can't tell if the root problem is in `dash` or `dash-core-components`.

**Comment by chriddyp** [comment]
Thanks @sabas ! Just to clarify, you're seeing these warnings in the JavaScript console, right?

**Comment by sabas** [comment]
Yes!

**Comment by pipech** [comment]
Just got this warning too.

pip3 list

	Click                7.0
	dash                 1.9.0
	dash-core-components 1.8.0
	dash-html-components 1.0.2
	dash-renderer        1.2.4
	dash-table           4.6.0
	Flask                1.1.1
	Flask-Compress       1.4.0
	future               0.18.2
	itsdangerous         1.1.0
	Jinja2               2.11.1
	MarkupSafe           1.1.1
	pip                  19.0.3
	plotly               4.5.0
	retrying             1.3.3
	setuptools           40.8.0
	six                  1.14.0
	Werkzeug             0.16.1

OS

- Windows 10

**Comment by alexcjohnson** [comment]
Closed by https://github.com/plotly/dash-core-components/pull/754
