### ISSUE TITLE
asyncio

### ISSUE THREAD

**Issue by Elektra58** [plotly/dash#111]
Is it possible to pull the data from an asynchronous API such as InteractiveBrokers' and use Dash for realtime data? We are using a new framework `ib_insync` and integrating this with Dash would be fantastic.

**Comment by chriddyp** [comment]
Your best bet right now would probably be to use the `Interval` component (see https://plot.ly/dash/live-updates) and read the data from a file or a shared memory store like Redis (see https://plot.ly/dash/performance)
