### ISSUE TITLE
[BUG] WARN: Too many auto-margin redraws.

### ISSUE THREAD

**Issue by pipech** [plotly/dash#1112]
**Describe your context**
Got `WARN: Too many auto-margin redraws.` in browser console when using `dcc.Loading` and `go.Layout.Margin` with some type or config of graph.

**Sample code**
```python
import dash
import dash_core_components as dcc
import dash_html_components as html
import time
import plotly.graph_objs as go

from dash.dependencies import Input, Output

app = dash.Dash(__name__)

app.layout = html.Div([
    dcc.Loading(
        dcc.Graph(id='too-many-redraws'),
    ),
    dcc.Input(
        id='load',
        type='text',
        value='ForceLoad',
        style={'display': 'none'},
    ),
])


@app.callback(
    Output('too-many-redraws', 'figure'),
    [Input('load', 'value')])
def update_figure(v):
    time.sleep(2)

    # error
    data = [
        go.Bar(
            x=['A'],
            y=[22],
            marker={
                'color': 'rgb(191, 222, 207)'
            }
        )
    ]

    # # error
    # data = [
    #     go.Waterfall(
    #         measure=[
    #             'absolute', 'relative', 'relative',
    #             'relative', 'relative', 'absolute'
    #         ],
    #         x=[
    #             'A', 'B', 'C',
    #             'D', 'E', 'F'
    #         ],
    #         y=[
    #             100,
    #             20,
    #             20,
    #             20,
    #             20,
    #             200,
    #         ],
    #     )
    # ]

    # # no error
    # data = [
    #     go.Pie(
    #         labels=['Oxygen','Hydrogen','Carbon_Dioxide','Nitrogen'],
    #         values=[4500, 2500, 1053, 500],
    #     )
    # ]

    # # no error
    # data = [
    #     go.Bar(
    #         x=[1,2,3],
    #         y=[4,1,2],
    #         name='SF',
    #     ),
    #     go.Bar(
    #         x=[1,2,3],
    #         y=[2,4,5],
    #         name='MON',
    #     ),
    # ]

    layout = go.Layout(
        margin={
            'l': 0,
            'r': 0,
            'b': 0,
            't': 0,
        },
        height=300,
    )

    fig = go.Figure(
        data=data,
        layout=layout,
    )
    return fig


if __name__ == '__main__':
    app.run_server(debug=True)

```

-  `pip list | grep dash`
```
dash                 1.7.0
dash-core-components 1.6.0
dash-html-components 1.0.2
dash-renderer        1.2.2
dash-table           4.5.1
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: Windows 10 Build
    - Browser: Chrome
    - Version: 79.0.3945.130 (Official Build) (64-bit)

**Describe the bug**

	WARN: Too many auto-margin redraws.
	i @ plotly.min.js:7
	a.warn @ plotly.min.js:7
	v.doAutoMargin @ plotly.min.js:7
	v.autoMargin @ plotly.min.js:7
	e.exports @ plotly.min.js:7
	r.drawMarginPushers @ plotly.min.js:7
	M @ plotly.min.js:7
	l.syncOrAsync @ plotly.min.js:7
	L @ plotly.min.js:7
	l.syncOrAsync @ plotly.min.js:7
	a @ plotly.min.js:7
	Promise.then (async)
	l.syncOrAsync @ plotly.min.js:7
	r.plot @ plotly.min.js:7
	r.newPlot @ plotly.min.js:7
	r.react @ plotly.min.js:7
	value @ Graph.react.js:95
	value @ Graph.react.js:224
	commitLifeCycles @ react-dom@16.v1_2_2m1574885967.8.6.js:17469
	commitAllLifeCycles @ react-dom@16.v1_2_2m1574885967.8.6.js:18871
	callCallback @ react-dom@16.v1_2_2m1574885967.8.6.js:143
	invokeGuardedCallbackDev @ react-dom@16.v1_2_2m1574885967.8.6.js:193
	invokeGuardedCallback @ react-dom@16.v1_2_2m1574885967.8.6.js:250
	commitRoot @ react-dom@16.v1_2_2m1574885967.8.6.js:19083
	(anonymous) @ react-dom@16.v1_2_2m1574885967.8.6.js:20553
	unstable_runWithPriority @ react@16.v1_2_2m1574885967.8.6.js:735
	completeRoot @ react-dom@16.v1_2_2m1574885967.8.6.js:20552
	performWorkOnRoot @ react-dom@16.v1_2_2m1574885967.8.6.js:20481
	performWork @ react-dom@16.v1_2_2m1574885967.8.6.js:20389
	performSyncWork @ react-dom@16.v1_2_2m1574885967.8.6.js:20363
	requestWork @ react-dom@16.v1_2_2m1574885967.8.6.js:20232
	scheduleWork @ react-dom@16.v1_2_2m1574885967.8.6.js:20046
	enqueueSetState @ react-dom@16.v1_2_2m1574885967.8.6.js:11304
	Component.setState @ react@16.v1_2_2m1574885967.8.6.js:423
	handleChange @ dash_renderer.v1_2_2m1574885974.dev.js:27180
	dispatch @ dash_renderer.v1_2_2m1574885974.dev.js:28180
	(anonymous) @ dash_renderer.v1_2_2m1574885974.dev.js:27669
	dispatch @ dash_renderer.v1_2_2m1574885974.dev.js:27727
	updateRequestQueue @ dash_renderer.v1_2_2m1574885974.dev.js:30864
	handleJson @ dash_renderer.v1_2_2m1574885974.dev.js:31150
	Promise.then (async)
	handleResponse @ dash_renderer.v1_2_2m1574885974.dev.js:31138
	Promise.then (async)
	updateOutput @ dash_renderer.v1_2_2m1574885974.dev.js:31094
	_callee$ @ dash_renderer.v1_2_2m1574885974.dev.js:30811
	tryCatch @ polyfill@7.v1_2_2m1574885967.7.0.min.js:1
	invoke @ polyfill@7.v1_2_2m1574885967.7.0.min.js:1
	t.<computed> @ polyfill@7.v1_2_2m1574885967.7.0.min.js:1
	tryCatch @ polyfill@7.v1_2_2m1574885967.7.0.min.js:1
	invoke @ polyfill@7.v1_2_2m1574885967.7.0.min.js:1
	(anonymous) @ polyfill@7.v1_2_2m1574885967.7.0.min.js:1
	Promise.then (async)
	invoke @ polyfill@7.v1_2_2m1574885967.7.0.min.js:1
	(anonymous) @ polyfill@7.v1_2_2m1574885967.7.0.min.js:1
	callInvokeWithMethodAndArg @ polyfill@7.v1_2_2m1574885967.7.0.min.js:1
	enqueue @ polyfill@7.v1_2_2m1574885967.7.0.min.js:1
	t.<computed> @ polyfill@7.v1_2_2m1574885967.7.0.min.js:1
	o.async @ polyfill@7.v1_2_2m1574885967.7.0.min.js:1
	_callee @ dash_renderer.v1_2_2m1574885974.dev.js:30632
	(anonymous) @ dash_renderer.v1_2_2m1574885974.dev.js:27666
	dispatch @ dash_renderer.v1_2_2m1574885974.dev.js:27727
	(anonymous) @ dash_renderer.v1_2_2m1574885974.dev.js:30536
	triggerDefaultState @ dash_renderer.v1_2_2m1574885974.dev.js:30527
	(anonymous) @ dash_renderer.v1_2_2m1574885974.dev.js:30483
	(anonymous) @ dash_renderer.v1_2_2m1574885974.dev.js:27666
	initialization @ dash_renderer.v1_2_2m1574885974.dev.js:29653
	componentWillReceiveProps @ dash_renderer.v1_2_2m1574885974.dev.js:29613
	callComponentWillReceiveProps @ react-dom@16.v1_2_2m1574885967.8.6.js:11576
	updateClassInstance @ react-dom@16.v1_2_2m1574885967.8.6.js:11786
	updateClassComponent @ react-dom@16.v1_2_2m1574885967.8.6.js:14829
	beginWork @ react-dom@16.v1_2_2m1574885967.8.6.js:15779
	performUnitOfWork @ react-dom@16.v1_2_2m1574885967.8.6.js:19447
	workLoop @ react-dom@16.v1_2_2m1574885967.8.6.js:19487
	renderRoot @ react-dom@16.v1_2_2m1574885967.8.6.js:19570
	performWorkOnRoot @ react-dom@16.v1_2_2m1574885967.8.6.js:20477
	performWork @ react-dom@16.v1_2_2m1574885967.8.6.js:20389
	performSyncWork @ react-dom@16.v1_2_2m1574885967.8.6.js:20363
	requestWork @ react-dom@16.v1_2_2m1574885967.8.6.js:20232
	scheduleWork @ react-dom@16.v1_2_2m1574885967.8.6.js:20046
	enqueueSetState @ react-dom@16.v1_2_2m1574885967.8.6.js:11304
	Component.setState @ react@16.v1_2_2m1574885967.8.6.js:423
	handleChange @ dash_renderer.v1_2_2m1574885974.dev.js:27180
	dispatch @ dash_renderer.v1_2_2m1574885974.dev.js:28180
	(anonymous) @ dash_renderer.v1_2_2m1574885974.dev.js:27669
	dispatch @ dash_renderer.v1_2_2m1574885974.dev.js:27727
	(anonymous) @ dash_renderer.v1_2_2m1574885974.dev.js:30346
	Promise.then (async)
	(anonymous) @ dash_renderer.v1_2_2m1574885974.dev.js:30345
	Promise.then (async)
	(anonymous) @ dash_renderer.v1_2_2m1574885974.dev.js:30341
	(anonymous) @ dash_renderer.v1_2_2m1574885974.dev.js:27666
	initialization @ dash_renderer.v1_2_2m1574885974.dev.js:29641
	componentDidMount @ dash_renderer.v1_2_2m1574885974.dev.js:29608
	commitLifeCycles @ react-dom@16.v1_2_2m1574885967.8.6.js:17469
	commitAllLifeCycles @ react-dom@16.v1_2_2m1574885967.8.6.js:18871
	callCallback @ react-dom@16.v1_2_2m1574885967.8.6.js:143
	invokeGuardedCallbackDev @ react-dom@16.v1_2_2m1574885967.8.6.js:193
	invokeGuardedCallback @ react-dom@16.v1_2_2m1574885967.8.6.js:250
	commitRoot @ react-dom@16.v1_2_2m1574885967.8.6.js:19083
	(anonymous) @ react-dom@16.v1_2_2m1574885967.8.6.js:20553
	unstable_runWithPriority @ react@16.v1_2_2m1574885967.8.6.js:735
	completeRoot @ react-dom@16.v1_2_2m1574885967.8.6.js:20552
	performWorkOnRoot @ react-dom@16.v1_2_2m1574885967.8.6.js:20481
	performWork @ react-dom@16.v1_2_2m1574885967.8.6.js:20389
	performSyncWork @ react-dom@16.v1_2_2m1574885967.8.6.js:20363
	requestWork @ react-dom@16.v1_2_2m1574885967.8.6.js:20232
	scheduleWork @ react-dom@16.v1_2_2m1574885967.8.6.js:20046
	scheduleRootUpdate @ react-dom@16.v1_2_2m1574885967.8.6.js:20707
	updateContainerAtExpirationTime @ react-dom@16.v1_2_2m1574885967.8.6.js:20735
	updateContainer @ react-dom@16.v1_2_2m1574885967.8.6.js:20792
	ReactRoot.render @ react-dom@16.v1_2_2m1574885967.8.6.js:21088
	(anonymous) @ react-dom@16.v1_2_2m1574885967.8.6.js:21225
	unbatchedUpdates @ react-dom@16.v1_2_2m1574885967.8.6.js:20594
	legacyRenderSubtreeIntoContainer @ react-dom@16.v1_2_2m1574885967.8.6.js:21221
	render @ react-dom@16.v1_2_2m1574885967.8.6.js:21290
	DashRenderer @ dash_renderer.v1_2_2m1574885974.dev.js:29939
	(anonymous) @ (index):28
	Show 34 more frames

**Expected behavior**

Drawn graph without error.

**Screenshots**

![image](https://user-images.githubusercontent.com/24489363/73908453-52f4c780-48dc-11ea-8f30-8cf373e88fed.png)

**Comment by wbrgss** [comment]
What version of plotly.js are you using? This may be a https://github.com/plotly/plotly.js issue. E.g. plotly/plotly.js#2704 or plotly/plotly.js#4028

**Comment by wbrgss** [comment]
If you're using Dash Core Components 1.7.0 it's probably 1.52.1 (https://github.com/plotly/dash-core-components/blob/dev/CHANGELOG.md); you can find out by typing `Plotly.version` in your browser console.

**Comment by pipech** [comment]
It's version "1.51.2".

Should I close and re-open this issues on plotly.js ?

**Comment by chriddyp** [comment]
@pipech - does this only happen when it is wrapped in a `dcc.Loading` component?

**Comment by pipech** [comment]
> @pipech - does this only happen when it is wrapped in a `dcc.Loading` component?

It only happen when combine `dcc.Loading`, `go.Layout.Margin` and some type or config of graph as shown in the example.

Remove either `dcc.Loading` or `go.Layout.Margin` will solve the issues.

**Comment by wbrgss** [comment]
Some more info on this bug in plotly.js/issues#4572

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
