### ISSUE TITLE
dash-responsive-grid-layout

### ISSUE THREAD

**Issue by sgsikuga** [plotly/dash#1113]
Hey,
has anyone experience with this package? I can't change the layouts in the provided example on https://github.com/AlgorithmHub/dash-responsive-grid-layout/blob/master/usage.py

When I change something here it has no effect on the layout of the Div or graph. How is it possible to control the layout?

layouts = {
    'lg': [
        {'i': 'a', 'x': 0, 'y': 0, 'w': 1, 'h': 2, 'static': False},
        {'i': 'b', 'x': 1, 'y': 0, 'w': 1, 'h': 2, 'minW': 1, 'maxW': 2},
        {'i': 'c', 'x': 2, 'y': 0, 'w': 1, 'h': 2}
    ],
    'sm': [
        {'i': 'a', 'x': 0, 'y': 0, 'w': 1, 'h': 2, 'static': False},
        {'i': 'b', 'x': 1, 'y': 0, 'w': 1, 'h': 2, 'minW': 1, 'maxW': 2},
        {'i': 'c', 'x': 2, 'y': 0, 'w': 1, 'h': 2}
    ]
}

Thanks in advance!

**Comment by alexcjohnson** [comment]
Interesting question, but out of scope for the dash repo itself - this would be a great question for https://community.plot.ly/c/dash, or if you think you've found a bug with the dash-responsive-grid-layout package you can certainly report it in that repo.

Thanks for understanding :)
