### ISSUE TITLE
[BUG] Attempting to Freeze dash with Flask Freezer results in some Mal-formed URLs

### ISSUE THREAD

**Issue by BracketMaster** [plotly/dash#1119]
Attempting to Freeze dash with Flask Freezer results in some Mal-formed URLs - mainly those referencing dash.js scripts...

Basically, this can be fixed with appropriate URL [generators](https://pythonhosted.org/Frozen-Flask/), I played around with this, but I realized I'm too unfamiliar with Dash internals to resolve this.

here are some excerpts from the frozen HTML generated by flask.

```html
<script src="/_dash-component-suites/dash_renderer/react@16.v1_2_3m1581487068.8.6.min.js"></script>
<script src="/_dash-component-suites/dash_renderer/react-dom@16.v1_2_3m1581487068.8.6.min.js"></script>
<script src="/_dash-component-suites/dash_renderer/prop-types@15.v1_2_3m1581487068.7.2.min.js"></script>
<script src="/_dash-component-suites/dash_html_components/dash_html_components.v1_0_2m1581487070.min.js"></script>
<script src="/_dash-component-suites/dash_core_components/dash_core_components.v1_7_0m1581487069.min.js"></script>
<script src="/_dash-component-suites/dash_core_components/dash_core_components-shared.v1_7_0m1581487069.js"></script>
<script src="/_dash-component-suites/dash_cytoscape/dash_cytoscape.v0_1_1m1581487332.min.js"></script>
<script src="/_dash-component-suites/dash_renderer/dash_renderer.v1_2_3m1581487068.min.js"></script>
```

ideally, those scripts should get copied into the ``./build`` directory generated by flask freeze, and the paths ins the ``src`` field in the HTML should be updated accordingly.

**Comment by bthng** [comment]
Did you manage to resolve this issue?

**Comment by BracketMaster** [comment]
Haha no. Been doing other things.
