### ISSUE TITLE
[Feature Request] Ability to redefine/reload a callback inputs or outputs after app.run

### ISSUE THREAD

**Issue by michaelfBoxer** [plotly/dash#1122]
**Is your feature request related to a problem? Please describe.**
As of now, all call backs need to be defined before the dash app starts running. Defining every possible input or output is fine for smaller scales, but gets out of hand quickly with larger projects. The ability to reload or refresh a call back would be amazing.

**Describe the solution you'd like**
When the input or outputs of a callback change, it either automatically changes, or we can make a function call to let the app know to reload callback x

**Additional context**

```python
@app.callback( 
     Output(component_id='my-test', component_property='children'),
    generated_inputs())
def filter_test(*args):   
    return [*args]
```
When generated_inputs() function output changes, having the ability to 'reload' this callback.

something like this would be awesome
```python
#callback to be refreshed
@app.callback( 
     Output(component_id='my-test', component_property='children'),
      generated_inputs(),
      callback_id = '123')
def filter_test(*args):   
    return [*args]

#A simple example of refreshing 
@app.callback( 
     Output(component_id='my-test', component_property='children'),
    [Input(component_id='my-test', component_property='children')])
def refresh():   
    dash.load_callback(id = 123)
```

**Comment by alexcjohnson** [comment]
This kind of situation is what we had in mind with wildcard callbacks - issue #475 and PR #1103 under review (and still fixing a few bugs...) right now. In this way of thinking, the callback definition never changes, but the specific inputs & outputs passed to the callback are just derived from IDs in the layout that match the given patterns. Would love your feedback on #1103!
