### ISSUE TITLE
[BUG] Client side callback does not work ( need to add namespace in JS code )

### ISSUE THREAD

**Issue by chabb** [plotly/dash#1139]
Thank you so much for helping improve the quality of Dash!

We do our best to catch bugs during the release process, but we rely on your help to find the ones that slip through.

**Describe your context**
Please provide us your environment so we can easily reproduce the issue.

-  replace the result of `pip list | grep dash` below
dash                            1.8.0
dash-auth                       1.3.2
dash-core-components            1.7.0
dash-dangerously-set-inner-html 0.0.2
dash-flow-example               0.0.5
dash-html-components            1.0.2
dash-katex                      0.0.1
dash-renderer                   1.2.3
dash-table                      4.6.0
jupyterlab-dash                 0.1.0a3
pydash                          4.7.6
**Describe the bug**

The documentation for clientside callback is incorrect. https://community.plot.ly/t/dash-0-41-0-released/22131

```

if(!window.dash_clientside) {window.dash_clientside = {};}
window.dash_clientside.clientside = {
    display: function (value) {
        return 'Client says "' + value + '"';
    }
}
```

But if you look at the code that dash executes at startup: ( i just put the relevant part )
```

try {
      var _window$dash_clientsi;

      returnValue = (_window$dash_clientsi = window.dash_clientside[clientside_function.namespace])...
```

( `clientside_function.namespace` matches the `namespace`  defined in the python code )
you can see that it will trigger a console error. You have to add the namespace in the client-side code that you put in the asset folder. Something like that : 

```
window.dash_clientside = Object.assign({}, window.dash_clientside, {
    clientside: {
         highlightSegment: function(largeValue1) {
            console.log('called with', largeValue1)
        }
    }
})

```
would fix it.

Maybe I've missed the `right` documentation. Otherwise it seems the documentation is incorrect. I'd be happy to update it if needed

**Comment by alexcjohnson** [comment]
Thanks @chabb - you're absolutely correct, and I've moved your note over to the docs repo where there's an existing issue to improve this https://github.com/plotly/dash-docs/issues/754

We certainly welcome contributions over there if you're interested in helping out!
