### ISSUE TITLE
Error loading react-dom@15.4.2

### ISSUE THREAD

**Issue by radumas** [plotly/dash#114]
I've deployed a Dash app to [Heroku](https://mighty-savannah-97969.herokuapp.com/) and the page was loading fine on my development computer, but my colleagues ran into errors loading the page. The error I'm getting in the console at the moment is:
`mighty-savannah-97969.herokuapp.com/:24 GET https://unpkg.com/react-dom@15.4.2/dist/react-dom.min.js `
Playing with URLs at unpkg, I see that [`15.4.1`](https://unpkg.com/react-dom@15.4.1/dist/react-dom.min.js) and [`15.5.1`](https://unpkg.com/react-dom@15.5.1/dist/react-dom.min.js) exist.

**Comment by jimaek** [comment]
You can use jsDelivr instead https://cdn.jsdelivr.net/npm/react-dom@15.4.2/dist/react-dom.min.js

It's more reliable and built to be production ready, without such problems.You can use jsDelivr instead https://cdn.jsdelivr.net/npm/react-dom@15.4.2/dist/react-dom.min.js

It's more reliable and built to be production ready, without such problems.

**Comment by radumas** [comment]
Indeed the problem appears to be with unpkg. Now `bundle.js` is struggling to be delivered.

How do I change the javascript sources in Dash?

**Comment by ned2** [comment]
The react javascript files are included within the dash-renderer package rather than dash itself. I've submitted this PR https://github.com/plotly/dash-renderer/pull/12 to update the react files to 15.6.1.

If you look at the changes you'll see how to point to the javascript file you want.

**Comment by chriddyp** [comment]
For now, you can render the files locally without relying on the CDN with
```
app.css.config.serve_locally = True
app.scripts.config.serve_locally = True
```

**Comment by ned2** [comment]
Ah, so now I see what is meant by local CSS/JS is not supported. I've just been adding them with eg `app.css.append_css({"external_url": '/static/css/foo.css'})` which has been working fine, however setting `app.css.config.serve_locally = True` now means that Dash can't find the file. As I get this UserWarning:

    A local version of /static/css/foo.css is not available

Strangely it's finding local javascript files fine. Perhaps this wants to be a separate issue...

**Comment by radumas** [comment]
Can confirm that 
```python
app.css.config.serve_locally = True
app.scripts.config.serve_locally = True
```
works on heroku as well.

Thanks @chriddyp !

**Comment by chriddyp** [comment]
FYI - The original issue (failures serving react-dom from unpkg cdn) is being tracked here: https://github.com/unpkg/unpkg-website/issues/54
