### ISSUE TITLE
[BUG] Dropdown do not show for one line DataTable

### ISSUE THREAD

**Issue by therealarty** [plotly/dash#1140]
**Describe your context**

```
dash                      1.9.0
dash-bootstrap-components 0.8.3
dash-core-components      1.8.0
dash-html-components      1.0.2
dash-renderer             1.2.4
dash-table                4.6.0
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: MacOsX 10.14
    - Browser Chrome 
    - Version  80.0.3987.87

**Describe the bug**

When I have a DataTable with only one row and I select a cell with a dropdown, the dropdown doesn't "overflow" the table, and therefore is not accessible / visible. (It is too small to scroll in it).

**Expected behavior**

The dropdown dialog should be able to continue below the datatable's end to make sure its options are accessible.

**Screenshots**

With one row
<img width="1167" alt="Capture d’écran 2020-03-02 à 17 21 04" src="https://user-images.githubusercontent.com/9209293/75695482-6829ff80-5caa-11ea-961f-ffa984632ac9.png">

With multiple rows
<img width="1167" alt="Capture d’écran 2020-03-02 à 17 21 47" src="https://user-images.githubusercontent.com/9209293/75695472-66603c00-5caa-11ea-95f0-8189e7f89ca2.png">

**Comment by jorge243** [comment]
Hi! Any news on this issue? I am facing the same problem
