### ISSUE TITLE
Get transformation matrix from the user?

### ISSUE THREAD

**Issue by ilianakp** [plotly/dash#1144]
I'm quite new to plotly and dash. I'm currently using them to visualize 3D point clouds on a web based interface and have some user interaction features.

I'm also using Open3D to align the point clouds. My goal is to be able for the user to rotate only one trace in a graph (the one of the two point clouds) and save the transformation matrix.
I've been searching for something similar, but I haven't found anything.

Is there a way to do this? Or will it be implemented in the future?

**Comment by alexcjohnson** [comment]
This kind of question would be better suited to https://community.plot.ly/ - but offhand I'd guess there should be a way to do this with two 3D scenes sharing the same domain, the one in front having hidden axes and a transparent background.

If you want to also be able to rotate the entire scene (which seems like it would be useful for an application like this!) the only way I can see to do it is to put the two clouds on the same scene and have the transformation matrix defined by controls outside the graph (`dcc.Slider` perhaps). If you do that, for performance you'd probably have to put the raw data into a `dcc.Store` and apply the transformation via clientside callbacks.

Closing as this won't lead to new code in this repo - feel free to follow up on https://community.plot.ly/
