### ISSUE TITLE
Component Div inside tab cannot render when upgrading from dash 1.6.1 to 1.7.0

### ISSUE THREAD

**Issue by ycaokris** [plotly/dash#1146]
App related: https://github.com/plotly/dash-sample-apps/tree/master/apps/dash-manufacture-spc-dashboard
Callback related: https://github.com/plotly/dash-sample-apps/blob/854b8df105e24b04f6b3f9124c016f1e01b23691/apps/dash-manufacture-spc-dashboard/app.py#L943-L993

-  replace the result of `pip list | grep dash` below
```
dash                 1.7.0  
dash-core-components 1.6.0  
dash-daq             0.4.0  
dash-html-components 1.0.2  
dash-renderer        1.2.2  
dash-table           4.5.1  
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: [e.g. iOS]: MacOS Mojave
    - Browser [e.g. chrome, safari]: MacOS Chrome Version 80.0.3987.132 (Official Build) (64-bit), Firefox 73.0.1

**Describe the bug**

Div(as callback Output) within tab1 cannot be updated by dropdown in the same tab after dropdown option change - > tab switching back. 

**Expected behavior**

I noticed this problem when updating from **dash1.6.1** to **dash1.7.0**. As shown on the gif below,  a callback is fired from dropdown selection within first tab to update the control sections on the right. This section doesn't render for me for dash1.7.0 when I : 1) Click on tab1 2) change dropdown value to a different one 3) Navigate to tab2 then Navigate back to tab1. 

I've tried to simplify the [output](https://github.com/plotly/dash-sample-apps/blob/854b8df105e24b04f6b3f9124c016f1e01b23691/apps/dash-manufacture-spc-dashboard/app.py#L957-L988) to an individual `html.Div("update time" + str(time.time())),` and still behaves the same. My callback is fired as usual upon tab navigation/dropdown-toggling. Looking into dev-tool has indicated that the dash_update_component has been sent back to front-end, so I wonder it could simply be a render-related issue.

![app](https://user-images.githubusercontent.com/35306149/76096608-5d19ec80-5f94-11ea-9caa-8de6c62a9dd1.gif)

![Screen_Shot_2020-03-06_at_10_37_11_AM](https://user-images.githubusercontent.com/35306149/76098194-0366f180-5f97-11ea-80c2-24da372335aa.png)

**Comment by alexcjohnson** [comment]
This looks similar to several of the bugs that are fixed in #1103 - @ycaokris would you be able to try it off that branch? You have to rebuild the renderer after pulling the branch down.

**Comment by ycaokris** [comment]
@alexcjohnson  It worked with this rebuild 👍  and I don't see this issue happening. Here's dev env: 

```
(venv) ➜  dash-manufacture-spc-dashboard git:(master) ✗ pip list | grep dash
dash                            1.9.1      /Users/yicao/PycharmProjects/dash              
dash-core-components            1.8.1      
dash-dangerously-set-inner-html 0.0.2      
dash-flow-example               0.0.5      
dash-html-components            1.0.2      
dash-renderer                   1.2.4      /Users/yicao/PycharmProjects/dash/dash-renderer
dash-table                      4.6.1      

```

![app](https://user-images.githubusercontent.com/35306149/76118305-91ed6a00-5fbb-11ea-9961-191fc403441d.gif)

**Comment by alexcjohnson** [comment]
Great! Thanks for testing it. I'll mark the PR as closing this issue.
