### ISSUE TITLE
deploy dash on IIS error

### ISSUE THREAD

**Issue by lx1054331851** [plotly/dash#115]
my flask demo app works fine  on IIS, the demo code is : 

![image](https://user-images.githubusercontent.com/12423206/29410848-0dc0336c-8385-11e7-81a6-2b60f337ebf2.png)

so I replace the flask demo code with dash demo code copied from dash official website, it looks like : 

![image](https://user-images.githubusercontent.com/12423206/29410923-50da89f4-8385-11e7-8eb1-70703639c386.png)

there, the dash app on IIS went wrong, the error information is : 

![image](https://user-images.githubusercontent.com/12423206/29410958-8091c81a-8385-11e7-93ff-216abd822b5a.png)

the dash demo code works fine in the debug environment with the command:
`python.exe hello.py`

my environment is Anaconda 3, Python 3.6 x64.

I'm not sure where is the problem? 
should I need to do more configuration on IIS  after I replace the flask code with dash code?
My flask app name is hello.py, I just replace the hello.py file's content.

**Comment by chriddyp** [comment]
Solved in https://community.plot.ly/t/solved-deploy-dash-on-iis-error/5434
