### ISSUE TITLE
use plotly dash as a django application

### ISSUE THREAD

**Issue by sherry0429** [plotly/dash#1155]
nearly I try to use plotly dash with django,
I know plotly use flask, So I try to make a bridge between of them,

here are my solution:
```python
def dispatcher(request):
    '''
    Main function
    @param request: Request object
    '''
    url = request.get_full_path().split('?')[0]
    content_type, _encoding = mimetypes.guess_type(url)
    params = {
        'data': request.body,
        'method': request.method,
        'content_type': content_type
    }
    with server.test_request_context(request.path, **params):
        server.preprocess_request()

        try:
            response = server.full_dispatch_request()
        except Exception as e:
            response = server.make_response(server.handle_exception(e))

        response.direct_passthrough = False
        return response.get_data(), content_type
```
this solution is inspired by  https://github.com/ned2/dash-django-example

my thinking is give dash a flask server, and redirect django request to flask server and return response.

here is my dash init code
```python
URL_BASE_PATHNAME = '/viz/'

server = Flask(__name__)

app = Dash(
    __name__,
    server=server,
    url_base_pathname=URL_BASE_PATHNAME,
    # routes_pathname_prefix=URL_BASE_PATHNAME
)

app.layout = html.Div(
    children=[
        html.H1(children='测试'),
    ]
)


app.config['suppress_callback_exceptions'] = True
```

and url redirect in django urls.py
```python
# Application Name: viz
urlpatterns = [
    re_path('^_dash-', views.dash_json),
    re_path('^assets/', views.dash_guess_mimetype),
    re_path('^', views.dash_index),
]
```

and now when i go to localhost:8000/viz/, I can see dash favicon, but nothing render, I really make sure all assets has been loaded.

here are some images:
1.my solution Dash App with request redirect
![image](https://user-images.githubusercontent.com/11309831/76949500-9151bd80-6943-11ea-9b19-e90512c13c2c.png)

2.pure Dash App with app.run_server() 
![image](https://user-images.githubusercontent.com/11309831/76949519-9b73bc00-6943-11ea-84c1-47b309c29501.png)

and, in 1 image, console panel have two error, when refresh page, error changed between error A and error B

error A:
![image](https://user-images.githubusercontent.com/11309831/76949558-ac243200-6943-11ea-9f23-ce147139eed3.png)

error B:
![image](https://user-images.githubusercontent.com/11309831/76949605-c0682f00-6943-11ea-88ef-6ffef8268358.png)

I guess this situation is cause by flask test_request_context method, maybe this can't do same thing in 'run_server'

Could anyone give me some advice ? Thanks.

By the way, I know django-plotly-dash repo, but our project don't suitable to use that way.

**Comment by sherry0429** [comment]
Ok, I read dash render js source code and find problem, solve it.

note here:
replace flask with django is possible, in this mode dash will be a app in django.

**Comment by LiorA1** [comment]
@sherry0429 
How you handle scaling ?
Isnt it worth while to deploy Django and Dash using containers and use Async View (Django) ?
