### ISSUE TITLE
[BUG] data-dash-is-loading is always true

### ISSUE THREAD

**Issue by ethanopp** [plotly/dash#1160]
Trying to set up some spinners with the css approach but the `data-dash-is-loading` always shows true even after the chart is loaded.

![image](https://user-images.githubusercontent.com/11603814/77238779-e68f0880-6ba9-11ea-9ae7-78aeb2aee582.png)

Google Chrome

```
 html.Div(className='col-lg-6', children=[
     dbc.Card(children=[
         dbc.CardHeader(id='power-curve-kpis'),
         dbc.CardBody(
             dcc.Graph(id='power-curve-chart', className='loader', config={'displayModeBar': False},
                       style={'height': '100%'}))
     ]),
 ]),
```

CSS:
```
*[data-dash-is-loading="true"].loader::before,
*[data-dash-is-loading="true"].loader-fade::before {
    z-index: 9999;
    visibility: visible;
    content: '';
    box-sizing: border-box;
    position: absolute;
    top: 50%;
    left: 50%;
    width: 30px;
    height: 30px;
    margin-top: -10px;
    margin-left: -10px;
    border-radius: 50%;
    border: 2px solid #999;
    border-top-color: #222;
    /* Wait for 1s before displaying spinner using 'offset' anomation This
       avoids flickering when wait times are low. */
    animation: offset 1s, spinner .6s linear infinite;
}
```

**Comment by ned9** [comment]
I'm seeing this issue too. After all callbacks have completed, when I run the following selector in Chrome devtools, I can see that all the components that are outputs of callbacks still have `data-dash-is-loading="true"`.

`$$("*[data-dash-is-loading=\"true\"]"`

This means, (I think) that the functionality described in the latter part of this page is currently broken: ishttps://dash.plotly.com/loading-states

**Comment by ned9** [comment]
Wow, looks like there's a fix for this over in plotly/dash-core-components#837 that was merged just 3 hours ago!

This issue is also reported over in plotly/dash-core-components#632.

**Comment by ned2** [comment]
Just came across this issue. Looks like there's a fix for this over in plotly/dash-core-components#837 that was merged just 3 hours ago!

This issue is also reported over in plotly/dash-core-components#632. Closing this in favour of that issue.
