### ISSUE TITLE
dash refushed to connect while running through jupyter notebook container

### ISSUE THREAD

**Issue by Mannu007-alt** [plotly/dash#1161]
While Running on local machine,its working fine.But while integrating the dash in jupyternotebook container and trying to launch on the same host,its through error as 'Refushed to Connect'.
Here is my dockerfile:

FROM jupyter/datascience-notebook
RUN apt-get update && apt-get install -y gcc g++ make python
RUN pip install dash==0.17.7
pip install dash-renderer==0.7.4 
pip install dash-html-components==0.7.0 
pip install dash-core-components==0.12.0 
pip install plotly==2.0.13
pip install jupyter_plolty_dash
Expose 8050

Here is my dash app:

import dash
import dash_core_components as dcc
import dash_html_components as html
external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']
app = dash.Dash(__name__, external_stylesheets=external_stylesheets)
app.layout = html.Div(children=[
    html.H1(children='Hello Dash'),
   html.Div(children='''
        Dash: A web application framework for Python.
    '''),

    dcc.Graph(
        id='example-graph',
        figure={
            'data': [
                {'x': [1, 2, 3], 'y': [4, 1, 2], 'type': 'bar', 'name': 'SF'},
                {'x': [1, 2, 3], 'y': [2, 4, 5], 'type': 'bar', 'name': u'Montréal'},
            ],
            'layout': {
                'title': 'Dash Data Visualization'
            }
        }
    )
])
if __name__ == '__main__':
    app.run_server(debug=False)

output:

Running on http://127.0.0.1:8050

While trying to launch this on my host IP as 10.*.*.*:8050.Its  not launching on this nor on local host ip mentioned.

I have run the same app using jupyter plotly dash package,its running fine.I am not understanding why the dash refushed to connect .

Here is my code using jupyter_plotly_dash 

import jupyter_plotly_dash as JupyterDash
import dash_core_components as dcc
import dash_html_components as html
external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']
app = JupyterDash('Sample Dash')
app.layout = html.Div(children=[
    html.H1(children='Hello Dash'),
   html.Div(children='''
        Dash: A web application framework for Python.
    '''),

    dcc.Graph(
        id='example-graph',
        figure={
            'data': [
                {'x': [1, 2, 3], 'y': [4, 1, 2], 'type': 'bar', 'name': 'SF'},
                {'x': [1, 2, 3], 'y': [2, 4, 5], 'type': 'bar', 'name': u'Montréal'},
            ],
            'layout': {
                'title': 'Dash Data Visualization'
            }
        }
    )
])
if __name__ == '__main__':
    app.run_server(debug=False)

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
