### ISSUE TITLE
[BUG] numpy types used in arguments like Slider.marks are not JSON encoded

### ISSUE THREAD

**Issue by alessioarena** [plotly/dash#1169]
I created a multi page dashboard using the Location components to trigger different layout. However, I discovered that if using directly numpy types to set properties like marks in a Slider, those trigger the `dash.exceptions.InvalidCallbackReturnValue` exception.

**Describe your context**
Python 3.6.6

```
dash                          1.9.1
dash-core-components          1.8.1
dash-html-components          1.0.2
dash-renderer                 1.2.4
dash-table                    4.6.1
```
    - OS: Windows 10
    - Browser: Any

**Describe the bug**

if running the following example you will receive the following exception:
```
dash.exceptions.InvalidCallbackReturnValue: 
The callback for property `children`
of component `page-content` returned a value
which is not JSON serializable.

In general, Dash properties can only be
dash components, strings, dictionaries, numbers, None,
or lists of those.
```
```python
import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output, State
import numpy as np


app = dash.Dash(__name__)
app.scripts.config.serve_locally = True
app.css.config.serve_locally = True
server = app.server
app.config['suppress_callback_exceptions']=True

app.layout = html.Div([
    dcc.Location(id='url', refresh=True),
    html.Div(id='page-content', className='twelve columns')
])


@app.callback(
    output=Output('page-content', 'children'),
    inputs=[Input('url', 'hash')]
)
def renderer(pathname):
    out = dcc.Slider(
        id='distance_slider',
        min=0,
        max=150,
        step=1,
        marks={i:str(i) for i in np.arange(0, 151, 25)},
        value=12,
        className='ghost input-slider'
    )
    return out

if __name__ == '__main__':
    app.run_server(debug=True)
```

However, if replacing the mark argument with `{int(i):str(i) for i in np.arange(0, 151, 25)}`, the error will disappear and the slider will be correctly rendered.

I could not find any problem using numpy types in other arguments like `max`. For that reason I suspect that the dictionary wrapping those values may have something to do with the bug.

Once isolated this is a simple problem to fix. However, if having a hierarchical HTML structure with many Div and other components, this may be very hard to isolate. This was in fact my case. 

**Expected behavior**
numpy types to be casted to JSON compatible one prior to JSON encoding

**Comment by nickmelnikov82** [comment]
When you use the `max` argument, it is directly converted to a regular numeric value, in the case of `marks`, the object is converted to json, but `json.dumps` does not support numpy types. You can either manually cast the type to a number (`int(i):str(i)`), or use the method to convert a numpy list to a normal list (`np.arange(0, 151, 25).tolist()`).

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
