### ISSUE TITLE
[BUG] dcc.DatePickerRange component: component does not accept manual date

### ISSUE THREAD

**Issue by rmmariano** [plotly/dash#1178]
**Describe your context**

Please provide us your environment so we can easily reproduce the issue.

```
dash                 1.10.0 
dash-core-components 1.9.0  
dash-html-components 1.0.3  
dash-renderer        1.3.0  
dash-table           4.6.2
```

-  if frontend related, tell us your Browser, Version and OS

    - OS: Ubuntu 16.04 LTS
    - Browser: Firefox
    - Version: 75.0 (64-bit)

**Describe the bug**

I'm trying to use [dcc.DatePickerRange](https://dash.plotly.com/dash-core-components/datepickerrange) component in my application in order to create a date picker range to my graph.

When I try to insert a manual date inside the input, the new value is saved, but it is not showed on the calendar.

**Expected behavior**

I believe the expected behavior would be the component accept manual date and the calendar date changes to the new value as the current one.
For example: my current year is 2016 and I would like to go to 2019, then I write 2019 on the component and the calendar changes its year to 2020, instead of being showing 2016.

**Reproducible example**

A reproducible example can be found [here](https://github.com/inpe-cdsr/catalog-dash/tree/example). I've created this branch from an application I'm starting developing. The steps to run the application are described inside the `README.md` file. This branch does not need database connection, then set the environment variables is not necessary, in other words, the step `set -a && source dash.env && set +a` is not needed to run.

**Screenshots**

My application:

![catalog-dash-2](https://user-images.githubusercontent.com/10242509/78392106-079a2500-75be-11ea-893a-e9ee398c7355.png)

[dcc.DatePickerRange](https://dash.plotly.com/dash-core-components/datepickerrange) example:

![calendar](https://user-images.githubusercontent.com/10242509/78813197-06447000-79a3-11ea-9e07-c1f09e4764ba.png)

Thank you in advance.

**Comment by chriddyp** [comment]
Thanks @rmmariano ! Could you share a simple, reproducible example?

**Comment by rmmariano** [comment]
Of course sir.

I've created a reproducible example and I updated my issue.

One thing I've noticed is that the component accepts the manual date, but the calendar date does not change, because of that, I got confused and I will update the issue.

Excuse me for bothering you.

Thank you so much.

**Comment by arisliang** [comment]
this would be pretty useful, because it seems the picker widget can't jump around the years

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
