### ISSUE TITLE
[BUG] dcc.Location does not trigger callback under certain conditions

### ISSUE THREAD

**Issue by ghost** [plotly/dash#1181]
Thank you so much for helping improve the quality of Dash!

We do our best to catch bugs during the release process, but we rely on your help to find the ones that slip through.

**Describe your context**
Please provide us your environment so we can easily reproduce the issue.

-  replace the result of `pip list | grep dash` below
```
dash                 1.9.0
dash-core-components 1.8.0
dash-html-components 1.0.2
dash-renderer        1.2.4
dash-table           4.6.0
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: Linux (openSUSE Leap 15.1)
    - Firefox (68.6.0esr 64-bit) / Chrome (80.0.3987.163 64-bit)

**Describe the bug**

A callback in a multi-page app only gets triggered by a url change if the callback has a single output. If there are two outputs, the callback never happens.

**Expected behavior**

A callback that is triggered by a url change should always fire, independent of the number and type of outputs.

**Simple reproducible example**

In the following simple, reproducible example app2 works correctly, app1 does not. The only difference between both apps is that the callback in app2 has a single output (updating a label with the pathname), while the callback in app1 has two outputs (updating two labels with the pathname).

app.py

```
import dash
app = dash.Dash(__name__)
server = app.server
app.config.suppress_callback_exceptions = True
```

index.py

```
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output

from app import app
import app1
import app2


app.layout = html.Div([
    dcc.Location(id='url', refresh=True),
    html.Div(id='page-content')
])

index_page = html.Div([
    html.Div([
        html.H1('Index Page'),
        dcc.Link('Go to Page 1', href='app1'),
        dcc.Link('Go to Page 2', href='app2'),
    ], className='subpage')
], className='page')

@app.callback(Output('page-content', 'children'),
              [Input('url', 'pathname')])
def display_page(pathname):
    print('index:', pathname)
    if pathname == '/app1':
        return app1.layout
    elif pathname == '/app2':
        return app2.layout
    else:
        return index_page

if __name__ == '__main__':
    app.run_server(debug=True)
```

app1.py

```
import dash_html_components as html
import dash_core_components as dcc
from dash.dependencies import Input, Output

from app import app

layout = html.Div([
    html.Div([
        html.H1('Page 1'),
        dcc.Link('Go to Index', href='index_page'),
        dcc.Link('Go to Page 2', href='app2'),
        html.H3(id='label_page1', children='none'),
        html.H3(id='label2_page1', children='none'),
        ], className='subpage')
], className='page')


@app.callback([Output('label_page1', 'children'),
               Output('label2_page1', 'children')],
              [Input('url', 'pathname')])
def update_sample_info(pathname):
    print('page1:', pathname)
    return(pathname, pathname)

```
app2.py

```
import dash_html_components as html
import dash_core_components as dcc
from dash.dependencies import Input, Output

from app import app

layout = html.Div([
    html.Div([
        html.H1('Page 2'),
        dcc.Link('Go to Index', href='index_page'),
        dcc.Link('Go to Page 1', href='app1'),
        html.H3(id='label_page2', children='none')
        ], className='subpage')
], className='page')


@app.callback(Output('label_page2', 'children'),
              [Input('url', 'pathname')])
def update_sample_info(pathname):
    print('page2:', pathname)
    return(pathname)
```

**Comment by chriddyp** [comment]
I suspect that this will be fixed as part of #1103

**Comment by chriddyp** [comment]
@clausimu - Could you try upgrading to Dash 1.11.0 and see if this error has been fixed? We fixed many issues related to multiple callbacks in that release.

**Comment by clausimu** [comment]
@chriddyp - When I upgrade to Dash 1.12.0 I get the following error:

`socket.gaierror: [Errno -2] Name or service not known`

The problem disappears once I revert back to version 1.9.0. I did notice that in version 1.9.0 the first output line says: 

`Running on http://127.0.0.1:8050/`

whereas in version 1.12.0 it says:

`Running on http://BrainDynamics:8050/`

I'm sorry, I'll have to figure out where this comes from before I can test using the new version of Dash.

**Comment by chriddyp** [comment]
@clausimu - Just wanted to follow up here - is this still an issue for you after upgrading? It's not clear to us if this is a bug or not yet.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
