### ISSUE TITLE
[BUG] Ordering dash_table does not work properly.

### ISSUE THREAD

**Issue by sorenwacker** [plotly/dash#1188]
Thank you so much for helping improve the quality of Dash!

We do our best to catch bugs during the release process, but we rely on your help to find the ones that slip through.

**Describe your context**
Please provide us your environment so we can easily reproduce the issue.

-  replace the result of `pip list | grep dash` below
```
dash                      1.9.0      
dash-bootstrap-components 0.8.3      
dash-core-components      1.8.0      
dash-html-components      1.0.2      
dash-renderer             1.2.4      
dash-table                4.6.0 
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: Windows10
    - Browser Chrome
    - Version latest

Ordering dash_table does not work properly. Ordering by a column that contains: 'CA_1', 'CA_2', 'CA_3', 'CA_4' unsorted. 

When sorted it ends up 'CA_2', 'CA_1', 'CA_3', 'CA_4'.

This is the only column that where sorting is activated. So, interference from other columns. I would expect 

 'CA_1', 'CA_2', 'CA_3', 'CA_4' 

or

 'CA_4', 'CA_3', 'CA_2', 'CA_1'

**Comment by alexcjohnson** [comment]
Thanks for the report @soerendip! Can you provide a simplified app that reproduces this?

**Comment by sorenwacker** [comment]
Closing this for now.
