### ISSUE TITLE
[BUG] Rangebreaks from Figure.update_xaxes() aren't applied when rendered with Dash

### ISSUE THREAD

**Issue by StaticVOiDance** [plotly/dash#1196]
```
dash                 1.9.1
dash-core-components 1.8.1
dash-daq             0.1.7
dash-html-components 1.0.2
dash-renderer        1.2.4
dash-table           4.6.1
```
Platform:
    - OS: Windows 10 x64
    - Browser: Chrome
    - Version:  81.0.4044.92

Using _Figure.update_xaxes()_ with _rangebreaks_ it is expected that the xaxis will be broken where specified in the _values_ parameter. Behaviour is different when rendering the plot using _Figure.show()_.
When rendering the plot using _dcc.Graph()_ the _rangebreaks_ parameters are not applied and the axis remains continuous.

I also tested this using rangebreaks _pattern_ and _bounds_ with the same result.

Example below shows the same exact plotting code rendered with Dash vs show().

### Output from Figure.show() [Correct Behaviour]
![plotly_generated](https://user-images.githubusercontent.com/10998918/79279658-84f64d00-7e7c-11ea-9ada-55a988f36c29.png)
### Ouput from Dash [Incorrect Behaviour]
![dash_generated](https://user-images.githubusercontent.com/10998918/79279659-84f64d00-7e7c-11ea-8a85-6cf3bd3d19e0.png)

### Sample Code Used to Generate Plots
```
import datetime

import pandas as pd
import numpy as np

import dash
import dash_core_components as dcc
import dash_html_components as html

import plotly.graph_objects as go

app = dash.Dash(__name__)

ts = pd.date_range('2020-1-1', '2020-4-1', freq=datetime.timedelta(hours=1))
data = pd.DataFrame({
    'timestamp': ts,
    'data': np.random.rand(len(ts))
})
data.iloc[1000:1500, 1] = 0.5  # Add some flat data so it will be obvious if the range is removed from the xaxis

trace = go.Scatter(
    name='Value',
    x=data.timestamp,
    y=data.data,
    mode='lines'
)
fig = go.Figure([trace])
fig.update_xaxes(
    rangebreaks=[
        dict(
            dvalue=1000 * datetime.timedelta(days=1).total_seconds(),  # Set dvalue to one day
            values=data[data.data == 0.5].timestamp.dt.date.unique()   # Grab all the days where the data value is flat
        )
    ]
)

app.layout = html.Div(children=[
    dcc.Graph(
        id='time-series',
        figure=fig,
    )
])

if __name__ == '__main__':
    fig.show()
    app.run_server(debug=True)
```

**Comment by alexcjohnson** [comment]
You'll need the latest version of Dash as well - `pip install --upgrade dash`, which will upgrade `dash-core-components` as well - since it bundles its own version of plotly.js for async loading.

**Comment by StaticVOiDance** [comment]
I installed with conda. I didn't realize the conda-forge version version behind PyPI?

**Comment by StaticVOiDance** [comment]
Updating to latest on PyPI fixed this issue.

**Comment by alexcjohnson** [comment]
OK good. I'll close this issue, but yes, conda-forge is a bit behind. Currently the dash feedstock is a community effort, we'll discuss whether Plotly folks could take a more proactive role there. Sorry about the confusion!

**Comment by mihirpandya82** [comment]
> ```
> dash                 1.9.1
> dash-core-components 1.8.1
> dash-daq             0.1.7
> dash-html-components 1.0.2
> dash-renderer        1.2.4
> dash-table           4.6.1
> ```
> 
> Platform:
> - OS: Windows 10 x64
> - Browser: Chrome
> - Version: 81.0.4044.92
> 
> Using _Figure.update_xaxes()_ with _rangebreaks_ it is expected that the xaxis will be broken where specified in the _values_ parameter. Behaviour is different when rendering the plot using _Figure.show()_.
> When rendering the plot using _dcc.Graph()_ the _rangebreaks_ parameters are not applied and the axis remains continuous.
> 
> I also tested this using rangebreaks _pattern_ and _bounds_ with the same result.
> 
> Example below shows the same exact plotting code rendered with Dash vs show().
> 
> ### Output from Figure.show() [Correct Behaviour]
> ![plotly_generated](https://user-images.githubusercontent.com/10998918/79279658-84f64d00-7e7c-11ea-9ada-55a988f36c29.png)
> 
> ### Ouput from Dash [Incorrect Behaviour]
> ![dash_generated](https://user-images.githubusercontent.com/10998918/79279659-84f64d00-7e7c-11ea-8a85-6cf3bd3d19e0.png)
> 
> ### Sample Code Used to Generate Plots
> ```
> import datetime
> 
> import pandas as pd
> import numpy as np
> 
> import dash
> import dash_core_components as dcc
> import dash_html_components as html
> 
> import plotly.graph_objects as go
> 
> app = dash.Dash(__name__)
> 
> ts = pd.date_range('2020-1-1', '2020-4-1', freq=datetime.timedelta(hours=1))
> data = pd.DataFrame({
>     'timestamp': ts,
>     'data': np.random.rand(len(ts))
> })
> data.iloc[1000:1500, 1] = 0.5  # Add some flat data so it will be obvious if the range is removed from the xaxis
> 
> trace = go.Scatter(
>     name='Value',
>     x=data.timestamp,
>     y=data.data,
>     mode='lines'
> )
> fig = go.Figure([trace])
> fig.update_xaxes(
>     rangebreaks=[
>         dict(
>             dvalue=1000 * datetime.timedelta(days=1).total_seconds(),  # Set dvalue to one day
>             values=data[data.data == 0.5].timestamp.dt.date.unique()   # Grab all the days where the data value is flat
>         )
>     ]
> )
> 
> app.layout = html.Div(children=[
>     dcc.Graph(
>         id='time-series',
>         figure=fig,
>     )
> ])
> 
> if __name__ == '__main__':
>     fig.show()
>     app.run_server(debug=True)
> ```

I am facing same issue even with latest version of dash 1.19.0. rangebreaks working fine with fig.show() but when used with dcc.Graph rangebreaks not working... did you get what could be the reason for this ?

**Comment by pesuventurelabs** [comment]
Even I'm facing the same issue, Can someone please resolve this?
