### ISSUE TITLE
Dash Chloropeth Maps

### ISSUE THREAD

**Issue by parker84** [plotly/dash#1202]
Hi,

Excellent package!

Issue: the figures from this tutorial: https://plotly.com/python/choropleth-maps/ can't actually be passed into dash applications.

To replicate error:
```python
import plotly.express as px
import dash
import dash_core_components as dcc
import dash_html_components as html

df = px.data.election()
geojson = px.data.election_geojson()

fig = px.choropleth(df, geojson=geojson, color="Bergeron",
                    locations="district", featureidkey="properties.district",
                    projection="mercator"
                   )
fig.update_geos(fitbounds="locations", visible=False)
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})


app = dash.Dash()
app.layout = html.Div([
    dcc.Graph(figure=fig)
])

app.run_server(debug=True)  # Turn off reloader if inside Jupyter
```
Then you'll see the figure is empty.

And I've had a lot of difficulty finding any simple examples of deploying a chloropeth map using a GEOjson in Dash.

**Comment by chriddyp** [comment]
@parker84 Have you tried upgrading `dash` recently? `pip install dash --upgrade`

**Comment by alexcjohnson** [comment]
This kind of issue keeps coming up... I wonder if we should emit a warning when the `dash-core-components` version of plotly.js is older than the `plotly` version?

**Comment by chriddyp** [comment]
Yeah that's a great idea

**Comment by parker84** [comment]
The upgrade fixed it!
Thank you @chriddyp!

Weird because I very recently pip installed dash.
