### ISSUE TITLE
[Feature Request] callback_context support for clientside callbacks

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash#1213]
When implemented, there are some community forum requests to follow up on: https://community.plotly.com/t/clientside-callbacks-equivalent-for-dash-callback-context/29305

**Comment by mrdawson** [comment]
This would be great! Has anyone thought about how to implement this? I'm interested in working on it, but after some time digging around I'm still a bit unsure of where to start.

**Comment by mrdawson** [comment]
https://github.com/plotly/dash/pull/1240

**Comment by mfreeborn** [comment]
@chriddyp Suggest closing this now #1240 is merged?

**Comment by alexcjohnson** [comment]
Yes, thanks @mfreeborn - and thanks again @mrdawson for the great PR 🎉
