### ISSUE TITLE
[Feature Request] GUI for dash_app.layout code

### ISSUE THREAD

**Issue by karankharecha** [plotly/dash#1222]
### Problem Description
Users are linking custom CSS and JS that are currently available on the internet but if such **assets** are not available on the internet, they need some web development knowledge to design esthetic dashboard. Additionally, designing the standard layout that looks proper on all the devices, is still something that demands more time and efforts. In general, the layout of dashboards often uses **div** as parent tag that contains all the widgets, graphs or any other component. The issue is about setting parameters like: width (min. and max.), height (min. and max.), and other responsive properties among these **div** tags. However, the goal of _dash_ is to prevent Data Scientists in spending more time in layout and web design. For example, below dashboard would have prototype similar to:

Final Dashboard Design:
![image](https://user-images.githubusercontent.com/26277509/80730139-93c93a80-8adf-11ea-95f0-c882f13ca042.png)

Prototype:
![image](https://user-images.githubusercontent.com/26277509/80730570-1eaa3500-8ae0-11ea-94a0-0b66ddbe5582.png)

Above prototype is simple but may get complex when number of sections are increased. Data Scientists are not as skillful as web developers in designing standard responsive applications. Therefore, much of the time is spent in designing such layouts.

### Solution
Solution to this, is adding the feature of _allowing users to specify the parameters of all the sections of their application_. Basically, users can define the layout just by adjusting the sizes of the blocks. Considering a new webpage on the dash’s website that consists of cell grid (like spreadsheet). Adjusting the sizes will result into the similar prototype that is defined above.

Next step, after defining the prototype is to generate a **python file (.py file)**, that has **dash_app.layout** code ready.

Sample output of python code that should be generated.
![image](https://user-images.githubusercontent.com/26277509/80732306-82356200-8ae2-11ea-9477-1bc76a7702ca.png)

In the above image, green coloured text shows sections where users should write code of the components, without mentioning responsive styling properties. This feature will greatly affect the development time as dashboard creator will not have to write HTML tags again and again. They can simply focus on data processing and its visualization. The output python file will have tags or bookmarks that denote the sections where python code for data processing and visualization should be added. Therefore, users will not have to deal with responsive styling as **className and other properties will be pre-defined before they start plotting.**

### Alternatives (Similar Tools)
This feature is slightly similar to the [Bootstrap Studio](https://bootstrapstudio.io/). Users can use the studio to set the parameters using **GUI** and download the HTML file. In case of _Dash_, as the layout is defined in python file, _Dash’s new feature can provide users a **GUI** which eventually output the python file with **dash_app.layout**_. Another tool is [Spring Initializr](https://start.spring.io/) of Spring framework (Java) that provides the functionality to download the .zip file, as per the parameters set by users. **Further, these files can be used directly.**

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
