### ISSUE TITLE
Updatemenus support?

### ISSUE THREAD

**Issue by nkrumm** [plotly/dash#123]
Thanks for all the great work on Dash!

I am wondering if there is support for the `updatemenu` function, as there is in plotly proper. My initial efforts have resulted in rendering of the custom menu/buttons on the graph, but no action takes place (and the React state does not seem to update).

Alternatively -- Is there a way to have the updatemenu GUI be linked to a callback in dash?

Edit:
It looks like there is support for the `relayout` function via `updatemenus`. I am wondering if this also supports (perhaps unofficially) updating the `data`/traces of a plot? Looking at the source code it looks like it is possible, since Plotly.restyle does take a `traces` argument, but I'm not sure if that can actually update the traces on the plot itself.

**Comment by chriddyp** [comment]
Thanks @nkrumm !

You should be able to update the graph client-side through the `updatemenus` object. There is an example of this in the uber rides demo: https://plot.ly/dash/gallery/uber-rides/. Here is the source with `updatemenus`: https://github.com/plotly/dash-uber-rides-demo/blob/7f584e0af74da02bfb80d88a0dc37e8cded8dc7d/app.py#L467

> Alternatively -- Is there a way to have the updatemenu GUI be linked to a callback in dash?

This might be possible through listening to the `relayoutData` object, but I haven't tested this myself. Something like:
```
@app.callback(Output('graph', 'figure'), [Input('graph', 'relayoutData')])
```

**Comment by nkrumm** [comment]
@chriddyp thanks for the tip! I will try this. Let's close this now (would have been better to post this on the community forum anyways, but I didn't know about that at the time)
