### ISSUE TITLE
[BUG] persistence doesn't work with dict() id's

### ISSUE THREAD

**Issue by MM-Lehmann** [plotly/dash#1245]
```
dash                 1.12.0
dash-core-components 1.10.0
dash-html-components 1.0.3
dash-renderer        1.4.1
dash-table           4.7.0
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: linux
    - Browser firefox
    - Version 76

**Describe the bug**

When using new style `id=dict(...)` compoents like `dcc.Checklist` or `dcc.Input`, the value is not persistent (`persistence_type='session'`) over a page refresh. An ambiguous storage item is created but vanishes upon page refresh: `_dash_persistence.[object Object].value.true`. All is good, when using the old style `id=str(...)`.

**Comment by alexcjohnson** [comment]
Thanks @MM-Lehmann - good catch! Should be an easy fix.

**Comment by MM-Lehmann** [comment]
Cool. If there's anything I can help with (apart from testing ;)), let me know.
