### ISSUE TITLE
[CODE-DOC] replace attribute=Component.UNDEFINED by default values

### ISSUE THREAD

**Issue by MM-Lehmann** [plotly/dash#1251]
When displaying the inline code documentation, it is very hard to read through all those `Component.UNDEFINED` attribute defaults. Could we not replace those by their default values or None? At least with a `repr()` of some kind?
Or is this just me with PyCharm?

**Comment by chriddyp** [comment]
We can't actually use `None` or default values because explicitly providing `None` is different than not providing any value at all. For context, see this PR that introduced `Component.UNDEFINED`: https://github.com/plotly/dash/pull/276
