### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by hivemall** [plotly/dash#1268]
adding a `Input` and `Div` to the layout_index of your exmaple, suddenly react warns:
example: `Dynamically Create a Layout for Multi-Page App Validation`

```
import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output, State

import flask

app = dash.Dash(__name__)

url_bar_and_content_div = html.Div([
    dcc.Location(id='url', refresh=False),
    html.Div(id='page-content')
])

layout_index = html.Div([
    dcc.Link('Navigate to "/page-1"', href='/page-1'),
    html.Br(),
    dcc.Link('Navigate to "/page-2"', href='/page-2'),
    html.Br(),
    dcc.Input(id="input_1", type="text", placeholder="PW", debounce=True),
    html.Div('div_1', id='div_1'),
])

layout_page_1 = html.Div([
    html.H2('Page 1'),
    dcc.Input(id='input-1-state', type='text', value='Montreal'),
    dcc.Input(id='input-2-state', type='text', value='Canada'),
    html.Button(id='submit-button', n_clicks=0, children='Submit'),
    html.Div(id='output-state'),
    html.Br(),
    dcc.Link('Navigate to "/"', href='/'),
    html.Br(),
    dcc.Link('Navigate to "/page-2"', href='/page-2'),
])

layout_page_2 = html.Div([
    html.H2('Page 2'),
    dcc.Dropdown(
        id='page-2-dropdown',
        options=[{'label': i, 'value': i} for i in ['LA', 'NYC', 'MTL']],
        value='LA'
    ),
    html.Div(id='page-2-display-value'),
    html.Br(),
    dcc.Link('Navigate to "/"', href='/'),
    html.Br(),
    dcc.Link('Navigate to "/page-1"', href='/page-1'),
])

# index layout
app.layout = url_bar_and_content_div

# "complete" layout
app.validation_layout = html.Div([
    url_bar_and_content_div,
    layout_index,
    layout_page_1,
    layout_page_2,
])


# Index callbacks
@app.callback(Output('page-content', 'children'),
              [Input('url', 'pathname')])
def display_page(pathname):
    if pathname == "/page-1":
        return layout_page_1
    elif pathname == "/page-2":
        return layout_page_2
    else:
        return layout_index


# Page 1 callbacks
@app.callback(Output('output-state', 'children'),
              [Input('submit-button', 'n_clicks')],
              [State('input-1-state', 'value'),
               State('input-2-state', 'value')])
def update_output(n_clicks, input1, input2):
    return ('The Button has been pressed {} times,'
            'Input 1 is "{}",'
            'and Input 2 is "{}"').format(n_clicks, input1, input2)


# Page 2 callbacks
@app.callback(Output('page-2-display-value', 'children'),
              [Input('page-2-dropdown', 'value')])
def display_value(value):
    print('display_value')
    return 'You have selected "{}"'.format(value)


@app.callback(Output('div_1', 'children'),
              [Input('input_1', 'value')])
def update_output(value_1):
    return f'ok: {value_1}'
    # return dash.no_update # same issue


if __name__ == '__main__':
    app.run_server(debug=True)

```

The warning appears Once on the first change, please how to solve?:

 
> react-dom@16.v1_4_1m…89749557.13.0.js:82 Warning: A component is changing an uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components
>     in input (created by n)
>     in n (created by CheckedComponent)
>     in CheckedComponent (created by TreeContainer)
>     in UnconnectedComponentErrorBoundary (created by withRadiumContexts(UnconnectedComponentErrorBoundary))
>     in withRadiumContexts(UnconnectedComponentErrorBoundary) (created by ConnectFunction)
>     in ConnectFunction (created by TreeContainer)
>     in TreeContainer (created by ConnectFunction)
>     in ConnectFunction (created by TreeContainer)
>     in div (created by u)
>     in u (created by CheckedComponent)
>     in CheckedComponent (created by TreeContainer)
>     in UnconnectedComponentErrorBoundary (created by withRadiumContexts(UnconnectedComponentErrorBoundary))
>     in withRadiumContexts(UnconnectedComponentErrorBoundary) (created by ConnectFunction)
>     in ConnectFunction (created by TreeContainer)
>     in TreeContainer (created by ConnectFunction)
>     in ConnectFunction (created by TreeContainer)
>     in div (created by u)
>     in u (created by CheckedComponent)
>     in CheckedComponent (created by TreeContainer)
>     in UnconnectedComponentErrorBoundary (created by withRadiumContexts(UnconnectedComponentErrorBoundary))
>     in withRadiumContexts(UnconnectedComponentErrorBoundary) (created by ConnectFunction)
>     in ConnectFunction (created by TreeContainer)
>     in TreeContainer (created by ConnectFunction)
>     in ConnectFunction (created by TreeContainer)
>     in div (created by u)
>     in u (created by CheckedComponent)
>     in CheckedComponent (created by TreeContainer)
>     in UnconnectedComponentErrorBoundary (created by withRadiumContexts(UnconnectedComponentErrorBoundary))
>     in withRadiumContexts(UnconnectedComponentErrorBoundary) (created by ConnectFunction)
>     in ConnectFunction (created by TreeContainer)
>     in TreeContainer (created by ConnectFunction)
>     in ConnectFunction (created by UnconnectedContainer)
>     in div (created by UnconnectedGlobalErrorContainer)
>     in div (created by GlobalErrorOverlay)
>     in div (created by GlobalErrorOverlay)
>     in GlobalErrorOverlay (created by DebugMenu)
>     in div (created by DebugMenu)
>     in DebugMenu (created by UnconnectedGlobalErrorContainer)
>     in div (created by UnconnectedGlobalErrorContainer)
>     in UnconnectedGlobalErrorContainer (created by withRadiumContexts(UnconnectedGlobalErrorContainer))
>     in withRadium

**Comment by hivemall** [comment]
solution: set the value to empty string to have it not be `undefined` in react
`    dcc.Input(value='THIS', id="input_1", type="text", placeholder="PW", debounce=True),
`

**Comment by tashrifbillah** [comment]
Hi @hivemall , setting `value=''` solved the warning. Can we update this [doc](https://dash.plotly.com/dash-core-components/input) accordingly? I think I can do a PR as well if you guide me a little how to.
