### ISSUE TITLE
[BUG] no way to run the first tutorial on distant machine

### ISSUE THREAD

**Issue by camelator** [plotly/dash#1273]
My system is a distant ARM machine.
I've simply installed dash with pip as described on part 1 of the tutorial.
I tried to run the first tutorial:
https://dash.plotly.com/layout

Then instead of visit localhost in firefox I just wrote the address of the ARM machine in my address bar:
http://192.168.2.114:8050/ instead of http://127.0.0.1:8050/ as written in the tutorial.
it displays a connection failed page.

Don't know what to do, my ARM machine is definitely accessible: I have docker running on it, with portainer, code-server , web server, ...

any help?

**Comment by camelator** [comment]
ok.. Found the issue,
for a distant machine, it is important to write :
app.run_server(host='ip address',debug=True) instead of
app.run_server(debug=True)

**Comment by alexcjohnson** [comment]
or `host='0.0.0.0'` I believe will work regardless of the specific IP address.

Closing as this won't result in changes to dash itself, but if you can see a good place to describe this in the docs `dash.plotly.com` feel free to open an issue (or even better make a PR!) at https://github.com/plotly/dash-docs

**Comment by camelator** [comment]
I admit it is a better answer :)
