### ISSUE TITLE
[Feature Request] Provide CSS wrappers for laying out element of the app

### ISSUE THREAD

**Issue by gioxc88** [plotly/dash#1286]
After digging a bit in the official documentation I think that it is not clear to people without any knowledge of html or CSS, how to actually lay out elements within the app layout.

Similar to what `ipywidgest` provides in [this](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Styling.html#The-Grid-layout) documentation, I think also the Dash documentation should have a page specific to the layout.

Also it would be advisable to provide some basic classes for this. This should be something similar to what `ipywidgets` does by providing `HBox` and `VBox` which make the layout of you application very easy to organize and you don't even need to know about the existence of CSS.

In the end I think it all comes down to user experience and I think that with little tweaks this would become much more enjoyable to use from a user perspective.

Here is an example of what the wrapper should look like (and it is very very simple). Again I was inspired by `ipywidgets`  `HBox` and `VBox` because you end up using this two base wrappers all the time when building the app.

**First of all you should decide which CSS framework to use fro the wrapper.**
For illustration I decided to go with [Skeleton](https://github.com/dhg/Skeleton) because is the one that Dash uses.

**Second you need to provide two basic wrappers for rows and columns that should be used instead of the class `Div`.**
The code below illustrates the idea. Basically you define a class `Column(number, offset)` that returns returns a `Div` with a specific skeleton class for example `Column(2)` corresponds to `Div(className='two columns')`. The second parameter offset, for example `Column(2, 3)` is the same as `Div(className='two columns offset-by-three')`

```
class Row(Div):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, className='row', **kwargs)


class Column(Div):
    def __init__(self, *args, **kwargs):
        '''
        :param number: int or float. Number of columns according to Skeleton CSS. 
                       For example 2 corresponds to className='two columns', 0.5 corresponds to className='six columns'.
        :param offset: int or float. Number of columns to offset according to Skeleton CSS. 
                       For example 2 corresponds to className='offset-by-two', 
                       0.5 corresponds to className='offset-by-six'
        '''

        number = args[0] if len(args) == 1 else kwargs.pop('number', 1.0)
        offset = args[1] if len(args) == 2 else kwargs.pop('offset', None)

        className = self._to_class_name(number, offset)
        super().__init__(*args[2:], className=className, **kwargs)

    @staticmethod
    def _to_class_name(number, offset=None):
        if isinstance(number, float):
            number = round(12 * number)

        number_map = {1: 'one', 2: 'two', 3: 'three', 4: 'four', 5: 'five',
                      6: 'six', 7: 'seven', 8: 'eight', 9: 'nine', 10: 'ten',
                      11: 'eleven', 12: 'twelve'}
        class_name = f'{number_map.get(number)} column{"" if number == 1 else "s"}'
        if offset:
            if isinstance(number, float):
                offset = round(12 * offset)
            offset = f'offset-by-{number_map.get(offset)}'
            class_name = f'{class_name} {offset}'
        return class_name
```

**Third you need to provide a section in the documentation that explains the basics of how it works** Even simply linking to [this](http://getskeleton.com/) would do the job.
I am sure I was not paying enough attention but I could find anything about this topic in the documentation.

Finally if used in conjunction with the new layout I proposed [here](https://github.com/plotly/dash/issues/1282) this would be very powerful way to create a layout.

![image](https://user-images.githubusercontent.com/41852601/83175220-dd776600-a11b-11ea-8c8c-4dda97249a7e.png)

below the code for creating this simple layout by using the `Row` and `Column` class defined above

```
app.layout = (
        Div(className='container') *
            Row() *
                html.Img(src='https://upload.wikimedia.org/wikipedia/commons/3/37/Plotly-logo-01-square.png',
                             style={'width': '30%', 'height': 'auto'}) /
            Row() *
                Column(0.15) *
                    html.Label('start date') @
                    dcc.DatePickerSingle(id='date_start',
                                         placeholder='start date',
                                         persistence=True,
                                         display_format='DD MM YYYY') @
                    html.Label('end date') @
                    dcc.DatePickerSingle(id='date_end',
                                         placeholder='end date',
                                         persistence=True,
                                         display_format='DD MM YYYY') @
                    html.Label('Input1') @
                    dcc.Input(id='input1',
                              type='number',
                              placeholder='input2',
                              persistence=True,
                              style={'width': 130}, min=1) @
                    html.Label('Input2') @
                    dcc.Input(id='input2',
                              type='number',
                              placeholder='input1',
                              persistence=True,
                              style={'width': 130}, min=1) @
                    html.Div(style={'margin-top': '30px'}) *
                        html.Button('generate', id='gen', className='button-primary') /2/
                Column(0.5, id='out') *
                    table /2/
            html.Div(id='hidden-div', style={'display': 'none'})
)
```

**Comment by nicolaskruchten** [comment]
Have you checked out [Dash Bootstrap Components](https://dash-bootstrap-components.opensource.faculty.ai/) ? It implements something similar to what you describe.

**Comment by gioxc88** [comment]
> Have you checked out [Dash Bootstrap Components](https://dash-bootstrap-components.opensource.faculty.ai/) ? It implements something similar to what you describe.

This is exactly what I was looking for.
I am sorry for opening the issue but, after checking the Dash documentation, I wrongly assumed that all the opensource components were already listed on the web site.

This is actually super useful!!!
