### ISSUE TITLE
[BUG] Page gets refreshed during callback and the Output gets cleared whenever I write something to the app folder

### ISSUE THREAD

**Issue by gioxc88** [plotly/dash#1293]
I have a callback that gets fired when I click on a button.
Inside the call back:

1. I download some data from the web and 
2. I write them to a csv file as well as 
3. I log to a .txt file. 
4. The `Output` of my callback are the `children` of an empty `Div` that gets populated with a dash table containing the data I just downloaded

my folder structure is the following
```
app
    log
        log.txt
    output
        df.csv
    app.py
```
I had a very hard time isolating the problem but I am 100% sure because I ran line by line.
What happens is that every time I write something, either the logger that logs to the .txt of the callback function that writes the dataframe to the csv, the dash app gets refreshed and the `Output` of the call back function is goes back to it's original state of empty `Div`, so it's updated after the function successfully terminate.

So I can actually see the page gets refreshed a number of times equal to the the times the log function gets called (like `logger.info('something') `) plus when I write to csv

As long as I comment all the line were I write to file everything works as expected.
As long as there is even only one line were I write to a file the page gets refreshed and the `Output` gets back to it's original state of empty 'Div`.

So to be precise the `Output` is updated but then is deleted because of this refreshing.
It's like the app is listening to what is happening in the folders ad is refreshed as soon as something changes.

Any idea of why this is happening and how to solve it?
Many thanks

**Comment by alexcjohnson** [comment]
Are you running the app with hot reloading enabled? By default if you use 
```py
app.run_server(debug=True)
```
that will turn on hot reloading. To disable it (but keep the rest of debugging enabled) do:
```py
app.run_server(debug=True, dev_tools_hot_reload=False)
```
More details: https://dash.plotly.com/devtools

**Comment by gioxc88** [comment]
I appreciate you answer. Thank you for clarifying. I did indeed read about this feature but my understanding was that it only looks at python files and inside the assets folder.
At this point I realize my understanding is wrong.

Is there a way to specify the exclusion of certain folders from the hot reload?

Many thanks for taking time to answer my issue.
Gio

**Comment by GitHunter0** [comment]
> Is there a way to specify the exclusion of certain folders from the hot reload?

This would help a lot.
