### ISSUE TITLE
[BUG] Markdown adding white space in links

### ISSUE THREAD

**Issue by leo-smi** [plotly/dash#1295]
**Markdown adding white space in links**

```
		    dcc.Markdown(id = 'markSobreOsDados', className = 'markSobreOsDados',
		        children = [
    		        """
                        #### SOBRE OS DADOS
                        - **Dados federais:**
                        Os dados de entrada que foram utilizados no modelo para os novos casos e óbitos relacionados ao
                        COVID-19 por município e estado, são provenientes de órgãos governamentais como, Secretarias estaduais
                        de saúde e do Ministério da Saúde, compilados por iniciativas independentes (BRASIL.IO, 2020; COTA, 2020),
                        uma vez que os dados para os municípios de todas as regiões brasileiras não estão consolidados em uma única
                        base de dados governamental aberta.
                        - **Dados mundiais:**
                        Os dados mundiais são obtidos através do [link](https://www.ecdc.europa.eu/en/publications-data/download-todays-data-geographic-distribution-covid-19-cases-worldwide).
                        - **Dados de taxa de letalidade:**
                        Outra alteração realizada é que não havia a Taxa de Letalidade (do inglês, Infection Fatality Rate, IFR)
                        para alguns Estados (GO, MS, MT e DF). Nestes casos, foi realizada uma interpolação com os dados de IFR e
                        Renda média per capita de SP e SC (IBGE, 2019).
                        - **Nota:**
                        Apesar dos dados serem atualizados diariamente, por limitações computacionais e o sistema já estar operacional
                        para cada um dos municípios, por enquanto, as simulações serão apresentadas apenas para o Brasil e os Estados.
                        Além disso, os resultados serão atualizados semanalmente e a previsão será de 20 dias, embora já seja possível realizar para um período maior.

                        Referências
                        BRASIL IO. COVID-19 - Datasets - Brasil.IO. 2020. Disponível em: https://brasil.io/dataset/covid19/caso/. Acesso em: 4 maio 2020.
                        COTA, W. wcota/covid19br. [S.l: s.n.], 2020. Disponível em: https://github.com/wcota/covid19br. Acesso em: 4 maio 2020.
                        IBGE  IBGE divulga o rendimento domiciliar per capita 2019. Disponível em: https://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/26956-ibge-divulga-o-rendimento-domiciliar-per-capita-2019
    		        """
		        ]
		    )
````

```
dash                      1.12.0
dash-bootstrap-components 0.10.1
dash-core-components      1.10.0
dash-html-components      1.0.3
dash-renderer             1.4.1
dash-table                4.7.0
```
- Hosted in pythonanywhere.com

![image](https://user-images.githubusercontent.com/20663547/84180378-ca3e9180-aa5d-11ea-8b2a-6e97d099cdde.png)

**Comment by alexcjohnson** [comment]
Is there some extra CSS on the page adding this spacing? Inspecting the `<a>` element should be able to tell you which file this spacing is coming from. I don't think the `dcc.Markdown` itself is doing this, as we use that for links all over https://dash.plotly.com/ among other places.

**Comment by leo-smi** [comment]
> Is there some extra CSS on the page adding this spacing? Inspecting the `<a>` element should be able to tell you which file this spacing is coming from. I don't think the `dcc.Markdown` itself is doing this, as we use that for links all over https://dash.plotly.com/ among other places.

Yes, there is a ``<a>`` tag, but I did not put in there, my css code:

```
.markPublicacoes, .markSobreOModelo, .markSobreOsDados {
    grid-column: 2/3;
    width:100%;
    overflow: scroll;
}
```

![image](https://user-images.githubusercontent.com/20663547/84225463-8e371b00-aab5-11ea-9cf2-72c8cf94cdfb.png)

**Comment by leo-smi** [comment]
> The place to look to figure out which CSS setting is creating this padding is the style pane:
> <img alt="Screen Shot 2020-06-10 at 10 39 15 AM" width="336" src="https://user-images.githubusercontent.com/2678795/84281641-d0d51380-ab06-11ea-9706-90ad5ce7d9ed.png">
> It's not necessarily exactly a `padding` property creating this, but that pane also lets you turn off these properties one-by-one, by clicking the checkbox that appears when you hover over a property - that should allow you to figure out exactly which one is responsible. That screenshot is from Chrome but most browsers should have similar functionality.

My bad

The website is: https://projetogyro.pythonanywhere.com/

![image](https://user-images.githubusercontent.com/20663547/84338152-be43f400-ab71-11ea-871c-db39cef96331.png)

**Comment by leo-smi** [comment]
Problem solved, thank you!

![image](https://user-images.githubusercontent.com/20663547/84338738-3eb72480-ab73-11ea-8007-a41dac881020.png)

Code before:
```
a {
	color:white;
	padding:0px 2vw 0px 2vw;
	text-decoration:none;
}
```

Code after:
```
.aInicio, .aPublicacoes,  .aSobreOModelo, .aSobreOsDados, .aInMemoriam, .aEquipe {
	color:white;
	padding:0px 2vw 0px 2vw;
	text-decoration:none;
}
```
