### ISSUE TITLE
[BUG] ClickData callback not triggering when clicking the same segment of pie chart

### ISSUE THREAD

**Issue by wompo** [plotly/dash#1300]
**Describe your context**
Please provide us your environment so we can easily reproduce the issue.

```
dash                 1.12.0
dash-core-components 1.10.0
dash-html-components 1.0.3
dash-renderer        1.4.1
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: Windows 10
    - Browser: chrome
    - Version: 83.0.4103.97 (Official Build) (64-bit)

**Describe the bug**

When using pie chart clickData as an input for a callback, it does not trigger when clicking the same segment twice (or multiple times) in a row.

**Expected behavior**

I would expect the callback to trigger again with the same clickData.

**Simple app**

A simple app to help reproduce the bug.

```
import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output
import json

labels = ['Oxygen','Hydrogen','Carbon_Dioxide','Nitrogen']
values = [4500, 2500, 1053, 500]

app = dash.Dash(__name__)

app.layout = html.Div([
    dcc.Graph(
        id='pie',
        figure={
            'data': [{
                'values': values,
                'labels': labels,
                'type': 'pie'
            }]
        }
    ),
    html.Pre(id='clickDataDisplay')
])

@app.callback(
    Output('clickDataDisplay', 'children'),
    [Input('pie', 'clickData')]
)
def display_click_data(clickData):
    print("Processing click data.")
    return json.dumps(clickData, indent=2)

if __name__ == '__main__':
    app.run_server(debug=True)
```

**Comment by codebicycle** [comment]
It affects bar charts as well as pie charts.
Actually, it affects all charts supported by `dcc.Graph`, starting with Dash version 1.11.0.

From Dash v1.11.0 release notes:
>"A user interaction which returns the same property value as was previously present will not trigger the component to re-render, nor trigger callbacks using that property as an input."

Are there any workarounds to trigger a callback when clicking on the same section of a graph again?

**Comment by ValeriyaGriffiths** [comment]
I've got the same problem in dash 1.13.4. Any updates regarding a fix or a workout would be very much appreciated.

**Comment by bonobo1** [comment]
I have the same problem with a Choroplethmapbox

**Comment by panizoeva** [comment]
Same issue here in environment:
```
dash                                      1.17.0.             
dash-core-components      1.13.0             
dash-html-components      1.1.1   
dash-renderer                     1.8.3  
dash-table                           4.11.0   
```

**Comment by nukescott** [comment]
still broken in:
dash 1.19.0
dash-core-components 1.15.0
dash-html-components 1.1.2
dash-renderer 1.9.0
dash-table 4.11.2

**Comment by alexcjohnson** [comment]
We've been discussing internally whether there's a better way to handle this, but as a workaround in dash 1.19, due to https://github.com/plotly/dash/pull/1525, you should be able to set `clickData` to `None` or some such as the output of your callback, then repeated clicks will register.

```py
@app.callback(
    Output('clickDataDisplay', 'children'),
    Output('pie', 'clickData'),
    Input('pie', 'clickData')
)
def display_click_data(clickData):
    print("Processing click data.")
    return json.dumps(clickData, indent=2), None
```

**Comment by nukescott** [comment]
Adding an Output with clickData, and returning None does indeed avoid the problem.  Thanks so much!

**Comment by pmkroeker** [comment]
> 
> 
> We've been discussing internally whether there's a better way to handle this, but as a workaround in dash 1.19, due to #1525, you should be able to set `clickData` to `None` or some such as the output of your callback, then repeated clicks will register.
> 
> ```python
> @app.callback(
>     Output('clickDataDisplay', 'children'),
>     Output('pie', 'clickData'),
>     Input('pie', 'clickData')
> )
> def display_click_data(clickData):
>     print("Processing click data.")
>     return json.dumps(clickData, indent=2), None
> ```

When I try this I get a an error in the browser.

>"Same `Input` and `Output`"

The same solution was proposed [for this issue](https://github.com/plotly/dash/issues/1574#issuecomment-799794681), but the same problem happened. Is  there a way to prevent those errors? They cause the entire dashboard to not render.

**Comment by nphausg** [comment]
It works on dash:2.7.1

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson

**Comment by JulianoLagana** [comment]
This is still a problem in dash 2.15.0.
