### ISSUE TITLE
Flask route returns 403 due to CSRF failure when using multiple worker process

### ISSUE THREAD

**Issue by ned2** [plotly/dash#132]
I've tried running a Dash app with multiple worker processes using both Gunicorn and mod_wsgi-express and have found that this results in the `_dash-update-component` route responding with a 403 Bad Request response intermittently. 

After digging into it a bit I think what's happening is that the Dash app is loaded as a separate instance within each worker process, which results in a different CSRF secret key being generated for the SeaSurf middleware for each worker process, but the client only knows about one of them. So the app might work ok for a few requests, while worker with the right key happens to handle the requests, but as soon as a worker with a non-matching key is allocated to handle the request, we get this error: 

```
--------------------------------------------------------------------------------      
WARNING in flask_seasurf [[...]lib/python3.6/site-packages/flask_seasurf.py:282]:
Forbidden (CSRF token missing or incorrect.): /_dash-update-component                 
--------------------------------------------------------------------------------
```

And indeed initialising the Dash app with `csrf_protect=False` makes this problem go away.

I've found a simple workaround for this issue when using Gunicorn, which is to set the preload_app setting to True, which can be done by providing the --preload flag on the command line. eg:

`gunicorn  --preload --workers 2 --bind 0.0.0.0:5000 main:app.server`

This has the effect of making Gunicorn load the app first before the worker process are forked, meaning they all share the same initialised state (and therefore the same secret key). This is also useful if your Dash app involves memory intensive objects, as you only need to store one copy in memory rather than n copies, where n is the number of workers.

It could be worth finding a more general solution (I haven't looked into whether there's a similar preload setting for mod_wsgi), or maybe this this is an acceptable workaround, in which case perhaps this wants to be documented somewhere. I'd be happy to put together a Gunicorn section for the deployment page in the Dash User Guide.

**Comment by nirvana-msu** [comment]
You should simply explicitly set the key when creating a Flask server:

```python
server = Flask(__name__)
server.secret_key = 'your_secret_key_here'

app = dash.Dash(server=server)
```

This way all workers would have the same key.

**Comment by ned2** [comment]
Ahhh, yes of course. Good point. I guess the one advantage of my workaround is that you then don't need to have to worry about managing a secrets file etc, seeing as you wouldn't want to explicitly set it within a file that's going into source control.

**Comment by nirvana-msu** [comment]
You generally do want to manage those secrets in production, If you keep generating new secret key on each restart (and workers may well often be reloaded) it will invalidate user sessions, so users will constantly see those 403 errors and would need to reload the page all the time.

**Comment by ned2** [comment]
Ahh yes, another good point! Thanks for that :)

**Comment by chriddyp** [comment]
The way these secrets are typically managed is through environmental variables like this:
```
server.secret_key = os.environ.get('secret_key', 'secret_key_default')
```
