### ISSUE TITLE
[BUG] DataTable argument cell_selectable not accepted but stated in documentation 

### ISSUE THREAD

**Issue by maulberto3** [plotly/dash#1321]
**Describe your context**
DataTable argument cell_selectable not accepted but yes in documentation 

```
dash==1.9.1
dash_table==4.6.1
dash_core_components==1.8.1
```
```
OS: Windows 10 Home
Browser: Microsoft Edge v83
Version: 
```

**Describe the bug**

DataTable argument cell_selectable not accepted but stated at documentation .

**Expected behavior**

It should accept it and not let data cells highlight to red when clicked on.

**Screenshots**

![image](https://user-images.githubusercontent.com/22672781/86519740-11206c80-bdfb-11ea-8b71-65131950f6c6.png)

![image](https://user-images.githubusercontent.com/22672781/86519745-1f6e8880-bdfb-11ea-8305-49bb8a938244.png)

**Comment by chriddyp** [comment]
This was added in dash-table 4.8.0. Try upgrading dash with `pip install dash --upgrade` 🙂

**Comment by chriddyp** [comment]
(https://github.com/plotly/dash-table/blob/master/CHANGELOG.md#480---2020-06-17)
