### ISSUE TITLE
[BUG] connectgaps working strange in dash 

### ISSUE THREAD

**Issue by avats-dev** [plotly/dash#1334]
**Strange behavior of go.scatter in dash app**
I'm using dash on windows 10

-  as grep can't be used on windows, I'm attaching below a snap from `pip list`
![pip dash list](https://user-images.githubusercontent.com/35889327/87215211-db770880-c351-11ea-90a1-e63a28aa375d.png)

-  other system configurations and info

    - OS: Windows 10 *(Build:19041.329)*
    - Browser: Chrome *(Version 83.0.4103.116 (Official Build) (64-bit)*

I plotted using following code:
```df = pd.read_csv('day_wise.csv')
fig = go.Figure()
fig.add_trace(go.Scatter(x=df['date'], y = df['tot'],
                            mode='lines+markers',
                            connectgaps=True
                        )
             )
fig.show()
```
**It seems that `connectgaps` is not working as it should**

It rendered strangely in dash app, and when I plotted it in jupyter notebook, it worked fine. 
In dash app, it looked like this:
![newplot (1)](https://user-images.githubusercontent.com/35889327/87215300-f302c100-c352-11ea-9ae4-be04561ce080.png)

And in notebook, it looked like this:
![newplot](https://user-images.githubusercontent.com/35889327/87215316-2c3b3100-c353-11ea-899b-11d5c0445368.png)

**I have also mentioned it on the community forum and the topic can be found [here](https://community.plotly.com/t/scatter-plot-behaving-strange-in-dash-app/42331?u=avats-dev).**

The dataset used in this plot can be found [here](https://drive.google.com/file/d/1lNMliafZgAwwauBDst-SxW0m8hKZ9Gc3/view?usp=sharing).

**Comment by chriddyp** [comment]
This is likely not a bug but a difference in version numbers or other differences in the preprocessing before the data was plotted. Let's continue the discussion in the community forum, where some folks in the community are already helping out by creating reproducible examples.
