### ISSUE TITLE
[BUG] setting UTF-8 locale cause closing of app

### ISSUE THREAD

**Issue by zdenop** [plotly/dash#1335]
After upgrading python from 3.6 to 3.8.3  (Windows 10 64bit) my app stop to working (dash/flask server finished and no information in browser was shown). Finally I found problem: setting locale to UTF-8 variant. 
Here is minimal  code for reproducing problem:

```
import locale
import dash
import dash_html_components as html

app = dash.Dash(__name__)
ret_val = locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')
print(ret_val)
app.layout = html.Div('working')

if __name__ == '__main__':
    app.run_server(port=9999, debug=True)
```

If I use `ret_val = locale.setlocale(locale.LC_ALL, 'en_US')`  code is working as expect. But I see no reason why `UTF-8` should (silently) close my app (especially my app was working on python 3.6 without problem).

**Comment by T4rk1n** [comment]
I don't think this is related to dash but something with the locale going from python 3.6 to 3.8
