### ISSUE TITLE
[BUG] Second digit of Page number in DashTable gets cropped

### ISSUE THREAD

**Issue by e-alizadeh** [plotly/dash#1336]
Results of `pip list | grep dash`
```
dash                  1.4.1               
dash-core-components  1.3.1               
dash-daq              0.2.2               
dash-html-components  1.0.1               
dash-renderer         1.1.2               
dash-table            4.4.1 
```

**Describe the bug**
When dash table has more than 10 pages, the second digit of the page number gets cropped.

**Expected behavior**
If the DashTable has more than 10 pages, I would expect the page number (out of total) appears completely.

**Screenshots**
<img width="444" alt="Screen Shot 2020-07-15 at 8 44 40 AM" src="https://user-images.githubusercontent.com/30320825/87546530-b2b78180-c677-11ea-88fc-487577391faa.png">

**Comment by elfjes** [comment]
This seems to be a CSS issue. What happens when you disable all (custom) css?

**Comment by alexcjohnson** [comment]
Closed by https://github.com/plotly/dash-table/pull/819
