### ISSUE TITLE
AttributeError: partially initialized module ‘dash_html_components’ has no attribute ‘Div’ (most likely due to a circular import)

### ISSUE THREAD

**Issue by reazmohiuddin** [plotly/dash#1356]
I am running Ubuntu LTS 20.04 with Python 3.8.2

I have used ‘pip3 install’ to install all latest required packages.

I am trying to run the following code:

import dash
import dash_core_components as dcc
import dash_html_components as html

app = dash.Dash() #creates flask application

colors = {'background':'#111111','text':'#7FDBFF'}

app.layout = html.Div(children = [
        html.H1('Hello Dash!',style={'textAlign':'center',
                                     'color':colors['text']}),
        #html.Div('Dash: Web Dashboards with Python'),
        dcc.Graph(id = 'example',
                  figure={'data':[
                          {'x':[1,2,3],'y':[4,2,1],'type':'bar','name':'SF'},
                          {'x':[1,2,3],'y':[2,4,5],'type':'bar','name':'NYC'}
                          ],
                          'layout':{
                                  'plot_bgcolor':colors['background'],
                                  'paper_bgcolor':colors['background'],
                                  'font':{'color':colors['text']},
                                  'title':'BAR PLOTS!'
                                  }})
        ], style = {'backgroundColor':colors['background']}
)

if _name_ == '__main__':
    app.run_server()

**Comment by alexcjohnson** [comment]
Thanks @reazmohiuddin - can you post the complete traceback?

**Comment by reazmohiuddin** [comment]
Hi, I have fixed it. I had a file named dash_html_components.py in my working directory. When I tried to import the package, it was pulling in the file in the working directory instead of the correct file in the package. I removed the file and that fixed it. Thanks.
