### ISSUE TITLE
[Feature Request] Support for Pytest 6

### ISSUE THREAD

**Issue by rbpatt2019** [plotly/dash#1365]
**Is your feature request related to a problem? Please describe.**
Currently, I use the dash-testing extra for writing tests for my apps. Big fan of how streamlined it makes the progress! However, it pegs pytest at v5.3.5 as a requirement, which means I can't take advantage of the new Pytest v6 release - can you say pyproject.toml and full type hinting!

**Describe the solution you'd like**
Support for pytest v6

**Describe alternatives you've considered**
Not supporting pytest v6. But there are some pretty powerful features added here, so (personally) I don't think this is a good decision. 

**Additional context**
I'm not sure if this would be a big undertaking or not. I'm happy to tackle it, if people are interested, though I'll probably have questions along the way!

**Comment by alexcjohnson** [comment]
Thanks @rbpatt2019 - we'd be happy to use the latest and greatest, and I don't know what kind of breaking changes pytest v6 makes but AFAIK we're not using really esoteric features of it anyway. So feel free to make a PR and maybe everything will just work - CI will tell us :)

**Comment by rbpatt2019** [comment]
See #1368.
