### ISSUE TITLE
Triggering local script from Dash webapp

### ISSUE THREAD

**Issue by sovisova** [plotly/dash#1381]
Hi I'm building dash enterprise application with Heroku. I want users to be able to trigger, from a button in dash app, a local (pre-installed) executable file. Is this possible? How might I do this?

**Comment by emilhe** [comment]
When you say ‘local’, do you mean server side (where the Dash app runs) or client side?

**Comment by sovisova** [comment]
Client side sorry. I know that could be seen as a security risk. However, the apps will be secured and the local exe files perform some harmless tasks. The apps may also be deployed only on a private network. Machines are Windows 10. Reason is I want users to have Dash app as main work interface and not exit to use the exe files. We have a lot of legacy exe files that should run client side, more efficient from a resource point of view.

**Comment by sovisova** [comment]
Client side sorry. I know that could be seen as a security risk. However, the apps will be secured and the local exe files perform some harmless tasks. The apps may also be deployed only on a private network. Machines are Windows 10. Reason is I want users to have Dash app as main work interface and not exit to use the exe files. We have a lot of legacy exe files that should run client side, more efficient from a resource point of view.

**Comment by sovisova** [comment]
Client side sorry. I know that could be seen as a security risk. However, the apps will be secured and the local exe files perform some harmless tasks. The apps may also be deployed only on a private network. Machines are Windows 10. Reason is I want users to have Dash app as main work interface and not exit to use the exe files. We have a lot of legacy exe files that should run client side, more efficient from a resource point of view.

**Comment by sovisova** [comment]
Client side sorry. I know that could be seen as a security risk. However, the apps will be secured and the local exe files perform some harmless tasks. The apps may also be deployed only on a private network. Machines are Windows 10. Reason is I want users to have Dash app as main work interface and not exit to use the exe files. We have a lot of legacy exe files that should run client side, more efficient from a resource point of view.

**Comment by sovisova** [comment]
Client side sorry. I know that could be seen as a security risk. However, the apps will be secured and the local exe files perform some harmless tasks. The apps may also be deployed only on a private network. Machines are Windows 10. Reason is I want users to have Dash app as main work interface and not exit to use the exe files. We have a lot of legacy exe files that should run client side, more efficient from a resource point of view.

**Comment by sovisova** [comment]
Client side sorry. I know that could be seen as a security risk. However, the apps will be secured and the local exe files perform some harmless tasks. The apps may also be deployed only on a private network. Machines are Windows 10. Reason is I want users to have Dash app as main work interface and not exit to use the exe files. We have a lot of legacy exe files that should run client side, more efficient from a resource point of view.

**Comment by sovisova** [comment]
Client side sorry. I know that could be seen as a security risk. However, the apps will be secured and the local exe files perform some harmless tasks. The apps may also be deployed only on a private network. Machines are Windows 10. Reason is I want users to have Dash app as main work interface and not exit to use the exe files. We have a lot of legacy exe files that should run client side, more efficient from a resource point of view.

**Comment by sovisova** [comment]
Client side sorry. I know that could be seen as a security risk. However, the apps will be secured and the local exe files perform some harmless tasks. The apps may also be deployed only on a private network. Machines are Windows 10. Reason is I want users to have Dash app as main work interface and not exit to use the exe files. We have a lot of legacy exe files that should run client side, more efficient from a resource point of view.

**Comment by sovisova** [comment]
Client side sorry. I know that could be seen as a security risk. However, the apps will be secured and the local exe files perform some harmless tasks. The apps may also be deployed only on a private network. Machines are Windows 10. Reason is I want users to have Dash app as main work interface and not exit to use the exe files. We have a lot of legacy exe files that should run client side, more efficient from a resource point of view.

**Comment by sovisova** [comment]
Client side sorry. I know that could be seen as a security risk. However, the apps will be secured and the local exe files perform some harmless tasks. The apps may also be deployed only on a private network. Machines are Windows 10. Reason is I want users to have Dash app as main work interface and not exit to use the exe files. We have a lot of legacy exe files that should run client side, more efficient from a resource point of view.

**Comment by sovisova** [comment]
Client side sorry. I know that could be seen as a security risk. However, the apps will be secured and the local exe files perform some harmless tasks. The apps may also be deployed only on a private network. Machines are Windows 10. Reason is I want users to have Dash app as main work interface and not exit to use the exe files. We have a lot of legacy exe files that should run client side, more efficient from a resource point of view.

**Comment by sovisova** [comment]
Client side sorry. I know that could be seen as a security risk. However, the apps will be secured and the local exe files perform some harmless tasks. The apps may also be deployed only on a private network. Machines are Windows 10. Reason is I want users to have Dash app as main work interface and not exit to use the exe files. We have a lot of legacy exe files that should run client side, more efficient from a resource point of view.

**Comment by sovisova** [comment]
Client side sorry. I know that could be seen as a security risk. However, the apps will be secured and the local exe files perform some harmless tasks. The apps may also be deployed only on a private network. Machines are Windows 10. Reason is I want users to have Dash app as main work interface and not exit to use the exe files. We have a lot of legacy exe files that should run client side, more efficient from a resource point of view.

**Comment by sovisova** [comment]
Client side sorry. I know that could be seen as a security risk. However, the apps will be secured and the local exe files perform some harmless tasks. The apps may also be deployed only on a private network. Machines are Windows 10. Reason is I want users to have Dash app as main work interface and not exit to use the exe files. We have a lot of legacy exe files that should run client side, more efficient from a resource point of view.

**Comment by sovisova** [comment]
Client side sorry. I know that could be seen as a security risk. However, the apps will be secured and the local exe files perform some harmless tasks. The apps may also be deployed only on a private network. Machines are Windows 10. Reason is I want users to have Dash app as main work interface and not exit to use the exe files. We have a lot of legacy exe files that should run client side, more efficient from a resource point of view.

**Comment by emilhe** [comment]
I don't believe that this is possible. As you indicate yourself, it would be a security risk.
