### ISSUE TITLE
prevent_initial_call in callback throws exception [BUG]

### ISSUE THREAD

**Issue by rpmchale** [plotly/dash#1383]
Thank you so much for helping improve the quality of Dash!

We do our best to catch bugs during the release process, but we rely on your help to find the ones that slip through.

**Describe your context**
Please provide us your environment so we can easily reproduce the issue.

-  replace the result of `pip list | grep dash` below
```
dash                      1.15.0
dash-bootstrap-components 0.9.2
dash-core-components      1.11.0
dash-html-components      1.1.0
dash-renderer             1.7.0
dash-table                4.10.0
```

**Describe the bug**

With the release of Dash 1.15.0. Setting prevent_initial_call in a callback now throws an exception.
It appears prevent_initial_call must be explicitly provided as a named parameter ex. prevent_initial_call=True. This was not previously the case if all parameters (Output, Input, State, and prevent_initial_call) were provided.

  File "C:\Program Files\Python36\lib\site-packages\dash\dash.py", line 980, in callback
    _args, _kwargs
  File "C:\Program Files\Python36\lib\site-packages\dash\dependencies.py", line 159, in handle_callback_args
    prevent_initial_call = args.pop()
AttributeError: 'tuple' object has no attribute 'pop' 

**Expected behavior**

An exception should not be thrown.

**Comment by alexcjohnson** [comment]
Thanks @rpmchale - confirmed. I think I see another issue in `handle_callback_args` as well. We'll get this fixed!
