### ISSUE TITLE
Flask-cache cannot cache go.Layout and go.scatter object

### ISSUE THREAD

**Issue by flamingofugang** [plotly/dash#139]
Hi,

I tried to use Flask-Cache according to this post: https://plot.ly/dash/performance
I have a callback function to update the figure of a dcc.Graph, the figure is a dict of data and layout, both of which are plotly.graph_objs, something like:
@cache.memoize(timeout=60) 
def update_figure(value):
    return {'data': [], 'layout': go.Layout()}

I got the NoneType error message:
  File "/local/anaconda3/envs/tsmodel/lib/python3.6/site-packages/werkzeug/contrib/cache.py", line 582, in dump_object
    return b'!' + pickle.dumps(value)
TypeError: 'NoneType' object is not callable

I think the plotly.graph_objs cannot be serielized in this case, how to solve this issue?

Best,
Gang

**Comment by chriddyp** [comment]
Good question @flamingofugang . For now, you can work around this issue by replacing the `go.*` objects with simple `dict` and `list`. The `go` objects actually subclass `dict` and `list`, so this is safe to do.

For the trace types, you'll need to add a ``type'` key that specifies the type of trace. For example, these two objects are "equivalent" (in the sense that they will end up getting serialized as JSON as the same thing and therefore will render the same graph):

```python
go.Bar(
   x=[1, 2, 3],
   y=[3, 1, 5],
   marker=go.Marker(color='blue')
)
```

```python
dict(
   x=[1, 2, 3],
   y=[3, 1, 5],
   marker=dict(color='blue'),
   type='bar' # Note this!
)
```

For `go.Layout`, it's the same thing as a dict:
```
go.Layout(title='my graph title', xaxis=go.XAxis(title='my x axis title'))
```

is the same as
```
dict(title='my graph title', xaxis=go.XAxis(title='my x axis title'))
```

**Comment by chriddyp** [comment]
I'll close this for now but feel free to reopen if this doesn't fix the issue. Thanks for reporting!
