### ISSUE TITLE
Running into functools32 requirement error for requirements.txt on python3.4

### ISSUE THREAD

**Issue by sangmeshcp** [plotly/dash#14]
hi ,

I'm trying to install the requirements.txt and running into functools32 .. I see tox.ini for python3 and python2.7 .. So , I'm assuming it is suppose to work .. any issues here ??
OS : Mac 
Python Version: python 3.4 
Collecting functools32==3.2.3.post2 (from -r requirements.txt (line 14))
  Using cached functools32-3.2.3-2.zip
    Complete output from command python setup.py egg_info:
    This backport is for Python 2.7 only.

**Comment by chriddyp** [comment]
thanks for reporting @sangmeshcp ! The `requirements.txt` file is just for developing on the package locally. Can you confirm that `pip install plotly` works on `Python 3.4`? 

Perhaps we should make the `requirements.txt` more explicit for each version: `requirements-27.txt` and `requirements-3.txt`?

**Comment by jackwluo** [comment]
Same error as I had the other day for the oil and gas app. I think best
approach is to freeze two requirements

**Comment by chriddyp** [comment]
@jackwluo - Can you confirm that `pip install plotly` works on Python 3.4? The requirements.txt is only used (by me) for development for now, so the end-users shouldn't need to install this. I can update the file for the contributors though.

**Comment by jackwluo** [comment]
I'll try in a venv for py3.4

On Jun 21, 2017 1:33 PM, "Chris Parmer" <notifications@github.com> wrote:

@jackwluo <https://github.com/jackwluo> - Can you confirm that pip install
plotly works on Python 3.4? The requirements.txt is only used (by me) for
development for now, so the end-users shouldn't need to install this. I can
update the file for the contributors though.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/plotly/dash/issues/14#issuecomment-310150780>, or mute
the thread

**Comment by stephen-hoover** [comment]
`pip install plotly` and `pip install dash` work under Python 3.6.0 (OS X)!

You can use environment markers for requirements.txt to do conditional installations: https://www.python.org/dev/peps/pep-0508/#environment-markers .

**Comment by jackwluo** [comment]
@stephen-hoover yup, just tested that both pip installs on python 3.6 (and 3.4) are working. It seems like the only issue is for the requirements.txt file for contributors, I'll update a version for py 3.x

**Comment by chriddyp** [comment]
Thanks folks!

**Comment by rmarren1** [comment]
I just got this error too, might be useful to have requirement markers

**Comment by toddyc** [comment]
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'appdirs==1.4.3'
PS C:\Users\Chidembot\Desktop\PROJECTS\TRACY\ITS_Smart\smart-tutor-master> pip install -r requirements.txt
Collecting appdirs==1.4.3
  Using cached appdirs-1.4.3-py2.py3-none-any.whl (12 kB)
Collecting certifi==2017.1.23
  Using cached certifi-2017.1.23-py2.py3-none-any.whl (382 kB)
Collecting functools32==3.2.3.post2
  Using cached functools32-3.2.3-2.tar.gz (31 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Chidembot\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\CHIDEM~1\\AppData\\Local\\Temp\\pip-install-zb6z6oby\\functools32\\setup.py'"'"'; __file__='"'"'C:\\Users\\CHIDEM~1\\AppData\\Local\\Temp\\pip-install-zb6z6oby\\functools32\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\CHIDEM~1\AppData\Local\Temp\pip-install-zb6z6oby\functools32\pip-egg-info'
         cwd: C:\Users\CHIDEM~1\AppData\Local\Temp\pip-install-zb6z6oby\functools32\
    Complete output (1 lines):
    This backport is for Python 2.7 only.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by toddyc** [comment]
> ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'appdirs==1.4.3'
> PS C:\Users\Chidembot\Desktop\PROJECTS\TRACY\ITS_Smart\smart-tutor-master> pip install -r requirements.txt
> Collecting appdirs==1.4.3
> Using cached appdirs-1.4.3-py2.py3-none-any.whl (12 kB)
> Collecting certifi==2017.1.23
> Using cached certifi-2017.1.23-py2.py3-none-any.whl (382 kB)
> Collecting functools32==3.2.3.post2
> Using cached functools32-3.2.3-2.tar.gz (31 kB)
> ERROR: Command errored out with exit status 1:
> command: 'C:\Users\Chidembot\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\CHIDEM~1\AppData\Local\Temp\pip-install-zb6z6oby\functools32\setup.py'"'"'; **file**='"'"'C:\Users\CHIDEM~1\AppData\Local\Temp\pip-install-zb6z6oby\functools32\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\CHIDEM~1\AppData\Local\Temp\pip-install-zb6z6oby\functools32\pip-egg-info' cwd: C:\Users\CHIDEM~1\AppData\Local\Temp\pip-install-zb6z6oby\functools32
> Complete output (1 lines):
> This backport is for Python 2.7 only.
> ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Getting this error on trying to pip install requirements.txt. Any workaround?
