### ISSUE TITLE
[Feature Request] Dash pattern matching MATCH without matching outputs

### ISSUE THREAD

**Issue by ronw98** [plotly/dash#1400]
Hi!
I want to use pattern matching to match an Input and a State to update a "global" output (with no MATCH wildcard), as shown in the decorator below
`@app.app.callback(
    Output(utils.GRAPH_CREATION_DIALOG_GRAPH_TITLE, 'value'),
    [
        Input({'type': utils.GRAPH_ITEM_EDIT_BUTTON, 'index': MATCH}, 'n_clicks')
    ],
    [
        State({'type': utils.GRAPH_ITEM_SOURCE_DATA_STORE, 'index': MATCH}, 'data')
    ]
)`

Which is not yet possible is Dash. I found an easy workaround but it would be great if these kind of things could be available in the future!

Thanks!

**Comment by alexcjohnson** [comment]
This is inherently ambiguous and therefore will remain disallowed - see https://github.com/plotly/dash/pull/1103#issuecomment-688898997

Depending on what you're really trying to do, `ALL` may be the solution you're looking for. But this kind of question is better suited to https://community.plotly.com. Thanks!
