### ISSUE TITLE
Default stylesheet showing pen not found error

### ISSUE THREAD

**Issue by DnanaDev** [plotly/dash#1410]
I noticed that one of my hosted Dash app is rendering without any styling. Turns out that the default stylesheet used in the tutorial is not accessible.

I followed the link to the Default style-sheet from codepen and it is showing a Pen Not Found error. I can see the stylesheet after removing the .css suffix. Problem on codepens end ?

https://codepen.io/chriddyp/pen/bWLwgP.css

UPDATE: It's working again or if you have problems see alexcjohnson's solution below.

**Comment by TanguyRiou** [comment]
I was wondering what happened on my dash app thank you DnanaDev!

**Comment by alexcjohnson** [comment]
Thanks for the heads up @DnanaDev! It was always a bit unorthodox for us to be using Codepen to serve CSS - it doesn't look like anything changed with the pen itself but we probably hit some limit on Codepen's side and they've cut it off.

In the short term, your best bet is to visit the full Codepen https://codepen.io/chriddyp/pen/bWLwgP, copy the entire CSS pane, and paste it into a .css file in your app's `assets` directory.

Meantime we'll work out a better place to put publicly accessible stylesheets.

**Comment by DnanaDev** [comment]
@alexcjohnson Thank you, that solves my problem. 
It seems to be happening with all the pens on the explore section too. Could just be an issue on their end.

**Comment by alexcjohnson** [comment]
It looks intentional to me - seems they've started inlining that CSS in the pen HTML and disabled serving the CSS by itself. Perhaps they got tired of serving as a CDN for folks like us 🙈
