### ISSUE TITLE
[Question] How can we change the loading screen and set a custom preloader?

### ISSUE THREAD

**Issue by i-bond** [plotly/dash#1411]
![loading_scr](https://user-images.githubusercontent.com/49706046/93733758-8e889b80-fbf8-11ea-9350-d93afc8fff14.png)

Hello! Is there a way to change the "Loading..." caption when a dashboard is loading or maybe set a custom preloading screen?

**Comment by chriddyp** [comment]
You can override the default "Loading..." and other aspects of the index page that appears on page load via `app.index_string` and other methods, see "Customizing Dash's HTML Index Template" in https://dash.plotly.com/external-resources
