### ISSUE TITLE
dash-table GitHub tag version lags pypi release version

### ISSUE THREAD

**Issue by greyltc** [plotly/dash#1412]
https://github.com/plotly/dash/blob/98e81fc9b531608f6b5e3a6d49f7347772c4188a/requires-install.txt#L7

The latest as of now is 4.10.0

**Comment by alexcjohnson** [comment]
https://pypi.org/project/dash-table/ shows 4.10.1 - what specific symptoms are you seeing?

**Comment by greyltc** [comment]
That's weird.
Where does that release come from?
It's not tagged in the source code: https://github.com/plotly/dash-table/releases
Which is why I said it doesn't exist.

**Comment by squeezer44** [comment]
I also have dash-table 4.10.1. It came during `pip install dash`.

**Comment by greyltc** [comment]
Right.
But what is the origin of that revision if it's not tagged in the source code repositry?
How can the pip repo and the github one even be out of sync?
Shouldn't all info flow from github --> https://pypi.org/ ?

 I build/package from the github source tarballs so I don't care what's hosted on pypi.org

**Comment by alexcjohnson** [comment]
@greyltc I see, thanks for clarifying. In our release process, the PyPI release and the GitHub tag are independent steps, and we purposely delayed the GitHub tags this time around as we're trying to figure out the process for our third back-end language, Julia: https://github.com/plotly/Dash.jl
Bear with us for a bit, once we have that all sorted out there will again be congruence between the two sets of versions.

**Comment by greyltc** [comment]
It's great to hear that you're aware of the issue and it's just a transient one!

**Comment by harryturr** [comment]
@greyltc The dash-table GitHub releases have been retroactively tagged and are up to date.
