### ISSUE TITLE
[BUG] Input, Dropdown, and Graph objects not shown with dash 1.6.1, renderer 1.8.1, core-components 1.12.1

### ISSUE THREAD

**Issue by fspreck-indiscale** [plotly/dash#1414]
**Describe your context**

-  replace the result of `pip list | grep dash` below
```
dash                          1.16.1
dash-bootstrap-components     0.10.6
dash-core-components          1.12.1
dash-daq                      0.5.0
dash-html-components          1.1.1
dash-renderer                 1.8.1
dash-table                    4.10.1
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: Arch Linux
    - Browser: Firefox
    - Version: 81.0

**Describe the bug**

After upgrading to dash-1.16.1, dash-renderer-1.8.1, and dash-core-components-1.12.1, Input, Dropdown, and Graph objects are not displayed in my django dash app, resulting in TypeErrors in `dash_renderer.v1_8_1m1600852457.min.js`.  Downgrading to 1.16.0, 1.8.0, and 1.12.0, respectively, resolves the issue.

**Expected behavior**

All core components that work in 1.16.0 etc should work in 1.16.1, too.

**Comment by alexcjohnson** [comment]
Yikes, that's a bad one! I haven't been able to reproduce it though. Those are the package versions running on https://dash.plotly.com/, do you see any errors if you load for example https://dash.plotly.com/basic-callbacks? What if you copy one of the example apps off that page (for example "Dash App With Multiple Inputs") and run it locally?

**Comment by fspreck-indiscale** [comment]
Hi, and thanks for the answer!  Loading the apps on dash.plotly.com works fine.  I will try running a few of the examples locally later this week and see whether I can reproduce the errors.

**Comment by fspreck-indiscale** [comment]
Whatever the problem was, going to dash-1.16.2 and dash-renderer-1.8.2 resolved it for me.
