### ISSUE TITLE
When providing explicit Flask server, name should not be necessary

### ISSUE THREAD

**Issue by sstirlin** [plotly/dash#142]
When I supply an explicit Flask server, e.g.

    server = Flask('myapp')

then I shouldn't have to supply the `name` to the Dash constructor, i.e. I should just be able to do

    app = dash.Dash(server=server)

instead of

    app = dash.Dash(name='myapp', server=server)

However, currently that doesn't work because of this line:

https://github.com/plotly/dash/blob/master/dash/dash.py#L44

**Comment by ned2** [comment]
I don't think this is a problem any more. @chriddyp?

**Comment by chriddyp** [comment]
Yeah, I don't think it's an issue anymore.
