### ISSUE TITLE
Cannot update a component from a function

### ISSUE THREAD

**Issue by Ierezell** [plotly/dash#1428]
**Describe your context**
-  `pip list | grep dash` 
```
dash                     1.16.1
dash-core-components     1.12.1
dash-html-components     1.1.1
dash-renderer            1.8.1
dash-table               4.10.1
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: Linux (archlinux / zen kernel 5.8.13 )
    - Browser : Firefox
    - Version 81.0.1

**Describe the bug**
I'm writting a benchmark app. 
I added the possibility to run the benchmark python script from dash (a button calling a callback which call the python function).

This benchmark print to stdout which I want to capture and show in the UI. This can be done once the benchmark is finished but I would like to make it more interactive. 

For that I need something to update one element from my funtion (decorated with the callback) 

**Expected behavior**
Be able to update a component from a function. 
**Code example**

Components in a tab :  
```
html.Div(children=[
            html.H5("Frameworks"),
            dcc.RadioItems(
                id="framework_names",
                persistence=True,
                options=[{'label': fn, 'value': fn} for fn in FRAMEWORK_NAMES]
            ),
            html.H5("Datasets"),
            dcc.RadioItems(
                id="dataset_names",
                persistence=True,
                options=[{'label': dn, 'value': dn} for dn in DATASET_NAMES]
            ),
            html.H5("Number of intents"),
            dcc.Slider(
                id="intent_nb", min=2, max=99, value=10, step=1,
                persistence=True,
                marks={v: {'label': str(v)} for v in [2, 5, 10, 20, 50, 80]}
            ),
            html.H5("Number of train utterances per intent"),
            dcc.Slider(
                id="train_nb", min=3, max=99, value=10, step=1,
                persistence=True,
                marks={v: {'label': str(v)} for v in [3, 5, 10, 20, 50, 80]}
            ),
            html.H5("Number of test utterances per intent"),
            dcc.Slider(
                id="test_nb", min=1, max=99, value=10, step=1,
                persistence=True,
                marks={v: {'label': str(v)} for v in [3, 5, 10, 20, 50, 80]}
            ),
            html.Button(id="run_button", children="Run Benchmark"),
            html.P(id="logs", children=[], hidden=False)
        ])
```

My function to launch the code
```
@ app.callback(Output('logs', 'children'),
               [Input('run_button', 'n_clicks')],
               state=[State('intent_nb', 'value'), State('test_nb', 'value'),
                      State('train_nb', 'value'),
                      State('framework_names', 'value'),
                      State('dataset_names', 'value')
                      ])
def launch_benchmark(btn: int, int_nb: int, test_nb: int, train_nb: int,
                     framework_name: str, dataset_name: str):
    if btn is None:
        return

    ch = [html.P(children=str(x)) for x in [int_nb, train_nb, test_nb]]
    ch.extend([html.P(children=" ".join(x))
               for x in [dataset_name, framework_name]])

    with open('./limits.json', 'w') as file:
        json.dump({"MAX_INTENT_NB": int_nb,
                   "MAX_UTT_PER_INTENT": train_nb,
                   "MAX_UTT_PER_TEST": test_nb
                   }, file)
    try:
        f = io.StringIO()
        with redirect_stdout(f), redirect_stderr(f):
            run_benchmark(datasets=[dataset_name], frameworks=[framework_name],
                          test=True)
        create_graphs()
        # print(f.getvalue().split('\n'))
        return html.Div(children=[html.P(c) for c in f.getvalue().split('\n')])

    except BaseException as e:
        print("Error ", e)
        return html.Div(children=[html.H3("Error : "), html.P(str(e))])
```

I can make the `run_benchmark` function iterative and I would like to be able to update the logs at each step... something like : 

```
for step in run_benchmark(datasets=[dataset_name], frameworks=framework_name],True):
    get_logs() = format(step) # which update the log component iteratively
```

I know it's a weird problem, thanks in advance for any help and thanks a lot for this beautiful framework

**Comment by alexcjohnson** [comment]
Not too weird, this kind of issue comes up from time to time. Questions like this are best suited to https://community.plotly.com/ but I'll take a quick stab here:

The typical solution for something like this is to create a `dcc.Interval`, which can normally be turned off (`disabled: True`) until you launch the run; then a callback using the interval as `Input` returns the complete set of logs available at that point. If the logs are extremely long you could just return the new lines to a `dcc.Store` and use a clientside callback to concatenate them onto the previous lines.

For completeness, Dash Enterprise has a push feature that would enable faster responses without the interval.

I'm going to close this as it isn't related to new features or bugs, for further discussion please use the community forum. Thanks!
