### ISSUE TITLE
minor change to documentation on appending css

### ISSUE THREAD

**Issue by jwhendy** [plotly/dash#143]
I just referred to [this page](https://plot.ly/dash/external-resources) on external resources. I think this is a copy/paste error:

>You can embed this stylesheet with this URL https://codepen.io/chriddyp/pen/bWLwgP.css.
>`app.scripts.append_css({'external_url': 'https://codepen.io/chriddyp/pen/bWLwgP.css'})`

I believe that should be:

`app.css.append_css({'external_url': 'https://codepen.io/chriddyp/pen/bWLwgP.css'})`

Sorry if this isn't the right place to post for documentation catches on the actual plot.ly site.

**Comment by chriddyp** [comment]
Thanks for reporting @jwhendy ! Just added this fix in https://github.com/plotly/dash-docs/commit/03c58ceaea700012485ede6aa58325cbf12f596a
