### ISSUE TITLE
[BUG] react-dom: Each child in a list should have a unique "key" prop

### ISSUE THREAD

**Issue by tashrifbillah** [plotly/dash#1433]
I experienced this issue in a bigger context but I found an easy way to reproduce it. Please run the `Quickstart` tutorial from https://dash.plotly.com/datatable

**Screenshots**
![image](https://user-images.githubusercontent.com/35086881/95768459-61258f80-0c84-11eb-9e0e-6b5b95347bba.png)

**Describe your context**
Windows 10 machine on both Edge and Chrome browsers

```
dash                   1.16.2
dash-core-components   1.12.1
dash-extensions        0.0.18
dash-html-components   1.1.1
dash-renderer          1.8.2
dash-table             4.10.1
```

**Expected behavior**

No warning.

**Additional info**
[This](https://github.com/plotly/dash/issues/891) issue might be related but does not appear to give a clear reproduction way which I did in the above.

**Comment by themegaphoenix** [comment]
Hi,
I am also having the same issue.
This pull request might be what we need:
https://github.com/plotly/dash-table/pull/690

**Comment by chriddyp** [comment]
These are just warnings and can be ignored unless you've found a way that this effects the behavior of the table itself.

**Comment by themegaphoenix** [comment]
> These are just warnings and can be ignored unless you've found a way that this effects the behavior of the table itself.

I understand, but nothing makes me happier than a clean console :). It should hopefully be resolved soon

**Comment by tashrifbillah** [comment]
I would love to test this PR. Two points--

* Is the PR from February? Seems a little old.
* How do I install just `dash-table`? I have always done `pip install dash` which had `dash-table` dependency. I can clone the `dash` master and try `pip install .` locally but how do I point to the PR for `dash-table` dependency?

**Comment by antoinerg** [comment]
Closed by https://github.com/plotly/dash/pull/1778

**Comment by michaelbabyn** [comment]
reopening since it looks like this issue still appears when the `presentation` column attribute is set to `markdown` in any of the columns.

E.g see this simple example from the forum:
```python
import dash_bootstrap_components as dbc
from dash import Dash, html, dash_table

import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/solar.csv")

app = Dash(__name__)

app.layout = dash_table.DataTable(
    df.to_dict("records"),
    [{"name": i, "id": i, "presentation": "markdown"} for i in df.columns],
)

if __name__ == "__main__":
    app.run_server(debug=True, port=8092)
```

It appears that this was an omission when markdown presentation mode was added because[ it doesn't have a key prop added](https://github.com/plotly/dash/blob/07be9e2d0c060b929540aee88457bba717123a66/components/dash-table/src/dash-table/derived/cell/contents.tsx#L227-L233) whereas input and [dropdown do](https://github.com/plotly/dash/blob/07be9e2d0c060b929540aee88457bba717123a66/components/dash-table/src/dash-table/derived/cell/contents.tsx#L201)

**Comment by alexjercan** [comment]
I have made the change you suggested @michaelbabyn and the example works without the console error.

**Comment by BaconEggsRL** [comment]
Hi--I am still getting this warning when running the example code here:
https://dash.plotly.com/dash-ag-grid/tooltips
Thoughts?

**Comment by Coding-with-Adam** [comment]
hi @BaconEggsRL 
Can you please share the text message or an image of the warning you're getting?

**Comment by Coding-with-Adam** [comment]
The warning is from ag-grid, It may be missing a key somewhere.
The aria-description is a new dom attribute, seems like it's not supported by earlier react version which is to be expected.

I think you can disregard the warning unless it's impacting the app performance.
