### ISSUE TITLE
Is there a way to export the dash layout as an html?

### ISSUE THREAD

**Issue by diego-ardila-alvarez** [plotly/dash#145]
Is there a way to export the dash layout as an html?

I am familiar with:

import dash
import dash_core_components as dcc
import dash_html_components as html

app = dash.Dash()
...
app.run_server()

In order to render the html output in a browser. Is there a way to directly export the html output into a file? With plotly objects for example, I use,

plot(figure, output_type='div')

To export a single plot as a div. But I would like to combine plots and html components (text, list, etc..) into a single html.

**Comment by ned2** [comment]
The Dash server sends the remote client a JSON serialised representation of the layout tree which is hydrated into HTML by React in the browser. It wouldn't take much to write an HTML export function for a Python layout tree consisting only of the HTML components, however the Dash core components correspond to Dash/React components so the potentially complex custom HTML generation logic for these is handled on the client side -- so server side HTML export doesn't really make sense.

You can however open up the developer tools and copy the HTML contents of nodes in the DOM that you're after.

**Comment by chriddyp** [comment]
You could also try to save the file in your browser as an HTML file. 
![save-file](https://user-images.githubusercontent.com/1280389/32334158-2382b388-bfc0-11e7-8b3b-b2b357cfa358.gif)

This isn't available programatically yet - we would need to somehow render the Dash app in the web browser and then download it (using electron or selenium)

Also note that if you save the file this way as an HTML file, any of the interactivity in your code that use `app.callback` won't work in a standalone HTML file - `app.callback` requires a python server. We may add client-side (JS) built-in interactivity in the future through some type of declarative API (see https://github.com/plotly/dash-renderer/pull/7) but that isn't available yet.

**Comment by ned2** [comment]
Ah yeah saving as HTML in browser works too. View source just shows the initial skeleton HTML so had assumed the same would apply to saving as HTML.

**Comment by chriddyp** [comment]
This will be possible with https://github.com/plotly/dash/issues/266

**Comment by AveryData** [comment]
any new features making the export as HTML possible? Looking to have a button to save as PDF.

**Comment by rsandler00** [comment]
This no longer works. If you save to html and open it, it just says "loading..."
