### ISSUE TITLE
Combining Dropdown and DatePicker!

### ISSUE THREAD

**Issue by bilative** [plotly/dash#1463]
Hi,

Nowadays i am making a dashboard. I have some problem. 
I wanna combine datetimePicker and a dropdown.
I have about 15 variables. And I wanna select a time integer (maybe this could be only 1 day) and after day selected, i wanna see the list of uniqueID's in a dropdown. 

Everyday there are about 10 different unique id. Actually in my dataset there are about 1000 unique id. But as i said when i select 1 day i wanna see only the uniqueID's from this specific day.

Is this possible? Can you help me?

Thanks in advance!!

**Comment by bilative** [comment]
After a week i can say this is so easy. There is no so much example on the internet and generally they are not clear but [this could be good starting point for you](https://www.youtube.com/watch?v=ZxshFO0bbZM&t=160s) about this problem. If you fail when you imp , you can ask me on twitter.

**Comment by hoatranobita** [comment]
@bilative Hi, can you share code for this case? I'm stucking.

**Comment by bilative** [comment]
> @bilative Hi, can you share code for this case? I'm stucking.

Hi,

```python
@app.callback(Output('dropdown-to-send-list', 'options'),
              Input('datetime-picker-that-selected', 'value'))
def listed_ids_by_datepicker(selected_date):
    df = read_from_sql()
    filtered_df = df[df['date'] == selected_date]
    my_unique_ids = filtered_df['unique_id'].unique()
    list_ids = [{'label': i, 'value': i} for i in list(my_unique_ids)]
    return list_ids
```
- Now, I can say that for this task you need 2 callback step. This one is first one; aim of this callback is;
   - When you select a date, this callback filter your possible situations to dropdown for this day, And fills dropdown.
- After this callback you should create another callback and you should only take "dropdowns's value" as input. second callbacks shouldn take datetimepicker.

I hope I could told smooth enough.

**Comment by hoatranobita** [comment]
@bilative Thank for sharing your knowledge.
