### ISSUE TITLE
[Feature Request] relayoutData returns a proper object/dict for 'update_layout' roundtrip and convenience

### ISSUE THREAD

**Issue by sdementen** [plotly/dash#1468]
**Is your feature request related to a problem? Please describe.**

The relayoutData is very useful yet it comes in a format Dict[str]->Any that is not very convenient as keys may have dot and [] notations like in 'xaxis.range[0]' and cannot roundtrip with fig.update_layout (like in `fig.update_layout(**relayoutData)`)

**Describe the solution you'd like**

I would like to get as relayoutData a proper dict/object.
So instead of receiving:
`{'xaxis.range[0]': '2019-01-01', 'xaxis.range[1]': '2019-02-07 04:21:40.9199'}`
I would like to get
`{'xaxis': {'range': ['2019-01-01', '2019-02-07 04:21:40.9199']}}`
or even better 
`{'xaxis': {'range': [datetime(2019,1,1), datetime(2019,2,7,4,21,40.9199)]}}`
(datetime could also be a pandas.timestamp)

**Comment by chriddyp** [comment]
Thanks for opening @sdementen ! Our current spec for addressing this is with a new property for the entire figure minus the data. See https://github.com/plotly/dash-core-components/issues/584

**Comment by chriddyp** [comment]
Thanks for opening @sdementen ! Our current spec for addressing this is with a new property for the entire figure minus the data. See https://github.com/plotly/dash-core-components/issues/584

**Comment by sdementen** [comment]
Even better indeed, thanks!
