### ISSUE TITLE
[BUG] Reproducing tutorial: colorbar does not display

### ISSUE THREAD

**Issue by j-bac** [plotly/dash#1479]
**Describe your context**
Please provide us your environment so we can easily reproduce the issue.

-  replace the result of `pip list | grep dash` below
```
plotly                        4.13.0
dash                          1.17.0
dash-core-components          1.13.0
dash-html-components          1.1.1
dash-renderer                 1.8.3
dash-table                    4.11.0
jupyter-dash                  0.3.1
jupyterlab-dash               0.1.0a2
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: WSL2 (Ubuntu 20.04) in Windows 10
    - Browser: Firefox 
    - Version: 83.0 (64 bits)

**Describe the bug**

The [Colorscales in Dash example](https://plotly.com/python/colorscales/) does not display the colorbar in my browser. It also does not properly switch between colormaps.
`python app.py `

```
Running on http://127.0.0.1:8050/
Debugger PIN: 930-093-681
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
Running on http://127.0.0.1:8050/
Debugger PIN: 983-105-347
```

**Expected behavior**

Expected behavior is the one that is produced in the tutorial webpage

**Screenshots**

![Dash - Mozilla Firefox 12_4_2020 6_02_28 PM](https://user-images.githubusercontent.com/36225255/101192173-fb89ca00-365a-11eb-8ad8-f8f21177ecb2.png)

**Comment by alexcjohnson** [comment]
Thanks @j-bac - that's a puzzling one, I can't reproduce it. Do you see any errors printed either in Python or in the JavaScript console?

**Comment by j-bac** [comment]
Hello, sorry, I ended up solving my issue by recreating my environment, I don't have the initial one anymore. I did not install jupyterlab-dash and this apparently solved my issue, hope it helps others

`pip list | grep dash`

`dash                 1.17.0
dash-core-components 1.13.0
dash-html-components 1.1.1
dash-renderer        1.8.3
dash-table           4.11.0
jupyter-dash         0.3.1`
