### ISSUE TITLE
[BUG] Dash loads the wrong assets folder

### ISSUE THREAD

**Issue by gioxc88** [plotly/dash#1481]
Thank you so much for helping improve the quality of Dash!

We do our best to catch bugs during the release process, but we rely on your help to find the ones that slip through.

**Describe your context**
Please provide us your environment so we can easily reproduce the issue.

-  replace the result of `pip list | grep dash` below
```
dash                 0.42.0
dash-core-components 0.47.0
dash-html-components 0.16.0
dash-renderer        0.23.0
dash-table           3.6.0
```
-  if frontend related, tell us your Browser, Version and OS

**Describe the bug**

**Expected behavior**

**Screenshots**

If applicable, add screenshots or screen recording to help explain your problem.

**Comment by alexcjohnson** [comment]
@gioxc88 looks like this report was submitted without any content - care to elaborate, or did you solve the problem and we should close it?

**Comment by gioxc88** [comment]
> @gioxc88 looks like this report was submitted without any content - care to elaborate, or did you solve the problem and we should close it?

sorry @alexcjohnson for some reason the copy paste didn't work and I didn't notice.
If you want you ca close it for now. I'll reopen it in the weekend.
