### ISSUE TITLE
Dash Basic Authentication Does Not Work on GCP App Engine

### ISSUE THREAD

**Issue by askorostelev** [plotly/dash#1482]
this code works locally on my box, but when deployed to GCP app Engine the application just exits with nothing in the app engine logs or debugging window in Chrome
```
VALID_USERNAME_PASSWORD_PAIRS = {
    'hello': 'world'
}
app = dash.Dash(__name__,external_stylesheets=external_stylesheets)

import dash_auth
VALID_USERNAME_PASSWORD_PAIRS = {
    'hello': 'world'
}
auth = dash_auth.BasicAuth(
    app,
    VALID_USERNAME_PASSWORD_PAIRS
)
```

Error: Server Error
The server encountered an error and could not complete your request.
Please try again in 30 seconds

If i comment out the following line of code, the application works as expected
```
auth = dash_auth.BasicAuth(
    app,
    VALID_USERNAME_PASSWORD_PAIRS
)
```

**Comment by rsavjanimdphd** [comment]
I am having the exact same issue with GCP App Engine. Was there a solution to this issue?

**Comment by askorostelev** [comment]
use a basic yaml file

my yaml was complicated, and after simplification everything works

**Comment by psubbiah** [comment]
Having the same issue, has anyone solved it? My yaml is quite simple.

**Comment by ogyalcin** [comment]
> use a basic yaml file
> 
> my yaml was complicated, and after simplification everything works

I can't believe this worked for me :)
