### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by keithing** [plotly/dash#15]
Hi! I see in your readme and [here](https://github.com/plotly/dash/blob/master/setup.py#L11) that his project has an MIT license.  Would you mind adding a license file just to make that crystal clear?  I'm basing this off the recommendation [here](https://help.github.com/articles/licensing-a-repository/):

> As a best practice, we encourage you to include the license file with your project.

**Comment by chriddyp** [comment]
Just added a license. Thank you @keithing !

**Comment by keithing** [comment]
Quick turnaround! Thanks!
