### ISSUE TITLE
AttributeError: partially initialized module 'dash_html_components' has no attribute 'Div' (most likely due to a circular import)

### ISSUE THREAD

**Issue by pantinashekhar** [plotly/dash#1502]
```py
import dash_html_components as html 
app = Dash(__name__)
app.layout =html.Div(children=[html.H1(children='Hello Dash'),html.Div(children='''Dash: A web application framework for Python.'''),
                                dcc.Graph(id='example-graph', figure={
            'data': [
                {'x': [1, 2, 3], 'y': [4, 1, 2], 'type': 'bar', 'name': 'SF'},
                {'x': [1, 2, 3], 'y': [2, 4, 5], 'type': 'bar', 'name': u'Montréal'},
            ],
            'layout': {
                'title': 'Dash Data Visualization'
                      }
                }
                )
               ])


if __name__ == '__main__':
    app.run_server(host='127.0.0.1',port='8050',debug=True)
```

Dash app is not working because of layout not being there but when I included then the error as shown in title comes.Please request you to help me at the earliest.

Regards
Chandrashekhar

**Comment by alexcjohnson** [comment]
This sounds similar to https://github.com/plotly/dash/issues/1143 (which has been fixed in the dev branch but not yet released). What is the name of this file?

**Comment by pantinashekhar** [comment]
dash.py

**Comment by alexcjohnson** [comment]
yep, that would be it - you can't give your own script a name that matches any of the packages in your system, or when someone else (in this case `dash_html_components`) tries to do `import dash` they'll get your file rather than the installed package. Just change the name to something unique.

**Comment by pantinashekhar** [comment]
Ok I will look into it.Thanks for the prompt reply.

**Comment by pantinashekhar** [comment]
After changing dash to dashed the errors have reduced.but the error I m
getting is class Dash(object) which we defined when I wrote app = Dash() it
says Dash is not defined.

**Comment by alexcjohnson** [comment]
haha I wondered about that - you need `from dash import Dash`

**Comment by pantinashekhar** [comment]
(base) C:\Users\panti\Downloads\dash-dev\dash-dev\dash>python dashed.py
  File "dashed.py", line 1761
    if __name__ == '__main__' :
                              ^
SyntaxError: invalid syntax

**Comment by pantinashekhar** [comment]
if __name__ == '__main__':
    app.run_server(host='127.0.0.1',port='8050',debug=True)


the above is my code and the error is:-
File "dashed.py", line 1760
    if  __name__ ==  '__main__':
                                                 ^
SyntaxError: invalid syntax

**Comment by alexcjohnson** [comment]
Wow, line 1760... you have a lot of code in this file. I'd guess unmatched parentheses or something like that somewhere above this line, but I'd recommend getting an IDE with Python syntax checking, that should help you find the problem. The short code you posted first works fine for me once I add the two additional import statements (`dash` and `dcc`)

**Comment by pantinashekhar** [comment]
Ok thanks I will look into it.

**Comment by alexcjohnson** [comment]
Closing, as this issue won't lead to code changes in this repo. For further usage questions, a better forum may be https://community.plotly.com/c/dash/16

Thanks!
