### ISSUE TITLE
callback context not working along with dcc.upload

### ISSUE THREAD

**Issue by ghost** [plotly/dash#1510]
Hi,

I am using multiple elements in a page and all elements operate within nested loops. Inside the loop I first upload a file using dcc.upload and then use callback context to check when a submit button is pressed. However on using dcc.upload the callback context returns to upload file and never goes inside the submit button callback context. Attached is a loop output which will help you understand the problem.

Refer to the image - after "all done" I have initalized
ctx = dash.callback_context
print(ctx.triggered[0]['prop_id'].split('.')[0])
if ctx.triggered[0]['prop_id'].split('.')[0] == 'hive':

<img width="173" alt="Screenshot 2020-12-23 at 2 53 46 PM" src="https://user-images.githubusercontent.com/64469406/102982067-f4562d80-452f-11eb-8636-cfefdf1947fd.png">

**Comment by alexcjohnson** [comment]
This isn't really enough info to tell what's going on here and whether it's a bug or just some usage that needs clarification. If you can pare this down to a complete standalone example I can run locally, then we can look into it. That said, typically when you have a button you want to trigger a callback, the pattern to shoot for is to have only that button as `Input` and the other parameters as `State`, which reduces the need for `callback_context`.
