### ISSUE TITLE
[BUG] Error duplicate output callbacks when defining layout as a function 

### ISSUE THREAD

**Issue by angel-langdon** [plotly/dash#1515]
**Describe your context**[X]
I am developing a Dashboard using Dash in python 3.8.6 and PyCharm everything in .py files

-  replace the result of `pip list | grep dash` below [X]
```
dash                 1.18.1
dash-core-components 1.14.1
dash-html-components 1.1.1
dash-renderer        1.8.3
dash-table           4.11.1
jupyter-dash         0.3.1
```

**Describe the bug** [X]

When creating app layout and assign it to a function with app parameter, every callbacks fail saying that there are duplicate callbacks from same output but there aren't. It only fails with app callbacks

server.py:
```
import dash
from layout import layout # layout is where i define all layout logic/ components

def serve_layout():
    return layout(app)

app = dash.Dash(__name__)

app.layout = serve_layout
app.title = 'Example app'
if __name__ == "__main__":
    app.run_server(debug=True,
                   host='0.0.0.0')
```

NOTE: If I assign  app.layout = layout(app)  there aren't any errors and everything works fine.  But, this is not an option because I want the app to reload the data every time user reloads the page.

Error:
```
In the callback for output(s):
  information-container.style
Output 0 (information-container.style) is already in use.
Any given output can only have one callback that sets it.
To resolve this situation, try combining these into
one callback function, distinguishing the trigger
by using `dash.callback_context` if necessary.
```

**Expected behavior** [X]
The expected behaviour is to work without those app.callback duplicate output errors.
NOTE: Graphs which don't have callbacks work okay, but graphs which have callbacks stop working.

**Comment by 007sya** [comment]
I've made a workaround by following documentation guidelines for multi paged apps https://dash.plotly.com/urls

**Comment by reem** [comment]
The workarounds suggested in the post unfortunately do not help when creating libraries of dash components which need to take `app` in order to define internal callbacks. They cannot import a statically defined app since they are defined in a library, and not in the end user application. This is quite a blocker!

**Comment by 007sya** [comment]
> The workarounds suggested in the post unfortunately do not help when creating libraries of dash components which need to take `app` in order to define internal callbacks. They cannot import a statically defined app since they are defined in a library, and not in the end user application. This is quite a blocker!

@reem  Maybe, you could pass app as a parameter to the function component?

**Comment by justinalberta** [comment]
Having the exact same problem as stated above. :(

**Comment by T4rk1n** [comment]
You should not define callbacks after the app  started, if layout is a function it will be called on every page load.
I'd suggest adding a `setup_callbacks(app)` function the user can call in the global scope.
