### ISSUE TITLE
[BUG] dcc.Input not show text as it is when input hex value

### ISSUE THREAD

**Issue by Tambura** [plotly/dash#1517]
Thank you so much for helping improve the quality of Dash!

We do our best to catch bugs during the release process, but we rely on your help to find the ones that slip through.

**Describe your context**
Please provide us your environment so we can easily reproduce the issue.

-  replace the result of `pip list | grep dash` below
```
dash                      1.17.0
dash-bootstrap-components 0.10.7
dash-core-components      1.13.0
dash-daq                  0.5.0
dash-html-components      1.1.1
dash-renderer             1.8.3
dash-table                4.11.0
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: [windows]
    - Browser [chrome]
    - Version [87.0.4280.141]

**Describe the bug**

dcc.Input(type='text'). When input "0xa", the value becomes "10" after focus out.

**Expected behavior**

The value showed in the input box keeps "0xa".

**Screenshots**

**Comment by chriddyp** [comment]
@Tambura  - Thanks for reporting! However I can't reproduce this. I tried on the official docs: https://dash.plotly.com/dash-core-components/input

![hex](https://user-images.githubusercontent.com/1280389/103780125-93842600-5002-11eb-9605-15605fee53ea.gif)

**Comment by Tambura** [comment]
Some other info: it keeps same as input in Microsoft Edge.

And after checking the page using F12, seeing some warning, doing nothing, refreshing, the problem disappeared.
