### ISSUE TITLE
[BUG] External assets not reflected in get_asset_url

### ISSUE THREAD

**Issue by karosc** [plotly/dash#1527]
When serving assets from an external path by setting:

`serve_locally=False` 
and 
`assets_external_path=<url to external asset folder>` 

css, js, and favicon assets are pulled from the external asset directory when the app is initialized, but if I try to use `app.get_asset_url(<asset>)` it still pulls the asset from the dash directory rather than the external directory. 

Would developers be ammenable to a pull request altering the [get_asset_url function](https://github.com/plotly/dash/blob/3402cb8f67466bcee8776b1d07dd3134d08bda76/dash/dash.py#L1187) to look more like below?
```python
def get_asset_url(self, path):
    if self.config.assets_external_path:
        asset = get_asset_path(
            self.config.assets_external_path,
            path,
            self.config.assets_url_path.lstrip("/"),
        )
    else:
        asset = get_asset_path(
            self.config.requests_pathname_prefix,
           path,
            self.config.assets_url_path.lstrip("/"),
       )

    return asset

```
For reference [get_asset_path](https://github.com/plotly/dash/blob/3402cb8f67466bcee8776b1d07dd3134d08bda76/dash/_utils.py#L49) is defined in _utils.py as:
```python
def get_asset_path(requests_pathname, asset_path, asset_url_path):

    return "/".join(
        [
            # Only take the first part of the pathname
            requests_pathname.rstrip("/"),
            asset_url_path,
            asset_path,
        ]
    )
````

**Comment by alexcjohnson** [comment]
Nice find, would you like to make a PR to fix this oversight?
