### ISSUE TITLE
Adding webmanifest

### ISSUE THREAD

**Issue by rcastellotti** [plotly/dash#1538]
Hi,
I wrote [a simple dashboard](https://rcwtracker.herokuapp.com) and I would like to add a `manifest.json` but I' m having a few problems.
As you can see I added a `html.Link` element and checking the website it correctly loaded, as per screenshot.
```python
app.layout = html.Div([
    html.Link(href="/assets/manifest.json",rel="manifest"),
    dcc.Tabs(
        id="tabs-with-classes",
        children=[
            dcc.Tab(label="Plot", children=[
                html.Div(children=[
                    dcc.Graph(
                        id='weight_graph',
                        figure=fig,
                        style={
                            "margin": "auto",
                            "maxWidth": "1600px",
                        }
                    )

                ])
            ]),
            dcc.Tab(label="Table", children=[
                dash_table.DataTable(
                    id='table',
                    columns=[{"name": i, "id": i} for i in df.columns],
                    data=df.to_dict('records'),
                    style_table={
                        "margin": "auto",
                        "max-width": "400px",
                    }
                )]
            )
        ], style=tabs_styles)
])
```

![image](https://user-images.githubusercontent.com/43064224/105163054-b0951a80-5b13-11eb-851d-15b562de1ec9.png)
The static directory `assets` is served correctly by gunicorn, however chrome cannot find the manifest while firefox can.
Am I doing something wrong?
Thanks in advance.
(Sorry for bad english, I am not native)

**Comment by alexcjohnson** [comment]
@rcastellotti did you solve the problem? I've never used a web manifest, but seems like this is [expected](https://developer.mozilla.org/en-US/docs/Web/Manifest#deploying_a_manifest_with_the_link_tag) to go in the `<head>` which is best done with a [custom html template](https://dash.plotly.com/external-resources)
