### ISSUE TITLE
Live Updating Components

### ISSUE THREAD

**Issue by len-n-a-rt** [plotly/dash#1540]
The first example on the tutorial page of https://dash.plotly.com/live-updates is not working when using it. I get the error:

dash.exceptions.IncorrectTypeException: The input argument `<dash.dependencies.Input object at 0x0D0F5BB0>` is not a list of `dash.dependencies.Input`s.

The call back is defined like that:

@app.callback(
                Output('live-update-text', 'children'),
                Input('interval-component', 'n_intervals')
)

And the input is:

dcc.Interval(
            id='interval-component',
            interval=1*1000, # in milliseconds
            n_intervals=0
        )

Two weeks ago this was working good, any idea?

**Comment by len-n-a-rt** [comment]
It can be easily fixed by modifying the input to a List of inputs, but why it is not working alone?:

@app.callback(
                Output('live-update-text', 'children'),
                Input('interval-component', 'n_intervals')
)

To:

@app.callback(
                Output('live-update-text', 'children'),
                [Input('interval-component', 'n_intervals')]
)

**Comment by alexcjohnson** [comment]
What version of `dash` do you have? In [v1.15 last summer we relaxed the requirement to put inputs, states, and multi-outputs in lists](https://github.com/plotly/dash/blob/dev/CHANGELOG.md#1150---2020-08-25) and we recently updated the docs to use the simplified syntax.

**Comment by len-n-a-rt** [comment]
You are absolutely right! I first installed the newest version and downgraded for some tutorial because of some version difference to follow along and forgot about it. Thank you very much, helped a lot,
