### ISSUE TITLE
[BUG]Dropdown inside DataTable hard to use

### ISSUE THREAD

**Issue by audetto** [plotly/dash#1545]
It is very well visible in one of the demo apps on the plotly website

https://dash.plotly.com/datatable/dropdowns

Scroll at the bottom and activate the Venice dropdown.
Very hard to use.
One needs to use the mouse wheel to scroll the table up.

If the table contains only 1 or 2 rows or if the list is long, it becomes very hard to use.

Ideally the dropdown should display in an area not limited to the table.

**Comment by celia-plotly** [comment]
It has already been fixed:
https://github.com/plotly/dash/assets/101562106/72909559-d8e4-4990-95ff-68cf395ed893
