### ISSUE TITLE
[BUG] callback_context.triggered includes all dcc.Store.data

### ISSUE THREAD

**Issue by amarvin** [plotly/dash#1554]
```
dash                 1.19.0
dash-core-components 1.15.0
dash-html-components 1.1.2
dash-renderer        1.9.0
dash-table           4.11.2
```

**Describe the bug**

Dash callbacks that include multiple Inputs of `dcc.Store` attribute "data" run if any of the `dcc.Store` change their data, but the `callback_context.triggered` lists all `dcc.Store` even those unchanged.

**Expected behavior**

Only `dcc.Store` that have changed should be listed.

**Comment by alexcjohnson** [comment]
Thanks @amarvin - can you boil what you're seeing down to a simple standalone app that exhibits the issue? Here's my attempt, I only see one `Store` in `callback_context.triggered`:

```py
import json

import dash
from dash.dependencies import Input, Output
import dash_core_components as dcc
import dash_html_components as html


app = dash.Dash(__name__)

app.layout = html.Div(children=[
    dcc.Input(id="in", value="0"),
    dcc.Store(id="a", data="a"),
    dcc.Store(id="b", data="b"),
    html.Div(id="out")
])


@app.callback(Output('a', 'data'), Input('in', 'value'))
def a(v):
    return v


@app.callback(Output('out', 'children'), Input('a', 'data'), Input('b', 'data'))
def out(a, b):
    return json.dumps([a, b, dash.callback_context.triggered])


app.run_server(debug=True)
```
![Screen Shot 2021-02-12 at 7 20 27 PM](https://user-images.githubusercontent.com/2678795/107835404-63e5dd80-6d67-11eb-856b-6ba0f0e42fbc.png)

**Comment by amarvin** [comment]
Thanks for the fast response, @alexcjohnson! Your example works for me and made me realize there must be something else going on in my app. I'll close this Issue and reopen it if I find the bug isn't me 😄

**Comment by amarvin** [comment]
I was using `dcc.Store(storage_type="session")` elements, and when the page initially loaded the session local storage values were populated into the `dcc.Store` elements so that both appeared in the `dash.callback_context.triggered`.
