### ISSUE TITLE
[BUG] Plotly Dash ignores ticklabelposition

### ISSUE THREAD

**Issue by martinspurr89** [plotly/dash#1557]
**Describe your context**
Please provide us your environment so we can easily reproduce the issue.

MWE:

```
import plotly.graph_objects as go
import dash
import dash_core_components as dcc
import dash_html_components as html

fig = go.Figure()
fig.layout.yaxis.ticklabelposition = "inside"
fig
fig.write_image("img.png")

dash_fig = dcc.Graph(id='graph', figure=fig)
app = dash.Dash(__name__)
app.layout = html.Div(children=[dash_fig])

if __name__ == '__main__':
    app.run_server()
```

-  replace the result of `pip list | grep dash` below
```
dash                 1.12.0
dash-bootstrap-components 0.10.2
dash-core-components 0.47.0
dash-html-components 1.0.3
dash-renderer        1.4.1
dash-table           4.7.0
django-plotly-dash 1.4.2
jupyter-plotly-dash 0.4.2
```

**Describe the bug**

When creating a plotly chart with ticklabelposition = "inside" set - the y tick label position is correct if you export as an image (or offline html), but if you insert it into a Dash app the label position is ignored? Any workarounds?

**Expected behavior**

Tick labels should be inside the plot (as seen in exported png)

**Screenshots**

If applicable, add screenshots or screen recording to help explain your problem.

Correct png export result:
![img](https://user-images.githubusercontent.com/60694950/108705976-e1e37a80-7505-11eb-842c-c9a824384d0f.png)

Dash app screenshot (incorrect tick label position):
![dash](https://user-images.githubusercontent.com/60694950/108705972-e14ae400-7505-11eb-80fc-3262caaf4c64.png)

**Comment by alexcjohnson** [comment]
Please `pip install —upgrade dash` - somehow you have a very old `dash-core-components` which brings along an old `plotly.js`. Upgrading `dash` should get you the latest dcc.

**Comment by martinspurr89** [comment]
Ahh yes thats worked!
