### ISSUE TITLE
i have an issue related to table style

### ISSUE THREAD

**Issue by enalpha** [plotly/dash#156]
I am new to Dash and try to make a web app on my own. So I took the Dash table example as reference, here is the example code below:
```
import dash
import dash_core_components as dcc
import dash_html_components as html

import pandas as pd

df = pd.read_csv(
    'https://gist.githubusercontent.com/chriddyp/'
    'c78bf172206ce24f77d6363a2d754b59/raw/'
    'c353e8ef842413cae56ae3920b8fd78468aa4cb2/'
    'usa-agricultural-exports-2011.csv')

def generate_table(dataframe, max_rows=10):
    return html.Table(
        # Header
        [html.Tr([html.Th(col) for col in dataframe.columns])] +

        # Body
        [html.Tr([
            html.Td(dataframe.iloc[i][col]) for col in dataframe.columns
        ]) for i in range(min(len(dataframe), max_rows))]
    )

app = dash.Dash()

app.layout = html.Div(children=[
    html.H4(children='US Agriculture Exports (2011)'),
    generate_table(df)
])

if __name__ == '__main__':
    app.run_server(debug=True)
```
This should be the output I am supposed to get :
![dash_table222](https://user-images.githubusercontent.com/27722028/32529229-52ffb91a-c472-11e7-9440-700721a4de45.png)

But it turned out to be this:
![table_data](https://user-images.githubusercontent.com/27722028/32529295-b5c8c37a-c472-11e7-99f9-6d62c306bd18.png)

The problem is I dont see any css code from the original example code and I want to know how to get the same table style like the one in first pic.

**Comment by chriddyp** [comment]
@enalpha - Add this to your code
```
app.css.append_css({"external_url": "https://codepen.io/chriddyp/pen/bWLwgP.css"})
```

You can view (and fork) this stylesheet here: https://codepen.io/chriddyp/pen/bWLwgP.
