### ISSUE TITLE
[Feature Request] Improve Holoviews Integration

### ISSUE THREAD

**Issue by tstrutz** [plotly/dash#1565]
**Is your feature request related to a problem? Please describe.**
Yes. I was attempting to use the holoviews integration, however encountered numerous issues when trying to load data dynamically via a callback. I know this is due to the way that dash assigns callbacks to the server before startup. I would load a batch of data based on user input and attempt to plot it using holoviews. There were several issues with this approach:
1. The zooming and rerendering of the plot doesn't work as expected.
2. The `to_dash` function defines callbacks at startup. This makes it only useful if you want to load a `hard-coded` set of data once. All examples were written with this assumption in mind.

**Describe the solution you'd like**
I want to be able to create an interactable holoviews plot with data loaded based on user-selected inputs. This avoids having to load enormous amounts of data into the global scope and having to change the code every time to respond to using another dataset. (The current implementation of the holoviews Dash interface as I understand it.)

In order to do this, it sounds like Dash would need to be able to dynamically add new callbacks while the server is up. Is this possible? 

I don't want to have to up-front load gigabytes or (terabytes) even of data to make such a thing possible oterwise. There is a point at which none of this will fit into RAM easily.

**Describe alternatives you've considered**
I've tried a few solutions:
1. Tried to rewrite the `to_dash` function to not generate randomly generated string ids. This sort of worked but the callbacks still didn't work correctly. In this approach I tried to just update the data that an existing callback at global scope was pointing to but with an empty dataset.
2. Tried to spin up a Dash server in the callback which had the callbacks then run it in an iframe. This actually worked, but had other issues. Such as how do I shut it down without shutting down the main server? The main approach ("HTTP Post to `werkzerg.server.shutdown` to this ended up shutting down both so this is a no-go.

**Additional context**

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson

**Comment by szilike10** [comment]
I've had this very exact problem for quite a while now, every example is provided in a way that you already have the data at hand when starting up the server. I would like to load new data and update my existing graph while keeping the zooming functionality. Here I provided a short example of what I mean.

`import dash
from dash import dcc, html
import holoviews as hv
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from dash.dependencies import Input, Output
from holoviews.operation.datashader import datashade
from holoviews.plotting.plotly.dash import to_dash

# Enable Holoviews Plotly extension
hv.extension('plotly')

# Generate synthetic dataset
def generate_large_data():
    np.random.seed(42)
    n = 1_000_000  # Number of points
    return pd.DataFrame({
        'x': np.random.normal(size=n),
        'y': np.random.normal(size=n),
        'value': np.random.random(size=n),
    })

def generate_large_data_():
    np.random.seed(42)
    n = 1_000_000  # Number of points
    return pd.DataFrame({
        'x': np.random.uniform(size=n),
        'y': np.random.normal(size=n),
        'value': np.random.random(size=n),
    })

# Create Holoviews + Datashader plot
def create_hv_plot(data):
    points = hv.Points(data, ['x', 'y'])
    shaded = datashade(points, cmap=['lightblue', 'blue', 'purple'])
    return shaded.opts(width=800, height=400)

# Initialize Dash app
app = dash.Dash(__name__)

# Convert Holoviews plot to Plotly
def holoviews_to_plotly(hv_plot):
    # Render the Holoviews plot to a Plotly figure
    plotly_fig = to_dash(app, [hv_plot], responsive=False)
    return plotly_fig

# Generate the data and create the plot
data = generate_large_data()
hv_plot = create_hv_plot(data)
plotly_fig = holoviews_to_plotly(hv_plot)

graph_div = html.Div(plotly_fig.children, id='graph')

# Layout for Dash app
app.layout = html.Div([
    html.H1("Dash + Plotly + Holoviews + Datashader"),
    html.Button('Generate New Data', id='generate-button', n_clicks=0),
    graph_div,
])


@app.callback(
    Output('graph', 'children'),
    [Input('generate-button', 'n_clicks')]
)
def update_graph(n_clicks):
    if n_clicks > 0:
        # Generate new data on button click
        new_data = generate_large_data_()
        
        # Create a new plot with the new data
        new_hv_plot = create_hv_plot(new_data)
        
        # Convert the new Holoviews plot to Plotly figure
        new_plotly_fig = holoviews_to_plotly(new_hv_plot)
        
        return new_plotly_fig.children  # Return the updated Plotly figure
    
    return plotly_fig.children  # Return the initial plot if no click yet



# Run the app
if __name__ == "__main__":
    app.run_server(debug=True)
`
Here everything works as expeced until I click on the generate data button. Then I indeed replace my data in thhe graph, but on zoom there is not update in the rastered image, I only enlarge the existing one making it more pixelated. The original owner of this request seems to be more aware of what the limitation really is, but I have seen several posts on Dash forums describing this exact same problem with no real solution or answer to it. However, having a feature like this, or perhaps solving the currently existing bug would be highly appreciated.
