### ISSUE TITLE
[BUG] callback_context.triggered returns [{'prop_id': '.', 'value': None}] for Graphs

### ISSUE THREAD

**Issue by gibberishbc** [plotly/dash#1574]
**Context**
Our app has three scatter plots displaying different aspects of the same data. Users can select (box / lasso) data points from any of the graphs and we process the selection differently for each graph - thus it is important to know which graph triggered the callback.

Initially, we checked  `dash.callback_context.triggered` to find the ID of the graph that triggered the callback, but the only thing returned was `[{'prop_id': '.', 'value': None}]`

We thought it would be a simple workaround to just check which graph has` selectedData` - but after selecting once from a graph it seems to retain that selectedData, so if then select from another graph there will be selectedData in two inputs. Therefore, checking which graph has the selectedData only works the first time.  We sure could use the ID of the element that triggered the callback...

```
dash                                       1.18.1
dash-bootstrap-components 0.11.1
dash-core-components          1.14.1
dash-html-components          1.1.1
dash-renderer                         1.8.3
dash-table                              4.11.1
```

**Bug Description**
**dash.callback_context.triggered** returns `[{'prop_id': '.', 'value': None}]`, even though all graphs have unique IDs.

**Expected behavior**
Each element that triggers a callback should have its ID returned via `dash.callback_context.triggered`

**Comment by alexcjohnson** [comment]
`[{'prop_id': '.', 'value': None}]` is what's in `dash.callback_context.triggered` for an initial call of the callback, before the user has done anything. So I'm surprised you're getting that from a user interaction. Are you able to reproduce this in a simple standalone app so we can see it happening?

As a workaround, if you don't want `selectedData` to persist to the next callback, you can set it as both an input and an output of the callback (in the latest `dash` version, which you're using), and as output set it to `None` for all three graphs.

**Comment by gibberishbc** [comment]
Hi Alex, thanks very much for the prompt reply.  For some reason, _(despite two of us poring over the code yesterday and verifying what was happening numerous times before the github report was opened...)_ this morning the `callback_context.triggered` is now working as per design. `callback_context` is now returning the `prop_id` as you confirmed it is supposed to do. Quite sure that we observed the problem over multiple days, but perhaps yesterday just felt like multiple days and a reboot fixed things.  Will report back if/when it happens again with additional details. Will leave this bug report open for a bit longer.

**Comment by gibberishbc** [comment]
I believe this problem was possibly related to Dash 1.18.  Since upgrading to 1.19 we've not seen this happen again. Closing.
