### ISSUE TITLE
[BUG] html error misinterpreted as raw string

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/dash#1581]
Seen in a support ticket:

![unnamed](https://user-images.githubusercontent.com/2678795/113009111-a90e7500-9145-11eb-99bc-a25ee10f9e42.jpg)

I'm not sure where this html error string is coming from, but it's being interpreted as a raw string because the doctype declaration is lowercase. Should be an easy fix to this condition:

https://github.com/plotly/dash/blob/e8ac94919105a91c76a966c21aca2ec7b0297e22/dash-renderer/src/components/error/FrontEnd/FrontEndError.react.js#L112-L114

**Comment by pgebert** [comment]
I would suggest to close this issue as it was resolved in the current dev branch:

https://github.com/plotly/dash/blob/e145b407bb41bd2845246dea231efe48e3391600/dash/dash-renderer/src/components/error/FrontEnd/FrontEndError.react.js#L112-L114
