### ISSUE TITLE
How do you test the Upload component?

### ISSUE THREAD

**Issue by theNewFlesh** [plotly/dash#1591]
**Describe your context**
I am trying to test an upload component I have in a web app I am coding. I am using selenium and pytest, and I have not the slightest clue on how to do this. I have tried methods involving:
- `dcc.Upload._upload`
- `executeCommand('uploadFile', True, filepath)`
- `webdriver.ActionCommands().drag_and_drop`
and nothing works.

-  replace the result of `pip list | grep dash` below
```
dash                                          1.19.0
dash-core-components          1.15.0
dash-html-components          1.1.2
dash-renderer                          1.9.0
dash-table                                4.11.2
```
-  if frontend related, tell us your Browser, Version and OS
    - python 3.7.10
    - ChromeDriver 89.0.4389.90 (62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534})
    - OS: Ubuntu 18.04.5 LTS  inside Docker container
    - Chromium 89.0.4389.90 Built on Ubuntu , running on Ubuntu 18.04

**Describe the bug**
Extreme difficulty in uploading file data via the dcc.Upload component. No clear idea of how to do it.

**Expected behavior**
A way of testing this component that works and doesn't require hours of research.

**Screenshots**

**Comment by JB2001216** [comment]
Now the tests for the component dcc.Upload have already been added.
https://github.com/plotly/dash/blob/dev/components/dash-core-components/tests/integration/upload/test_upload_different_file_types.py

**Comment by nickmelnikov82** [comment]
Now the tests for the component have already been added.
https://github.com/plotly/dash/blob/dev/components/dash-core-components/tests/integration/upload/test_upload_different_file_types.py
