### ISSUE TITLE
[BUG] clickData not including customdata

### ISSUE THREAD

**Issue by pmkroeker** [plotly/dash#1594]
Dependencies
```
dash  1.19.0
dash-bootstrap-components 0.11.1
dash-core-components 1.14.1
dash-html-components 1.1.1
dash-renderer  1.9.0
dash-table 4.11.2
```
**Expected behavior**

When clicking on a chart that contains a `lines+markers` scatter trace, as shown below, I would expect to get `customdata` back in the clickData, but it is not appearing. If the same thing is supplied to just a `markers` scatter trace it works as expected and `customdata` is included in the clickData.

**Screenshots**
![image](https://user-images.githubusercontent.com/10147685/114773802-5aa3cd80-9d24-11eb-9bef-d38841756ba3.png)
Adding custom data like so, same is applied to just `markers`.

![image](https://user-images.githubusercontent.com/10147685/114774001-92ab1080-9d24-11eb-986e-3095da3dbc82.png)
Here is a screenshot of the value the VSCode debugger shows when the trace is clicked, `customdata` is not in the object.

**Comment by alexcjohnson** [comment]
I'm not able to reproduce this. I notice your `customdata` attribute only has one element - when I test this, regardless of `mode`, that means it'll only return `customdata` with the `clickData` if I click the first point (`pointNumber=pointIndex=0`)

If you're still seeing it after making `customdata` the same length as `x` or `y`, can you include a complete app that shows the issue?
