### ISSUE TITLE
unclear on dcc.Input type argument effect

### ISSUE THREAD

**Issue by jwhendy** [plotly/dash#160]
I assumed that `dcc.Input(..., type='number')` would return the contents as an `int` or `float`. My request:

- if this is false and `dcc.Input` are always of type `str`, could this be made more clear [in the docs](https://plot.ly/dash/dash-core-components/input)?

- if this *should* be the case, could someone take a look at what's going on?

- in either case, could the docs be more clear about the effect of the `type` argument? At present it simply says "The type of control to render." I'm starting to suspect it only affects a minor appearance of the input box.

Thanks!

**Comment by jwhendy** [comment]
Per the comment over in #161, I looked at the `html` docs themselves and found [this page](https://www.w3schools.com/jsref/dom_obj_number.asp) on `<input type="number">` elements.

I'm still a *little* confused, but think it's because `js` must do some automatic type conversion. For example, this:

```
<input type="text" id="myNumber" value="2">
function myFunction() {
    var x = document.getElementById("myNumber").value * 2;
    document.getElementById("demo").innerHTML = x;
}
```

Still returned `4` even though it's set to type `text` and the value appears to be a string, `"2"`.

So... I'm going to take it that in the `dash` context, `dcc.Input` will always return `str`. If that's the case, I think this can just be closed and I was wrong in my assumption. The `type` just gives a certain *kind* of input box tailored to what format its contents will be, but doesn't change what it returns.

**Comment by chriddyp** [comment]
This behaviour was actually changed in https://github.com/plotly/dash-core-components/pull/100 as discussed in https://github.com/plotly/dash/issues/124. The new behaviour is in the latest version of dash-core-components, released last sunday (https://github.com/plotly/dash-core-components/blob/master/CHANGELOG.md#changed)

**Comment by jwhendy** [comment]
Ha! What timing. Great news and good reminder to search/post issues in the right place (sorry about that). Also a good reminder to keep more up to date on my installs. Thanks!

**Comment by jwhendy** [comment]
Am I misunderstanding what that PR was supposed to do? I just took the example from #124 and simply added some version printing at the top, but I get what I'm assuming was @Madhu94 's intent to show how this *shouldn't* work?

```
## added to the top of that file:
print('dash: {}\ndcc: {}\nhtml: {}'.format(
    dash.__version__, dcc.__version__, html.__version__))
```

After changing the values from their initialized `0.7`, I get:

![2017-11-23_173423](https://user-images.githubusercontent.com/379357/33190651-8d7a999e-d074-11e7-9b47-dfd0357ee3b7.png)

Command line output:
```
$ python dash_issue_124.py
dash: 0.19.0
dcc: 0.15.0
html: 0.8.0
```

I just retried after `pip install --user --upgrade git+https://github.com/plotly/dash-core-components.git` and still get the same behavior.

**Comment by Madhu94** [comment]
@jwhendy Thanks for reporting the issue, I'll check this.

**Comment by chriddyp** [comment]
@Madhu94 @jwhendy - Thanks for reporting! Sorry about this - the build on `0.15.0` was bad. I've updated this on `v0.15.2`, so give this a try:

```
pip install dash-core-components==0.15.2
```

```python
import dash
import dash_core_components as dcc
import dash_html_components as html

app = dash.Dash()

app.layout = html.Div([
    dcc.Input(id='input', type='number'),
    html.Div(id='output')
])


@app.callback(
    dash.dependencies.Output('output', 'children'),
    [dash.dependencies.Input('input', 'value')])
def update_output(value):
    print type(value)
    return value


if __name__ == '__main__':
    app.run_server(debug=True)
```

**Comment by jwhendy** [comment]
Rockin! I just replicated @Madhu94 's example from #124 and it works like a charm now. Thanks for the quick fix!

![2017-11-24_182002](https://user-images.githubusercontent.com/379357/33225806-47179b8e-d144-11e7-8391-09dc9d593452.png)
