### ISSUE TITLE
[BUG] "Go to the last page" >> button is not working in DataTable

### ISSUE THREAD

**Issue by stoufa** [plotly/dash#1602]
**Context**

`pip list | grep dash` output:
```
dash                          1.19.0             
dash-bootstrap-components     0.11.3             
dash-core-components          1.15.0             
dash-html-components          1.1.2              
dash-renderer                 1.9.0              
dash-table                    4.11.2             
dash-treeview-antd            0.0.1
```

Web Browser: `Google Chrome 90.0.4430.72 `

**Bug Description**

Unlike the "Go to the first page" `<<` button, the "Go to the last page" `>>` button is not working.
The code is the one put on the ["DataTable - Python Callbacks" documentation page](https://dash.plotly.com/datatable/callbacks) in the "Backend Paging with Filtering and Multi-Column Sorting" section.
By the way, you can notice that even on the documentation page, you don't need to run that code locally to notice this bug.

**Expected behavior**

That button should be, first of all, enabled/clickable, currently, it's grayed out/disabled/unclickable, and it should take us to the last page of the data frame.

**Screenshots**

![](https://i.ibb.co/ZLmYwsd/Bug-Report-Peek-2021-04-22-14-20.gif)

**Comment by nickmelnikov82** [comment]
For this button to work, you need to add parameter `page_count = len(df)/PAGE_SIZE`, or use `page_action='native'`.

**Comment by stoufa** [comment]
Thanks for the answer @nickmelnikov82.
Adding the `page_count` parameter worked perfectly.
Though, changing the `page_action` parameter didn't work for some reason!
The pagination controls disappear when I change the value to `'native'`.

For reference, here's the output of `pip list | grep dash` on my development environment:
```
dash                            2.3.0
dash-bootstrap-components       0.12.2
dash-core-components            2.0.0
dash-dangerously-set-inner-html 0.0.2
dash-html-components            2.0.0
dash-renderer                   1.9.1
dash-table                      5.0.0
dash-treeview-antd              0.0.1
```

**Comment by nickmelnikov82** [comment]
You need to pass the entire array of data to make pagination on the clientside. Here is a simple example of `native` pagination.
```
from dash import Dash, dash_table
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/gapminder2007.csv')
df[' index'] = range(1, len(df) + 1)
app = Dash(__name__)

app.layout = dash_table.DataTable(
    data=df.to_dict('records'),
    columns=[
        {"name": i, "id": i} for i in sorted(df.columns)
    ],
    page_size=5,
    page_action='native'
)

if __name__ == '__main__':
    app.run_server(debug=True)
```

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
