### ISSUE TITLE
[BUG] Error when trying to serve Dash app using waitress

### ISSUE THREAD

**Issue by gbaltz** [plotly/dash#1609]
Thank you so much for helping improve the quality of Dash!

We do our best to catch bugs during the release process, but we rely on your help to find the ones that slip through.

**Describe your context**

```
dash                 1.19.0
dash-core-components 1.15.0
dash-html-components 0.0.51
dash-renderer        1.9.0
dash-table           4.11.2
```

**Describe the bug**

I get an error when trying to serve Dash app using waitress. It seems like Dash doesn't like something about the port value.

My app runs just fine on the local computer using the Flask server, but when I try to serve via waitress using:

```
app = dash.Dash(__name__, external_stylesheets=external_stylesheets, suppress_callback_exceptions=True)

if __name__ == '__main__':
    serve(app.run_server, host='0.0.0.0', port=8080)
```
I get the following traceback error when i try to access using my web browser:
```
ERROR:waitress:Exception while serving /
Traceback (most recent call last):
  File "C:\Users\-\-\web_build_env\lib\site-packages\waitress\channel.py", line 397, in service
    task.service()
  File "C:\Users\-\-\web_build_env\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "C:\Users\-\-\web_build_env\lib\site-packages\waitress\task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "C:\Users\-\-\web_build_env\lib\site-packages\dash\dash.py", line 1667, in run_server
    port = int(port)
TypeError: Expecting an integer from 1 to 65535, found port=<function WSGITask.execute.<locals>.start_response at 0x0000020828C8BEE8>
```

Am I not implementing this correctly or is this some sort of bug?

**Comment by anders-kiaer** [comment]
I haven't used `waitress` before, but I guess `waitress` maybe want the Flask server instance (and not the Dash method `run_server`)? I.e. you can maybe try this (only a guess from reading your snippet):
```python
    serve(app.server, host='0.0.0.0', port=8080)
```

**Comment by gbaltz** [comment]
Yep, that seemed to be the problem! Thanks for your help
