### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SonjaThompson** [plotly/dash#1618]
Thank you so much for helping improve the quality of Dash!

We do our best to catch bugs during the release process, but we rely on your help to find the ones that slip through.

**Describe your context**
I am using Windows 10 on a home computer.  I installed dash 1.19.0 and core and html components on my home computer.  All of the components below are present.  I am taking a Coursera class and we use an IBM environment, Watson Studio, with Jupyter notebooks using Jupyter-dash.  I've attempted to run code in Jupyter notebooks in Watson Studio, in Google Colab, and on my home computer.  I've tried using a straight Python file (without Jupyter-dash).  When I first ran into my problem, I was using dash 1.20.0, and switched to 1.19.0 on recommendation from another student, which didn't help.

(I don't know if there is a bug, or if none of the environments I've used are set up right...since it doesn't work in so many environments, and I'm trying to run code I didn't write that used to work for other people, I can only assume there is a bug somewhere in Dash.)

-  replace the result of `pip list | grep dash` below
```
dash                 0.42.0
dash-core-components 0.47.0
dash-html-components 0.16.0
dash-renderer        0.23.0
dash-table           3.6.0
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: [e.g. iOS]                                  Microsoft Windows 10 Home, 10.0.19042 Build 19042
    - Browser [e.g. chrome, safari]         Chrome, both regular and incognito
    - Version [e.g. 22]                             Chrome:  Version 90.0.4430.93 (Official Build) (64-bit)

**Describe the bug**

Even the simplest sample code from the tutorials shows no results.  Google Colab showed some of the layout, but no graphics.  The only clues I have are a message at install, and a message at run, just before the runtime ends (see screenshots in the last section).  Lots of people in my Coursera class are also unable to run their code.

**Expected behavior**

I expected to see a browser tab open, layout to show, and a graphic.  Never happened....ever.  See the screenshot below for the code I was running, straight from the first Dash Tutorial.  Can you help?

If applicable, add screenshots or screen recording to help explain your problem.

![pip install dash 1-19-0](https://user-images.githubusercontent.com/81829868/116787320-95b23a80-aa60-11eb-8851-7b18a6e1c2d5.JPG)
![Python3IDLEcode](https://user-images.githubusercontent.com/81829868/116787484-7cf65480-aa61-11eb-9742-3e73c5fb290d.JPG)
![run-message](https://user-images.githubusercontent.com/81829868/116787322-95b23a80-aa60-11eb-8734-b878f72d7e82.JPG)

**Comment by alexcjohnson** [comment]
In plain dash we don't automatically open a browser window - but once you start the server, pointing your browser to `localhost:8050` should show the app. In jupyter-dash you should be able to use `app.run_server(mode="inline")` to show the app in an output cell or `app.run_server(mode="jupyterlab")` to see it in a new jupyter lab tab.

**Comment by SonjaThompson** [comment]
Thanks for the suggestions.  I appreciate the effort - and the insight.

I tried this:
![image](https://user-images.githubusercontent.com/81829868/117044067-373cc480-accb-11eb-8e58-44955742f8a4.png)

I got:
![image](https://user-images.githubusercontent.com/81829868/117044184-62271880-accb-11eb-9372-56678ef947ae.png)

No browser action.  Is that what you meant by "pointing your browser to localhost:8050 should show the app"?

When I 'ping localhost', it's there and working.
Someone suggested reinstalling IIS.  I did that.  No change.  I even tried installing extra features in IIS.  No change.
I am using an Xfinity router, but localhost is showing as 127.0.0.1.  I tried using that in place of 'localhost'.  Nothing.

I checked the values of the listening ports with my browser up.  There was no 8050 listed, so it should have been safe to send to - or maybe that's bad.  I'm afraid I'm not great on system details.

I tried the other mode suggestions you gave me in Jupyter before ... no luck there.

It's weird because one of my assignments had us use plotly express which worked weird in Jupyter when I tried to show it from inside Dash.  First I called it to show outside JupyterDash, then it was referenced from inside JuptyerDash with additional HTML added to the app.  The first show appeared fine.  

But the JupyterDash piece didn't work and threw error, so I used it from Python IDLE with plan Dash.  First the outer show came up in the browser tab, as expected.  Then Dash was supposed to produce some HTML and show it again.  It brought up a second tab, but repeated the first show with no additional HTML and no interactivity -- at least a second tab appeared.  

I don't know what more to check.  Do you have any more suggestions?

Thanks in advance for your help.

Sonja

**Comment by SonjaThompson** [comment]
Oh, I forgot to mention:  This was in the browser at http://localhost:8050/

![image](https://user-images.githubusercontent.com/81829868/117047802-84229a00-accf-11eb-932e-6784870ded7f.png)

**Comment by anders-kiaer** [comment]
Based on the above I think it is difficult to say what the problem is, but I don't think this is due to a bug in `dash`.

Another observation is these lines:
```python
if __name__ == '__main__':
    app.run_server(debug=True, host="localhost", port=8050)
    subprocess.Popen(['python', '-m', 'SimpleHTTPServer', '8050'])
    webbrowser.open_new_tab("localhost:8050")
```
The reason you don't see a browser tab open (with `webbrowser.open_new_tab`) is likely that `app.run_server` is running indefinitely and as long as you want the server to run (until you e.g. stop the Python process with `Ctrl + C`). The line `subprocess.Popen` is also not needed (Dash creates a Flask server instance on its own).

The "`127.0.0.1` refused to connect" problem is probably due to some system settings/cache/environment on the computer, not related to Dash. You can try running a simple web server directly, without Dash, using `python -m SimpleHTTPServer 8050` (or `python -m http.server 8050` when on Python 3.7+ which is preferred today) and see if the problem persists.

https://community.plotly.com/c/dash could also be a good source for community support.

**Comment by alexcjohnson** [comment]
> Dash is fine. Sorry to have bothered you.

Don't worry about it, that's what we're here for. For future reference some of these questions can be addressed more quickly in https://community.plotly.com/ but when there are bugs GitHub is preferred.

> By the way, I also have to run with debug = False to see graphs.

That's a bit disturbing, can you say more? Do you see any error messages appear in the browser window when `debug=True`? If it's blocking rendering it should appear in the browser window, but some errors could also only make it to the JavaScript console.

**Comment by SonjaThompson** [comment]
That's a bit disturbing, can you say more? 

Unfortunately, no, not with the example I'm using for this conversation.  It only shows this and quits:

          Dash is running on http://localhost:8050/
          
           * Serving Flask app "mytest" (lazy loading)
           * Environment: production
          [31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
          [2m   Use a production WSGI server instead.[0m
           * Debug mode: on

While the above says it's running on http://localhost..., the browser says the site can't be reached.

Sonja

**Comment by SonjaThompson** [comment]
Oh, and it still doesn't show graphs when I run from a jupyter notebook.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
