### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Roh-codeur** [plotly/dash#1622]
Thank you so much for helping improve the quality of Dash!

We do our best to catch bugs during the release process, but we rely on your help to find the ones that slip through.

**Describe your context**
Please provide us your environment, so we can easily reproduce the issue.

-  replace the result of `pip list | grep dash` below
```
dash                 0.42.0
dash-core-components 0.47.0
dash-html-components 0.16.0
dash-renderer        0.23.0
dash-table           3.6.0
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: Big Sur
    - Chrome

**Describe the bug**
dcc and ddk don't seem to work well together
`
controls = [
    dcc.DatePickerRange(
        id="FILTER_START_DATE",
        min_date_allowed=date(2017, 1, 1),
        max_date_allowed=datetime.today(),
        initial_visible_month=datetime.today(),
        end_date=datetime.today(),
        start_date=datetime.today(),
    )
]

app.layout = ddk.App([
    ddk.ControlCard(controls, width=100, orientation='horizontal'),
])
`

**Expected behavior**
I should be able to select the dates

**Screenshots**

If applicable, add screenshots or screen recording to help explain your problem.

**Comment by alexcjohnson** [comment]
Hi @Roh-codeur - those are extremely old version of the Dash packages, please only file bug reports against the current version. Also, this repo is the home of open-source Dash; if you're having problems with our enterprise products such as DDK, please contact Plotly support. Thanks!
