### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by gijs-romme** [plotly/dash#1639]
I would like to filter data based on the 'restyleData' attribute of pie charts (the selection made in the legend), but currently callbacks on this attribute are not returning anything at all.

What would be perfect, for me at least, is to get a list of all of the labels that are currently selected in the pie chart (or something similar) as input parameter of the callback function that has 'restyleData' as an input dependency.

This is the first time I've ever done a feature request, so hopefully I've supplied you with enough information!

**Comment by alexcjohnson** [comment]
Check `relayoutData` - pie legend selection stores its state in `layout.hiddenlabels` rather than in the pie trace, because it will synchronize across multiple pies if they have matching labels.

**Comment by gijs-romme** [comment]
I could have sworn that I already tried that one, but apparently not in the correct way. This indeed works, thank you!
