### ISSUE TITLE
Missing classifiers for Python 3.8/3.9

### ISSUE THREAD

**Issue by samlishak-artemis** [plotly/dash#1642]
Python 3.8 and 3.9 are missing from the classifiers in `setup.py`:

https://github.com/plotly/dash/blob/358c5089c929b2e99996f9d4ee6ec634f65437fe/setup.py#L55-L63

But there is no restriction to 3.7 or below in `python_requires`:
https://github.com/plotly/dash/blob/358c5089c929b2e99996f9d4ee6ec634f65437fe/setup.py#L29

Anecdotally, I've been using Dash on Python 3.9 with no issues. Reporting as an issue as I can't see any mention of Python 3.8 and 3.9 compatibility so far!

**Comment by alexcjohnson** [comment]
Good call, the classifiers haven't been updated in a while. FYI in the upcoming Dash 2.0 we're planning to change `python_requires` to `">=3.6"` - dropping Py2 altogether as well as 3.5 and below.

**Comment by samlishak-artemis** [comment]
I can submit a basic PR to add 3.8 and 3.9 if you like? Not a big job, but it's something 😄

**Comment by samlishak-artemis** [comment]
Never mind, looks like you beat me to it - thanks very much!
