### ISSUE TITLE
Official WHEEL file.

### ISSUE THREAD

**Issue by Ozzey** [plotly/dash#1644]
**Is your feature request related to a problem? Please describe.**
While installing DASH through pip command, there are several compiling error due to either setup tools no being compatible or VSC not supporting the  package.

**Describe the solution you'd like**
This can be easily avoided if there was an official pre-compiled wheel file. 

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by anders-kiaer** [comment]
See also #1440 (duplicate?) 🙂

**Comment by Ozzey** [comment]
> See also #1440 (duplicate?) 🙂

Right!
