### ISSUE TITLE
[BUG] Dropdown duplicated values

### ISSUE THREAD

**Issue by pik94** [plotly/dash#1647]
Hello!

I try to use the dropdown component  with duplicated values in `options` attribute, but search and select of elements don't work as expected:
1. When I type "1", "12", "123" or "1234", it finds only "1234" instead of  "name 1234" and "1234". 
2. When clicking on the dropdown search panel, I see a list of all possible variants, however, I can click only on "name 1234", but not "1234" and "name 1234". If I try to click on "1234", "name 1234" is selected.

When I do the same without duplicates in values, it works correctly. Could you allow to use duplicates for dropdown's options?

Please, find a code snippet here (with little changes of [dropdown tutorial](https://dash.plotly.com/dash-core-components/dropdown) ):
```
import dash
import dash_html_components as html
import dash_core_components as dcc

external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']

data = {1234: 'name 1234'}

options = [{'label': name, 'value': id_} for id_, name in data.items()]
options.extend([{'label': str(id_), 'value': id_} for id_ in data])

app = dash.Dash(__name__, external_stylesheets=external_stylesheets)
app.layout = html.Div([
    dcc.Dropdown(
        id='demo-dropdown',
        options=options,
    ),
    html.Div(id='dd-output-container')
])


@app.callback(
    dash.dependencies.Output('dd-output-container', 'children'),
    [dash.dependencies.Input('demo-dropdown', 'value')])
def update_output(value):
    return 'You have selected "{}"'.format(value)


if __name__ == '__main__':
    app.run_server(debug=True)
```

My environment:
```
dash==1.20.0
dash-core-components==1.16.0
dash-html-components==1.1.3
dash-renderer==1.9.1
dash-table==4.11.3
```

**Comment by nickmelnikov82** [comment]
The "value" attribute must be unique.
Here's a working example for this issue:
```
import dash
from dash import html
from dash import dcc

external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']

data = [
    {'label': 'name_1234', 'value': 1234},
    {'label': '1234', 'value': 1234},
    {'label': 'na34', 'value': 1234}
]

options = [{'label':item['label'], 'value':index} for index,item in enumerate(data)]

app = dash.Dash(__name__, external_stylesheets=external_stylesheets)
app.layout = html.Div([
    dcc.Dropdown(
        id='demo-dropdown',
        options=options,
    ),
    html.Div(id='dd-output-container')
])


@app.callback(
    dash.dependencies.Output('dd-output-container', 'children'),
    [dash.dependencies.Input('demo-dropdown', 'value')])
def update_output(value):
    if value is not None:    
        return 'You have selected "{}:{}"'.format(data[value]['label'], data[value]['value'])
    else:
        return 'No values selected'


if __name__ == '__main__':
    app.run_server(debug=True)

```

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
