### ISSUE TITLE
[BUG] Dash dev tools poor contrast with dark themes

### ISSUE THREAD

**Issue by vikigenius** [plotly/dash#1649]
**Describe your context**
Please provide us your environment, so we can easily reproduce the issue.

-  replace the result of `pip list | grep dash` below
```
dash                          1.20.0
dash-bootstrap-components     0.12.2
dash-core-components          1.16.0
dash-html-components          1.1.3
dash-renderer                 1.9.1
dash-table                    4.11.3
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: Linux
    - Browser: Firefox
    - Version: 88.0

**Describe the bug**
When using a dark theme, the DEV tools menus when showing errors has very poor contrast.

**Expected behavior**
The debug menus should still be properly visible when using dark themes.

**Screenshots**

![scrot_20210516_142357](https://user-images.githubusercontent.com/12724810/119188950-61bbab00-ba49-11eb-97f4-d9a5782fcfc6.png)

**Comment by alexcjohnson** [comment]
Thanks @vikigenius - looks like we just need to reset font colors within the devtools (including the little bubble at the bottom that's supposed to show the error count). I don't think it's worth trying to theme the devtools themselves, would you agree?

**Comment by vikigenius** [comment]
Yeah, i think that makes sense. @tcbegley what do you think? Would that work?

**Comment by tcbegley** [comment]
Yeah, I was thinking you'd just set `color: black` or something. Since it's just for development there's no need for anything fancier.
