### ISSUE TITLE
Source-maps not generated when dash-renderer bundle is created

### ISSUE THREAD

**Issue by HammadTheOne** [plotly/dash#1661]
As a continuation of https://github.com/plotly/dash/pull/1611#discussion_r641143808, the ONLY case we're generating a sourcemap now is when you run `webpack-serve` (which is what you get with `npm start`). The other build commands now seem to be all the same (as far as the bundle itself is concerned) and create no sourcemap. npm run build:js and build:dev are now literally the same command.

Some discussion might be required to determine if this was an intentional change with the tooling updates in https://github.com/plotly/dash/pull/1576, or if this is something we need to address.

**Comment by gvwilson** [comment]
@HammadTheOne is this still a concern?

**Comment by HammadTheOne** [comment]
We can close this for now.
