### ISSUE TITLE
Unable to load _dash-layout and _dash-dependencies from dash app running behind Nginx 

### ISSUE THREAD

**Issue by SivaKanishka** [plotly/dash#1665]
Urls for `_dash-layout` and `_dash-dependencies` are missing the revers proxy uri when dash app is served behind Nginx.

```
dash==1.14.0
dash-bootstrap-components==0.10.5
dash-core-components==1.10.2
dash-html-components==1.0.3
dash-renderer==1.6.0
dash-table==4.9.0
```

    - Windows and Centos
    - Chrome
    - 91.0.4472.77

**Describe the bug**

I am serving dash content inside a Flask app which uses blueprint for registering the routes. 
**App setup:**
1. Dash is initialised with `route_pathname_prefix=/dashapp/`
```
dash_app = dash.Dash(
        server=server,
        routes_pathname_prefix='/dashapp/',
    )

dash_app.css.config.serve_locally = True
dash_app.scripts.config.serve_locally = True
    
```
2. Registered dash app with Flask server
3. Used UWSGI to serve Flask app inside a docker container
```
[uwsgi]
wsgi-file = </path/to/app.py>
callable = app
http = 0.0.0.0:8080
processes = 4
threads = 2
master = true
chmod-socket = 660
vacuum = true
die-on-term = true
```
Upto this point everything was working fine locally. Once I added Nginx proxy, I got the below issue

**Issue:**

urls for `_dash-layout` and `_dash-dependencies` are missing the revers proxy uri. For example, I am serving my flask app at `www.example.com/app/`. But, on the browser, I saw that requests for `_dash-layout` and `_dash-dependencies` are requested at `www.example.com/dashpp/_dash-layout` instead of `www.example.com/app/dashpp/_dash-layout`.

I found out that url for `_dash-component-suites` is generated as expected `www.example.com/app/dashpp/_dash-component-suites`. I went through the dash source code to understand how urls are generated. Both, `_dash-component-suites` and `_dash-layout` are prefixed with `routes_pathname_prefix`. Line 428 to 448 of dash.py in version 1.14.0 has the code for building urls.

This is confusing!!!

I read the following forum [discussion](https://community.plotly.com/t/dash-error-loading-layout/8139/5) and tried applying the solution, and got this error,
`requests_pathname_prefix` needs to start with /`

This is my Nginx config,
```
location /app/ {
    proxy_pass http://localhost:<port>;
    proxy_redirect http://localhost:<port> http://example.com/app/;
    proxy_set_header Accept Encoding "";
    sub_filter_types *;
    sub_filter 'href="/' 'href="/app/';
    sub_filter 'src="/' 'src="/app/';
    sub_filter_once off;
}
```

@ned2 , I saw your posts on similar issue on dash forums too. Please let me know if I need to provide any additional information about this.

Thanks

**Comment by ned2** [comment]
I believe Dash doesn't know that you've configured nginx with the additional `app` route prefix, so you need to make it aware of that. Try initialising the `Dash` instance with `requests_pathname_prefix='/app/dashapp/'.

This forum thread looks like it could be relevant to your situation: https://community.plotly.com/t/host-dash-under-alternate-path/21237

**Comment by SivaKanishka** [comment]
Hi @ned2 , thanks for the reply. I incorporated your suggestion and added `requests_pathname_prefix='/app/dashapp/'`. The dash UI is stuck and displayed `Loading`. Upon inspecting, I got this error in console
```
Uncaught ReferenceError: DashRenderer is not defined
```
I am attaching full error trace below
![Screenshot 2021-06-14 at 2 00 21 PM](https://user-images.githubusercontent.com/27818774/121863302-59d5ea80-cd19-11eb-947d-75ba91bcf851.png)

**Comment by ned2** [comment]
Do you want to start a thread in the community forum and then we can continue the discussion there? This sounds like a configuration issue rather than a Dash issue.

**Comment by SivaKanishka** [comment]
Sure. I already started a thread on forum. [This](https://community.plotly.com/t/unable-to-load-dash-layout-and-dash-dependencies-from-dash-app-running-behind-nginx/53810) is the link.

**Comment by alexcjohnson** [comment]
Talking with @BRONSOLO just now, I think this may be the same issue we're encountering with our new deployment of the Dash docs, and I think it may in fact require a change to Dash itself.

In our case, we have the app deployed on a Dash Enterprise server under the path `/docs/`, but this is exposed by a reverse proxy to `dash.plotly.com` with `/docs/` removed. Given this situation, what we really want is to have `routes_pathname_prefix="/docs/"` and `requests_pathname_prefix="/"`. However, this conflicts with a validation rule we have that `requests_pathname_prefix` must end with `routes_pathname_prefix`:

https://github.com/plotly/dash/blob/efc42b46fef033bd4ec1f082cfe5cbab97a62646/dash/_configs.py#L120-L123

@chriddyp do you see any issue with removing that rule to enable this reverse proxy case?

**Comment by chriddyp** [comment]
@alexcjohnson - I don't think I see an issue with it. As far as I know, these two settings should be independent of each other.

**Comment by SivaKanishka** [comment]
I was able fix this issue. I listed the approach I took on [this](https://community.plotly.com/t/unable-to-load-dash-layout-and-dash-dependencies-from-dash-app-running-behind-nginx/53810/9?u=kanishka) dash forum page.
