### ISSUE TITLE
Display an error if propType value is a reference to a variable when building backend components wuth `dash-generate-components`

### ISSUE THREAD

**Issue by HammadTheOne** [plotly/dash#1674]
As pointed out in https://github.com/plotly/dash-bio/pull/564, if we reference a variable within the `react.js` source code for a component `propType`, the components are generated for Python and R, but missing the values themselves when mapping  from the `PropTypes` js type object to the Python/R type. For Julia, the components fail to generate with a type-error. 

As @alexcjohnson suggested, it makes more sense to have the component generator throw an error when this happens so that component authors can fix this kind of problem up front rather than expecting them to notice a problem later and fix it.

**Comment by gvwilson** [comment]
@HammadTheOne is this still a concern? thanks - @gvwilson

**Comment by HammadTheOne** [comment]
No, we can close it for now.
