### ISSUE TITLE
[How to make a datatable cell containing URLs clickable]

### ISSUE THREAD

**Issue by banyous** [plotly/dash#1714]
Hi,
When I try to use dash_table.DataTable to show the content of a DataFrame column containing URLs (named 'link'), the column is displayed as text (non-clickable). What I want is to have its rows displayed in the datatable as clickable links. I tried many suggestions but couldn't figure it out. Thanks.

Here is the simple code:

```
dash_table.DataTable(
      id='tweets_table',
      data=tweets_df.to_dict('records'),
      columns=[{'id': c, 'name': c, 'presentation':'markdown'} for c in tweets_df.columns],
      markdown_options={'link_target': '_blank'},
      filter_action = 'native',
      sort_action = 'native',
      sort_mode = 'multi',
      export_format = "csv",
      page_action="native",
      page_size=5,
)
```

**Comment by AnnMarieW** [comment]
Hi @banyous 

To make the link, the data just needs to be formatted as a [Markdown link](https://www.markdownguide.org/basic-syntax/#links) ie `[link text](url)`.  Here is an example.  

```
import dash
import dash_table
import dash_html_components as html
import pandas as pd

app = dash.Dash(__name__)

data = dict(
    [
        (
            "Company",
            [
                "[Plotly](https://dash.plotly.com)",
                "[Google](https://google.com)",
                "[Amazon](https://amazon.com)",
            ],
        ),
        ("Rating", ["⭐⭐⭐⭐⭐", "⭐⭐⭐⭐", "⭐⭐⭐"]),
    ]
)
df = pd.DataFrame(data)

app.layout = html.Div(
    [
        dash_table.DataTable(
            id="tweets_table",
            data=df.to_dict("records"),
            columns=[
                {"id": c, "name": c, "presentation": "markdown"} for c in df.columns
            ],
            markdown_options={"link_target": "_blank"},
            filter_action="native",
            sort_action="native",
            sort_mode="multi",
            export_format="csv",
            page_action="native",
            page_size=5,
        )
    ]
)

if __name__ == "__main__":
    app.run_server(debug=True)
```
![image](https://user-images.githubusercontent.com/72614349/130299578-3cc9e7a1-cb93-446d-b24d-551870fb53f0.png)

If you have any more questions, please feel free to post this as a topic on the Dash Community Forum.

**Comment by banyous** [comment]
Thanks a lot AnnMarie. Your suggestion worked. I had just to transform my df column to the format you mentionned :
`
df['link'] = "[Tweet]("+ df['link'].astype(str) + ")"`

**Comment by banyous** [comment]
Hi AnnMarie, Sorry to bother again. I need to replace the clickable tweet link by a clickable Twitter logo image. Can you advise on how to do it ?

**Comment by AnnMarieW** [comment]
Hi @banyous Yes, I can help you, but the [Dash Community Forum](https://community.plotly.com/c/dash/16) is a better place for "how-to" questions.  Please close this issue and if you post this on the forum, I'll answer it over there.
