### ISSUE TITLE
[Feature Request] Serving component_suite assets from external domain

### ISSUE THREAD

**Issue by adrianoesch** [plotly/dash#1723]
**Is your feature request related to a problem? Please describe.**
We're deploying dash via serverless to aws lambda. The high number of dependency requests at page load makes lambda scale up the concurrency which leads to higher latency due to lambda's cold-start.

**Describe the solution you'd like**
I'd like to serve the static javascript dependencies via s3 by adding an `external_component_suite_url_pattern` parameter at initiation of the main `Dash` object. This url pattern - if provided - is being used when constructing the dependency scripts url. For example: Given `external_component_suite_url_pattern="https://my-bucket.s3.eu-west-1.amazonaws.com/{package}@{version}/{file}"` the index page would ask for https://my-bucket.s3.eu-west-1.amazonaws.com/dash-renderer@12.1.0/dash-renderer.min.js". One downside of this solution, is the fetching and uploading of the dependency scripts to s3. But that would only need to be done on version updates.

**Describe alternatives you've considered**
I've thought about...
* string replacements somewhere before the index page is being built and served (a bit hacky)
* proxying component_suite requests in api-gateway to s3 (fingerprinted url's are cumbersome)
* asking AWS to introduce a max concurrency parameter. currently, one can only reserve concurrency increases costs significantly. (I don't expect AWS to listen.)

**Additional context**
I've started looking into how to fix this and i think i could fork sth that works for me. But before spending too much time on the code level, I'd like to get your input and see what you think and whether others would also be interested in this.

And as always, thanks a lot for your work! Dash is great!

**Comment by alexcjohnson** [comment]
Have you tried `app = dash.Dash(serve_locally=False)`? This uses the [unpkg](https://unpkg.com/) CDN for these assets.

**Comment by adrianoesch** [comment]
I haven't and that actually solves my issue. Many thanks!
