### ISSUE TITLE
[Feature Request] Anchors for sections in the documentation

### ISSUE THREAD

**Issue by jlfsjunior** [plotly/dash#1733]
First issue here, I hope this is the right way to do it... :-) 

This is a tiny request for modification to improve the documentation. 

I have been trying to be more engaged in the community and I noticed that **the Dash docs don't have anchors for page sections**. For example,  in https://dash.plotly.com/advanced-callbacks, there is no direct way to point an user to the callback context section, which makes references to the docs somehow imprecise or convoluted.

I wonder if there is a quick way to add anchors to the docs, to make references easier. I know the docs are themselves a Dash application and I never added anchors to those I created, so I am not sure if anchors are supported or can be "hacked into" it.
In any case, I would be happy to make a PR if anyone has ideas on how to implement it.

Thanks for this amazing library!

**Comment by alexcjohnson** [comment]
You're absolutely right @jlfsjunior, and this is an issue we've been wanting to tackle for a long time. There's more to it than just adding anchors, unfortunately. The elements don't exist on the page at first - we have to wait for the layout and in fact for a few callbacks to run before we can try to scroll. We have a private issue where we've been discussing a generalized solution to this https://github.com/plotly/dash-core/issues/89 but there's really no reason it needs to be private. Here's the key part, in case anyone is interested in contributing:

---

Seems to me there may be three pieces to this:
- An option for our `dcc.Markdown` components to automatically create anchors & ids for headings, ala github-flavored markdown.
- A facility to automatically scroll to an id matching `location.hash`, if one is added to the page too late for the browser to do it automatically. This might need to be built into the renderer, as it seems to me this should happen if that id is added any time during the sequence of callbacks that's kicked off on page load, but NOT after a later user action
- Except if `dcc.Link` / `dcc.Location` changes the hash - this should cause the page to scroll either without kicking off a callback (if only the hash changed) or after that callback and any callbacks chained onto it have completed
  - Also while we're on the topic, if `dcc.Link` causes the page content to change, we should automatically scroll at least to the top of whatever changed, maybe even to the top of the page. Currently in the docs you can click on a section and wind up looking halfway down that section's content.

**Comment by red-patience** [comment]
Hi @jlfsjunior, we've implemented anchors for https://dash.plotly.com/. Thanks for the issue, and I hope you have a better time reading and sharing the docs!

**Comment by avm19** [comment]
> Hi [@jlfsjunior](https://github.com/jlfsjunior), we've implemented anchors for https://dash.plotly.com/.

Hi @red-patience, would you please elaborate? I haven't found a way to create an `id=...` target inside Markdown, so that it could be targeted from within or from outside Markdown. Section headers are translated by `dcc.Markdown` into bare h-elements, e.g. `<h2>foo bar</h2>` without any `id` property attached to them.
