### ISSUE TITLE
Split out Dash CI only requirements into `requires-ci.txt`?

### ISSUE THREAD

**Issue by anders-kiaer** [plotly/dash#1742]
Both `pip install dash[dev]` and `pip install dash[testing]` are extra public Dash features (respectively for building Dash components, and using the shipped Dash app test utilities).

Looking at [`requires-dev.txt`](https://github.com/plotly/dash/blob/dev/requires-dev.txt) and [`requires-testing.txt`](https://github.com/plotly/dash/blob/dev/requires-testing.txt), there appears to have leaked https://github.com/plotly/dash CI/test suite dependencies into both files (i.e. dependencies not used by the features in `dash[dev]` and `dash[testing]`). Latest one introduced is [`flaky`](https://github.com/plotly/dash/pull/1741).

Split out Dash CI only dependencies to a new file?

**Comment by alexcjohnson** [comment]
Thanks @anders-kiaer - I was just thinking about exactly this last night and you're exactly right. I think internally we haven't been very clear about what these two extras mean but you're correct as to their original intent.
