### ISSUE TITLE
[BUG] Static files not loading for dash 2.0.0

### ISSUE THREAD

**Issue by mfagundes** [plotly/dash#1746]
**Context**
App using Django Plotly Dash on AWS, using Elastic Beanstalk (Python 3.8)

```
dash                 2.0.0
dash-core-components 2.0.0
dash-html-components 2.0.0
dash-renderer        1.9.1
dash-table           5.0.0
django-plotly-dash    1.6.4
```
    - OS: Windows 10
    - Browser Chrome
    - Version 93

**Describe the bug**

All static files from Dash 2.0.0 or Dash Table 5.0.0, served by unpkg dot com returns 404 error

**Expected behavior**

A table with date range filter doesn't load, due to the lack of all static files. Trying to reach directly, like https://unpkg.com/dash-core-components@2.0.0/dash_core_components/dash_core_components-shared.js, returns

```Cannot find package dash-core-components@2.0.0``` 

also

```Cannot find package dash-table@5.0.0```

![image](https://user-images.githubusercontent.com/140761/132138159-ac312527-78bc-44a8-8a80-198e2b6d7b1e.png)

**Comment by mfagundes** [comment]
I notice that it was, in fact, a dash core component issue - which only since version 2 is part of Dash. Django Plotly Dash installed Dash 2 as dependency, and that was the incompatibility. New version limits to Dash 1.21 and the upgrade solved the problem.

**Comment by alexcjohnson** [comment]
Thanks for pointing out that the unpkg CDN versions hadn't been updated - that's fixed now!
