### ISSUE TITLE
Initial n_clicks for a Button is None instead of 0 inside a callback

### ISSUE THREAD

**Issue by Akronix** [plotly/dash#177]
I have a Button imported from dash_html_components and I'm using it as an Input for a callback. In the very first execution, the initial value of n_clicks is `None`, but I would expect it to be `0` :confused:

**Comment by chriddyp** [comment]
Yeah, that's definitely confusing. Right now, any unspecified property in a dash component defaults to `None` (so at least the behaviour is consistent).
You can get around this by explicitly setting the initial property of the component in the layout with e.g.
```
app.layout = html.Div([
    html.Button(n_clicks=0)
])
```

**Comment by Akronix** [comment]
Ok that works.
However, it is specially confusing when you see that the Button react component initial state is 0, whereas that in Dash callback it evaluates to None.

**Comment by chriddyp** [comment]
Yeah, perhaps in the future we can use the values in the `defaultProps` as the initial state. That could be done as part of the push described in https://github.com/plotly/dash/issues/150#issuecomment-350872879
