### ISSUE TITLE
[Feature Request] suport patter-matching dependencies in @long_callback

### ISSUE THREAD

**Issue by vsisl** [plotly/dash#1813]
Pattern-matching dependencies are currently not supported by the `@long_callback` operator as stated in the [documentation](https://dash.plotly.com/long-callbacks).

I don't know what are the technical obstacles to enable pattern-matching long callbacks but for me personally, this feature would be super helpful.

**Alternatives**
It is possible to manually execute a pattern-matching callback asynchronously with Celery. However, one has to write all the boilerplate code: `Interval` component, one callback for task submission, second callback for task state monitoring and results retrieval, third callback for disabling the `Interval`.

What is the reason why the `@long_callback` does not support pattern-matching dependencies out of the box? Is the support planned for the future versions of Dash?

**Comment by vsisl** [comment]
A forum user **ajm** suggested a [workaround](https://community.plotly.com/t/long-callback-with-celery-redis-how-to-get-the-example-app-work/57663/12):

> As a workaround, you can use a normal callback with pattern matching and store the inputs as a JSON string in a hidden div.
Then add a long_callback with the hidden div as input.
Not pretty but works for me.

**Comment by halemade** [comment]
https://plotly.zendesk.com/agent/tickets/5153
customer requested! will suggest the workaround

**Comment by BBSeward** [comment]
+1 for this feature request! The workaround may be simple for some applications, but the return back from the long callback gets complicated with complex inputs to the hidden div.

**Comment by Mereep** [comment]
+1

**Comment by T4rk1n** [comment]
Implemented in 2.6.0 as part of the background callback refactor.
