### ISSUE TITLE
Set a cookie from callback function

### ISSUE THREAD

**Issue by oryba** [plotly/dash#182]
It seems that setting a cookies from callback function is currently impossible. I think it would be great if this feature will appear in the future versions.

Thank you:)

**Comment by ned2** [comment]
My immediate thought was that this could be done with a callback that inserts a <script> tag with some JavaScript that sets a cookie, but according to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML), the html5 spec says that <script> tags inserted via innerHTML should not execute. So no go there.

There are other ways to get arbitrary JS code to execute via innerHTML, which might work (the same MDN article provides an example of how), but at that point it's definitely a hack job.

**Comment by oryba** [comment]
Thank you for response!

Interesting and useful workaround. But despite the fact it's a hack job, setting `httponly` cookie couldn't be done this way.

**Comment by chriddyp** [comment]
I suspect this could be a custom Dash component.

What's the use case that you have in mind?
