### ISSUE TITLE
[Feature Request] Consider replacing Lenna.jpg

### ISSUE THREAD

**Issue by jeffBP** [plotly/dash#1823]
### Overview

When looking at the source code for `dash-core-components` i noticed the use of an antiquated image (lenna.jpg) in testing downloads. I don't want to debate about it's merits for image processing but the use of this photo may make development on dash more hostile towards women. Linked here (https://www.tandfonline.com/doi/full/10.1080/09500340.2016.1270881) is an article briefly discussing the history of the image and some potential alternatives. Given that this is being used to test downloading, id also like to propose using an image of my late cat (named Chuck) as an alternative (pictured below).

**Additional context**
Article from the journal Nature discussing dropping the image: https://www.nature.com/articles/s41565-018-0337-2

![chuck](https://user-images.githubusercontent.com/8907185/139908745-d63d1207-3021-4ed4-a374-b08f44885d48.jpg)

**Comment by nicolaskruchten** [comment]
Strong approve. If you want to open a PR for this, we can merge it in short order. Thanks for bringing this to our attention, I wasn't aware we were using this image.

**Comment by jeffBP** [comment]
https://github.com/plotly/dash/pull/1825

**Comment by alexcjohnson** [comment]
Closed in #1825 - much appreciated @jeffBP !
