### ISSUE TITLE
Add link_target option to dcc.Markdown

### ISSUE THREAD

**Issue by nopria** [plotly/dash#1827]
Since `dash_table.DataTable` already has a `markdown_options` that allows to easily change the link target behavior of Markdown inside DataTable, I think  that even more so `dcc.Markdown` should have such a useful option.

The default link target behavior in HTML is `_self`, which opens the link in the same window. But most often you want the user to stay in your page, opening the link in a new window through the `_blank` HTML option.

Currently, to change the target behavior of a Markdown link you have to enable HTML inside Markdown, a cumbersome solution that poses **security issues**, as evident even from the name of the option which is `dangerously_allow_html`.

**Comment by aGitForEveryone** [comment]
I'd like to support this feature. Would be very useful.

**Comment by alexcjohnson** [comment]
Closed by @adrianoesch in #2034 🎉
