### ISSUE TITLE
Custom unpkg mirror domain name[Feature Request]

### ISSUE THREAD

**Issue by CNFeffery** [plotly/dash#1832]
In `Dash`, we can force our app to use **unpkg** cdn to load js files(`serve_locally=False`), it would be better if  `Dash` could add parameter (such as `unpkg_mirror_prefix`) to allow developer custom **unpkg** cdn mirror prefix, for example:

- origin unpkg：`https://unpkg.com/dash-renderer@1.10.0/build/dash_renderer.min.js`
- zhimg unpkg mirror：`https://unpkg.zhimg.com/dash-renderer@1.10.0/build/dash_renderer.min.js`

**Comment by CNFeffery** [comment]
@alexcjohnson

**Comment by alexcjohnson** [comment]
Thanks @CNFeffery - I wasn't aware of these mirrors, it sounds like a good idea but probably not something we'll get to any time soon. If you'd like to make a PR we'd be glad to review. Doesn't look like it's really a prefix, so I'd suggest to implement it as `unpkg_mirror="https://unpkg.zhimg.com"`

**Comment by CNFeffery** [comment]
@alexcjohnson finally, I found the easiest way to do it😂, `scripts=kwargs['scripts'].replace('https://unpkg.com/', 'https://unpkg.zhimg.com/')` , That's what I need

```Python

class CustomDash(dash.Dash):
    def interpolate_index(self, **kwargs):
        print(kwargs['scripts'])
        return '''
        <!DOCTYPE html>
        <html>
            <head>
                {metas}
                <title>{title}</title>
                {favicon}
                {css}
            </head>
            <body>
                {app_entry}
                <footer>
                    {config}
                    {scripts}
                    {renderer}
                </footer>
            </body>
        </html>
        '''.format(
            metas=kwargs['metas'],
            css=kwargs['css'],
            favicon=kwargs['favicon'],
            title=kwargs['title'],
            app_entry=kwargs['app_entry'],
            config=kwargs['config'],
            scripts=kwargs['scripts'].replace('https://unpkg.com/', 'https://unpkg.zhimg.com/'),
            renderer=kwargs['renderer'])


app = CustomDash(
    __name__,
    suppress_callback_exceptions=True,
    update_title=None,
    serve_locally=False,
)

```

**Comment by CNFeffery** [comment]
> Oh, neat solution! I suspect it could be simplified even further if you aren't changing the underlying template, something like:
> 
> ```python
> def interpolate_index(self, **kwargs):
>     scripts = kwargs.pop('scripts').replace('https://unpkg.com/', 'https://unpkg.zhimg.com/')
>     return super(dash.Dash, self).interpolate_index(scripts=scripts, **kwargs)
> ```

@alexcjohnson after I change to this code, I got `AttributeError: 'super' object has no attribute 'interpolate_index'` error message

**Comment by alexcjohnson** [comment]
Ah sorry, got the `super` call wrong, should have been:

```py
def interpolate_index(self, **kwargs):
    scripts = kwargs.pop('scripts').replace('https://unpkg.com/', 'https://unpkg.zhimg.com/')
    return super(CustomDash, self).interpolate_index(scripts=scripts, **kwargs)
```

**Comment by CNFeffery** [comment]
> Ah sorry, got the `super` call wrong, should have been:
> 
> ```python
> def interpolate_index(self, **kwargs):
>     scripts = kwargs.pop('scripts').replace('https://unpkg.com/', 'https://unpkg.zhimg.com/')
>     return super(CustomDash, self).interpolate_index(scripts=scripts, **kwargs)
> ```

It works, thanks a lot!🥳
