### ISSUE TITLE
1 is showing as prime number in Advanced callbacks[BUG]

### ISSUE THREAD

**Issue by yesdeepakmittal** [plotly/dash#1835]
![image](https://user-images.githubusercontent.com/50262096/141864608-18f66b60-7bab-4ff5-bc10-ac05e2a7c898.png)

In the documentation of [Dash](https://dash.plotly.com/advanced-callbacks), 1 is being shown as a prime number.

**Comment by alexcjohnson** [comment]
Heh fair enough, we'll restrict the input to 2 or greater
