### ISSUE TITLE
OK good. I'll close this issue, but yes, conda-forge is a bit behind. Currently the dash feedstock is a community effort, we'll discuss whether Plotly folks could take a more proactive role there. Sorry about the confusion!

### ISSUE THREAD

**Issue by TessieTong** [plotly/dash#1842]
OK good. I'll close this issue, but yes, conda-forge is a bit behind. Currently the dash feedstock is a community effort, we'll discuss whether Plotly folks could take a more proactive role there. Sorry about the confusion!

_Originally posted by @alexcjohnson in https://github.com/plotly/dash/issues/1196#issuecomment-614069028_

**Comment by TessieTong** [comment]
Hi 
I am using the latest version of dash:
dash                          2.0.0
dash-core-components          2.0.0
dash-html-components          2.0.0
dash-renderer                 1.2.4
dash-table                    5.0.0

```
import pandas as pd
columns=['Date','col1','col2', 'col3']
data={'row1':['2019-01-31',166.440, 73.417283, 59.702568],
'row2':['2019-02-01', 166.520, 73.530398, 59.782428],
'row3':['2019-02-04', 171.250, 79.536789, 64.288669],
'row4':['2019-02-05', 174.179, 82.418937, 66.771527],
'row5':['2019-02-06', 174.240, 82.478897, 66.823261],
'row6':['2019-02-07', 170.940, 67.869795, 61.266096],
'row7':['2019-02-08', 170.410, 65.689645, 60.397355],
'row8':['2019-02-11', 169.429, 61.428562, 58.737154],
'row9':['2019-02-12', 170.889, 65.333093, 60.478345],
'row10':['2019-02-13', 170.179, 61.784665, 59.170717]}

df=pd.DataFrame.from_dict(data, orient='index')
df.columns = columns
df['Date']=pd.to_datetime(df['Date'])

import plotly.graph_objs as go
from plotly.subplots import make_subplots

import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output

app = dash.Dash(__name__)

app.layout = html.Div([
    html.Div([
            dcc.Checklist(
                id='variables',
                values='value')
        ]),
    dcc.Graph(id='chart', figure={})
])

@app.callback(
    Output(component_id='chart', component_property='figure'), #],
    [Input('variables','values')])
def update_graph(variable):
    
    fig = make_subplots(rows=2, cols=1, row_heights = [0.75, 0.25], vertical_spacing=0.01, subplot_titles=(' ', ''))#, shared_xaxes=True)

    fig.add_trace(go.Scatter(x=df.Date, 
                        y=df['col1'], line_color='black', line_width = 1), row = 1, col = 1)
    fig.add_trace(go.Scatter(x = df.Date, 
                        y = df['col2'], line_color='cyan', line_width = 1), row = 2, col =1)
    fig.update_xaxes(rangebreaks=[dict(values=['2019-02-02','2019-02-03','2019-02-09','2019-02-10'])])
    return fig

# -------------------------------------------------- ----------------------------
if __name__ == '__main__':
    app.run_server(debug=False)
```

The rangebreaks still did not apply when rendering with dash. 
![Capture2](https://user-images.githubusercontent.com/94763783/142804682-bc57bf45-ec90-4764-add6-0da399821b31.PNG)

**If I upgrade dash-renderer from 0.20.0 to 1.2.4 or up, the app hangs Loading... forever.**

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
