### ISSUE TITLE
[BUG] Plotly Scatter3d Hover Box Not Colored in Dash

### ISSUE THREAD

**Issue by EricNeville** [plotly/dash#1859]
**Describe your context**
Please provide us your environment, so we can easily reproduce the issue.

-  replace the result of `pip list | grep dash` below
```
dash                               1.16.0
dash-auth                          1.3.2
dash-bootstrap-components          0.10.1
dash-core-components               1.12.0
dash-daq                           0.5.0
dash-html-components               1.1.1
dash-renderer                      1.8.0
dash-table                         4.10.1
django-plotly-dash                 1.3.1
jupyter-plotly-dash                0.4.2
jupyterlab-dash                    0.1.0a3
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: Windows 10
    - Browser: chrome

**Describe the bug**

When using plotly's Scatter3d with a color column specified in the data, it is expected that the info boxes that appear on hover match the color of the point. However if the exact same figure is presented in dash with dcc.Graph this is no longer the case, and these info boxes all show up the same color.

**Code Example**

Produces the plot, renders it in a browser window as well as running a dashboard containing the same plot. 

```
from scipy.stats import norm 
import numpy
import plotly.graph_objects as go

x = norm.rvs(size = 100)
y = norm.rvs(size = 100)
z = norm.rvs(size = 100)
color = np.random.choice([1,2,3,4], size = 100)
data = pd.DataFrame(dict(zip(["x","y","z", "c"], [x,y,z, color])), index = range(100))

fig = go.Figure()
fig.add_trace(go.Scatter3d(x = data.x, 
                            y = data.y, 
                            z = data.z, 
                            mode = "markers", 
                            marker = dict(color = data.c),                                                
                            ))

fig.update_layout(
    autosize = False,
    width = 1000,
    height= 1000
)
fig.show(renderer="browser")

import dash
import dash_bootstrap_components as dbc
import dash_core_components as dcc
import dash_html_components as html

dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = html.Div([
    dcc.Graph(figure = fig)
    ])
app.run_server(debug=False, use_reloader = False, host='0.0.0.0', port = 8050)
```

**Screenshots**

I have screenshots but can't seem to add them. Getting "Something went really wrong, and we can't process that file."

**Comment by alexcjohnson** [comment]
What version of `plotly` do you have? Typically issues like this come from differences in `plotly.js` version between the one included with `plotly` (used in `fig.show`) and `dash` (via `dash-core-components` in `dash v1.x`, via `dash.dcc` in `dash v2.x`). In particular I believe `plotly.js v2.0.0` improved some aspects of 3D hover, and this is included in `plotly.py>=5.0` and `dash>=2.0`. So upgrading to the latest `dash` will likely fix it for you.

**Comment by EricNeville** [comment]
> What version of `plotly` do you have? Typically issues like this come from differences in `plotly.js` version between the one included with `plotly` (used in `fig.show`) and `dash` (via `dash-core-components` in `dash v1.x`, via `dash.dcc` in `dash v2.x`). In particular I believe `plotly.js v2.0.0` improved some aspects of 3D hover, and this is included in `plotly.py>=5.0` and `dash>=2.0`. So upgrading to the latest `dash` will likely fix it for you.

I am also on plotly 4.12, though I can't update dash or plotly to 2.0 and 5.0 as I'm working in a company environment, but if this has been fixed in the later versions then fair enough I guess this can be closed.
