### ISSUE TITLE
dash won't install on Python 3.6.4

### ISSUE THREAD

**Issue by gfrair** [plotly/dash#1871]
Good day,

We have large clustered Data environment with no access to the internet.  I'm attempting to install "dash" from our local pip repository, but it doesn't want to install on Python 3.6.4.  I've tried version 2.0.0 and 1.21.1. 

When attempting to install dash 2.0.0, I get the following error:

ERROR: Package 'dash' requires a different Python: 3.6.4 not in '>=3.6'

When attempting to install dash 1.21.1, I get the following error:

ERROR: Package 'dash' requires a different Python: 3.6.4 not in '!=3.0.*,!=3.1.*,!=3.2.*,>=2.7'

Neither of these are appear to actually state 3.6.4 is not supported, however I can't for the life of me get it to install.  Is there a version of dash specific to Python 3.6.4, or is it simply not supported?  It's not an easy environment to update the Python version so this will likely not permit us to use dash in the near future if it is simply not supported.

Apologies if this is not the correct place for this question, I'm just getting a little desparate.

Thanks,

Greg

**Comment by alexcjohnson** [comment]
That's strange indeed - we have no issues installing dash in our CI test environments using Python 3.6, though for the most part this is a later version (currently 3.6.13 in this repo).

Locally (Mac) I have 3.6.8 and can install either dash 1.21.0 or 2.0.0 with various versions of pip. What OS and pip version are you using?

**Comment by gfrair** [comment]
Hi Alex,

I'm running CentOS 7.8 with pip 21.0.1. 

We have a small contained Kubernetes environment running Python 3.6.9 and I was able to successfully install dash 2.0.0 there from the same localized repository.  I'm really at a loss and feel like it might have to do with the version of Python in anaconda maybe (3.6.4 as I mentioned), however like I said, I can't upgrade it "willy nilly" since there are many code dependencies that would have to be tested.

Any advice or suggestions would be greatly appreciated.

Thanks,

Greg

**Comment by gfrair** [comment]
Good day,

I was able to determine my problem.

I had to download about 25 dependent packages for dash and based my download purely on the version that dash told me to download.  One of the packages (importlib-metadata) was not compatible with Python 3.6.4.  Once I downgraded this package it worked fine.

Thanks for your help and apologies for the user error.

Regards,

Greg

**Comment by gfrair** [comment]
For the record, I really wish pip told me which package it was having a hard time with rather than simply the one that I'm trying to install.

**Comment by alexcjohnson** [comment]
@gfrair I'm happy to hear you've solved the issue! Perhaps we can resolve this for anyone else in this situation by adding a line to https://github.com/plotly/dash/blob/dev/requires-install.txt, something like:

```
importlib-metadata==x.y.z;python_version<"3.6.8"
```
ie what version x.y.z did you end up needing?

**Comment by gfrair** [comment]
@alexcjohnson I ended up having to install version 4.8.3 of importlib_metadata.  Might be useful to add, as it took me a couple days of immense frustration to solve, so I'm sure it would be appreciated if it helped other users avoid the same scenario, however I definitely should of thought of reviewing the dependencies sooner.... a bit of an ID10T error :)

Thanks again,

Greg

**Comment by alexcjohnson** [comment]
OK interesting - 4.8.3 is the last version compatible with Py3.6 at all, so I'm not sure why pip couldn't figure out to give you that. Anyway I'll add that to the requirements and hopefully that will save others your headache. Thanks!
