### ISSUE TITLE
[BUG] merge_duplicate_headers breaks style_header_conditional

### ISSUE THREAD

**Issue by bernhardbarker** [plotly/dash#1877]
**Describe your context**

Environment:
```
dash                      2.0.0
dash-bootstrap-components 1.0.2
dash-core-components      2.0.0
dash-html-components      2.0.0
dash-table                5.0.0
```

Probably not important:
- OS: Ubuntu 21.10
- Browser: Chrome 96.0.4664.110

**Describe the bug**

When I run the below code which uses `style_header_conditional` to highlight columns `1_1a` and `1_1b`, it incorrectly highlights header cells `1b`, `2` and `2a`.

**Expected behavior**

It should highlight the cells corresponding to the specified columns, i.e. `1`, `1a` and `1b` (i.e. the same cells it would highlight if I remove `merge_duplicate_headers=True`).

Note: I understand that when specifying some, but not all, of the columns which are included in a merge, there may be a few reasonable ways that can be displayed. But in this case the expected behavior seems quite obvious and the observed behavior is clearly wrong.

**Code**

```python
from dash import Dash
import dash.dash_table as dt
import dash_bootstrap_components as dbc

app = Dash()

app.layout = dbc.Container([
    dt.DataTable(
        id='tbl', data=[],
        columns=[
            {'name': (), 'id': 'x'},
            {'name': (), 'id': 'y'},
            {'name': ('1', '1a'), 'id': '1_1a'},
            {'name': ('1', '1b'), 'id': '1_1b'},
            {'name': ('2', '2a'), 'id': '2_2a'},
            {'name': ('2', '2b'), 'id': '2_2b'},
        ],
        merge_duplicate_headers=True,
        style_header_conditional=[
            {
                'if': {'column_id': f'1_1{c}'},
                'backgroundColor': 'green',
                'fontWeight': 'bold'
            } for c in ['a', 'b']
        ],
    ),
])

if __name__ == "__main__":
    app.run_server(debug=True)
```

**Screenshots**

Actual highlighting:

![Screenshot from 2022-01-03 14-50-12](https://user-images.githubusercontent.com/36070131/147938692-5694c640-cbf1-4c78-a330-e749fac84ad7.png)

Desired highlighting:

![164121756719547194](https://user-images.githubusercontent.com/36070131/147938733-8d5f26d0-8264-4986-95b8-78a63e6456c7.png)

**Comment by alexcjohnson** [comment]
I'm seeing the "desired highlighting" when I try the code above now:
<img width="523" alt="Screenshot 2023-04-25 at 22 11 58" src="https://user-images.githubusercontent.com/2678795/234448508-0c77cf2c-d4ef-4cdf-9359-2e103b3a68a1.png">
So I believe #1968 resolved this issue but we forgot to close it 🎉

**Comment by korzi27** [comment]
Not sure if i should post it here or create something new but i think it falls into the same category. Actually i still get bugs with using merge_duplicate_headers=True and style_cell_conditional. I am only on 2.18.2 yet but as mentioned it should be fixed and i see no changes in the newer versions. Here is a minimal example where it happens with the most upper right column border. 

```
import dash
from dash import Dash, dash_table, html
import pandas as pd

# Sample data
data = {
    'Group A': ['Alice', 'Bob'],
    'Group A.1': [10, 20],
    'Group B': ['X', 'Y'],
    'Group B.1': [100, 200],
    'Group B.2': [1.1, 2.2]
}

# Create DataFrame
df = pd.DataFrame(data)

# Define columns with headers as lists for multi-level headers
columns = [
    {'name': ['Name', 'Person'], 'id': 'Group A'},
    {'name': ['Name', 'Score'], 'id': 'Group A.1'},
    {'name': ['Details', 'Code'], 'id': 'Group B'},
    {'name': ['Details', 'Value 1'], 'id': 'Group B.1'},
    {'name': ['Details', 'Value 2'], 'id': 'Group B.2'},
]

# Define style for bold black borders
style_cell_conditional = [
    {
        'if': {'column_id': col},
        'borderRight': '5px solid black',
        'fontWeight': 'bold'
    } for col in ['Group A.1', 'Group B.1']  # Columns to highlight
]

# Dash app
app = Dash(__name__)

app.layout = html.Div([
    dash_table.DataTable(
        data=df.to_dict('records'),
        columns=columns,
        merge_duplicate_headers=True,
        style_cell={'textAlign': 'center'},
        style_cell_conditional=style_cell_conditional
    )
])

if __name__ == '__main__':
    app.run_server(debug=True)

```
