### ISSUE TITLE
[BUG] Dash document is still using old ways to import core and html components

### ISSUE THREAD

**Issue by hopezh** [plotly/dash#1892]
As shown in the documents of [Dash Core Components](https://dash.plotly.com/dash-core-components), it is still using the old way to import the core and html components: 

```
import dash_core_components as dcc
import dash_html_components as html
```

This could lead to misunderstanding for the users. I have to spend quite a while to realize from the messages shown after updateing both dash-core-components and dash-html-components pacakges  that code above need to be udpated to: 

```
from dash import dcc
from dash import html
```

Can the Dash team to update the documents and the example codes to reflect such changes? Thanksl

**Comment by alexcjohnson** [comment]
Thanks @hopezh - cc @LiamConnors

**Comment by hopezh** [comment]
To reply myself, the issue mentioned above is covered in the documents on [**Dash 2.0 Migration**](https://dash.plotly.com/dash-2-0-migration). 

**Recommended Updates — Import Statements**

Dash 2.0 includes a simpler way to import Dash as well as its dependencies and components.

If you update your apps to use Dash 2.0, we recommend you use this simpler import statement and replace references to dash_html_components, dash_core_components, and dash_table in your app imports.

Dash 1.x
```
import dash_html_components as html
import dash_core_components as dcc
import dash_table
```

Dash 2.0
```
from dash import Dash, callback, html, dcc, dash_table, Input, Output, State, MATCH, ALL
```

In the above example, html, dcc, and dash_table are imported along with Dash, callback, Input, Output, State, MATCH, and ALL.

**Comment by LiamConnors** [comment]
Thanks @hopezh. Sorry for the delay. We will ensure we get the remaining examples updated with the next release of Dash, version 2.1.
