### ISSUE TITLE
[BUG] Dropdown:  Selected options not showing when the `value` contains a comma 

### ISSUE THREAD

**Issue by AnnMarieW** [plotly/dash#1908]
As [reported on the forum by @ marcus](https://community.plotly.com/t/dcc-dropdown-bug-suspected-please-confirm-or-correct-me/60585):

Problem is in this spot: 'value': "50 , 10"
Specifically comma in `value` string makes that selection is not being displayed. When coma is removed or replaced (dot creates no issue) it works fine, but when coma is within the string, the selections are not displayed in the input box and are not removed from the `options`

 This only occurs in Multi-Value dropdowns.  This is new in Dash V2.1.0  It works as expected in V2.0.0

```
from dash import Dash, dcc, html, Input, Output

app = Dash(__name__)

app.layout = html.Div(
    [
        dcc.Dropdown(
            id="dropdown",
            className="inputbox-long",
            options=[
                {"label": "New York City", "value": "50, 10"},
                {"label": "Montreal", "value": "MTL" },
                {"label": "San Francisco", "value": "SF"},
            ],
            placeholder="Select one or more",
            multi=True,
        ),
        html.Div(id="output"),
    ]
)


@app.callback(
    Output("output", "children"), Input("dropdown", "value"),
)
def update(value):    
    return value


if __name__ == "__main__":
    app.run_server(debug=True)
```
![dropdown_bug](https://user-images.githubusercontent.com/72614349/152015862-8680cc37-dc44-4ebd-b6c5-32975ee08e98.gif)

**Comment by astrowonk** [comment]
Yikes, yeah this bug is breaking my covid dashboard when I upgraded to 2.2 from 2.0. I have a Dropdown with County,State pairs: .e.g. `Harris, Texas`. It's all broken now.

This is a pretty bad breaking bug, can we get someone assigned to this?
