### ISSUE TITLE
[BUG] Slider displays marks when none are defined

### ISSUE THREAD

**Issue by DrGFreeman** [plotly/dash#1910]
**Describe your context**

```
dash                      2.1.0
dash-bootstrap-components 1.0.2
dash-core-components      2.0.0
dash-html-components      2.0.0
dash-table                5.0.0
```

**Describe the bug**

`dcc.Slider` displays marks even when none are defined.

**Steps to reproduce**

Run the Slider basic example from docs (with new imports):

```python
import dash
from dash import html
from dash import dcc

external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']

app = dash.Dash(__name__, external_stylesheets=external_stylesheets)

app.layout = html.Div([
    dcc.Slider(
        id='my-slider',
        min=0,
        max=20,
        step=0.5,
        value=10,
    ),
    html.Div(id='slider-output-container')
])

@app.callback(
    dash.dependencies.Output('slider-output-container', 'children'),
    [dash.dependencies.Input('my-slider', 'value')])
def update_output(value):
    return 'You have selected "{}"'.format(value)

if __name__ == '__main__':
    app.run_server(debug=True)
```

**Expected behavior**

No marks are displayed:

![image](https://user-images.githubusercontent.com/22901938/152583458-4b2c59c4-1b18-442e-b8fa-acbc56c621ef.png)

**Actual behavior**

Marks are displayed for every step:

![image](https://user-images.githubusercontent.com/22901938/152583563-3120445a-c604-496b-aa3e-e99c228304a2.png)

**Comment by alexcjohnson** [comment]
This is a change in behavior that we added in Dash 2.1 - if you want to remove the marks you now need to explicitly set `marks=None`.

That said in this case it doesn't seem like we're accurately implementing the behavior described in the [changelog](https://github.com/plotly/dash/blob/dev/CHANGELOG.md#rearranged-keyword-arguments--flexible-types):

> marks will be auto generated if not given. It will use `min` and `max` and will respect `step` if supplied. Auto generated marks labels are SI unit formatted. *Around 5 human-readable marks will be created.*

You're seeing way more than 5 marks, by that measure you should have seen marks only at 0,5,10,15,20 - I'll take a look at this.
