### ISSUE TITLE
[Feature Request]Ability to have 'mouseup' and 'drag' for slider

### ISSUE THREAD

**Issue by shelterpup** [plotly/dash#1912]
Not sure if this has already been considered (couldn't find an open or closed ticket).

In reference to https://community.plotly.com/t/ability-to-have-a-drag-and-a-mouseup-for-a-single-slider/24995, unsure if @[alexcjohnson](https://community.plotly.com/u/alexcjohnson) advise was taken, but it would be nice to have seperate trigger events for both `mouseup` and `drag` updatemodes.

The `drag` would be helpful to provide visual feedback to the user on their selected value, and then `mouseup` will allow callback(s) to be triggered once the value was set (symbolized by releasing the mosue)

**Comment by alexcjohnson** [comment]
It's tricky to find now because it's in the old separate DCC repo, but I think `drag_value` is what you want https://github.com/plotly/dash-core-components/pull/888
