### ISSUE TITLE
dropdown 'label' doesn't render (seemingly) depending on 'value'

### ISSUE THREAD

**Issue by DBCerigo** [plotly/dash#194]
Hi,
Possible bug report:
Dropdown labels won't render in the dropdown box if the corresponding 'value' for the label is a tuple.

In below example: selecting `test_label0` will result in no rendering of `test_label0` in the dropdown box. Selecting `test_label1` will result in it correctly rending within the dropdown box. 
Expected behaviour: that label would always render in dropdown irrespective of `value` value.

```

# -*- coding: utf-8 -*-
import dash
import dash_core_components as dcc
import dash_html_components as html
import plotly.graph_objs as go

dropdown_options = [
        {'label':'test_label0', 'value':(0,'test_label0')},
        {'label':'test_label1', 'value':1},
        ]

app = dash.Dash()

app.layout = html.Div(children=[
    html.H1(children='dropdown_test'),

    dcc.Dropdown(
        id='dropdown',
        options=dropdown_options,
    )])

if __name__ == '__main__':
    app.run_server(debug=True)
```

On OSX, install via pip in conda env:
```
dash                      0.19.0                    <pip>
dash-core-components      0.15.4                    <pip>
dash-html-components      0.8.0                     <pip>
dash-renderer             0.11.1                    <pip>
dash.ly                   0.17.3                    <pip>
```

**Comment by chriddyp** [comment]
Thanks for reporting @DBCerigo !

Yeah, `value` has to be a string. I'm not sure if this is a bug, as that's the expected behaviour. The error messages could certainly be improved if the type is incorrect and we could document these types better too (currently it's only documented in the JS source code at https://github.com/plotly/dash-core-components/blob/a74477bfd13e910b63c2bb456807b384ccc40681/src/components/Dropdown.react.js#L102-L126 - it's not getting mapped to the component docs at https://plot.ly/dash/dash-core-components/dropdown or when calling `help(dcc.Dropdown)`)



 If you need to map values to other objects, I recommend doing something like:
```
values = {
    'value-1': {'some': 'other data'},
    'value-2': {'some': 'more data'},
}

options = [
    {'label': 'label 1', 'value': 'value-1'},
    {'label': 'label 2', 'value': 'value-2'},
]

app.layout = ...

@app.callback(Output(...), [Input('dropdown', 'value')])
def update_dropdown(value):
     data = values[value]
```

Is there some other reason for wanting to supply a tuple for `value`?

**Comment by DBCerigo** [comment]
Thanks for the response. 

Great, that's good to know and will at least let me avoid the issue in future. I didn't receive an error message on the server (python) side, though I didn't check in the browser console if it threw. Though, I could parse the tuple successfully in the callback!!!...
So everything else in the page worked as intended (using both elements of data stored in the tuple in the graph I was feeding the data too, on the non-rendering of the label happened so.

Thanks for the tip on how to map the labels to more complex data than a single string. 

I wanted to map the labels to an id and a string, hence the tuple.

**Comment by chriddyp** [comment]
Got it, makes sense! I'll close this issue now and open an issue for the other items (error messages)

**Comment by DBCerigo** [comment]
Nice one

**Comment by DBCerigo** [comment]
Hi again,

Just an FYI; after working more with the dropdown values, I'm pretty sure that it's casting `str`s to `int`s if the string in `value` is just (the string) of a plain integer! :/ 

I haven't looked at where it could be happening in the code. Current solution is just recasting the input parameter (from dropdown value) in each callback to a string again...

Apart from this tricksy dropdown value, everything else is working great and looks great :)

**Comment by ned2** [comment]
I don't seem to be able to reproduce this behaviour using your same Dash dependencies. Here's the code I'm using:

```python
import dash
from dash.dependencies import Input, Output
import dash_core_components as dcc
import dash_html_components as html

dropdown_options = [
    {'label':'test_label1', 'value':'1'},
    {'label':'test_label2', 'value':'2'},
]

app = dash.Dash()

app.layout = html.Div([
    html.H1(children='dropdown_test'),
    dcc.Dropdown(
        id='dropdown',
        options=dropdown_options,
        value='1'
    ),
    html.Div(id='target')
])

@app.callback(Output('target', 'children'), [Input('dropdown', 'value')])
def callback2(value):
    print(type(value))
    return value

if __name__ == '__main__':
    app.run_server(debug=True)
```

Note also that you should probably be providing an initial value for `value` when you initialize the Dropdown, otherwise it will get the value `None` on each initial page load.

**Comment by DBCerigo** [comment]
@ned2 sorry for the lack of response! 

The "bug" (clearly not actually a bug) stopped, and I couldn't track down what the change was. 

But thanks for the response, and right that the issue is now closed 👍
