### ISSUE TITLE
[BUG] Hot reload not working when serving a Dash app using waitress

### ISSUE THREAD

**Issue by urig** [plotly/dash#1955]
### Context
I am building a dashboard application that is based on Dash and is served by [waitress](https://github.com/Pylons/waitress).

```
dash                 2.2.0
dash-core-components 2.0.0
dash-html-components 2.0.0
dash-table           5.0.0
```

### Description

I am serving my Dash app from waitress and I find that the "hot reload" feature is not working for me. I expect Dash's "hot reload" to work when serving through waitress.

### Steps to reproduce the issue
1. Create a new python project
2. Install dependencies `dash` (2.2.0) and `waitress` (2.0.0).
3. Add a `main.py` python file that contains a Dash app.
4. In the file, serve your app from waitress like so:
    ```
    app.enable_dev_tools(debug=True)
    waitress.serve(app.server, host="127.0.0.1", port=8050)
    ```
6. Run `main.py`, open a browser at `http://localhost:8050/` and observe your app.
7. Make a change to the app layout in `main.py` and save it.

### Expected behavior
The browser window should automatically refresh and display the change made to the layout.

### Actual behavior
Nothing happens.

### Notes 

1. A GH repo with a minimal reproduction of this issue is available here: https://github.com/urig/dash-hot-reload-repro

3. If you replace the two lines in step 4 above with: `app.run_server(debug=True)` and restart the process you can see that hot reload works when serving through Dash.

5. I have found a workaround in [a stackoverflow answer](https://stackoverflow.com/a/61920542/33404). It is based on hot reload functionality from [werkzeug](https://werkzeug.palletsprojects.com/en/2.0.x/). Despite this I think Dash would benefit from making its own hot reload feature available "out of the box" when serving through waitress.

**Comment by luchaoqi** [comment]
Similar feature requested, I am developing a multi-page app, and it seems `werkzeug` is not working for me. I would like to know if there's any way to hot reload the whole app like component validation in the initialization through callback?

**Comment by alexcjohnson** [comment]
I suppose you could create a clientside callback that calls [`location.reload()`](https://www.w3schools.com/jsref/met_loc_reload.asp)

**Comment by luchaoqi** [comment]
Thanks, @alexcjohnson! Will definitely try it out.

**Comment by T4rk1n** [comment]
Hot reload is meant for dev purpose, it leverage flask/werkzeug reload functionality and will only works when running that. I think you can develop your app with regular run and only run waitress on production.

**Comment by urig** [comment]
@luchaoqi maybe consider the approach taken here, based on [hupper](https://docs.pylonsproject.org/projects/hupper/en/latest/index.html): https://github.com/entropy-lab/entropy/pull/191.

**Comment by luchaoqi** [comment]
@urig Thanks!
