### ISSUE TITLE
[Feature Request] add size attribute to dcc.Dropdown

### ISSUE THREAD

**Issue by GNSS-Monitoring** [plotly/dash#1971]
Hey guy, was wondering if you could add the size attribute to the dcc.Dropdown so that we have the ability to show all the select options rather than display a vertical scrollbar if you have more than 6 options.  

In a normal html select tag you can specify a size attribute as follows:

<select name="cars" id="cars" size="8">

See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select for more info about the size attribute.

**Comment by alexcjohnson** [comment]
Closed by @AnnMarieW in https://github.com/plotly/dash/pull/2109 by adding a `maxHeight` prop 🎉
