### ISSUE TITLE
[Feature Request] give Plotly Dash a modern/unique/professional look

### ISSUE THREAD

**Issue by nibu147** [plotly/dash#1986]
Hi all,
I'm a big fan of plotly dash and I've just realized a dashboard with modals, graphic elements and also by using dash bootstrap components.

The appearance of my dashboard is quite ok, but it feels a bit oldish and similar to all the same dash and bootstrap pages: any suggestion on how to make it fancier? Any dash theming with .css settings or dash components which can make my dash look more modern/unique/professional?

Thanks!

**Comment by AnnMarieW** [comment]
Thanks for your question.


You might be interested in [Dash Enterprise Design Kit](https://plotly.com/dash/design-kit/) which was developed to address this concern.


If you are looking for open source solutions, there are several options.  You could create your own stylesheet, [customize  Bootstrap](https://getbootstrap.com/docs/5.0/customize/overview/), or use other Dash libraries such as [dash-mantine-components](https://dash-mantine-components.herokuapp.com/).   If you would like more information, please feel free to ask the question on the [Dash Community Forum.](https://community.plotly.com/)
