### ISSUE TITLE
[BUG] Wrong data type of returned value from dropdown when using options from a dictionary

### ISSUE THREAD

**Issue by disanman** [plotly/dash#2011]
# Context

```
dash                           2.3.1
dash-bootstrap-components      1.0.3
dash-core-components           2.0.0
dash-html-components           2.0.0
dash-table                     5.0.0
```

# Bug description

When using a dictionary to define the options of a dropdown, and the keys are integers, the return value of the selection is converted into string.

```python
# Example that creates two dropdowns: 1 using the label/value approach, the second using a dictionary
from dash import Dash, dcc, html, Input, Output


app = Dash(__name__)

options1 = [
        {'label': 'option1', 'value': 1},
        {'label': 'option2', 'value': 2},
        {'label': 'option3', 'value': 3}
]
options2 = {
    1: 'option1',
    2: 'option2',
    3: 'option3',
}

app.layout = html.Div([
        dcc.Dropdown(id='dropdown1', options=options1),
        html.Div(id='div1'),
        dcc.Dropdown(id='dropdown2', options=options2),
        html.Div(id='div2')
])


@app.callback(Output(component_id='div1', component_property='children'),
              Input(component_id='dropdown1', component_property='value'))
def update_output_div1(value_dropdown1):
    'Callback1: updates the text in div1 depending on the value of dropdown1'
    return f'{value_dropdown1 = }, data type: {type(value_dropdown1)}'


@app.callback(Output(component_id='div2', component_property='children'),
              Input(component_id='dropdown2', component_property='value'))
def update_output_div2(value_dropdown2):
    'Callback2: updates the text in div2 depending on the value of dropdown2'
    return f'{value_dropdown2 = }, data type: {type(value_dropdown2)}'


if __name__ == '__main__':
    app.run_server(debug=True)
```

# Expected behavior

The data type of the returned value for the `dropdown2` should be `int` (since its key had also an `int` datatype in its definition on `options2`).

# Screenshot

![bug_dropdown_value](https://user-images.githubusercontent.com/35890571/163080262-04d092e6-e112-4e62-8e23-51fd583a22c5.png)

**Comment by alexcjohnson** [comment]
Thanks @disanman - what's happening is when props are sent to the front end they're serialized to JSON format, and in JSON (and JavaScript), keys can only ever be strings, so numbers are automatically cast to strings and we no longer have any knowledge that they started as numbers.

I suppose in principle we could try to cast back to numbers (only when you use the dict shorthand), but then we run the risk of accidentally converting values that were always intended to be strings. Maybe that's a sufficiently unusual case that it would be a better outcome? Either way it's a limitation we'll need to document (cc @LiamConnors)

**Comment by disanman** [comment]
Oh I didn't know you can't have integer keys in JSON.
> I suppose in principle we could try to cast back to numbers (only when you use the dict shorthand), but then we run the risk of accidentally converting values that were always intended to be strings.

Yeah, maybe that is not the best solution, so it seems like this is in fact a limitation of using the dict shorthand.
Thanks a lot for taking a look at this @alexcjohnson!
