### ISSUE TITLE
[BUG] restyleData doesn't update with the graph

### ISSUE THREAD

**Issue by constance-scherer** [plotly/dash#2037]
**Environment**
-  result of `pip list | grep dash`:
```
dash                              2.3.0
dash-bootstrap-components         0.12.2
dash-core-components              2.0.0
dash-html-components              2.0.0
dash-renderer                     1.9.1
dash-table                        5.0.0

```
- Browser, Version and OS:

    - OS: Linux (Ubuntu) (also on Windows)
    - Browser: Firefox
    - Version: 99.0

**Description of the bug**

I have an application with an interactive graph. Selecting points from the graph (either by hand or from the legend items) updates other components, notably a span that just displays the number of selected points. The graph is linked to a slider. The slider value basically controls the number of colours in the legend. Updating the slider updates the figure.

This problem occurs when there is an active selection from the legend when the slider value is changed. The graph is correctly updated and the new legend is visually fully selected but the span still displays the previous number of points. 
This is because the information of points selected from the legend is found in the `restyleData` attribute of the graph, which is not updated when the graph changes. 

**Expected behaviour**
I expect the `restyleData` attribute to reflect the visual aspect of the legend when the graph updates: all legend items are selected, all points are shown on the graph, so I should see the correct number of points in the span (all of them).

## Is this the intended way of dealing with this attribute when the graph changes? 

**Minimal code example** (Edit- I've added a more complete example in a following message)
My actual application is very complex, but here is a minimal recreation of the bug:
```
from dash import dcc, html, Input, Output, State
import dash
import time
import json
import math
import pandas as pd
pd.options.plotting.backend = "plotly"

def plot_fig(df):
  """
  df: pd.DataFrame
  Create scatter plot from df
  """
  fig = df.plot.scatter( x='x_axis', y='y_axis',
          color='label', 
          hover_data={'x_axis': False, 'y_axis': False, 'label': True,}
          )

  fig.update_layout(legend= {'itemsizing': 'constant'})
  # Set the legend to the left
  fig.update_layout(legend={
      'x':0,
      'xanchor': 'right',
      'font_size':10
  })
  # Select the box selection tool by default
  fig.update_layout(dragmode="select")
  return fig

external_stylesheets = [
    'https://codepen.io/chriddyp/pen/bWLwgP.css', # regular dash css
    "https://codepen.io/chriddyp/pen/brPBPO.css" # loading screen css (method3)
    ]
app = dash.Dash(__name__, external_stylesheets=external_stylesheets)

# DATA
x = [1, 1, 1.5, 2, 4, 2.5, 3.5, 5, 3, 1]
y = [1, 3, 2, 3, 3.5, 4, 1, 4, 5, 4]
labels = [0,0,0,0,0,1,1,1,1,1]

df = pd.DataFrame({'x_axis': x, 'y_axis': y, 'label': labels})

fig = plot_fig(df)

# LAYOUT
app.layout = html.Div(
  [
      html.H3('Slider'),

      dcc.Slider(
          id="slider",
          min=2,
          max=5,
          step=1,
          value=2,
          marks={
              2: "2",
              3: "3",
              4: "4",
              5: "5",
          },
          disabled=False,
      ),

      html.H3('Graph'),

      dcc.Graph(
        id="plot_graph",
        figure=fig,
        config={
            'modeBarButtonsToRemove': ['autoScale2d', 'zoomIn2d', 'zoomOut2d', 'resetScale2d', 'hoverClosestCartesian', 'hoverCompareCartesian', 'toggleSpikelines'],
            'displaylogo': False
              }
      ),

      html.H3('Span'),

      html.Span(
        id="selected_nodes",
        children=['Elements selectionnes']
      ),

      dcc.Store(id='store_df', data=df.to_json()),
  ]
)

# CALLBACKS

# Change color of points based on slider value
@app.callback(
  [Output('plot_graph', 'figure'),
  Output('store_df', 'data')],
  Input('slider', 'value'), 
  State('plot_graph', 'restyleData')
)
def update_graph(n_labels, restyleData):
  #print('update_graph')

  labels = []
  step = math.ceil(10/n_labels)
  curr_label = 0
  while len(labels) <= 10:
    for i in range(0, step):
      labels.append(str(curr_label))
    curr_label += 1

  if len(labels) > 10:
    labels = labels[:10]

  df = pd.DataFrame({'x_axis': x, 'y_axis': y, 'label': labels})

  #print('restyleData', restyleData)

  return plot_fig(df), df.to_json()

# Show number of selected points
@app.callback(
  Output('selected_nodes', 'children'),
  [
  Input('plot_graph', 'restyleData'),
  Input('plot_graph', 'selectedData'),
  #Input('slider', 'value') 
  ], 
  State('store_df', 'data')
)
def update_selected_nodes(
                      restyleData, 
                      selectedData, 
                      #n_labels, 
                      data_json
                      ):
  #print('update_selected_nodes')

  df = pd.read_json(data_json)
  changed_id = [p['prop_id'] for p in dash.callback_context.triggered][0]
  count = -1

  if 'plot_graph.selectedData' in changed_id:
    if selectedData != None:
      count = len(selectedData['points'])
    else :
      count = len(df)
  
  elif 'plot_graph.restyleData' in changed_id:
    if restyleData != None:
      visible = restyleData[0]['visible']
      color_labels = restyleData[1]
      if visible == [True]*len(color_labels) :
        count = len(df)
      else :
        count = 0
        for (v, label) in zip(visible, color_labels):
          if v == True:
            count += len(df[df['label'] == label])
    else:
      count = len(df)

  else:
    count=len(df)

  return str(count)+' selected items'

if __name__ == '__main__':
    app.run_server(debug=True)
```
In this example, it is possible to add the slider value as an Input to `update_selected_nodes` to force the expected behaviour. However, this does **not** work in the real app, I get stuck on a loading screen indefinitely when there are too many points.

I haven't found any other posts describing the exact same bug, but #1853 might be related.

Any help on this issue would be greatly appreciated, thanks in advance!! :)

**Comment by constance-scherer** [comment]
Hey @nickmelnikov82, thank you for your answer! 

In the example, I store my dataFrame `df` because it contains info that is needed (in the real app). I didn't mention it, cause it seemed obvious to me since I'm the one working on it, but my example does not show it at all so you could not guess it was important. Sorry about that.

Your callback works perfectly, and since it uses `plot_graph.figure` as an Input, it does solve the problem occuring in this minimal example.

However, I still don't understand if what I've described previously is the intended behaviour for the `restyleData` attribute. 

**Should the `restyleData` attribute not change when the graph changes?** 

Furthermore, and while your answer is perfect for this example, it is unfortunately not applicable to my actual situation. Using `plot_graph.figure` as an Input leads to the same problem that I mentionned at the end of my previous message: infinite loading screen most of the time. It's actually unclear what causes the infinite loading, but it seems to be corrolated with the number of points and possibly the time needed to process them. 

**Is it possible for this loading screen to be the result of a callback taking 'too long'?** 

Just to recap:
- I have an app similar to, but much more complex than the minimal example I provided.
- In this app, I have to know when a selection is made to display the number of points that have been selected as well as info on them.
- I have ran into an issue where it seems that the `restyleData` attribute is not correctly triggered when the graph changes.
- Using `slider.value` or even `plot_graph.figure` as Inputs would in theory solve this issue.
- But using either one can cause an infinite loading screen.
- The infinite loading is not consistent, as it can appear with 1,000 points but sometimes doesn't appear with 10,000 points. 
- It's unclear to me what causes it to appear or not, but I reckon it's linked to the number of points and/or the time needed to process them.


Thanks again for taking the time to investigate my issue, I really appreciate it! :)

**Comment by constance-scherer** [comment]
To better represent my problem, here is a new example:

```
from dash import dcc, html, Input, Output, State
from dash import dash_table as dt
import dash
import time
import json
import math
import pandas as pd
pd.options.plotting.backend = "plotly"

def plot_fig(df):
  """
  df: pd.DataFrame
  Create scatter plot from df
  """
  fig = df.plot.scatter( x='x_axis', y='y_axis',
          color='label', 
          hover_data={'text': True, 'x_axis': False, 'y_axis': False, 'label': True,}
          )

  fig.update_layout(legend= {'itemsizing': 'constant'})
  # Set the legend to the left
  fig.update_layout(legend={
      'x':0,
      'xanchor': 'right',
      'font_size':10
  })
  # Select the box selection tool by default
  fig.update_layout(dragmode="select")
  return fig

external_stylesheets = [
    'https://codepen.io/chriddyp/pen/bWLwgP.css', # regular dash css
    "https://codepen.io/chriddyp/pen/brPBPO.css" # loading screen css (method3)
    ]
app = dash.Dash(__name__, external_stylesheets=external_stylesheets)

# DATA
x = [1, 1, 1.5, 2, 4, 2.5, 3.5, 5, 3, 1]
y = [1, 3, 2, 3, 3.5, 4, 1, 4, 5, 4]
text_init = [str(i) for i in range (0, len(x))]
labels = [0,0,0,0,0,1,1,1,1,1]

df = pd.DataFrame({'text': text_init, 'x_axis': x, 'y_axis': y, 'label': labels})

fig = plot_fig(df)

# LAYOUT
app.layout = html.Div(
  [
      html.H3('Slider'),

      dcc.Slider(
          id="slider",
          min=2,
          max=5,
          step=1,
          value=2,
          marks={
              2: "2",
              3: "3",
              4: "4",
              5: "5",
          },
          disabled=False,
      ),

      html.H3('Graph'),

      dcc.Graph(
        id="plot_graph",
        figure=fig,
        config={
            'modeBarButtonsToRemove': ['autoScale2d', 'zoomIn2d', 'zoomOut2d', 'resetScale2d', 'hoverClosestCartesian', 'hoverCompareCartesian', 'toggleSpikelines'],
            'displaylogo': False
              }
      ),

      html.H3('Span'),

      html.Span(
        id="selected_nodes",
        children=['Elements selectionnes']
      ),

      dt.DataTable(
          id='plot_graph_selected_data_table',
          sort_action="native",
          page_action="native",
          page_current= 0,
          page_size= 10,
          style_as_list_view=True
      ),

      dcc.Store(id='store_df', data=df.to_json()),
      dcc.Store(id='command_selection'),
  ]
)

# UTILS

def get_filtered_nodes(data_json, selectedTopics, selectedData):
  """
  return selected points
  """
  res = []

  if selectedData != None:#There is an active selection
      pointsList = json.loads(json.dumps(selectedData))
      if pointsList != None and len(pointsList['points']) > 0:#Some points are selected
          for point in pointsList['points']:
              text = point['customdata'][0]
              label = point['customdata'][1]
              if label not in selectedTopics.keys() or selectedTopics[label] == True:
                  res.append({'0': text, '1': label})

  elif data_json != None:#No active selection
      data = json.loads(data_json)
      textArray = data['text']
      labelsArray = data['label']
    
      for key in textArray.keys():
          if labelsArray[key] not in selectedTopics.keys() or selectedTopics[labelsArray[key]] == True:
            res.append({'0': textArray[key], '1': labelsArray[key]})

  return res


# CALLBACKS

# Change color of points based on slider value
@app.callback(
  [Output('plot_graph', 'figure'),
  Output('store_df', 'data'),
  Output('command_selection', 'data')
  ],
  Input('slider', 'value'), 
  State('plot_graph', 'restyleData')
)
def update_graph(n_labels, restyleData):
  #print('update_graph')

  labels = []
  step = math.ceil(10/n_labels)
  curr_label = 0
  while len(labels) <= 10:
    for i in range(0, step):
      labels.append(str(curr_label))
    curr_label += 1

  if len(labels) > 10:
    labels = labels[:10]

  df = pd.DataFrame({'text': text_init, 'x_axis': x, 'y_axis': y, 'label': labels})

  return plot_fig(df), df.to_json(), []

# Init data table
@app.callback(
    Output('plot_graph_selected_data_table', 'columns'),
    Input('store_df', 'data')
)
def generate_datatable_columns_list(data):
    return [{'name': 'Text', 'id': '0'}, {'name': 'Label', 'id': '1'}]

# Show number of selected points and populate data table
@app.callback(
  [
  Output('selected_nodes', 'children'),
  Output('plot_graph_selected_data_table', 'data'),
  ],
  [
  Input('plot_graph', 'restyleData'),
  Input('plot_graph', 'selectedData'),
  Input('command_selection', 'data'),
  Input('slider', 'value') 
  ], 
  State('store_df', 'data')
)
def update_selected_nodes(
                      restyleData, 
                      selectedData, 
                      command_selection,
                      n_labels, 
                      data_json
                      ):
  #print('update_selected_nodes')

  df = pd.read_json(data_json)
  changed_id = [p['prop_id'] for p in dash.callback_context.triggered][0]
  count = -1

  selectedTopics = {}
  if restyleData != None:
      states = restyleData[0]['visible']
      labels = restyleData[1]
      for index in range(len(restyleData[0]['visible'])):
          if states[index] == 'legendonly':#legend item has been deactivated
              selectedTopics[str(labels[index])] = False
          elif states[index] == True:#legend item has been activated
              selectedTopics[str(labels[index])] = True

  res = get_filtered_nodes(data_json, selectedTopics, selectedData)
  count = len(res)

  return str(count)+' selected items', res

# from functools import reduce
# @app.callback(
#   Output('selected_nodes', 'children'),
#   [
#   Input('plot_graph', 'restyleData'),
#   Input('plot_graph', 'selectedData'),
#   Input('plot_graph', 'figure'),
#   ]
# )
# def update_selected_nodes(restyleData, selectedData, figure):
#   changed_id = [p['prop_id'] for p in dash.callback_context.triggered][0]

#   if 'plot_graph.selectedData' in changed_id and selectedData != None:
#     count = len(selectedData['points'])
#   else:
    
#     count = reduce(lambda a, b: a+len(b['x']) if 'visible' not in b or b['visible']==True else a,figure['data'], 0)

#   return str(count)+' selected items'

if __name__ == '__main__':
    app.run_server(debug=True)

```

I've added a DataTable that's populated by the different selections. This table also shows some info about the selected points (a 'text' field in my dataFrame). The behaviour from this example more closely resembles what I'm actually dealing with.
Here are the steps to reproduced the bug:
- after loading the page, select 3 on the slider 
- double-click on legend item '2'
- a couple of points should be selected and shown below the graph
- without resetting the selection, select 2 on the slider
- even though the graph has changed and the selection has been reset, we can see that no points are shown in the DataTable
- expected behaviour: the DataTable should display all the points with the correct labels (0 and 1).

Again, this occurs because the `restyleData` attribute does not change when the graph changes.

Please let me know if you have any more insights on this situation!

**Comment by nickmelnikov82** [comment]
`Should the restyleData attribute not change when the graph changes?`
It appears that the `restyleData` event only fires when the user clicks on the legend, just like the `selectedData` event only fires when the user change the selection. In fact, when the graph changes, there is no more selection, just as there are no style changes. 

`Is it possible for this loading screen to be the result of a callback taking 'too long'?`
There are several loading screens. The first one occurs at the time of drawing the graph, and the second one takes place while the callback functions are being worked out.

I couldn't reproduce an infinite loop with neither 10000 nor a million points, although loading at a million points takes 35 seconds. Perhaps the reason is in the problematic data?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
