### ISSUE TITLE
[BUG] Long callbacks triggered multiple times with concurrency

### ISSUE THREAD

**Issue by vkolevrestec** [plotly/dash#2067]
**Describe your context**
```
dash                      2.0.0
dash-bootstrap-components 1.0.0
dash-core-components      2.0.0
dash-html-components      2.0.0
dash-table                5.0.0
```
**Describe the bug**

The long callback acts strange, the progress bar starts loading and then goes back and forth.
It is working locally on Ubuntu 18.

**Azure configuration:**
Azure App Service, Ubuntu 18

**Startup command:**
gunicorn --bind=0.0.0.0:$PORT -w 4 --timeout 60 wsgi:app & celery --app dashboard.celery_app worker --concurrency=8 -l info

**Code setup:**
long_callback_manager = CeleryLongCallbackManager(celery_dash_app, cache_by=[lambda: uuid4, ])
 dashapp = dash.Dash(
        ...,
        long_callback_manager=long_callback_manager
    )

**Expected behavior**

The snippet should work like this one [](https://dash.plotly.com/long-callbacks), Example 4: Progress Bar.

**Screenshots**
![long_callback](https://user-images.githubusercontent.com/103256174/170692458-ee162da2-8d4a-4b5c-844b-32af744decbd.gif)

**Comment by ayhteo** [comment]
I think this might also have been described in https://github.com/plotly/dash/issues/1769#issuecomment-946065283, I have a similar problem when using `for` loops in a `long_callback`.

**Comment by vkolevrestec** [comment]
Thank you for referencing the main thread. 
I tried to do a workaround by increasing the interval and It's still buggy.
![long_callback5](https://user-images.githubusercontent.com/103256174/171120021-567b040b-ca27-4105-866a-2fe92bbd69db.gif)

If I increase the interval to more than the job requires I get the result directly, but then I have to wait that extra time.

I'll try [this workaround](https://github.com/plotly/dash/issues/1769#issuecomment-1129982336) by sebbegg as well, until we get a proper solution by Dash.

**Comment by vkolevrestec** [comment]
Will be fixed in https://github.com/plotly/dash/pull/2039
