### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by ghost** [plotly/dash#2073]
go.Scattermapbox hover not responding when the list is long:

import plotly.graph_objects as go
AccessToken = My token
Lat = [58.08407, 58.07343, 58.03642, 58.07061, 58.03967, 58.05232, 58.09451, 58.06791, 58.0945, 58.06794, 58.59317,
       58.47269, 58.46814, 58.4994, 58.52724, 58.47948, 58.60443, 58.5771, 5856382.0, 58.55224, 58.54215, 58.51004,
       58.62932, 58.48171, 58.51903, 59.00007, 59.00235, 59.01721, 59.0215, 59.03595, 58.96764, 59.00157, 58.97495,
       58.97185, 58.97986, 58.98707, 58.99295, 59.00902, 58.61472, 59.01365, 60.91746, 60.91174, 60.85479, 60.85397,
       60.88379, 60.88737, 60.84751, 60.8419, 60.89555, 60.91368, 60.90144, 60.87921, 60.91457, 60.87132, 60.9155]

Long = [7.60501, 7.57984, 7.49395, 7.55316, 7.49834, 7.51422, 7.62384, 7.53446, 7.62378, 7.53442, 8.89745, 8.74466,
        8.73832, 8.79468, 8.84721, 8.75339, 8.89998, 8.90563, 8.89368, 8.87032, 8.8573, 8.82022, 8.89756, 8.75517,
        8.83875, 9.59379, 9.61643, 9.65601, 9.6714, 9.67685, 9.48388, 9.60494, 9.52533, 9.51339, 9.53643, 9.56081,
        9.57702, 9.62682, 8.90255, 9.64303, 10.70296, 10.81227, 10.9926, 11.00001, 10.91312, 10.89263, 11.02713,
        11.04692, 10.84395, 10.7619, 10.83315, 10.92894, 10.71544, 10.94735, 10.78851]

Text = ["Tennskap 743.030", "Tennskap 743.040", "Tennskap 743.204", "Tennskap 743.050", "Sandnesheiatunnel",
        "Tennskap 743.203", "Tennskap 743.020", "743.202", "743.201", "Tennskap 743.060", "Skrubbedalen",
        "Langsæveien", "Ravnåsveien", "Skap", "Trælfjell", "Torsbuås0", "Vennevannsliene", "Bråten bru", "Årdalen",
        "Rosstjern", "Skarkedalen", "Mørland", "Fløyheia", "Torsbuås1", "Hesthaugtunnel", "Europaveien0",
        "Europaveien1", "Europaveien2", "Europaveien3", "Rugtvedtveien", "Gongeveien", "Europaveien4", "Europaveien5",
        "Europaveien6", "Europaveien7", "Europaveien8", "Europaveien9", "Europaveien10", "Grendstøl", "Europaveien11",
        "Kastbakkvegen", "Rudsvegen", "Gamle Kongsveg", "Melgård", "Pellervika", "Harpviken", "Langbakken",
        "Nydalskrysset", "Åshøgdvegen", "Ulvegutua", "Gatelys", "Nils Amblis veg", "Røsslyngvegen", "Strandvegen",
        "Rudsflata"]

fig = go.Figure(go.Scattermapbox(lat= Lat, lon= Long, mode='markers', text= Text,
                                 marker=go.scattermapbox.Marker(size=9)))

fig.update_layout(autosize=True, hovermode='closest',mapbox=dict(accesstoken=AccessToken,
                                                                 bearing=0,center=dict(lat=59,lon=9),
                                                                 pitch=0,zoom=8 ))
fig.show()

Map is ok, But hover is not showing anything

Any Idea????

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
