### ISSUE TITLE
Error running WSGI application TypeError: 'Dash' object is not callable

### ISSUE THREAD

**Issue by weblanss** [plotly/dash#210]
I am trying to lunch dask on .pythonanywhere via flask web app : 
this is my code:
```
import dash
import dash_core_components as dcc
import dash_html_components as html

app = dash.Dash()

server = app.server
app.layout = html.Div(children=[
    html.H1(children='Hello Dash'),

    html.Div(children='''
        Dash: A web application framework for Python.
    '''),

    dcc.Graph(
        id='example-graph',
        figure={
            'data': [
                {'x': [1, 2, 3], 'y': [4, 1, 2], 'type': 'bar', 'name': 'SF'},
                {'x': [1, 2, 3], 'y': [2, 4, 5], 'type': 'bar', 'name': u'Montréal'},
            ],
            'layout': {
                'title': 'Dash Data Visualization'
            }
        }
    )
])

if __name__ == '__main__':

    server.run_server(debug=DEBUG)
```
 i am getting the following error : 
```
[Error running WSGI application
2018-02-17 20:10:52,118: TypeError: 'Dash' object is not callable](url)

```
how to fix it ?

**Comment by chriddyp** [comment]
See https://community.plot.ly/t/dash-pythonanywhere-deployment-issue/5062/2

**Comment by weblanss** [comment]
i fix code ,now i gotthefollowing error : 
Error running WSGI application
```
2018-02-18 10:32:28,664: ImportError: cannot import name 'app'
2018-02-18 10:32:28,664:   File "/var/www/lav_pythonanywhere_com_wsgi.py", line 16, in <module>
2018-02-18 10:32:28,665:     from wsgi import app as application
```

**Comment by chaowu2009** [comment]
received the same error.

 *** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55fbe1286560 pid: 27345 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 27345, cores: 1)
TypeError: 'Dash' object is not callable
[pid: 27345|app: 0|req: 1/1] 71.179.60.89 () {34 vars in 662 bytes} [Sat Mar 14 19:54:57 2020] GET / => generated 0 bytes in 0 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
