### ISSUE TITLE
[Long Callback] Support pattern matching for long callbacks side updates (progress/cancel/running)

### ISSUE THREAD

**Issue by T4rk1n** [plotly/dash#2111]
Long callbacks `progress`, `running` and `cancel` dependencies should support pattern matching ids.

**Comment by milind** [comment]
Was this issue ever resolved? I think that I'm running into it in my current application in trying to assign a pattern-matching component to the cancel parameter.

**Comment by Ciaran-YouSeq** [comment]
thank you @T4rk1n - can I ask if there are plans to add pattern matching for progress, running and cancel in the near future?

**Comment by T4rk1n** [comment]
@Ciaran-YouSeq It's in the backlog... If anyone want to work on this it would be a good introduction to renderer development, I can give some pointers below.

The side update are performed in this function:
https://github.com/plotly/dash/blob/093b5596f4836fb999365849b421892d8835c199/dash/dash-renderer/src/actions/callbacks.ts#L322-L336

We have a function to get path from id: https://github.com/plotly/dash/blob/093b5596f4836fb999365849b421892d8835c199/dash/dash-renderer/src/actions/paths.js#L70

The side update will need to be integrated with the `getPath` function, the returned path in that case may be a array of path or a path itself, then modify the dispatch to be on a loop depending on that result.
