### ISSUE TITLE
[BUG] No module named dash_core_components, dash_html_components as per latest plotly documentation ;  I really believe that this is an API change that wasn't documented

### ISSUE THREAD

**Issue by NishantJadhav369** [plotly/dash#2122]
When trying to run "Display Simple HoloViews Elements with Dash", need to download missing dependencies for Plotly Dash. After installation, still gives deprecation warning.  

Link to dash holoviews: https://dash.plotly.com/holoviews.

**Reproducable code:**
`import dash
from dash import html
from plotly.data import iris

import holoviews as hv
from holoviews.plotting.plotly.dash import to_dash  # No module named dash_core_components, dash_html_components

df = iris()
dataset = hv.Dataset(df)

scatter = hv.Scatter(dataset, kdims=["sepal_length"], vdims=["sepal_width"])
hist = hv.operation.histogram(
    dataset, dimension="petal_width", normed=False
)

app = dash.Dash(__name__)
components = to_dash(app, [scatter, hist])

app.layout = html.Div(components.children)

if __name__ == "__main__":
    app.run_server(debug=True)`

**Comment by T4rk1n** [comment]
Holoviews import the old style first for backward compat: https://github.com/holoviz/holoviews/blob/114aff1cf3210dafbfc044262b45be5d74691ecf/holoviews/plotting/plotly/dash.py#L23-L27

**Comment by alexcjohnson** [comment]
@T4rk1n that's funny though, the preferred way to do these imports is the opposite of that - ie first try `from dash import dcc, html` and if that fails fall back on the old packages. Would you mind following up with Holoviews and seeing if they would switch the order? As is it will emit warnings unnecessarily for the standard Dash v2.x installation.

**Comment by T4rk1n** [comment]
@alexcjohnson Right it should be the revers, opened issue on their repo: https://github.com/holoviz/holoviews/issues/5661
