### ISSUE TITLE
ability to export plotly dashboard into dash app

### ISSUE THREAD

**Issue by omkarok** [plotly/dash#215]
I have created a online sample dashboard using Plotly which is live at : "https://plot.ly/dashboard/rishabhshetty:11/"

I want a mechanism to export the entire dashboard and convert / Serve it as a dash application page.

What I've Tried:
1. embedding plots via divs and iframes.
the formatting isnt as good as actual live dashboard.
divs and embed tags work well in a html file but dont get executed or open up in a brand new page using dash.

An interface to convert the layout of the online dashboard and make it dash app pluggable is required

**Comment by chriddyp** [comment]
This is an interesting idea, but something that we probably won't do. Instead, we'll likely focus on the component libraries and templates that you could use to create nice looking dashboards directly from dash.
