### ISSUE TITLE
[Question]: Where is the Dash dashboard data stored

### ISSUE THREAD

**Issue by mChowdhury-91** [plotly/dash#2163]
Hi Team,

I recently started using ExplainerDashboard, and I found that internally it calls the **Dash** source code which spins up the the Flask web server and the dashboard shows up.
I also see some api calls to "/_dash-update-component" and "/_dash-component-suites"

Is the data stored somewhere is Dash?

**Comment by T4rk1n** [comment]
Dash is stateless and all Dash data (layout, callbacks definition, etc) is only kept in memory.

**Comment by T4rk1n** [comment]
For questions, it's preferred to ask them on the forums for more visibility by the community: https://community.plotly.com/

**Comment by T4rk1n** [comment]
There is no intermittent files created by dash unless using `background`/`long` callbacks with diskcache but that requires additional setup.

- `/_dash-update-component` is the callback route for updating props on the frontend.
- `/_dash-component-suites` serve the js bundles.

You can see all the dash routes and what they do in this document: https://github.com/plotly/dash/blob/dev/MAKE_A_NEW_BACK_END.md#dash-server-routes

**Comment by mChowdhury-91** [comment]
@T4rk1n Thank you for the info.
