### ISSUE TITLE
[BUG] 2.6.0 background callbacks cache_args_to_ignore missing

### ISSUE THREAD

**Issue by gaboc623** [plotly/dash#2169]
**Describe your context**
This is a multi-page app using BasicAuth and Flask Caching

```
dash                       2.6.0
dash-auth                  1.4.1
dash-bootstrap-components  1.2.0
dash-core-components       2.0.0
dash-html-components       2.0.0
dash-table                 5.0.0
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: MacOS Monterey
    - Browser: Chrome
    - Version: 103.0.5060.114 

**Describe the bug**

When using the new `background=True` flag to make a callback a background callback, I get the following error regardless of what the value for the `cache_args_to_ignore` argument is - 

![image](https://user-images.githubusercontent.com/98338242/181094378-abd4c420-a4a4-4518-86d1-1aa836bb0fe8.png)

**Expected behavior**

I expect the long callback to work with the CeleryManager as show in my callback below:

```
@callback(
    output={
        "data": Output(results_table.table, "data"),
        "info_div_style": Output(override_info_div, "style"),
    },
    inputs={'data': Input(upload_store, "data")},
    running=[
        (
                Output("progress_bar", "style"),
                {"visibility": "visible"},
                {"visibility": "hidden"},
        ),
    ],
    prevent_initial_call=True,
    background=True,
    manager=CeleryManager,
    cache_args_to_ignore=['data']
)
def validate_upload_rows(data: str):
    if not data:
        return dict(data={}, info_div_style={})
    upload_df = load_df_from_store(data)
    return_dfs = []
    for index, row in upload_df.iterrows():
        row = row.dropna()
        return_dfs.append(search_api_for_npi(row.to_dict()))
    final_df = pd.concat(return_dfs)
    return dict(
        data=final_df.to_dict(orient="records"), info_div_style={"display": "none"}
    )
```

**Comment by T4rk1n** [comment]
@gaboc623  you are passing the class `CeleryManager` to the manager parameter in the callback. The manager is not instantiated so when the callback is calling a method on the manager it is missing the self parameter because it is the class.

You can fix the issue by instantiating the `CeleryManager` before the callback definition and give that to the specific callback or the dash constructor to set it as default manager for all callbacks.

```python
import os

from dash import Dash, html, callback, dcc, Output, Input,CeleryManager
from celery import Celery


celery_app = Celery(
    __name__, broker="redis://localhost:6379/0", backend="redis://localhost:6379/1"
)
manager = CeleryManager(celery_app)
app = Dash(__name__, background_callback_manager=manager)
```

For this setup to work, you will also need a redis instance and celery workers.

**Comment by gaboc623** [comment]
@T4rk1n thanks for the reply! passing  the `manager` object to the callback instead oaf the CeleryManger one did the trick
