### ISSUE TITLE
[BUG] Multi Page App - First Load Fails

### ISSUE THREAD

**Issue by sjtrny** [plotly/dash#2171]
**Describe your context**

```
dash==2.6.0
```

**Describe the bug**

First request made to a multi-page app fails. Refreshing the page resolves the issue.

**Expected behaviour**

First request should work.

**Demo**

https://user-images.githubusercontent.com/3364754/181869444-2c9bdacf-0461-409d-8ece-5577a1c5356b.mp4

**Code**

```
import dash
from dash import Dash, html

app = Dash(__name__, use_pages=True, pages_folder='')

app.layout = dash.page_container

layout = html.Div(children=[
    html.H1(children='Hello Dash'),
])

dash.register_page("index", layout=layout, path="/", title="Index")

if __name__ == "__main__":
    app.run(host='0.0.0.0', debug=True)
```

**Comment by ned2** [comment]
I believe this is a known bug that was introduced by #2126 There's an open PR to revert the change that introduced the regression: #2168

**Comment by sjtrny** [comment]
Thanks @ned2!
