### ISSUE TITLE
Using app.config['suppress_callback_exceptions']=True results in Error Loading Dependencies

### ISSUE THREAD

**Issue by Seedarchangel** [plotly/dash#218]
I have an App with dynamic layout which will be controlled by a callback. 
By default, I have two input elements:
`html.Div([
    dcc.Input(
      style={'width': '12%'},
      id='vertex1',
      placeholder='Vertex',
      type='text',
      value='',),
    dcc.Input(
      style={'width': '12%'},
      id='vertex2',
      placeholder='Vertex',
      type='text',
      value='',)])`

In a callback, I will add more dcc.input with id = vertex(number from 3 to 8) by returning a HTML Div as a child. It's all good till this point, but if I try to initiate a third callback with the inputs say:
`@app.callback(
    Output(component_id='my-graph', component_property='figure'),
    [
     Input('vertex1', 'value'),
     Input('vertex2', 'value'),
     Input('vertex3', 'value'),
   ]
`
where vertex3 is yet to be generated and vertex1 and vertex2 exists, the page will fail to load with Error Loading Dependencies even though I have suppressed callback exceptions. Is this expected behavior in Dash?

**Comment by ned2** [comment]
Would you be able to post your question along with a code snippet containing a minimal example that shows the problem on the Dash community forum. That's a better place for getting help with these kinds of questions.

https://community.plot.ly/c/dash

**Comment by Seedarchangel** [comment]
@ned2 
Oh, sorry, I posted here because I thought this is more of a bug report than implementation question.

**Comment by ohMyRedEyes** [comment]
So, did you find a solution?

I have the same problem. My custom dash component creates a texbox with dynamically assigned id. In code this happens before the callbacks are attached, but I still have that 'Error Loading Dependencies'

**Comment by alexcjohnson** [comment]
As @ned2 says, this kind of question is a better fit for the community forum. Offhand what you're doing sounds incompatible with the way Dash handles things - only the id of the Dash component can be referenced in callbacks, not any random id on the page. If you find yourself needing to attach a callback to a piece of your custom component, make that piece into a prop of the full component. Happy to discuss more if you post this question in the community forum.
