### ISSUE TITLE
[BUG] Order of Inputs, Outputs and States in long_callbacks causing problems

### ISSUE THREAD

**Issue by nbolohan** [plotly/dash#2190]
An issue I had was [described as a potential bug on community.plotly](https://community.plotly.com/t/issues-switching-from-callback-to-long-callback/66882/4) and it was recommended I share here.

The following code runs properly:

```
import webbrowser
import diskcache

from threading import Timer
from dash import Dash, dcc, html, Input, Output, State
from dash.long_callback import DiskcacheLongCallbackManager

cache=diskcache.Cache("./cache")
long_callback_manager=DiskcacheLongCallbackManager(cache)

list_of_tables=[['Generic Table',['Table Columns']]]

app = Dash(__name__)

app.layout = html.Div([
    dcc.Checklist([table[0] for table in list_of_tables],id='table checklist'),
    html.H3(children='Run simulation: '),
    html.Button(id='run simulation button',n_clicks=0,children='Run'),
    html.Div(id='my-output'),
])

@app.callback(
    Output('my-output', 'children'),
    State('table checklist','value'),
    Input('run simulation button', 'n_clicks'),
    prevent_initial_call=True
    )
def test(tables_to_compute,n_clicks):

    if 'Generic Table' in tables_to_compute:
        string='Generic table is checked'
    else:
        string='Generic table is not checked'

    return string

if __name__ == '__main__':
    Timer(1, webbrowser.open('http://127.0.0.1:8054/')).start();
    app.run_server(debug=True,use_reloader=False,port=8054)
```
but when I change the callback decorator to
```
@app.long_callback(
    Output('my-output', 'children'),
    State('table checklist','value'),
    Input('run simulation button', 'n_clicks'),
    manager=long_callback_manager,
    prevent_initial_call=True
    )
```
an error occurs, telling me "TypeError: argument of type ‘int’ is not iterable". Here is the reply from community.plotly:

"Thanks for the reproducible example!

My suspicion before running was that it was mixing the order between Input and State and assigning the click count to tables_to_compute (therefore your error). I can confirm that this is exactly what happened and the error disappears if you switch the order in the decorator and in the function signature.

I think you can consider this a bug, although it is a good practice to have the Input before State in callbacks… I would recommend you to open an issue on GH to report it just in case."

**Comment by alexcjohnson** [comment]
Thanks @nbolohan! Feel free to include a link to the community post so the whole discussion stays together.

Is this still a problem with the updates in v2.6? (`@app.callback(background=True)` is the new syntax, `@app.long_callback` is deprecated, and the architecture behind it has changed substantially)

**Comment by nbolohan** [comment]
Would the appropriate changes be as follows? If so, the same error is produced if Input is below State.
```
@app.callback(
    Output('my-output', 'children'),
    State('table checklist','value'),
    Input('run simulation button', 'n_clicks'),
    manager=long_callback_manager,
    prevent_initial_call=True,
    background=True
    )
```

**Comment by alexcjohnson** [comment]
Yep that's it - thanks, so this bug survived the refactor, good to know!

**Comment by T4rk1n** [comment]
The background callback call with the wrong arguments.

https://github.com/plotly/dash/blob/b569dfe969edccfed621c93b5ec9d21c3ba09698/dash/_callback.py#L362-L378

`args` here should the same as the key:

`func_args if func_args else func_kwargs`

**Comment by alexcjohnson** [comment]
@T4rk1n but shouldn't background and foreground callbacks support exactly the same args? Putting `State` before `Input` works fine for regular callbacks but fails for background.

**Comment by T4rk1n** [comment]
> but shouldn't background and foreground callbacks support exactly the same args?

Yes but it's giving the raw `args` instead of the `func_args` which are ordered.
