### ISSUE TITLE
[BUG] Import from a page without application (For testing purpose)

### ISSUE THREAD

**Issue by T4rk1n** [plotly/dash#2193]
When `register_page` is called during import, if there is no app defined before it will throw a bare `Exception` with a message indicating there was no app  before the import. https://github.com/plotly/dash/blob/20b6467bf61024aba75fcdac60ee9952363355c4/dash/_validate.py#L465

This makes it hard to ignore that particular exception in the case of unit testing callbacks defined within a page file as [reported on the forums](https://community.plotly.com/t/dash-2-6-released-background-callbacks-unit-testing-persistent-selections-dropdown-features/66322/3) and should be changed to a custom exception.

**Comment by wcheek** [comment]
I'm having this exact same issue while trying to test callbacks within a page file. The fix you give on the forum,
```python
try:
    from pages.my_page import my_callback
except:
    pass
```
 doesn't work for me. Since the import raises the above `Exception` it means that `my_callback` never gets imported and I can't test it.

Is there currently no way to test a callback inside a page file?

**Comment by T4rk1n** [comment]
Hmm, yea the import fail so it's not available, best you can do rn is put the callback in another file separates from the pages.

**Comment by wcheek** [comment]
What would be the way to go about doing that? I currently have all of my callbacks being created with `@dash.callback` together with my page layout. Where should I move these callbacks and what do I do to ensure they get connected with the app/page?

**Comment by T4rk1n** [comment]
You can put the callbacks anywhere, just make sure the files are imported in the main app file.

@alexcjohnson Maybe we can check an environ variable like `DASH_TESTING` and not throw the error if there is no app?

**Comment by alexcjohnson** [comment]
What about [mocking](https://pytest-mock.readthedocs.io/en/latest/) `dash.register_page` and importing the page inside the test?
```py
def test_my_page_callbacks(mocker):
    mocker.patch("dash.register_page")
    from pages.my_page import my_callback
    assert my_callback(1, 2) == 3
```

What bothers me about an env var solution is you can't just run the test file, you need to know *how* to run it, and if this was used globally (ie including integration tests) we could easily swallow real errors.

What if we made a context manager to wrap around the imports? Then you could keep the imports up top where they belong, but dash would know not to even attempt `register_page`?

```py
from dash.testing import unit_import
with unit_import:
    from pages.my_page import my_callback
```
