### ISSUE TITLE
complex Layout Manager

### ISSUE THREAD

**Issue by davidpasquale** [plotly/dash#2201]
Thanks so much for developing Dash! It's awesome!

I would like to ask if anyone can work on the very interesting porting of Lumino to Dash.
[Dash-Lumino](https://github.com/VK/dash-lumino-components)
Unfortunately, the package doesn't seem mature yet (theming, saving/loading layout), but it looks very promising.

There are also interesting alternatives, such as 
[Golden-Layout](https://github.com/golden-layout/golden-layout)

The introduction of these packages into Dash would allow to make very complex dashboards.

THANK YOU in advance for your work, simply outstanding!

**Comment by alexcjohnson** [comment]
@davidpasquale this is a great topic that a lot of people will be interested in - but it’s a little broad for a GitHub issue, maybe better to discuss on https://community.plotly.com/ ?
