### ISSUE TITLE
Error when trying to use Dash in a flask server

### ISSUE THREAD

**Issue by jejesh26** [plotly/dash#221]
Dears,
Greetings from China !
first of all thks for this wonderful tool. Really very powerful
However, I'm trying to add my Dash APP into an existing website done in Flask.
When trying to run the dashapp1, I got the message "File "C:\ProgramData\Anaconda3\lib\site-packages\dash\resources.py", line 86, in get_inferred_resources
    for t in layout.traverse(): AttributeError: 'NoneType' object has no attribute 'traverse'"

I've seen many people getting this message for different reasons, but I can not find where I'm wrong.
Seems the systems is waiting for a layout, but there is one in dashapp1.py which is running well when this module is running on a standalone mode.
Thks for your help !

File structure:
- app.py
- index.py
- lib
| -- __init__.py
     - MyDashApps
        |-- __init__.py
        |-- dashapp1.py
- static
- templates

**## index.py** (which is the main file)

> from app import AppServer,DashServer
> from flask import render_template
> def home():
>     return render_template('pages/home.html')

**## app.py**

> from flask import Flask
> import dash
> AppServer = Flask(__name__)
> DashServer = dash.Dash(__name__, server=AppServer, static_folder='static')
> DashServer.scripts.config.serve_locally=True
> DashServer.css.config.serve_locally=True

**## dashapp1.py**

> from app import DashServer
> import dash_html_components as html
> DashServer.layout = html.Div([
>         html.Div('Carrefour sales Viewer') 
> 		])

**Comment by jejesh26** [comment]
Well, I found a way to bypass the issue, but I'm not quite satisfied with the solution:

Have added the following lines in **index.py**

> @AppServer.route('/analysis')
> def DashAnalysis():
> 	return redirect('/lib/MyDashApps')
>
> DashServer.layout = html.Div([ dcc.Location(id='url', refresh=False),html.Div(id='page-content') ])
> @DashServer.callback(Output('page-content', 'children'), [Input('url', 'pathname')])
> def display_page(pathname):
>     if pathname == '/lib/MyDashApps':
>          return dashapp1.layout

then added the url_base_pathname in **app.py**

> DashServer = dash.Dash(__name__, server=AppServer, static_folder='static', url_base_pathname='/lib/MyDashApps')

However, it means that all the links to the dash apps (there will be a lot of layouts) should be in the main flask index.
I tried to move the lines 

> DashServer.layout = html.Div([dcc.Location(id='url', refresh=False),html.Div(id='page-content')])
> @DashServer.callback(Output('page-content', 'children'),[Input('url', 'pathname')])
> def display_page(pathname):
>     if pathname == '/lib/MyDashApps':
>          return dashapp1.layout

into an **index.py** file in the dash apps subfolder, but then, error comes back again.
Seems that a minimum layout is necessary as long as the DASH app is instanciated

**Comment by ned2** [comment]
Your diagnosis sounds right, that the app is being run without the layout being attached to the Dash instance. This can get a little tricky for more complex apps that are spread across multiple points, notably because of the import chains. You need to structure your app such that the entry point you use to run the app exposes the Flask instance (in your case `AppServer`) and it also needs to have assigned the layout to the Dash instance (`DashServer` in your case). I'm wondering if you're using `app.py` as your entry point to run the app, as doing this would mean that the `dashapp1.py` is never imported and so no layout it set. 

I would suggest creating a file that is explicitly used as the entry point to your app. Following the convention for providing an entry point for WSGI apps, one way to do this is to create a `wsgi.py` file that imports everything the app requires to run and exposes the WSGI callable as a variable named `application`. In your case that would simply be:

`from dashapp1 import AppServer as application`

Then you can target that with a WSGI server such as gunicorn, like so:

`$ gunicorn wsgi`

Or if you want to just invoke Dash's `run_server` method, you could import also import the Dash instance into this file and run the whole file. I'd definitely recommend using gunicorn or another wsgi server though.

**Comment by jejesh26** [comment]
dear,
thks for your reply, but before reading it, I came up with a solution that is suitable to me, in terms of results but also of  project structure.

I have created at the root of the project 4 files 
- **server.py** where I just create an instance of flask which will be the main application, embedding the website and dash apps. in this file, I have as well defining the root route of this main application (which is in my case the home.html of the webiste)
- **website.py** where a flask instance is also created and all the routes of the website. In this file, I got also a "redirect" to the homepage of the dash apps, which is actually the url_base_pathname of the dash instance
- **maindash.py**: to create the instance of the dash server. Of course in the init of this instance, defining server= server of the main application(created in server.py), and the url_base_pathname. In this file I can create all the routes to the dash apps, using dcc.location and dcc.link and the callbacks method explained in the dash doc. 
Have also written a simple html.A to go back to the homepage of the website. I tried to use same callbacks method as for the dash urls to do the redirection, but seems that redirect is not working in dash callbacks.
In this file also, I define the first layout to render in the callback when the url is the equal to url_base_pathname. So for example simply return the layout of the dash app dashapp1.py

- **run.py** : the starting point of the application, linking the website server instance (created in website.py) and the main application server  (created in server,py), using DispatcherMiddleware of werkzeug.wsgi

 Seems quite complex and not straightforward but at least, can define the routes of the website and the dash apps totally independently, which is the goal. In project management, teams can work separately on the dash apps and on the website design, without all instances.

Will post later the code related to these files once I have access to my dev machine. Then close the issue 😃 

I want anyway to underline that this would be much more easier if we could use the Dash core components as an object that could be passed to and rendered by some JinJa2 templates (something like {{ dashgrah1 }}, {{ dashslider }}, ..,.. 
In terms of website design consistency, that would be the most efficient

I read that many people got the same request 😄 
 
rgds

**Comment by ned2** [comment]
Glad to hear to found a solution that works for you :)

I don't really see mixing Dash components with Jinja templates as being a likely direction that Dash will take. They're fundamentally different ways of building interfaces. Jinja templates are rendered server-side into HTML, whereas Dash apps are all rendered client-side using React. It's not clear how you even could combine them in a fruitful way. Perhaps just having more documentation around how to integrate Flask apps with templates and Dash apps along the lines of what you've done would be a good solution.

> Will post later the code related to these files once I have access to my dev machine. 

An even better place to post this would be the Dash community forum, where it's more likely to be seen and potentially result in community discussion.

**Comment by chriddyp** [comment]
Thanks @ned2 !
> An even better place to post this would be the Dash community forum, where it's more likely to be seen and potentially result in community discussion.

Indeed - more folks are going to see this solution in the forum. Closing this issue but feel free to add more information or share what you learned in the forum.

**Comment by mathfish** [comment]
@jejesh26 
Just curious if you ever ended up posting your code for this. I am facing a similar issue and it would be super useful. 

Thanks

**Comment by jejesh26** [comment]
Hi,

here it is :

**run.py** -  starting point of the main app
```
from werkzeug.wsgi import DispatcherMiddleware
from werkzeug.serving import run_simple
from server import AppServer
from webroutes import webServer
import sys,os

sys.path.append(os.path.dirname(os.path.abspath(__file__)))

myApp = DispatcherMiddleware(AppServer,{'/home': webServer})

if __name__ == '__main__':
   run_simple('127.0.0.1', 3000, myApp, use_reloader=True, use_debugger=True)
```
**server.py** - creation of the main Flask server instance
```
from flask import Flask, render_template

AppServer = Flask(__name__)

@AppServer.route('/')
@AppServer.route('/home')
def home():
    return render_template('pages/home.html')
```
**webroutes.py** - routes of the website 
```
from flask import Flask
from lib.postsDB import BlogPosts
from datetime import datetime
from flask import render_template, redirect

webServer = Flask(__name__)

@webServer.route('/contact')
def contact():
    return render_template('pages/contact.html')

```
**Dashserver.py**  - instantition of server dash
```
import dash
import os,sys
from server import AppServer
DashServer = dash.Dash(
	name='analysis', 
	sharing=True,
    server = AppServer,
	static_folder='static', 
	url_base_pathname='/analysis/')

DashServer.scripts.config.serve_locally=True
DashServer.css.config.serve_locally=True
DashServer.server.secret_key = os.environ.get('secret_key','secret')
DashServer.config['suppress_callback_exceptions']=True
```

**dashroute.py** - Dash app
```
from dashserver import DashServer

DashServer.layout = html.Div([
	dcc.Location(id='url', refresh=False),
	html.Div(id='page-content')
	])

@DashServer.callback(Output('page-content', 'children'),[Input('url', 'pathname')])
def display_page(pathname):
	if pathname == '/analysis/':

```
Hope this helps
please note that you will have access to your Dash App.
However, you will face some issues with callbacks, as the callbacks should be created before the server start. Check my post in Dash Plotly forum.

**Comment by cixingzhici** [comment]
Wonderful!
But how do I use dash in route?
In my case:
'''
@main.route('/dash1', methods=['GET', 'POST'])
def dash1():
    dash_app = dash.Dash(__name__, server=current_app)
    dash_app.layout = html.Div('dash1'）
    return dash_app.index()
'''
Error:
AssertionError: A setup function was called after the first request was handled. This usually indicates a bug in the application where a module was not imported and decorators or other functionality was called too late. To fix this make sure to import all your view modules, database models and everything related at a central place before the application starts serving requests.

**Comment by ned2** [comment]
@cixingzhici, you can't mix Dash and Flask routes in this way. Instead you need to tell Dash when you;re initialising it what URL base it will be served from:

```
server = Flask(__name__) 
app = Dash(server=server, url_base_pathname='/dash1/')
```

Now you can add all the routes that the pure Flask parts of your app needs, while still being able to navigate to the URL `HOSTNAME/dash1` to load the Dash app.

**Comment by gaberm** [comment]
@ned2 I'm interested in your past comment about mixing Dash & Flask routes.
I want to use a Flask flask_login for security which i can't do if dash will handle and return its own routes.

I came up with a workaround where a flask route is returning a full flask but this is far from clean or modular.

```
@main_bp.route('/dash', methods=['GET'])
@login_required
def dashboard():
    return dash1.dashApp.index()
```
any ideas ?

**Comment by ned2** [comment]
@gaberm, you do what you want, but you have to manually patch all of Dash's auto-generated routes with login protected versions. I've seen people post code for doing thiss with flask_login in a few places. Try looking through past (closed) issues here, and also on the community forums
