### ISSUE TITLE
Dropdown maxHeight being overridden by something in DataTable [BUG]

### ISSUE THREAD

**Issue by lukeallpress** [plotly/dash#2225]
Thank you so much for helping improve the quality of Dash!

We do our best to catch bugs during the release process, but we rely on your help to find the ones that slip through.

**Describe your context**
Please provide us your environment, so we can easily reproduce the issue.

-  replace the result of `pip list | grep dash` below
```
dash                      2.6.1              pyhd8ed1ab_0    conda-forge
dash-bootstrap-components 1.0.3              pyhd8ed1ab_0    conda-forge
dash-daq                  0.5.0              pyh9f0ad1d_1    conda-forge
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: macOS 12.4
    - Browser: Chrome 105

**Describe the bug**

I can change the maxHeight of the dcc.Dropdown component, but as soon as a DataTable loads (even with no styling) the background of the dropdown shrinks back to 200px and any text below that is left, with a transparent background. If I return a boring Div instead of a DataTable, the dropdown stays styled correctly. Seems to be css-related, because the "incorrect styling" sticks around until I close/reopen the tab, then it's good again until a DataTable loads.

**Screenshots**

If applicable, add screenshots or screen recording to help explain your problem.
![dropdown](https://user-images.githubusercontent.com/22620095/189718305-ca2f7205-02c4-4159-aeec-057bcde4b596.gif)
Dropdown creation:
`dropdown = dcc.Dropdown(options=options,
                            placeholder='Sport',
                            id="sport-dropdown",
                            searchable=False,
                            maxHeight=400,
    )`
DataTable creation
```
df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/solar.csv')
return dash_table.DataTable(df.to_dict('records'), [{"name": i, "id": i} for i in df.columns])
```

**Comment by pfbuxton** [comment]
I don't think that this is not unique to DataTable.

If you have a look at the Dash example: [https://dash.plotly.com/dash-core-components/dropdown](https://dash.plotly.com/dash-core-components/dropdown) you can see that "Rome" has a transparent background.

![Capture](https://github.com/plotly/dash/assets/4923588/7a887da3-7b14-4b3e-bea5-a580f106046e)

**Comment by nickmelnikov82** [comment]
This error is caused by a special CSS class used for documentation.
A fix is currently under development and will be available soon

**Comment by aGitForEveryone** [comment]
This issue is also discussed here: https://github.com/plotly/dash/issues/2529
