### ISSUE TITLE
[BUG] console log gets spammed

### ISSUE THREAD

**Issue by luggie** [plotly/dash#2229]
the js console gets flooded with logs from callbacks.ts: 460:
`console.log(cb.callback.output, getState().callbackJobs);`
is this intended? 

```
dash                 2.6.0
dash-core-components 2.0.0
dash-html-components 2.0.0
dash-table           5.0.0
plotly               5.10.0
```

**Comment by T4rk1n** [comment]
Already fixed in 2.6.1
