### ISSUE TITLE
Flask contexts not available inside background callback

### ISSUE THREAD

**Issue by ArtsiomAntropau** [plotly/dash#2235]
**Describe your context**

```
dash                              2.6.1
dash-core-components              2.0.0
dash-html-components              2.0.0
dash-table                        5.0.0

```

**Describe the bug**

> Background callbacks don't have flask's app and request contexts inside. 

**Expected behavior**

> Background callbacks have flask's app and request contexts inside. 

So, after creating callback function and before providing them to the Celery, we should provide flask contexts inside this function to imitate the default callback behaviour

```python3
with flask_app.app_context():
    return (copy_current_request_context(job_fn) if has_request_context() else job_fn)(*args, **kwargs)
```

Any recommendations for now?

**Comment by T4rk1n** [comment]
For celery the `copy_current_request_context` method doesn't work. An alternative we could do is provide the values like headers, path, remote, etc. inside the callback_context instead.

**Comment by T4rk1n** [comment]
The issue is that wrapping the function in the callback where it should be, doesn't return a celery task object to call (Missing func.delay). The callback_context I refactored to use a context_var instead of the flask.g object for that matter.

**Comment by T4rk1n** [comment]
@ArtsiomAntropau If you can prove that works with a test, (can add `path=flask.request.path` to `tests/integration/long_callback/app_callback_ctx.py` line 34 then test in test_lcbc012_long_callback_ctx) I'll gladly take a look in a PR.

**Comment by alexcjohnson** [comment]
From @JamesKunstle in #2636:

Update: For anyone looking for a solution, you can pass the 'request=flask.request' object into background callbacks and that seems to work.

https://community.plotly.com/t/how-to-read-cookies-inside-a-background-callback/70224/11

**Comment by kovalev-vladimir-da** [comment]
Hi @alexcjohnson !
It appears for me (and not only) that this method is not working cus i gor "Working outside of request context"

So, this solution `request=flask.request` is working when DiskCache is on, but not for Celery.
