### ISSUE TITLE
Flask redirect results in 404

### ISSUE THREAD

**Issue by monochromec** [plotly/dash#2264]
Thank you so much for helping improve the quality of Dash!

We do our best to catch bugs during the release process, but we rely on your help to find the ones that slip through.

**Describe your context**
When redirecting a URL defined as "url_base_pathname" in the Dash object creation to subsequent URL, I get a 404 error

-  replace the result of `pip list | grep dash` below
```
dash                      2.6.2
dash-bootstrap-components 1.2.1
dash-core-components      2.0.0
dash-html-components      2.0.0
dash-table                5.0.0
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: OSX 12.6
    - Consistent across all browsers

**Describe the bug**

Create a Dash object and redirect the root URL to another one which is under Dash Pages control:

```
    app = dash.Dash(__name__, external_stylesheets=[dbc.themes.BOOTSTRAP], url_base_pathname='/stats/', use_pages=True, pages_folder='.')
    dash.register_page(date, relative_path='ABC', layout=<valid html data>)
    app.css.config.serve_locally = True
    app.scripts.config.serve_locally = True
    first = 'ABC'

    @app.server.route('/stats/')
    def set_first():
        return flask.redirect('/stats/'+first)
```
**Expected behavior**

Page should redirect to '/stats/ABC'. Invoking '/stats/ABC' directly works.

More than happy to provide more info - just let me know what is required in addition.

**Comment by AnnMarieW** [comment]
Hi @monochromec 

You can do this by setting the ABC page as the root.  ie  `path="/"`  Then if you would like to add a redirect for `"/stats/ABC"` you can use the `redirect_from` prop.  Here is a minimal example:

```
import dash
from dash import html

app = dash.Dash(__name__,  url_base_pathname='/stats/', use_pages=True, pages_folder='')
dash.register_page("ABC", path='/', redirect_from = ["/ABC"], layout=html.Div("hello dash"))

app.layout = dash.page_container

if __name__ == "__main__":
    app.run_server(debug=True)

```

**Comment by monochromec** [comment]
@AnnMarieW Thanks for the quick reply.

Unfortunately this doesn't solve the problem as '/stats/ABC' has its own content (which is not accessible with the method you're describing)- I just want to to redirect '/stats/' to '/stats/ABC' and not the other way around.

**Comment by BSd3v** [comment]
Actually, you can leave the url_base_pathname, you just need to implement your flask server app and set its routings first.

```
server = Flask(__name__)

@server.route('/stats/')
def set_first():
    print('here')
    return redirect('/stats/' + first)

app = dash.Dash(__name__, server=server, external_stylesheets=[dbc.themes.BOOTSTRAP], url_base_pathname='/stats/',
```

**Comment by monochromec** [comment]
@BSd3v Thanks - that did the trick!
