### ISSUE TITLE
Feature Request: dcc.Switches

### ISSUE THREAD

**Issue by SterlingButters** [plotly/dash#227]
In case you want to cover all interface options, I thought switches would be a good addition for values that need only be True or False.

**Comment by ThomasProctor** [comment]
Could you create a reasonable kludge with a two-valued slider?

**Comment by chriddyp** [comment]
Or use a radio items for now.

This is a good candidate for a 3rd party component: you can make your own with React.js and the Dash plugin system: https://github.com/plotly/dash-table-experiments#usage-with-callbacks

**Comment by SterlingButters** [comment]
Was just an idea, I’ll keep that in mind tho! Thanks
