### ISSUE TITLE
Callback will wait indefinitely for callback that raises an exception

### ISSUE THREAD

**Issue by ThomasProctor** [plotly/dash#229]
If a callback on A is triggered by changes in two other properties, B and C, and B itself has a callback triggered by C, then the A callback will never be triggered if the callback on B stops due to an exception. Given that exceptions are the standard way to decline to update a property, this is unexpected behavior.

Here's a MWE:
```
import re
from time import sleep

import dash
import dash_html_components as html
import dash_core_components as dcc
from dash.dependencies import Output, Input, State


app = dash.Dash()
app.layout = html.Div([html.Div([dcc.Input(id='input', type='text'),
                                 html.Button(id='submit-button', n_clicks=0,
                                                    children='Count Number')],
                                className='row'),
                       html.Div([html.Div("An even number has been entered 0 times",
                                                    id='even'),
                                 html.Div("An odd number has been entered 0 times",
                                               id='odd')])])


@app.callback(Output(component_id='even', component_property='children'),
              [Input(component_id='submit-button',
                     component_property="n_clicks"),
               Input(component_id='odd',
                     component_property="children")],
              [State(component_id='input',
                     component_property="value"),
               State(component_id='even',
                     component_property="children")])
def update_even(clicks, odd_val, number_str, current):
"""
Should increment even count by one if an even number is entered.
However, it does not, because the odd counter is included as an
input to this function. Since the odd counter will raise an exception
if an even number is entered, this function will never fire if an even
number is input.
"""
    if number_str is None:
        raise dash.exceptions.PreventUpdate()
    number = int(number_str)
    if number % 2 == 0:
        regex = re.compile(r"(\d+)")
        match = regex.search(current)
        current_val = int(match.group(1))
        return "An even number has been entered {} times".format(current_val + 1)
    else:
        print("Number must be odd")
        raise dash.exceptions.PreventUpdate()


@app.callback(Output(component_id='odd', component_property='children'),
              [Input(component_id='submit-button',
                     component_property="n_clicks")],
              [State(component_id='input',
                     component_property="value"),
               State(component_id='odd',
                     component_property="children")])
def update_odd(clicks, number_str, current):
"""
This version works correctly because the even counter is not a
triggering input in the callback.
"""
    if number_str is None:
        raise dash.exceptions.PreventUpdate()
    number = int(number_str)
    if number % 2 != 0:
        regex = re.compile(r"(\d+)")
        match = regex.search(current)
        current_val = int(match.group(1))
        return "An odd number has been entered {} times".format(current_val + 1)
    else:
        print("Number must be even")
        raise dash.exceptions.PreventUpdate()


if __name__ == "__main__":
    app.run_server(debug=True, port=65003)
```

I encountered this situation in the wild building an app that retrieves a bunch of data from an SQL server when the user requests it, which is then written to a hidden div. If the user requests data that is already present, I would prefer not having to update the hidden div(it is a large amount of unnecessary data to transmit), but change the plots that are dependent on the data to match the requested data.

I'm presuming that a dash callback is designed to wait until all dependent callbacks are finished if they are supposed to run. If one of those callbacks raise an exception, it waits indefinitely. This is logical, but it really should run when all dependent callbacks finish, regardless of whether or not they actually change or `PreventUpdate` is raised and a 204 response is sent.

**Comment by chriddyp** [comment]
> then the A callback will never be triggered if the callback on B stops due to an exception. Given that exceptions are the standard way to decline to update a property, this is unexpected behavior.

There are likely cases to be made for both sets of behaviour: 
1 - preventing an update of the `Output` and stopping the callback chain
2 - preventing an update of the `Output` but continuing the callback chain with the same value of `Output`

In the existing behaviour, we prevent the callback chain from continuing (case 1). This allows you to program case 2 on a selective, per-callback basis by wrapping your function in a `try`/`except` and returning the existing value of the component in the `except` statement by passing it in as `State`.

**Comment by chriddyp** [comment]
I'll close this now but feel free to comment in case I'm missing something!
