### ISSUE TITLE
Hovardata callback in subplots. 

### ISSUE THREAD

**Issue by mk-michal** [plotly/dash#231]
Hi, I am trying to make a callback by hovering over data in subplot. In a regular plot it seems to work fine (like in second example in https://dash.plot.ly/interactive-graphing), but this callback does't seem to work in a subplot for me. Is there a way to make a callback by hoovering over data in subplots? And identify from which subplot the hover data comes from? I will pin a code if needed, but I believe this is a general question.

**Comment by mk-michal** [comment]
It works on subplots as well, found another mistake in my code

**Comment by Relent97** [comment]
Hi please can you share your code and the mistakes. It will be very helpful thank you
