### ISSUE TITLE
editing dash-renderer/build/dash_renderer.dev.js has no effect during runtime

### ISSUE THREAD

**Issue by nmz787-intel** [plotly/dash#2315]
**Describe your context**
linux, installed dash and dash-cytoscape with pip

-  replace the result of `pip list | grep dash` below
```
dash                            2.7.0
dash-core-components            2.0.0
dash-cytoscape                  0.3.0       /home/nmz787/git/dash-cytoscape
dash-dangerously-set-inner-html 0.0.2
dash-flow-example               0.0.5
dash-html-components            2.0.0
dash-table                      5.0.0
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: Windows 10
    - Browser - Chrome
    - Version - Version 107.0.5304.106 (Official Build) (64-bit)

**Describe the bug**

when I edit the `site-packages`  copy of `dash/dash-renderer/build/dash_renderer.dev.js` and hard-refresh my browser, my code changes do not show up.

What is the correct procedure for testing hot-patches like this? If I need to clone this repo and build a local copy after my changes/alterations, where are the build instructions?

**Expected behavior**

I edit the JS file, which is presumably being served when Dash is run, and my browser runs the changed code.

**Comment by T4rk1n** [comment]
> What is the correct procedure for testing hot-patches like this? If I need to clone this repo and build a local copy after my changes/alterations, where are the build instructions?

You can fork the repo and then our [contributing guide](https://github.com/plotly/dash/blob/dev/CONTRIBUTING.md) should get started you with building dash-renderer.

To rebuild, I mostly use `npm run build` from the root or for the renderer I cd to `dash/dash-renderer` then `npm run build`, the browser need a manual reload for the renderer.

If you have something you wish to add to dash, we'll be happy to take a look at a PR.

**Comment by nmz787-intel** [comment]
is there no way to edit the "compiled" JS? I don't have experience with NPM.
