### ISSUE TITLE
[BUG] Why setProps rather than setState?

### ISSUE THREAD

**Issue by fmarotta** [plotly/dash#2328]
While making a custom slider component, I stumbled upon some problems that are ultimately due to the fact that Dash uses `setProps()` instead of `setState()`.

First, let's say I have a parent component an a child component, but the parent is completely static and doesn't need to change state at all; only the children is dynamic and has a state. The parent component gets the props from Dash, and passes them to the child. By calling `setProps()` in the child, the parent is re-rendered every time the child changes, which is is slow and inefficient, while using `setState()` doesn't have this limitation. Maybe there are workarounds to this (if so, please advise: I'm not a React pro), but there is another, more subtle problem.

The second problem is that every time `setProps()` is called, my component loses focus. I want to control my slider either with mouse or arrow keys, but whenever it re-renders, it loses the focus because everything is re-rendered from scratch, so my component cannot detect the arrow keys being pressed. Again, there may be workarounds, but the point is that these problems do not occur if I just use `setState()`. So, is there any reason why Dash uses setProps, which by the way is deprecated?

(This issue may be related to #1011)

**Describe your context**
Please provide us your environment, so we can easily reproduce the issue.

-  replace the result of `pip list | grep dash` below
```
dash                          2.6.1
dash-core-components          2.0.0
dash-html-components          2.0.0
dash-table                    5.0.0
```

**Comment by T4rk1n** [comment]
> So, is there any reason why Dash uses setProps, which by the way is deprecated?

`setProps` is the prop added by Dash to set the properties for use in callbacks, it is not the same as the old react `setProps`. Props of dash components are controlled by the dash renderer, if you have a value that is not to be used in callbacks then you can use a state. Changing props on a component will trigger a re-render, to configure what will trigger it, you can implement [shouldComponentUpdate](https://reactjs.org/docs/react-component.html#shouldcomponentupdate) in class components or use memo for functional components.

**Comment by fmarotta** [comment]
I see, thanks for the explanation! I was able to solve both problems. For posterity, I had to call my children components as variables rather than sub-components, i.e. do
```
function ParentComponent(props) {
    render(
        <div>
            {ChildComponent1}
            {ChildComponent2}
        </div>
    )
}
```
rather than
```
function ParentComponent(props) {
    render(
        <div>
            <ChildComponent1 />
            <ChildComponent />
        </div>
    )
}
```
This solved the focus issue. To avoid the unnecessary re-rendering, I memoize the component that doesn't need to change.
