### ISSUE TITLE
Turn off undo/redo by default in Dash 1.0

### ISSUE THREAD

**Issue by Moisan** [plotly/dash#234]
The current solution to remove the undo-redo button is to [change the css of the page to hide it](https://community.plot.ly/t/is-it-possible-to-hide-the-floating-toolbar/4911/11) while [using a hosted css file](https://stackoverflow.com/questions/45137459/how-to-remove-the-undo-button-in-plotly-dash-after-a-dropdown-update). 

It would be much simpler to have an option that toggles this button, a bit like the graph toolbar.

**Comment by charleyferrari** [comment]
@Moisan Thanks for writing in. This seems like a good feature to have within Dash. Adding some tags to encourage some discussion and collaboration.

**Comment by ebber** [comment]
Would very much appreciate this feature as well. I am having trouble using the workaround. While I will be able to do it, it seems like a useful feature to be able to config, rather than making messy code.

**Comment by Myijin** [comment]
The undo button does not change anything for my dash app, which has input box and button.
My function looks like this:
```
@app.callback(Output('Docs', 'children'),
              [Input('button', 'n_clicks')],
              [State('input', 'value')])
def clean_data(n_clicks, input):
     if n_clicks is not None and input is not None:
            return ...
```
For example, I enter “A” in the input box and click the button, then enter “B” in the input box and click the button. Then clicking undo nothing is changed. I am hoping that the undo can go back to the result for “A”.

**Comment by rmarren1** [comment]
@Myijin I think this issue describes the behavior you are talking about https://github.com/plotly/dash-renderer/issues/66, does that sound right?

**Comment by Myijin** [comment]
@rmarren1 That's right. When I only use the input box, the undo can go back to previous input. But it's not working after using button.

**Comment by rmarren1** [comment]
@Myijin Okay, I have a PR to fix this that is ready but have not merged, I'll see if I can expedite that

**Comment by vanbenschoten** [comment]
Is there any update on an easy option to remove the Undo-Redo button? I'll add my support for an easy toggle option as the button currently gets in the way of our dashboards.

**Comment by T4rk1n** [comment]
Include a css file in the assets folder with this:

```
._dash-undo-redo {
  display: none;
}
```

**Comment by vanbenschoten** [comment]
@T4rk1n thanks! That took care of the issue (though I still think a toggle feature would be helpful as well)

**Comment by eddy-ojb** [comment]
I would like the undo-button but have no control over where it is displayed. For example, I don't want its position fixed but would like it as part of my menu bar as a relative element. A better feature would be to be able to supply positional css straight to the element, including display: none.

**Comment by Akronix** [comment]
> I would like the undo-button but have no control over where it is displayed. For example, I don't want its position fixed but would like it as part of my menu bar as a relative element. A better feature would be to be able to supply positional css straight to the element, including display: none.

hmm What's wrong with using the `._dash-undo-redo` css class and add your desired custom style into your css stylesheet?
