### ISSUE TITLE
[BUG] Clustering (#5827) breaks callback on the scattermapbox graph element

### ISSUE THREAD

**Issue by ghost** [plotly/dash#2341]
**Describe your context**
I'm trying to use the [clustering feature](https://plotly.com/python/reference/#scattermapbox-cluster) for  that was introduced to plotly in the latest update (see [documentation](https://github.com/plotly/plotly.js/pull/5827)). 

In the following example you can test it by commenting out `fig.update_traces(cluster=dict(enabled=True))`. Clicking dots without clustering will display the click data in the seconds div. 
```python
import plotly.graph_objects as go  # or plotly.express as px
import plotly.express as px
import pandas as pd

import dash
from dash import dcc
from dash import html
from dash.dependencies import Input, Output

df = pd.read_csv(
    "https://raw.githubusercontent.com/plotly/datasets/master/2011_february_us_airport_traffic.csv"
)
fig = px.scatter_mapbox(df, lat="lat", lon="long",
                        size="cnt", zoom=3, mapbox_style="open-street-map")
fig.update_traces(cluster=dict(enabled=True))

app = dash.Dash()
app.layout = html.Div([
    html.Div([
        dcc.Graph(figure=fig, id="map")
    ], style={"width": "500px", "height": "500px"}),
    html.Div(id='my-div', className='col-12')
])


@ app.callback(
    Output('my-div', 'children'),
    Input('map', 'clickData')
)
def display_clicked_content(clickData):
    return repr(clickData)


app.run_server(debug=True, use_reloader=False)
```

-  replace the result of `pip list | grep dash` below
```
dash                      2.7.0
dash-bootstrap-components 1.2.1
dash-core-components      2.0.0
dash-draggable            0.1.2
dash-html-components      2.0.0
dash-table                5.0.0
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: Windows 11 Pro - Version	10.0.22000 Build 22000
    - Browser: Firefox 
    - Version 107.0 (64 Bit)

**Describe the bug**

When using the clustering feature on a scattermap calbacks that use inputs of the map no longer work. The error shown in the browser looks like [this](https://user-images.githubusercontent.com/110903179/204575926-e04068f8-741e-46d4-9a44-6574068fd454.png).

**Expected behavior**

Clicking on markers on the map should trigger callbacks that e.g. use `clickData` as an Input.

**Comment by alexcjohnson** [comment]
Possibly related to #2343 (cc @AnnMarieW) - @archmoj would you be able to look into this?

**Comment by archmoj** [comment]
> Possibly related to #2343 (cc @AnnMarieW) - @archmoj would you be able to look into this?

OK. Let me see if I could replicate the bug using plotly.js.

**Comment by ned2** [comment]
I suspect this issue is independent of #2343, as I just tested and found that issue to be fixed with the plotly.js version bump in Dash 2.17.1, however the problem described in this issue still persists with 2.7.1.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
