### ISSUE TITLE
[Feature Request][BUG] Disable html.Iframe scrolling

### ISSUE THREAD

**Issue by matthewyangcs** [plotly/dash#2353]
I classify as a feature request + a bug because without being able to set `scrolling="no"`, the IFrame attribute is extremely bugged and is hard to work around with other css styles.

My issue is basically that I want to use html.IFrame without the scrollbar (in html you can set the scrolling attribute="no"). Right now my work-around is setting the height to be extremely high via the style attribute, but my htmls are of different sizes so it's not a very effective work around.

**Comment by ned2** [comment]
The `scrolling` attribute of the `<iframe>` element is actually deprecated (see [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe)). So this is expected to not be available in Dash's `html.Iframe`.

Ordinarily you would reach for setting the `overflow` style of an HTML element to `hidden` to remove the scrollbar, but I suspect in this case it's the top level `html` element _inside_ the `iframe` that you need to hide the scrollbar for, which is not something you can do with CSS.
