### ISSUE TITLE
[BUG] Flaky project dir parsing in debug mode.

### ISSUE THREAD

**Issue by slmg** [plotly/dash#2375]
**Environment**

* Windows 10
* Python 10
* dash 2.7.1

**Describe the bug**

I am willing to run dash in a non standard way, by running `python -c 'from dash_app import app; app.run()'`.

It works fine when it does not run in debug mode, but breaks in debug mode as shown below.

```sh
> DASH_DEBUG=true python -c 'from dash_app import app; app.run()'
Dash is running on http://127.0.0.1:8050/

 * Serving Flask app 'dash_app.app'
 * Debug mode: on
C:\Path\to\python.exe: can't open file 'C:\\Users\\slmg\\dash-app\\-c': [Err no 2] No such file or directory]
```
We can see dash was able to run fine in the first place, but (presumably the watcher) got confused by python's arg `-c`, which hints assumption was made app would always be run via a `python path/to/app.py` command, leading to a parsing error.

**Expected behavior**

Run the app without issue in debug mode and watch the whole app dir for changes.

**Comment by slmg** [comment]
Possibly the last issue for 2022, happy new year! :wink:

**Comment by alexcjohnson** [comment]
It's a little hard to tell, but my guess is this is a problem in Flask's hot reloader rather than in Dash itself. If you don't need hot reloading - or just as a test to narrow down the cause - you could try `app.run(dev_tools_hot_reload=False)`

Curious, what's your use case for running with `python -c 'command'`?

**Comment by ned2** [comment]
Can confirm this behaviour. 

Your suspicion looks to be right @alexcjohnson, running Dash like this is tripping up Flask's reloader. 

We can reproduce this using Flask alone:

**min_flask.py**
```python
from flask import Flask

app = Flask(__name__)

@app.route("/")
def hello_world():
    return "<p>Hello, World!</p>"
```

This runs fine:
    python -c 'from min_flask import app; app.run()'

But turning on the auto reloader gives us that exception:
    python -c 'from min_flask import app; app.run(use_reloader=True)'
    
    >>> python: can't open file '/home/ned/scratch/dash/-c': [Errno 2] No such file or directory

So to run your Dash app with the debugger you can do this:

    DASH_DEBUG=true python -c 'from dash_app import app; app.run(use_reloader=False)'
