### ISSUE TITLE
Install error - Python 3.6.1

### ISSUE THREAD

**Issue by xnoder** [plotly/dash#24]
Hi,

I'm seeing an error when installing 0.17.5 on Python 3.6.1:

```
pip install --no-cache-dir dash==0.17.5
Collecting dash==0.17.5
  Downloading dash-0.17.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/p9/_xrpxf9n5bzbvxzyj664fhvh0000gn/T/pip-build-vk_d_t2m/dash/setup.py", line 13, in <module>
        long_description=open('README.md').read(),
      File "/Users/paul.stevens/.virtualenv/dash/bin/../lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 711: ordinal not in range(128)
```

System specifics:

* macOS 10.12.5
* Homebrew 1.2.3
* Python 3.6.1 (`virtualenv -p python3 ~/.virtualenv/bin/dash`)

This is being triggered by line 13 in `setup.py`:

```
long_description=open('README.md').read(),
```

Locally, I fixed it to work by adding:

```
import io
...
long_description=io.open('README.md', encoding='utf-8').read(),
```

Not sure if its something odd with my environment, or something that may affect other users.

I submitted pull request #23, but I can be a bit thick, so treat with suspicion. More testing is likely required, because I may have missed something painfully obvious to others.

**Comment by jackwluo** [comment]
Tested installation using exact same setup and wans't able to reproduce the error. Either way your PR got merged. Thanks :)
