### ISSUE TITLE
Checklist weird behavior

### ISSUE THREAD

**Issue by m-ibm** [plotly/dash#240]
I am trying to create a page with Dash where I have multiple "complex" components, each having a Checklist (single checkbox really), a couple of Inputs and a slider.

The relevant code is similar to this:

```
def generate_filter_element(label):
	return html.Div(children=[
			html.Div(
				dcc.Checklist(
						id='{}-check-box'.format(label),
				    options=[ {'label': label, 'value': label} ],
				    values=display_columns,
				    labelStyle={'width':'100px', 'display': 'inline-block', 'padding-right':'20px'}
				),
				style={'display':'inline-block'}
			), ... etc
```

And in the layout I have:
```
	html.Div(id='filters_container', children=[generate_filter_element(c) for c in columns]),
```

This creates a *very* weird problem in the callbacks.
The callback receives the values of *all* check-boxes that I define, not just the one I am trying to write the listener for.

```
for column in columns:
	# Gray out min input box when check-box is false
	@app.callback(
	    dash.dependencies.Output('{}-slider'.format(column), 'disabled'),
	    [dash.dependencies.Input('{}-check-box'.format(column), 'values')])
	def gray_min_input_box(values):
		# Values here is a list of all check-boxes which are True, e.g. [u'cb1', u'cb2', u'cb4']
		print values
```

What am I doing wrong?

**Comment by chriddyp** [comment]
It might have to do with the way that the decorator is wrapping the functions in a loop. Try changing the function to a function generator and wrapping your callback in it like:
```
def create_callback():
    def gray_min_input_box(values):
         #...
    return gray_min_input_box

for column in columns:
    @app.callback(...)(create_callback())
```

**Comment by m-ibm** [comment]
Your suggestion didn't quite work - `values` still contains all the (checked) checkboxes.
However, I now have a workaround for the problem.

E.g.
_Before_

0. All 5 boxes checked
1. Uncheck CB1. Values ['2', '3', '4', '5']
2. Uncheck CB3 Values ['2', '4', '5']

At this point I cannot tell (without saving history) which CB was changed.

_Now_

0. All 5 boxes checked
1. Uncheck CB1. Values ['2', '3', '4', '5']
2. Uncheck CB3 Values ['1', '2', '4', '5']

Intersecting with the full list lets me know CB was changed.

**Comment by MM-Lehmann** [comment]
have you considered using wildcard callbacks and dash.callback_context.triggered to determine which input changed?

**Comment by m-ibm** [comment]
It has been 2+ years since I posted the issue. Meanwhile I moved to a different project so I cannot test your suggestion, sorry.
