### ISSUE TITLE
[BUG] JS Error for a multi-page dash application when upgrading to > `2.7`

### ISSUE THREAD

**Issue by kevalshah90** [plotly/dash#2406]
Noticing JS errors with a Dash multi-page Application with dash upgrade. No JS errors on Dash v`2.6.2`

-  replace the result of `pip list | grep dash` below
```
app==0.0.1
boto==2.49.0
boto3==1.20.23
botocore==1.23.26
census==0.8.18
censusgeocode==0.5.1
dash==2.7.1
dash_bootstrap_components==1.2.0
dash_daq==0.5.0
Flask==1.1.4
Flask_Login==0.5.0
Flask_SQLAlchemy==2.5.1
geocoder==1.38.1
geolib==1.0.7
geopandas==0.10.2
geopy==2.2.0
pygeodesy==22.1.22
google_streetview==1.2.9
googlemaps==4.5.3
google-cloud-bigquery==2.31.0
mapbox==0.18.0
matplotlib==3.4.3
numpy==1.20.3
pandas==1.3.4
plotly==5.3.1
pyarrow==6.0.1
pandas-gbq==0.16.0
protobuf==3.19.1
pygeohash==1.2.0
rtree==0.9.7
pygeos==0.12.0
python_dateutil==2.8.2
Quandl==3.5.3
requests==2.26.0
sagemaker==2.70.0
scikit_learn==1.0.2
scipy==1.7.1
seaborn==0.11.2
sendgrid==6.7.0
Shapely==1.8.2
statsmodels==0.12.2
sympy==1.6.2
us==2.0.2
utm==0.7.0
walkscore_api==1.0.1
Werkzeug==1.0.1
xgboost==1.5.1
mysqlclient==2.1.0
pymysql==1.0.2
configparser==5.2.0
usaddress==0.5.0
markupsafe==2.0.1
geojson==2.5.0

```
-  if frontend related, tell us your Browser, Version and OS

    - Browser [chrome]
    - Version [109.0.5414.119]

**Describe the bug**

I have a Dash App running inside a Flask App. I am seeing a bunch of JS errors in the console after upgrading dash to `2.7.1`.  The Application renders a set of rows from a pandas dataframe containing `Lat`, `Long` on a mapbox map layer. 

**Expected behavior**

The data must show on the map. It works as expected on dash v`2.6.1`. 

More details about the code / app files can be found here: https://community.plotly.com/t/dash-js-errors-callback-error-updating/72124/4

**Comment by alexcjohnson** [comment]
This is the same as https://github.com/plotly/plotly.js/issues/6444, correct?

**Comment by kevalshah90** [comment]
@alexcjohnson correct, they are related to plotly version upgrade to `2.7.1`.

**Comment by alexcjohnson** [comment]
OK - let me close this one then, we'll continue the discussion in the plotly.js repo.
