### ISSUE TITLE
[BUG] Content-type of image type is application/json

### ISSUE THREAD

**Issue by rsewell97** [plotly/dash#2447]
**Context**

I'm using Dash 2.8.0 with Python 3.8. 

I have a multi-page app using the default `use_pages=True` setup with pages defined in the `pages/` directory.

I also have a variety of static assets in the `assets/` directory. The folder structure is as follows:

```
assets/
- styles.css
- typography.css
- mountain.png
pages/
- some_page.py
app.py
```

If I try to load the image using an Img(src=get_asset_url('mountain.png')) tag. I get the following response.

![image](https://user-images.githubusercontent.com/38791439/223382174-06e583df-bf18-4388-9124-bec5fa3eccb5.png)

The content-type header of the requested mountain.png is "application/json", therefore my binary_encoding rules try to load the image in plaintext, causing an error rendering of the resource. 

**Expected behavior**

I would expect the Content-type header to be image/png or another generic image MIME type.

**Comment by Alexi8787** [comment]
bro
It seems that there might be an issue with the way the image is being served by your server. The MIME type of the response header should be "image/png" or a similar image format.

One possible solution is to explicitly set the MIME type of the image in the server response. In Dash, you can use the send_file function from the flask module to send the image file with the correct MIME type. Here's an example:

python

from flask import send_file
import os
import dash
import dash_html_components as html

app = dash.Dash(__name__)

image_filename = 'mountain.png'
image_path = os.path.join('assets', image_filename)

@app.server.route('/assets/<path:path>')
def serve_static(path):
    root_dir = os.getcwd()
    return send_file(os.path.join(root_dir, 'assets', path), 
                     mimetype='image/png')

app.layout = html.Div([
    html.Img(src='/assets/mountain.png')
])

if __name__ == '__main__':
    app.run_server(debug=True)

In this example, we define a Flask route to serve static assets from the assets/ directory. The send_file function sets the MIME type of the response to image/png explicitly. We then use the html.Img component with a relative URL to the mountain.png file.

Note that we are using the os module to construct the path to the image file. You may need to modify the path depending on the structure of your project.

I hope this helps!

**Comment by rsewell97** [comment]
Unfortunately this would change all assets in the assets directory to have the image/png content type. If you read my question, I have .css and other text content types in my assets directory.

It would be neatest if this could be handled within Dash. I don't want to manually set content-type per resource.

**Comment by alexcjohnson** [comment]
Odd, I can't reproduce this - I see `Content-Type: image/png` whether I run `python app.py` or through `gunicorn`. Only difference is when it uses a cached version of the file via `ETag`, then I get no `Content-Type` header at all.

@rsewell97 how are you running your app, and on what OS?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
