### ISSUE TITLE
[BUG] No dialog box for dcc.Download component in Edge browser

### ISSUE THREAD

**Issue by Pomurnik** [plotly/dash#2454]
# Software
```
dash                 2.7.0
```
### Browser

* OS: Windows 10
* Browser: Edge
* Version: 110.0.1587.69 (Official Build) (64-bit)

# Issue
### Describe the bug
In the Microsoft Edge browser, after clicking the download button, it is directly saved to the default folder for downloads. The window with the selection of the path and name for the file is not displayed.

![image](https://user-images.githubusercontent.com/19503667/224761944-659eda52-5564-4166-84ed-f07070d0cce7.png)

### Expected behavior
Showing dialog box like in Chrome browser.
![image](https://user-images.githubusercontent.com/19503667/224761210-97739738-ac83-4b1a-b229-c184ebd6fe9f.png)

# Code
Code from https://dash.plotly.com/dash-core-components/download
```
from dash import Dash, dcc, html, Input, Output
import pandas as pd

app = Dash(__name__)
app.layout = html.Div(
    [
        html.Button("Download CSV", id="btn_csv"),
        dcc.Download(id="download-dataframe-csv"),
    ]
)

df = pd.DataFrame({"a": [1, 2, 3, 4], "b": [2, 1, 5, 6], "c": ["x", "x", "y", "y"]})


@app.callback(
    Output("download-dataframe-csv", "data"),
    Input("btn_csv", "n_clicks"),
    prevent_initial_call=True,
)
def func(n_clicks):
    return dcc.send_data_frame(df.to_csv, "mydf.csv")


if __name__ == "__main__":
    app.run_server(debug=True)
```

**Comment by Pomurnik** [comment]
To resolve this we need just to change one setting in Edge browser settings.
![edge_dialog_box](https://user-images.githubusercontent.com/19503667/225034138-5121c1cb-4e15-4bb1-a6f9-9f96ed229d0e.png)

![image](https://user-images.githubusercontent.com/19503667/225034409-2af9af0b-6cce-44e3-a149-6659f67aa522.png)

**Comment by alexcjohnson** [comment]
Glad you were able to solve this @Pomurnik - most likely since Edge has that as a setting there wouldn't have been anything we could do in the code to affect this behavior!
