### ISSUE TITLE
How to change the size of the output image?

### ISSUE THREAD

**Issue by neosun100** [plotly/dash#246]
The default takes up half of the browser space，How should I set up the image to fill the entire browser space?
![tim 20180417234829](https://user-images.githubusercontent.com/13846998/38881108-de51ea38-4299-11e8-89e2-f4f9c4a23ef9.png)

**Comment by neosun100** [comment]
Thanks to the dash developers for providing such a nice visualization tool.

**Comment by charleyferrari** [comment]
Thanks for reaching out @neosun100. Graphs fill the entire container their put in unless the height or width is explicitly set. Try changing the css of your divs to make the graph.

To talk further about this, I would recommend using our [community site](https://community.plot.ly/c/dash), or checking out our [support plans](https://support.plot.ly/plans).
