### ISSUE TITLE
Passing the 'children' property as a State will lock the component

### ISSUE THREAD

**Issue by alessioarena** [plotly/dash#248]
Hi,
I'm having some issues creating a dashboard where:
1. there is a DIV built dynamically based on user input (dropdown)
2. pressing a button will run a function that reads the components in this DIV, and output the 'id' and 'value' properties
3. I could have a variable number of components within the built DIV

The way I was trying to tackle the third point was to pass the 'children' of the DIV, then iterate through the number of components and get their values.
Unfortunately passing the 'children' property (as a State) somehow corrupts the components, and I'm now not able to change the value of those components.

I'm running:
python = 2.7.14
dash = 0.21.0
dash_core_components = 0.22.1
dash_html_components = 0.10.0

Here is an example of what I'm talking about (sorry, the code is a bit long):

```
import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output, State, Event
# import plotly.plotly as py
import numpy as np
import json

app = dash.Dash()
app.scripts.config.serve_locally=True
app.css.append_css({"external_url": "https://codepen.io/chriddyp/pen/bWLwgP.css"})

choice1 = html.Div([
    html.Div(html.Label('one'), className='six columns'),
    html.Div([
        dcc.Input(
            id='one',
            placeholder='one',
            type='number',
            inputmode='numeric',
            min=0,
            max=100,
            value=50
        )
    ], className='six columns')
])
choice2 = html.Div([
    html.Div(html.Label('two'), className='six columns'),
    html.Div([
        dcc.Input(
            id='two',
            placeholder='two',
            type='number',
            inputmode='numeric',
            min=0,
            max=130,
            value=50
        )
    ], className='six columns')
])
choice3 = html.Div([
    html.Div(html.Label('three'), className='six columns'),
    html.Div([
        dcc.Input(
            id='three',
            placeholder='three',
            type='number',
            inputmode='numeric',
            min=0,
            value=3
        )
    ], className='six columns')
])


app.layout = html.Div([
    dcc.Dropdown(
    id='dropdown',
    options=[
        {'label': 'choice1', 'value': 'choice1'},
        {'label': 'choice2', 'value': 'choice2'},
    ],
    value='choice1'
    ),
    html.Div([choice1], id='test_space', className='twelve columns'),
    html.Button('Test!', id='test'),
    html.Div(id='output')
], className='twelve columns')

@app.callback(output=Output('test_space', 'children'),
inputs=[Input('dropdown', 'value')
])
def build_testspace(value):
    if value == 'choice1':
        return [choice1]
    elif value == 'choice2':
        return [choice2, choice3]

@app.callback(
    output = Output('output', 'children'),
    inputs = [Input('test', 'n_clicks')],
    state = [
        State('dropdown', 'value'),
        State('test_space', 'children')
    ]
)
def run(n_clicks, dropdown, test_space):
    out_string = 'You selected '+str(dropdown)+' and the testspace is displaying: '
    for i in test_space:
        var = i['props']['children'][1]['props']['children'][0]['props']
        out_string += '    '+str(var['id']+' ->'+str(var['value']))
    return out_string

if __name__ == '__main__':
    app.run_server(debug=True)
```
![dash_testing](https://user-images.githubusercontent.com/33886395/38966042-8267b380-43c3-11e8-8952-558fd2cf91d6.gif)

**Comment by DavidKunFF** [comment]
The same locking happens when directly referencing values property of dcc.Checklist or children property of html.Div. 
Regarding triage this makes checklists more or less unusable with State, and using them as Input is very inconvenient (as every change in checks will trigger the calculation).

**Comment by lauraln** [comment]
ddd

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
