### ISSUE TITLE
[BUG] Inline clientside_callback scripts not found in Dash 2.9.2

### ISSUE THREAD

**Issue by RenaudLN** [plotly/dash#2488]
**Environment**
```
dash                 2.9.2
```

**Describe the bug**

In Dash 2.9.2, the clientside callbacks defined inline get a random function name which seems to break. Note: the issue solves itslef when refreshing the page, however every first load triggers this issue. Tested in 2.9.1 and this does not happen, it was introduced with the random function names in 2.9.2.

Using a deterministic function name instead solves the issue:

```python
import itertools
COUNTER = itertools.count()

def register_clientside_callback(...):
    ...

    increment = next(COUNTER)
    function_name = f"inline-script-{increment:06d}"
    ...
```

**Expected behavior**

The clientside_callbacks defined inline should work from the first load.

**Screenshots**

![image](https://user-images.githubusercontent.com/20662281/229090259-de16ddce-8273-449c-9ad7-fc6c2c0d164b.png)

**Comment by T4rk1n** [comment]
I put md5 on the function code in #2491 which should fix the issue, but uncovered another side effect related to hot-reload and clientside function not being actually reloaded when the code changes.
