### ISSUE TITLE
ImportError: No module named 'dash_renderer' Python 3.5.2

### ISSUE THREAD

**Issue by rohansb** [plotly/dash#25]
Was able to successfully install using `pip install plotly && pip install dash`

Platform: OSX

Getting following error: 
 ` 
File "/Users/@@/.virtualenvs/dash2.0/lib/python3.5/site-packages/dash/dash.py", line 15, in <module>
    import dash_renderer
ImportError: No module named 'dash_renderer'
`

Generated by first line of code here:
`
import dash
app = dash.Dash('Hello World')
if __name__ == '__main__':
    app.run_server()
`
Does pip installation for the Dash frontend is bundled in separately? https://github.com/plotly/dash-renderer?

**Comment by jackwluo** [comment]
At the time being, you need to also install dash_renderer using pip

**Comment by rohansb** [comment]
Gotcha! thanks for the response

**Comment by rohansb** [comment]
Install guide is on its way?

**Comment by jackwluo** [comment]
Simply run 'pip install dash_renderer' and you should be good to go. Don't also forget dash_html_components and dash_core_components

**Comment by rohansb** [comment]
Thanks. Anything else missing too ?
`  File "/Users/@@/.virtualenvs/dash2.0/lib/python3.5/site-packages/dash/resources.py", line 87, in get_inferred_resources
    for t in layout.traverse():
AttributeError: 'NoneType' object has no attribute 'traverse'`

**Comment by jackwluo** [comment]
Have you specified an app.layout somewhere? See https://plot.ly/dash/getting-started

**Comment by rohansb** [comment]
I had not.. woooot! now i can see my first running example :) thanks @jackwluo
