### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sorenwacker** [plotly/dash#2504]
Thank you so much for helping improve the quality of Dash!

We do our best to catch bugs during the release process, but we rely on your help to find the ones that slip through.

**Describe your context**
`dcc.Download()` takes a long time or does not finish with a tiny bit more data. It works with smaller amounts of data. There is no error thrown in the console. Trying to send a dataframe with 27k rows. It seems `dcc.send_data_frame()` is very inefficcent. It works when the download format is csv, but not with xlsx.

-  replace the result of `pip list | grep dash` below
```
dash                      2.9.2
dash-bootstrap-components 1.4.1
dash-core-components      2.0.0
dash-html-components      2.0.0
dash-table                5.0.0
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: W11
    - Browser chrome
    - Version 112.0.5615.49 (Official Build) (64-bit)

**Describe the bug**

`dcc.Download()` takes a long time or does not finish with a tiny bit more data. It works with smaller amounts of data. There is no error thrown in the console. Only the waitress task queue is increasing:

WARNING:waitress.queue:Task queue depth is 1
WARNING:waitress.queue:Task queue depth is 1
WARNING:waitress.queue:Task queue depth is 1
WARNING:waitress.queue:Task queue depth is 2
WARNING:waitress.queue:Task queue depth is 1
WARNING:waitress.queue:Task queue depth is 2
WARNING:waitress.queue:Task queue depth is 3
WARNING:waitress.queue:Task queue depth is 4
WARNING:waitress.queue:Task queue depth is 5
WARNING:waitress.queue:Task queue depth is 6

**Expected behavior**

The download should be done in seconds.

**Screenshots**

![image](https://user-images.githubusercontent.com/3391614/231296901-01746f01-ca3a-4faf-97bc-d23a362ce380.png)

**Comment by nickmelnikov82** [comment]
Hi, I found some useful information regarding your problem:

1)[ The issue with dcc.Loading not showing up when calling long functions.](https://community.plotly.com/t/dcc-loading-not-working-with-long-function-calls/68772)
2) Here are some articles from StackOverflow that might be useful for you: [article1](https://stackoverflow.com/questions/59317363/how-to-make-dash-app-run-faster-if-its-slowed-by-large-data-imported), [article2](https://stackoverflow.com/questions/74387012/dash-plotly-unable-to-download-the-processed-excel-file-on-button-click), [article3](https://stackoverflow.com/questions/55857058/how-to-find-the-cause-of-task-queue-depth-warnings-from-waitress), [article4](https://stackoverflow.com/questions/61784556/download-csv-file-in-dash).
3) [I keep getting the warning 'WARNING:waitress.queue:Task queue depth is 1'.](https://github.com/plotly/dash/issues/1874)
4) [You have a similar error.](https://github.com/Pylons/waitress/issues/235)

Please let me know if any of the above helped you. If not, please provide the code and we can work on resolving this issue.

**Comment by nickmelnikov82** [comment]
Could you kindly provide a Minimal Working Example (MWE), which refers to a code snippet that can be executed and reproduces the error you encountered? Additionally, could you specify the size of the data you are working with? It would be helpful to know the time it takes to write the dataframe to an Excel file (xlsx) on the local disk. Lastly, could you inform me if there are any timeouts or size limitations in your current production setup?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
