### ISSUE TITLE
[BUG] Support React.memo() equal function in react functional component develope

### ISSUE THREAD

**Issue by CNFeffery** [plotly/dash#2528]
When I develop dash component in react functional component, if I set the `equal` function to prevent some unnecessary redraw, the component won't be generated after the build:

![image](https://github.com/plotly/dash/assets/49147660/25ec5a30-7d5a-4204-9f04-cc028db62d68)
![image](https://github.com/plotly/dash/assets/49147660/6b7a50cb-e179-4077-aa24-6b5eb51278a9)

@T4rk1n

**Comment by T4rk1n** [comment]
is that with typescript, js component or both ?

**Comment by CNFeffery** [comment]
@T4rk1n js, I haven't tested in ts.

**Comment by CNFeffery** [comment]
@T4rk1n Works perfectly for me, thanks very much!
