### ISSUE TITLE
[BUG] Graphs in vertical tabs do not use available space

### ISSUE THREAD

**Issue by TheNyneR** [plotly/dash#2547]
Installed Dash versions:
```
dash                          2.9.2
dash-core-components          2.0.0
dash-html-components          2.0.0
dash-table                    5.0.0
dash-testing-stub             0.0.2
```
Browsers/OS
    - OS: Linux
    - Browser ungoogled-chromium, firefox

**Describe the bug**

The width of the graph object does not extend to the right side of the screen. When removing `vertical=True` the graph fills the entire screen.

**Expected behavior**

The graph object should use the available space to the right.

**Screenshots**
`vertical=True`
![vertical_true](https://github.com/plotly/dash/assets/36898462/b8dee9ac-da53-469a-be1e-eae07e70736f)
`vertical=False`
![vertical_false](https://github.com/plotly/dash/assets/36898462/782093e3-c6c1-4b0c-b5b2-fad5934c32cc)

**Minimal example used**
```
from dash import Dash, html, dcc
import plotly.express as px
import pandas as pd

app = Dash(__name__)

daily_profile = [0, 0, 0, 0, 0, 0, 0, 0.05, 0.15, 0.2, 0.4, 0.8, 0.7, 0.4, 0.2, 0.15, 0.05, 0, 0, 0, 0, 0, 0, 0]
daily_production = pd.DataFrame(data=daily_profile)

tab = dcc.Tab([dcc.Graph(figure=px.bar(daily_production))], label="tab")

app.layout = html.Div([
    dcc.Tabs([tab]
             , vertical=True # remove to fix graph behavior
             )
])

if __name__ == "__main__":
    app.run_server(debug=True)

```

**Comment by nickmelnikov82** [comment]
Am I understanding this correctly? You want the chart to be located in the center of the screen, not just on the left. And not take up all the available space

**Comment by nickmelnikov82** [comment]
These lines of code create a histogram with data from the daily_production variable. The width parameter sets the width of the chart to 1800 pixels (you can set any width), and the autosize parameter allows you to automatically scale the chart. Here is the code, check if it suits you:

from dash import Dash, html, dcc
import plotly.graph_objects as go
import pandas as pd

app = Dash(__name__)

daily_profile = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0.05, 0.15, 0.2, 0.4, 0.8, 0.7, 0.4, 0.2, 0.15, 0.05, 0, 0, 0, 0, 0, 0, 0, 0]
daily_production = pd.DataFrame(data=daily_profile)

fig = go.Figure(data=go.Bar(x=daily_production.index, y=daily_production[0]))
fig.update_layout(width=1800, autosize=True) # Increase the width of the graph and automatically resize it

tab = dcc.Tab([dcc.Graph(figure=fig)], label="tab")

app.layout = html.Div([
    dcc.Tabs([tab], vertical=True)
])
if __name__ == "__main__":
    app.run_server(debug=True)

Please let me know if this option satisfies you.

**Comment by nickmelnikov82** [comment]
Define the layout of the application using html.Div and dcc.Tabs. html.Div is used as a container, and dcc.Tabs creates a tabbed block.
Create a render_content callback function that displays the content depending on the selected tab.
The render_content callback returns an html.Div with a text header and a graphic if the tab "tab-1-example" is selected.
Together, these steps allow us to create a tabbed block where the graphic fills the entire width of the screen.
Please review the code below to make sure it meets your requirements:

from dash import Dash, html, dcc
from dash.dependencies import Input, Output
import plotly.express as px
import pandas as pd

app = Dash(__name__)

daily_profile = [0, 0, 0, 0, 0, 0, 0, 0.05, 0.15, 0.2, 0.4, 0.8, 0.7, 0.4, 0.2, 0.15, 0.05, 0, 0, 0, 0, 0, 0, 0]
daily_production = pd.DataFrame(data=daily_profile)

app.layout = html.Div([
    dcc.Tabs(
        id="tabs-example",
        value='tab-1-example',
        children=[
            dcc.Tab(
                label='Tab One',
                value='tab-1-example'
            ),
        ],
        vertical=False,
        parent_style={'float': 'left'}
    ),
    html.Div(
        id='tabs-content-example',
        style={'float': 'left', 'width': '100%'}  # Розміщуємо графік на всю ширину
    )
])


@app.callback(
    Output('tabs-content-example', 'children'),
    [Input('tabs-example', 'value')]
)
def render_content(tab):
    if tab == 'tab-1-example':
        return html.Div(
            [
                html.H3('Tab content 1'),
                dcc.Graph(
                    id='graph-1-tabs',
                    figure=px.bar(daily_production)
                )
            ]
        )


if __name__ == '__main__':
    app.run_server(debug=True)

**Comment by nickmelnikov82** [comment]
Is that what you meant? 
[Screencast from 31.05.23 10:33:59.webm](https://github.com/plotly/dash/assets/53801797/38c1a7e6-d66c-46de-a83f-0c454812b784)

**Comment by nickmelnikov82** [comment]
Try this code, it should work better. Here, we have created a parent element in which we have changed the data to the data we need:

```
from dash import Dash, html, dcc
from dash.dependencies import Input, Output
import plotly.express as px
import pandas as pd

app = Dash(__name__)

daily_profile = [0, 0, 0, 0, 0, 0, 0, 0.05, 0.15, 0.2, 0.4, 0.8, 0.7, 0.4, 0.2, 0.15, 0.05, 0, 0, 0, 0, 0, 0, 0]
daily_production = pd.DataFrame(data=daily_profile)

app.layout = html.Div(
    style={'width': '100vw', 'height': '100vh'},
    children=[
        dcc.Tabs(
            id='tabs-example',
            value='tab-1-example',
            children=[
                dcc.Tab(
                    label='Tab One',
                    value='tab-1-example'
                ),
                dcc.Tab(
                    label='Tab Two',
                    value='tab-2-example'
                ),
                dcc.Tab(
                    label='Tab Three',
                    value='tab-3-example'
                ),
            ],
            vertical=True,
            parent_style={'float': 'left'}
        ),
        html.Div(
            id='tabs-content-example',
            style={'width': 'calc(100% - 200px)', 'float': 'left', 'height': '100%'}  # Розміщуємо графік на всю ширину
        )
    ]
)


@app.callback(
    Output('tabs-content-example', 'children'),
    [Input('tabs-example', 'value')]
)
def render_content(tab):
    if tab == 'tab-1-example':
        return html.Div(
            [
                html.H3('Tab content 1'),
                dcc.Graph(
                    id='graph-1-tabs',
                    figure=px.bar(daily_production)
                )
            ]
        )
    elif tab == 'tab-2-example':
        return html.Div(
            [
                html.H3('Tab content 2'),
                dcc.Graph(
                    id='graph-2-tabs',
                    figure=px.line(daily_production)
                )
            ]
        )
    elif tab == 'tab-3-example':
        return html.Div(
            [
                html.H3('Tab content 3'),
                dcc.Graph(
                    id='graph-3-tabs',
                    figure=px.scatter(daily_production)
                )
            ]
        )


if __name__ == '__main__':
    app.run_server(debug=True, dev_tools_hot_reload=False)
```

**Comment by nickmelnikov82** [comment]
Hello! Having received an answer to my question on the [forum](https://community.plotly.com/t/graphs-in-vertical-tabs-do-not-use-available-space/75664/3), I want to share another working option

```
from dash import Dash, html, dcc
import plotly.express as px
import pandas as pd

app = Dash(__name__)

daily_profile = [0, 0, 0, 0, 0, 0, 0, 0, 0.05, 0.15, 0.2, 0.4, 0.8, 0.7, 0.4, 0.2, 0.15, 0.05, 0, 0, 0, 0, 0, 0, 0, 0]
daily_production = pd.DataFrame(data=daily_profile)

tab = dcc.Tab(
    children=[
        html.Div(
            dcc.Graph(
                figure=px.bar(
                    daily_production
                )
            ),
            style={'width': '100vw'}
        )
    ], label="tab"
)

app.layout = html.Div([
    dcc.Tabs([tab]
             , vertical=True # remove to fix graph behavior
             )
])

if __name__ == "__main__":
    app.run_server(debug=True)
```
