### ISSUE TITLE
[BUG] Opacity update using Patch() for px.density_mapbox, not working.

### ISSUE THREAD

**Issue by OMBeau** [plotly/dash#2566]
Using python 3.11.3
```
dash                      2.10.2
dash-core-components      2.0.0
dash-html-components      2.0.0
```
    - OS: [macos]
    - Browser [Chrome]
    - Version [113.0.5672.92]

Bug Discription:

Using the new Patch() feature, Opacity attribute for px.density_mapbox will not update. 
Here is a MWE

```
from configparser import ConfigParser

import dash
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from dash import Input, Output, Patch, State, callback, dcc, html

cf = ConfigParser()
cf.read("config.ini")
MAPBOX_API_KEY = cf["mapbox"]["api_key"]


def get_heatmap(dff):
    """
    This function generates a density heatmap using latitude, longitude, and size data and returns the
    resulting plot.
    """
    heatmap = px.density_mapbox(
        data_frame=dff,
        lat="lat",
        lon="long",
        z="size",
        opacity=0.2,
    )

    heatmap.update_layout(
        height=900,
        mapbox=dict(
            accesstoken=MAPBOX_API_KEY,
            center=go.layout.mapbox.Center(lat=38, lon=-96),
            zoom=4,
        ),
    )

    return heatmap


df = pd.DataFrame(
    {
        "lat": [40, 41, 42],
        "long": [-100, -101, -102],
        "size": [3000, 5000, 2000],
    }
)

main_map = dcc.Graph(
    id="main_map",
    figure=get_heatmap(df),
)

# Using Fig State
opacity_slider_with_fig_state = dcc.Slider(
    id="opacity_slider_with_fig_state",
    min=0,
    max=1,
    step=0.2,
    value=0.2,
)


@callback(
    Output("main_map", "figure", allow_duplicate=True),
    Input("opacity_slider_with_fig_state", "value"),
    State("main_map", "figure"),
    prevent_initial_call=True,
)
def update_map_opacity_using_fig_state(opacity, current_fig):
    """
    This function updates the opacity of a map using the current figure state.
    """
    current_fig["data"][0]["opacity"] = opacity
    return current_fig


# Using Patch
opacity_slider_with_patch = dcc.Slider(
    id="opacity_slider_with_patch",
    min=0,
    max=1,
    step=0.2,
    value=0.2,
)


@callback(
    Output("main_map", "figure"),
    Input("opacity_slider_with_patch", "value"),
    prevent_initial_call=True,
)
def update_map_opacity_using_patch(opacity):
    """
    This function updates the opacity of a patch in a figure.
    """
    patched_fig = Patch()
    patched_fig["data"][0]["opacity"] = opacity
    return patched_fig


app = dash.Dash()

app.layout = html.Div(
    [
        main_map,
        html.H3("Opacity Slider using Figure State"),
        opacity_slider_with_fig_state,
        html.H3("Opacity Slider using Patch"),
        opacity_slider_with_patch,
    ]
)


if __name__ == "__main__":
    app.run_server(
        debug=True,
    )
```

Expected Behavior:

Opacity of the data should change when updated with Patch(). This is the desired behavior. However, it will not update. 
The only workaround at the moment, is the old approach of acquiring the figure State, changing opacity attribute, then pushing figure to Output.

**Comment by nickmelnikov82** [comment]
Hi!
In this case, the problem is that for Patch() to work properly, you need to specify the location of the figure.
```
def update_map_opacity_using_patch(opacity):
    patched_fig = Patch(main_map.figure)
    patched_fig["data"][0]["opacity"] = opacity
    return patched_fig
```
Also in my opinion the __getitem__ function doesn't work properly, which can also cause this bug
```
def __getitem__(self, item):
        validate_slice(item)
        return Patch(location=self._location[item], parent=self)
```

**Comment by alexcjohnson** [comment]
@nickmelnikov82 what does `patched_fig = Patch(main_map.figure)` do? That's not a syntax I've seen and if I try it I just get see an error in the devtools.

> Also in my opinion the getitem function doesn't work properly, which can also cause this bug

Can you show a simple example where this doesn't behave correctly?

@OMBeau I think this is a bug in plotly.js - if I create a similar app, change opacity with the patch slider, then in the JS console I run:
```js
gd=document.querySelector('.js-plotly-plot')
Plotly.newPlot(gd,gd.data,gd.layout)
```
I get the desired result. Which means the `Patch` is working fine, but plotly.js is not properly updating the figure with `Plotly.react`. @archmoj would you mind taking a look and move this issue to plotly.js if you agree?

**Comment by OMBeau** [comment]
@alexcjohnson Thanks for looking into this. I also had a feeling it might be plotly.js related, but did not know how to test. What else can I do to move this bug fix along? Thanks everyone!

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
