### ISSUE TITLE
error UnsupportedOperation: not writable

### ISSUE THREAD

**Issue by wheeeee** [plotly/dash#257]
I had dash running on my pc before without problems. I had to reinstall and now I can't get it to work.
Even when I use the most basic code I get the same error.
Here I used the very first code example of the tutorial with montreal and sf [https://dash.plot.ly/getting-started#installation](url)

I still always get this error:

__________________________________________________________________________

  File "<ipython-input-14-ac9d1ad4fe84>", line 25, in <module>
    app.run_server(debug=True)

  File "/Users/Wheez/anaconda3/envs/py36/lib/python3.6/site-packages/dash/dash.py", line 568, in run_server
    self.server.run(port=port, debug=debug, **flask_run_options)

  File "/Users/Wheez/anaconda3/envs/py36/lib/python3.6/site-packages/flask/app.py", line 938, in run
    cli.show_server_banner(self.env, self.debug, self.name, False)

  File "/Users/Wheez/anaconda3/envs/py36/lib/python3.6/site-packages/flask/cli.py", line 629, in show_server_banner
    click.echo(message)

  File "/Users/Wheez/anaconda3/envs/py36/lib/python3.6/site-packages/click/utils.py", line 259, in echo
    file.write(message)

UnsupportedOperation: not writable

__________________________________________________________________________

I run it on python 3.6 with anaconda and spyder and followed the installation tutorial.
I have no idea what to do. Thanks for any help.

**Comment by MrR0b** [comment]
Same issue for me. Ran fine this morning. Then ran conda updates and received the same error as wheeeeeeee  with the 1st dash tutorial. i'm assuming an issue with the flask update?!? (shrug)

Python 3.6.5 |Anaconda custom (64-bit)| (default, Apr 29 2018, 16:14:56)
   
 app.run_server(debug=True)

  File "/opt/anaconda3/lib/python3.6/site-packages/dash/dash.py", line 566, in run_server
    self.server.run(port=port, debug=debug, **flask_run_options)

  File "/opt/anaconda3/lib/python3.6/site-packages/flask/app.py", line 938, in run
    cli.show_server_banner(self.env, self.debug, self.name, False)

  File "/opt/anaconda3/lib/python3.6/site-packages/flask/cli.py", line 629, in show_server_banner
    click.echo(message)

  File "/opt/anaconda3/lib/python3.6/site-packages/click/utils.py", line 259, in echo
    file.write(message)

UnsupportedOperation: not writable

**Comment by yunqu** [comment]
Same errors seen here.

```python
UnsupportedOperation                      Traceback (most recent call last)
/opt/python3.6/lib/python3.6/site-packages/spyn/lib/dash_app.py in <module>()
----> 1 show_app(app)

/opt/python3.6/lib/python3.6/site-packages/spyn/lib/dash_app.py in show_app(app, port, width, height, offline, style, **dash_flask_kwargs)
     85                           port=port,
     86                           host="0.0.0.0",
---> 87                           **dash_flask_kwargs)

/opt/python3.6/lib/python3.6/site-packages/dash/dash.py in run_server(self, port, debug, **flask_run_options)
    566                    debug=False,
    567                    **flask_run_options):
--> 568         self.server.run(port=port, debug=debug, **flask_run_options)

/opt/python3.6/lib/python3.6/site-packages/flask/app.py in run(self, host, port, debug, load_dotenv, **options)
    936         options.setdefault('threaded', True)
    937 
--> 938         cli.show_server_banner(self.env, self.debug, self.name, False)
    939 
    940         from werkzeug.serving import run_simple

/opt/python3.6/lib/python3.6/site-packages/flask/cli.py in show_server_banner(env, debug, app_import_path, eager_loading)
    627             message += ' (lazy loading)'
    628 
--> 629         click.echo(message)
    630 
    631     click.echo(' * Environment: {0}'.format(env))

/opt/python3.6/lib/python3.6/site-packages/click/utils.py in echo(message, file, nl, err, color)
    257 
    258     if message:
--> 259         file.write(message)
    260     file.flush()
    261 

UnsupportedOperation: not writable
```

**Comment by sahil-singla-03** [comment]
Python : 3.6
Same error. But, I tried to run the code through command prompt, and it ran successfully. Sadly, somehow it is not running via jupyter notebook.

Using cmd (Ran):
![cmd](https://user-images.githubusercontent.com/35290729/40023243-0ab89726-57e8-11e8-84ce-5d9595217268.PNG)

Using jupyter (Error):
![anaconda](https://user-images.githubusercontent.com/35290729/40023277-27c81d50-57e8-11e8-8d06-15cd5d8141aa.PNG)

**Comment by qraleq** [comment]
Has anyone managed to solve the problem? I'm facing same problem on Google Colab...

**Comment by MrR0b** [comment]
Running from terminal worked for me as well. Just does not run under
spyder after updating anaconda with the latest updates. Thank you for
the tip Sahil!

**Comment by josechval** [comment]
You need to edit the echo function definition  at ../site-packages/click/utils/utils.py the file default parameter must be  sys.stdout instead of None.
And do the same for the secho function definition at  ../site-packages/click/termui.py

**Comment by Domanic** [comment]
Apperantly flask update broke it. Downgrading flask is a workaround that works:

conda install flask=0.12.2

**Comment by tejaswi240292** [comment]
i am using jupyterhub and logged in as a user and do getting this error while executing
UnsupportedOperation                      Traceback (most recent call last)
<ipython-input-47-39e83444ab61> in <module>()
----> 1 show_app(app4)

<ipython-input-40-9f14ff113713> in show_app(app, port, width, height, offline, in_binder)
     28     return app.run_server(debug=False, # needs to be false in Jupyter
     29                           host = '0.0.0.0',
---> 30                           port=port)

/usr/lib/python3.4/site-packages/dash/dash.py in run_server(self, port, debug, **flask_run_options)
    566                    debug=False,
    567                    **flask_run_options):
--> 568         self.server.run(port=port, debug=debug, **flask_run_options)

/usr/lib64/python3.4/site-packages/flask/app.py in run(self, host, port, debug, load_dotenv, **options)
    936         """Registers a blueprint on the application.
    937 
--> 938         .. versionadded:: 0.7
    939         """
    940         first_registration = False

/usr/lib64/python3.4/site-packages/flask/cli.py in show_server_banner(env, debug, app_import_path, eager_loading)

/usr/lib/python3.4/site-packages/click/utils.py in echo(message, file, nl, err, color)
    257 
    258     if message:
--> 259         file.write(message)
    260     file.flush()
    261 

UnsupportedOperation: not writable

**Comment by chriddyp** [comment]
Is everyone that is seeing this issue seeing it from the Jupyter Notebook environment? Here is the relevant thread from Flask: https://github.com/pallets/flask/pull/2787

**Comment by Sleekery** [comment]
I just reinstalled the latest anaconda on June 8 and installed Dash and plotly today. I'm getting this same error.

**Comment by Raghuvar** [comment]
@josechval 
Thanks, Jose works for me!

**Comment by KarthikMudlapur** [comment]
@josechval : Sorry,I am new to this. Could you please let me know what exactly I have to change for 'echo function definition' ? Thanks in advance.

**Comment by abe-mart** [comment]
Seeing this same error from spyder but not the command line.  Looks like the latest release of ipykernel is 4.8.2 at this time, but @josechval's fix worked.

**Comment by prateekvyas1996** [comment]
@Domanic it works, it is the best solution

**Comment by rquintino** [comment]
same issue, installed flask==0.12.2, solved it

**Comment by renanxcortes** [comment]
@josechval it worked also! You rock!

**Comment by MarcoV10** [comment]
@josechval, It worked !!! Legend!!  many thanks

**Comment by yumyumz** [comment]
I tried reverting the flask version to 0.12.2, but I am still facing an issue with it not being writable. jupyter-plotly-dash seems to be working just fine as an alternative.

**Comment by YaoChen1** [comment]
@josechval 
I have changed echo and secho file parameter from none to sys.stdout as follow, but still have the same "not writable" error.

def echo(message=None, file=sys.stdout, nl=True, err=False, color=None):

def secho(text, file=sys.stdout, nl=True, err=False, color=None, **styles):

did I mis-understood your instructions? 
I also installed the latest version of flask, but still didn't solve

Please help!!!

**Comment by ChampionTej05** [comment]
Thanks @josechval  it worked for me perfectly...

**Comment by albertalegria** [comment]
Executing py file from cmd instead of from idle worked for me.

**Comment by sathvik0** [comment]
@josechval unable to find termui.py

**Comment by josechval** [comment]
Hi.

You'll see the path to the file you must edit at the end of the error 
message.

The path is different for each implementation.

Greetings.

**Comment by Jdustin31** [comment]
@josechval That worked for me as well. Thanks!

**Comment by akhilrajarj** [comment]
when I ran app.run_server() I got the following error.
Dash app.
Could someone please help me...........fast .....So I would really appreciate some help.

Running on http://0.0.0.0:8050/
Debugger PIN: 013-646-504
Traceback (most recent call last):
  File "C:\Python34\dtest.py", line 31, in <module>
    app.run_server(debug=True,host='0.0.0.0')
  File "C:\Python34\lib\site-packages\dash\dash.py", line 1293, in run_server
    **flask_run_options)
  File "C:\Python34\lib\site-packages\flask\app.py", line 938, in run
    cli.show_server_banner(self.env, self.debug, self.name, False)
  File "C:\Python34\lib\site-packages\flask\cli.py", line 629, in show_server_banner
    click.echo(message)
  File "C:\Python34\lib\site-packages\click\utils.py", line 218, in echo
    file = _default_text_stdout()
  File "C:\Python34\lib\site-packages\click\_compat.py", line 675, in func
    rv = wrapper_func()
  File "C:\Python34\lib\site-packages\click\_compat.py", line 436, in get_text_stdout
    rv = _get_windows_console_stream(sys.stdout, encoding, errors)
  File "C:\Python34\lib\site-packages\click\_winconsole.py", line 295, in _get_windows_console_stream
    func = _stream_factories.get(f.fileno())
io.UnsupportedOperation: fileno
>>>

**Comment by ned2** [comment]
If you're not already, try running from the command line. I've seen this error come up when people to to run from some other environment like IDLE etc.

**Comment by akhilrajarj** [comment]
> If you're not already, try running from the command line. I've seen this error come up when people to to run from some other environment like IDLE etc.

It worked .Thank you so much ...spent hours analyzing site packages .

**Comment by akhilrajarj** [comment]
Is it possible to create multiple web pages and navigate  in dash???

**Comment by ned2** [comment]
@akhilrajarj, yes! See https://dash.plot.ly/urls

**Comment by vanejaime** [comment]
> You need to edit the echo function definition at ../site-packages/click/utils.py the default value for the file parameter must be sys.stdout instead of None.
> Do the same for the secho function definition at ../site-packages/click/termui.py
Hola, como hago esa modificacion?

**Comment by ThisIsVenkatesh** [comment]
@josechval Thank you so much, It's worked.

**Comment by Anand-s-cmd** [comment]
File "C:\ProgramData\Anaconda3\lib\site-packages\click\utils.py", line 259, in echo
    file.write(message)

UnsupportedOperation: not writable
