### ISSUE TITLE
Be compatible with Flask 2.3 

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [plotly/dash#2592]
dash dependency of end of support **flask** branch
```Flask>=1.0.4,<2.3.0```
since https://github.com/plotly/dash/commit/7bd5b7ebec72ffbfca85a57d0d4c19b595371a5a

The 2.3.x branch is now the supported fix branch, the 2.2.x branch will become a tag marking the end of support for that branch.
https://github.com/pallets/flask/releases

**Comment by alexcjohnson** [comment]
Closed by #2674 and released in Dash v2.14.1. For full context on our decision around Flask/Werkzeug versioning, see https://community.plotly.com/t/dash-is-planning-to-lock-flask-werkzeug-versions/74829/22
