### ISSUE TITLE
[BUG] Missing Dash import in Documentation for Upload in Dash Core Components 

### ISSUE THREAD

**Issue by manavkush** [plotly/dash#2598]
**Describe your context**
Viewing the documentation of plotly-dash. And visiting the documentation of the Upload component.

-  replace the result of `pip list | grep dash` below
```
dash                 0.42.0
dash-core-components 0.47.0
dash-html-components 0.16.0
dash-renderer        0.23.0
dash-table           3.6.0
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: MacOs
    - Browser: Chrome
    - Version: 114

**Describe the bug**

When viewing the documentation of [Dash Upload Component](https://dash.plotly.com/dash-core-components/upload), in the first example, there is a missing Dash import which is used in the code.

**Expected behavior**

There should be an import of Dash in the first line.

**Screenshots**

![image](https://github.com/plotly/dash/assets/64668859/7ccb349f-4d62-43f3-a40c-5698be8eaf30)

**Comment by alexcjohnson** [comment]
Thanks! cc @LiamConnors

**Comment by LiamConnors** [comment]
@manavkush thanks for letting us know. I've updated it. The update is live now at:
https://dash.plotly.com/dash-core-components/upload#displaying-uploaded-spreadsheet-contents
