### ISSUE TITLE
[BUG] Duplicate callback outputs error when background callbacks or long_callbacks share a cancel input

### ISSUE THREAD

**Issue by C-C-Shen** [plotly/dash#2606]
**Describe your context**
Currently I am trying to migrate a Dash application from using versions 2.5.1 to a newer one, and as suggested for Dash >2.5.1 I am moving from using ```long_callbacks``` to using the ```dash.callback``` with ```background=True```, along with moving to using ```background_callback_manager```.

Environment
```
dash                >2.5.1
```

**Describe the bug**

Updating to Dash 2.6.0+ causes previously working ```long_callbacks```  to cause Dash to give a duplicate callback output error, even though there are no duplicate outputs, the error is still present even after switching to the ```dash.callback``` with ```background=True```, and moving to using ```background_callback_manager```. This only appears when multiple background (or long_callbacks) have a shared cancel input.

Here is a [link](https://github.com/C-C-Shen/dash_background_callback_test) to a test repo that shows this, with a Dash 2.5.1 version that works and a Dash 2.6.1 version that does not.

Here is a code snippet from the example repo:
```
@callback(
    output=Output("paragraph_id_1", "children"),
    inputs=Input("button_id_1", "n_clicks"),
    prevent_initial_call=True,
    background=True,
    running=[
        (Output("button_id_1", "disabled"), True, False),
    ],
    cancel=[Input("cancel_button_id", "n_clicks")],
)
def update_clicks(n_clicks):
    time.sleep(2.0)
    return [f"Clicked Button 1: {n_clicks} times"]

@callback(
    output=Output("paragraph_id_2", "children"),
    inputs=Input("button_id_2", "n_clicks"),
    prevent_initial_call=True,
    background=True,
    running=[
        (Output("button_id_2", "disabled"), True, False),
    ],
    cancel=[Input("cancel_button_id", "n_clicks")],
)
def update_clicks(n_clicks):
    time.sleep(2.0)
    return [f"Clicked Button 2: {n_clicks} times"]
```

**Expected behavior**

Sharing the same cancel parameter between multiple callbacks should work like it does in Dash 2.5.1. Moving to Dash 2.6.0+ should probably not be causing a duplicate callback output error when no outputs are duplicated.
- if this is expected then it should be mentioned in the changelog

**Screenshots**
This an example error that is associated with the ```new.py```  in the example repo linked above

![image](https://github.com/plotly/dash/assets/71462647/13b55ca8-01b6-44ba-ae53-9cf2d17a2733)

**Comment by T4rk1n** [comment]
This has been fixed in the latest dev and will be in the next release.
