### ISSUE TITLE
ModuleNotFoundError: No module named 'dash'

### ISSUE THREAD

**Issue by spencerlawrence36** [plotly/dash#261]
Hi, I am receiving a module not found error when trying to use Dash, even though I have installed all modules per the instructions [here](https://dash.plot.ly/getting-started#installation).  The only modification I made to the instructions was pip3 rather than pip. 

When running python3 my_app.py, I receive:

`  File "my_app.py", line 1, in <module>
    import dash
ModuleNotFoundError: No module named 'dash'`

When I run pip3 install dash: 

`Requirement already satisfied: dash in /usr/local/lib/python3.6/site-packages (0.21.1)`

I have checked for duplicate files/folders named dash or dash.py, but don't see any.  I have also tried uninstalling everything and re-installing, but I received the same errors.  Any help would be much appreciated- I've been googling around for a while and haven't found anything to solve this.

**Comment by chriddyp** [comment]
@spencerlawrence36 - Did you end up figuring this one out?

**Comment by spencerlawrence36** [comment]
@chriddyp I did not unfortunately

**Comment by spencerlawrence36** [comment]
OK, update- it seemed to work when I used pip instead of pip3.  Not sure
why that is- maybe some underlying problem with Python 3

**Comment by spencerlawrence36** [comment]
Thanks for the help on this

**Comment by chriddyp** [comment]
Thanks everyone for helping out ❤️

**Comment by nik-maheshwari19** [comment]
It still doesn't work on my setup. Can anyone please help?

**Comment by DitshegoRamokolo** [comment]
pip install dash

**Comment by baariu** [comment]
In my case I had selected the wrong python interpreter at the bottom right of my VS code, thus changing the path from the virtual environment that had dash installed to a global interpreter installed on my pc that did not have dash.

**Comment by ma-gh** [comment]
for me, it was in VS Code it would not run well even with the venv selected.
from terminal, loading the venv, it works
from vs code, running the global python, it works

idk
