### ISSUE TITLE
Slider jumps when Interval updates

### ISSUE THREAD

**Issue by alkasm** [plotly/dash#263]
Whenever a `dcc.Interval` is included and you are actively pulling a `dcc.Slider` handle, it jumps back to the value you originally grabbed it at each time the `dcc.Interval` updates.

For an MCVE, just add a `dcc.Slider` to the layout of the [basic interval recipe](https://github.com/plotly/dash-recipes/blob/master/basic-interval.py):

```python
import dash
from dash.dependencies import Input, Output
import dash_core_components as dcc
import dash_html_components as html
import datetime

app = dash.Dash()

app.layout = html.Div([
    dcc.Slider(id='my-slider', min=0, max=100, value=0),
    html.Div(id='my-output-interval'),
    dcc.Interval(id='my-interval', interval=200),
])


@app.callback(
    Output('my-output-interval', 'children'),
    [Input('my-interval', 'n_intervals')])
def display_output(n):
    now = datetime.datetime.now()
    return '{} intervals have passed. It is {}:{}:{}'.format(
        n,
        now.hour,
        now.minute,
        now.second
    )


if __name__ == '__main__':
    app.run_server(debug=True)
```

This is the behavior that I get with the above; note that the slider gets reset each time the interval updates, and only comes back if the mouse moves while still holding on to the handle. If the handle is let go when it is in the original position, it stays there. An annoyance at certain interval frequencies, and mostly impossible to use at others.

![slider-behavior](https://user-images.githubusercontent.com/9651002/40762644-5e634a2c-6456-11e8-88cc-9cbeceef375d.gif)

**Comment by xhlulu** [comment]
This is caused by the sliders being indirectly affected by the interval updates, since the position resets to where it was before you start dragging it. If the callback affected by the Slider is short, try changing `updatemode` to _'drag'_, i.e.

```
app.layout = html.Div([
    dcc.Slider(id='my-slider', min=0, max=100, value=0, updatemode='drag'),
    html.Div(id='my-output-interval'),
    dcc.Interval(id='my-interval', interval=200),
])
```

If you feel the Slider and Interval interactions should be updated, you are invited to modify it on a local branch and make a PR in the [dash core components repo](https://github.com/plotly/dash-core-components/).

**Comment by alkasm** [comment]
@xhlulu Thanks for the comments!

> This is caused by the sliders being indirectly affected by the interval updates, since the position resets to where it was before you start dragging it. 

Understood.

> If the callback affected by the Slider is short, try changing updatemode to 'drag'

Indeed for some apps this might be OK, but for others, it might not. 

> If you feel the Slider and Interval interactions should be updated, you are invited to modify it on a local branch and make a PR in the dash core components repo.

Yeah. Having a hard time thinking what the interaction should be that avoids this. To be clear, I believe this is the wanted behavior:

* The `dcc.Interval` should not affect the handle position or displayed value during a mouse press
* The `dcc.Slider` value should not be updated until mouse release

So it's a case of what's *displayed* vs what values are actually *stored* by the component. Not sure if this split between the view and the data is possible with these components, but I may try to play around and see what's possible.

**Comment by xianhu** [comment]
How to solve this problem?

**Comment by vivekvs1** [comment]
@alkasm : Hey sorry for being completely out of context - but what editor and theme are you using? It looks pretty!!! I tried the One Dark Pro on VS code, it doesn't look the same

**Comment by alkasm** [comment]
@vivekvs1 The screenshot is from Sublime Text 3. It is also a One Dark (from Atom) copycat. "One Dark Material" is the name of the theme. My email is on my profile, would be best to ping me with any additional questions.
