### ISSUE TITLE
[Feature Request] Add the Flask 'request' object to the dash callback context for background callbacks

### ISSUE THREAD

**Issue by JamesKunstle** [plotly/dash#2636]
I'm using Flask-Login to manage user sessions. Getting user preferences from the OAuth content server can be a long running task, so I wanted to use a background callback. However, background callbacks don't have the 'request' or Flask-Login 'current_user' proxies available because they're not responding as a Flask thread.

If the user session cookie value was available in background callbacks I could make authenticated requests in the Celery task, which would remove a lot of hacky multi-callback message passing.

**Comment by JamesKunstle** [comment]
Update: For anyone looking for a solution, you can pass the 'request=flask.request' object into background callbacks and that seems to work.

https://community.plotly.com/t/how-to-read-cookies-inside-a-background-callback/70224/11

**Comment by alexcjohnson** [comment]
Going to copy your workaround comment into duplicate issue #2235 and close - thanks!
