### ISSUE TITLE
[BUG] High cpu usage in debug mode

### ISSUE THREAD

**Issue by 029A-h** [plotly/dash#2639]
**Describe your context**

```
dash                      2.13.0

```

    - OS: Arch Linux/Debian

**Describe the bug**

High CPU usage is observed when running the Dash server.

I traced the source of the issue to line 1720 in dash.py.

Dash is installed within a Python virtual environment located in a folder named "venv" at the root of the project package. The variable component_packages_dist (referenced at line 1720) also includes this root path. Subsequently, the entire content of the venv folder is watched by the _watch.watch([self.config.assets_folder] + component_packages_dist, ...) function. Given the large number of files in the venv directory, this results in significant CPU usage.

I suspect this is a bug because this behavior is only observed when inheriting from AIO components.

**Hotfix**

Relocate the source code to a "src" directory and retain the "venv" folder at the root level.

Minimal example to replicate the bug:

file: \_\_main\_\_.py:
```
from dash import Dash
from aio import MyAIO

Dash().run(
    debug=True,
    # regular cpu usage when dev_tools_hot_reload=False 
    dev_tools_hot_reload=True,
)
```

file: aio.py
```
from dash import html

class MyAIO(
    #  regular cpu usage when "html.Div" is commented !
    html.Div
):
    pass
```

**Expected behavior**

The server should not watch installed dependencies in the same manner when AIO components are not in use.

**Comment by T4rk1n** [comment]
What is happening in the case of aio component is that it add a new package to the component dist, meaning if you have it in the base directory and not in package folder, it add the folder in which the component was defined.

Not sure there is an easy fix for such a situation, adding a pattern exclusion for `venv` is a weak fix that might break some reloading cases. Maybe there should be a warning/error when overriding the components and it's in the same folder as the app or in `__main__.py` but that put a constraint to using the pattern.

For a real hotfix I recommend putting the components code in a package, example directories:
```
my_components/
  __init__.py
  aio.py
app.py
```

cc @alexcjohnson

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson

**Comment by olejorgenb** [comment]
IMO this can be quite annoying - the whole hot reload process saturates almost a core on my system. I'm not sure exactly how - I would expect 0.3s polling to be less intense. But if I change `dev_tools_hot_reload_watch_interval` to 10s almost all the excess CPU usage go away.

Note that just looking at `top`, both the flask/WERKZEUG "supervisor" process and the actual dash process use significantly CPU - it almost seems like the hot reload code run in both processes 🤔

**Comment by olejorgenb** [comment]
<img width="622" height="224" alt="Image" src="https://github.com/user-attachments/assets/4f09ac0f-c9f2-4e0b-aaef-d8c6030d668a" />

Yes, the watcher thread seems to run in the "supervisor" process as well. That should be an easy 50% reduction win.

Note that this is running Dash v2. Apologizes if things have changed in v3.

UPDATE: Conditionally setting `dev_tools_hot_reload=False` when `werkzeug.serving.is_running_from_reloader()` is `False` eliminates the overhead without any downsides observed so far.
