### ISSUE TITLE
[BUG] AttributeError("Dropdown' object has no attribute 'multi")

### ISSUE THREAD

**Issue by whz11** [plotly/dash#2656]
I was able to use multi parameter in Dash version 2.7.0, but it does not pass the online test on edstem. I would like to know in which version of Dash the dropdown component does not have the multi parameter and what alternative is used.
```
 dcc.Dropdown(
        id="region",
        options=regions,
        value=[],
        multi=True,
        clearable=False
    ),
```

**Comment by T4rk1n** [comment]
What do you mean by `does not pass the online test on edstem.` ?

The Dropdown always had the multi argument to allow multiple choices to be selected.
