### ISSUE TITLE
Poor docstring formatting in vscode

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash#2670]
Here's what it looks like for getting the docstring within `@callback`. Lots of white space and odd newline breaks. Could be nicer!

<img width="730" alt="image" src="https://github.com/plotly/dash/assets/1280389/288da817-8db5-40a2-9be3-36b00c867e32">

**Comment by woefulpines** [comment]
Hello, I'm a little new to open source development. I wanted to try this issue to learn a thing or two. Whats the process to be assigned it?

**Comment by alexcjohnson** [comment]
Welcome @woefulpines! We don't normally bother with assignments in the Plotly open-source repos, you can just get started. Feel free to open a PR as soon as you have some progress to commit and mention this issue, so we know you're working on it and nobody duplicates your efforts.

**Comment by woefulpines** [comment]
I was looking through the repository. I saw that some of the python generation had proper doc string formatting, I was a little confused as the doc string in the image provided doesn't match the template in the component generation in dash/development/ python component code gen file. I'll continue looking but any other perspective would be appreciated.

**Comment by T4rk1n** [comment]
@woefulpines I think the components docstring are ok, it's in the callback docstring they are indented too much:
https://github.com/plotly/dash/blob/508cce6422c952c4ec13e037aacfa2973b1f3540/dash/_callback.py#L84-L134

**Comment by woefulpines** [comment]
I'm sorry for the slow speed on this, I think I have a solution, but I was confused when it comes to opening a pull request. Would I need to apply for certain permissions to create a branch?

**Comment by sofiemor** [comment]
Hello! Is this available to work on?

**Comment by LiamConnors** [comment]
This looks like it is now resolved in VS Code

<img width="734" alt="image" src="https://github.com/user-attachments/assets/7d5d7da2-222c-4511-b664-0ca0de0247e9">

There were a number of bug fixes here that dealt with docstring formatting
https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20246100-13-june-2024-prerelease
