### ISSUE TITLE
[BUG] dash requires old version of werkzeug

### ISSUE THREAD

**Issue by GavinB-hpe** [plotly/dash#2673]
**Describe your context**

Trying to deal with a security issue reported in werkzeug - fix is in 3.0.1. However recent versions of dash seems to require an old version of werkzeug

**Describe the bug**

Recent security fix in werkzeug 3.0.1, but : 

pip install fails with : 

```
The conflict is caused by:
    The user requested werkzeug>=3.0.1
    dash 2.14.0 depends on Werkzeug<2.3.0
```

There is a 2.3.7 release, but that doesn't work either.

```
The conflict is caused by:
    The user requested werkzeug>=2.3.0
    dash 2.14.0 depends on Werkzeug<2.3.0
```

Last update of werkzeug 2.2.x was in February.

Oddly, if I fix werkzeug==3.0.1, dash 2.9.3 gets installed - but that is pretty old.

**Expected behavior**

Dash should work with recent werkzeug release branches

**Comment by alexcjohnson** [comment]
Closed by #2674 and released in Dash v2.14.1. For full context on our decision around Flask/Werkzeug versioning, see https://community.plotly.com/t/dash-is-planning-to-lock-flask-werkzeug-versions/74829/22
