### ISSUE TITLE
@cache.memoize() does not work within a callback with background=True [BUG]

### ISSUE THREAD

**Issue by leijer** [plotly/dash#2683]
within a dash background callback
```
@dash.callback(background=True, manager=background_callback_manager)
def the_callback_method():

   x = get_data_from_db_that_needs_caching(bla)
```

If the code within the callback calls another method decorated with cache memoize.

e.g.
```
@cache.memoize()
def get_data_from_db_that_needs_caching(bla):
   return lots_of_data
```

Then nothing is cached. The next time the callback runs, the result is not pulled from cache but 'get_data_from_db_that_needs_caching' executes again.

With the following cache configurations:

```disk_cache = diskcache.Cache("./cache")
background_callback_manager = DiskcacheManager(disk_cache)

cache = Cache(config={
    'CACHE_TYPE': 'SimpleCache',
    'CACHE_DEFAULT_TIMEOUT': 14400, #4 hours
    'CACHE_IGNORE_ERRORS': True,
    'CACHE_THRESHOLD' : 20
})

app = Dash(__name__, use_pages=True, suppress_callback_exceptions=True, external_stylesheets=[dbc.themes.BOOTSTRAP])
app.enable_dev_tools(dev_tools_hot_reload=False)
cache.init_app(app.server)
```

if background=False / no background callback manager, then caching of 'get_data_from_db_that_needs_caching' works fine.

dash==2.9.3

**Comment by alexcjohnson** [comment]
`SimpleCache` creates a dict within its process to store the cached values, but background callbacks are executed in multiple processes - `DiskcacheManager` starts a separate process for each one, so any cache values generated there will be lost immediately. `CeleryManager` might run subsequent jobs in the same Celery worker, but it might not, and different workers can't share cache values.

Have you tried using one of the other [`CACHE_TYPE` values](https://flask-caching.readthedocs.io/en/latest/#built-in-cache-backends)? Many of the others should be able to share across processes.

**Comment by leijer** [comment]
Hi, yes I basically realized that as well after posting. It does seem to work with a cache_type of FileSystemCache.
Hoping to use a memory cache but waiting for org to deploy elasti-cache redis atm so that will prob end up being the solution.
thanks.
