### ISSUE TITLE
Remove http request logs by default?

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash#270]
Flask prints out the http logs, like:
```
127.0.0.1 - - [11/Jun/2018 12:01:33] "POST /celery-chris/_dash-update-componentHTTP/1.1" 204 -
127.0.0.1 - - [11/Jun/2018 12:01:33] "POST /celery-chris/_dash-update-componentHTTP/1.1" 204 -
127.0.0.1 - - [11/Jun/2018 12:01:33] "POST /celery-chris/_dash-update-componentHTTP/1.1" 204 -
127.0.0.1 - - [11/Jun/2018 12:01:33] "POST /celery-chris/_dash-update-componentHTTP/1.1" 204 -
127.0.0.1 - - [11/Jun/2018 12:01:33] "POST /celery-chris/_dash-update-componentHTTP/1.1" 204 -
```

I don't think that these logs are very useful for dash developers (as we aren't writing API routes). Perhaps we should suppress these logs by default?

**Comment by ned2** [comment]
That makes sense to me. They can always be re-enabled if people want to opt-in. But the for the majority, it's probably just cluttering up the terminal where they might be printing their own debugging output etc

**Comment by chriddyp** [comment]
@T4rk1n - I'm assigning you to this one since you expressed interest in it this morning. Feel free to unassign if you don't end up taking it!

**Comment by lakshaykc** [comment]
Is this done? I still see the logs in my terminal output. I tried @chriddyp 's method in [this](https://community.plot.ly/t/prevent-post-dash-update-component-http-1-1-messages/11132) forum's post, but that doesn't change anything. Any pointers?

```
import logging

logging.getLogger('werkzeug').setLevel(logging.ERROR)

URL_BASE_PATHNAME = '/'+'example/'

server = Flask(__name__)

app = Dash(name=__name__, server=server,
           url_base_pathname=URL_BASE_PATHNAME)
```

**Comment by mccarthysean** [comment]
> Is this done? I still see the logs in my terminal output. I tried @chriddyp 's method in [this](https://community.plot.ly/t/prevent-post-dash-update-component-http-1-1-messages/11132) post, but that doesn't change anything. Any pointers?
> 
> ```
> import logging
> 
> logging.getLogger('werkzeug').setLevel(logging.ERROR)
> 
> URL_BASE_PATHNAME = '/'+'example/'
> 
> server = Flask(__name__)
> 
> app = Dash(name=__name__, server=server,
>            url_base_pathname=URL_BASE_PATHNAME)
> ```

I'm still waiting for a solution in Nov 2023. I've done the same and the logs are still clogged with useless `"POST /dash/_dash-update-component HTTP/1.1"` messages... I really wish I could disable them...
