### ISSUE TITLE
[Feature Request] Remove dependency on LGPL licensed `ansi2html`

### ISSUE THREAD

**Issue by johnthagen** [plotly/dash#2713]
**Is your feature request related to a problem? Please describe.**

Dash currently depends on [`ansi2html`](https://pypi.org/project/ansi2html/)

https://github.com/plotly/dash/blob/7527383050b6fe59a11833bbeac6f1a741436084/requires-install.txt#L13

`ansi2html` is licensed under LGPL:

- https://github.com/pycontribs/ansi2html/blob/main/LICENSE

This is not a truly permissive license, such as MIT, BSD, or Apache, which can cause headaches when distributing some private code that depends on Dash (and transitively depends on `ansi2html`).

LGPL makes it challenging for including Dash inside of a binary due to the restriction that users need to be able to have the ability to swap out the LGPL library for another of their choosing, something infeasible/very tricky for a binary distribution.

For example, this affects users of [Pyinstaller](https://www.pyinstaller.org/), [Nuitka](https://nuitka.net/), [PyOxdizer](https://pyoxidizer.readthedocs.io/en/stable/), etc. that want to package their Python code and dependencies into a stand-alone binary.

**Describe the solution you'd like**

Dash only depends on fully permissive licensed packages (such as MIT, BSD, Apache).

**Related Historical Work**

For a long time `chardet` was an LGPL package depended on by popular packages, such as `requests`:

- https://github.com/chardet/chardet/issues/36

The community has migrated to a permissively licensed package [`charset_normalizer`](https://github.com/Ousret/charset_normalizer).

One of the motivations was to ensure that the full dependency tree was permissively licensed.

**Comment by Coding-with-Adam** [comment]
Thanks for create this issue, @johnthagen. We'll make sure to take a deeper look into this after the holidays. 
cc @alexcjohnson

**Comment by alexcjohnson** [comment]
Thanks @johnthagen! `ansi2html` is used here, to give nicely-formatted tracebacks in Jupyter:

https://github.com/plotly/dash/blob/7527383050b6fe59a11833bbeac6f1a741436084/dash/_jupyter.py#L474-L476

@T4rk1n unless you can think of a simple alternative, I'd be fine with dropping color entirely. Presumably we can get a plain ASCII traceback and display it in a `<pre>` tag or something?
