### ISSUE TITLE
[Feature Request] Python 3.12 support 

### ISSUE THREAD

**Issue by graingert-coef** [plotly/dash#2736]
**Is your feature request related to a problem? Please describe.**
Currently CI only tests on 3.9 and 3.

**Describe the solution you'd like**
 I'd like to see ci run against 3.8 and 3.12

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by Coding-with-Adam** [comment]
Thank you for submitting this feature request and for the PR, @graingert-coef

**Comment by lordbami** [comment]
how do i use plotly online to test a code
