### ISSUE TITLE
hover data not updating for all counties in a choropleth map in dash

### ISSUE THREAD

**Issue by paneja4** [plotly/dash#274]
Hello,

I searched for the issue I am facing but was not able to find any reference. I am working on a very basic choropleth map for counties in Florida and trying to pull in hoverdata which I need to use for further analysis. Hoverdata is correctly updated for most counties when we hover but as seen in the attached, looks like for a few counties even though we have values against them and we see appropriate color scale coding, we do not see any hover data for them.

In the attached, we see hover labels as well as the hover data for the Broward county but neither for the Monroe county.

Thanks for help!

code:-

fips = df_sample['FIPS'].tolist()
 values = df_sample['Unemployment Rate (%)'].tolist()

fig = ff.create_choropleth(
 fips=fips, values=values,scope=['Florida'],
 title='USA by Unemployment %',
 legend_title='% unemployed'
 )

app.layout=html.Div([html.Div([dcc.Graph(id='my-graph',figure=fig)]),
 html.Div(id='my-hoverdata')])

@app.callback(
 Output('my-hoverdata', 'children'),
 [Input('my-graph', 'hoverData')])
 def callback_image(hoverData):
 return json.dumps(hoverData, indent=2)

![hoverdata](https://user-images.githubusercontent.com/10531850/41680611-a2c91b58-74c1-11e8-841c-37284f8cb394.PNG)

Thanks!

**Comment by chriddyp** [comment]
@paneja4 - Thanks for reporting! Could you create a small, reproducable example demonstrating the issue?

**Comment by paneja4** [comment]
Thanks for looking into this!

Here is an example:-
We see in the output that not all counties display hover/click info e.g:- fips= 12087 

----Code---
import plotly.figure_factory as ff
import dash
import dash_html_components as html
import dash_core_components as dcc
from dash.dependencies import Input, Output
import json
import numpy as np
import pandas as pd

app=dash.Dash()

fig = ff.create_choropleth(
    fips=[12087,12001,12011,12021,12057], values=[2500,3000,2000,2800,3500],scope=['Florida'],
     title='county plot-Florida',
    legend_title='unemployed'
)

app.layout=html.Div([html.Div([dcc.Graph(id='my-graph',figure=fig)]),
                    html.Div(id='my-hoverdata')])

@app.callback(
    Output('my-hoverdata', 'children'),
    [Input('my-graph', 'hoverData')])
def callback_image(hoverData):
    return json.dumps(hoverData, indent=2)

if __name__ == '__main__':
    app.run_server()

--------------------------------------------------
Thanks!

**Comment by bcdunbar** [comment]
This looks more like an issue with nested lists. That is, the below works in python but not in dash.

```
fig = {
    'data': [{
        'type': 'scatter',
        'x': [[1],[2],[3],4,5],
        'y': [[1],[2],[3],4,5],
        'mode': 'markers',
        'marker': {'color': 'black'}
    }]
}
```

@paneja4 a temp workaround for the above would look something like:

```
import mpu

fig = ff.create_choropleth(
    fips=[12087,12001,12011,12021,12057],
    values=[2500,3000,2000,2800,3500],
    scope=['Florida'],
    title='county plot-Florida',
    legend_title='unemployed'
)

fig['data'][5]['x'] = mpu.datastructures.flatten(fig['data'][5]['x'])
fig['data'][5]['y'] = mpu.datastructures.flatten(fig['data'][5]['y'])
```

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
