### ISSUE TITLE
When moving the cursor, it will sometimes get stuck

### ISSUE THREAD

**Issue by Spillebulle** [plotly/dash#2765]
**Describe your context**
Please provide us your environment, so we can easily reproduce the issue.¨
16 core 32 Thread dual CPU server, view selected to show all cores
Running in Docker on Ubuntu Server

-  if frontend related, tell us your Browser, Version and OS

    - OS: Windows
    - Browser Chrome
    - Version 123.0.6308.0

**Describe the bug**

When moving the cursor around on the preview, especially on machines with many cores/threads the cursor will sometimes get stuck.
Video Attached

**Expected behavior**

Graph cursor should follow the mouse and not stay in a previous position

**Screenshots**

If applicable, add screenshots or screen recording to help explain your problem.

https://github.com/plotly/dash/assets/46653946/3576cae4-67ba-4d46-9b21-7af5febac7b3

**Comment by gvwilson** [comment]
We're unable to produce - I'll close the issue, but if you can generate a reprex (reproducible example) and add it, please feel free to reopen.
