### ISSUE TITLE
Add documentation/examples using CeleryManager as background_callback_manager together with Dash Pages

### ISSUE THREAD

**Issue by roar-skinderviken** [plotly/dash#2776]
From the Dash doc, I'm able to create a simple, single-page Dash-app that uses CeleryManager. Please see main-branch in this repo:
https://github.com/roar-skinderviken/dash-celery-docker-compose

When trying to apply background_callback_manager/CeleryManager using Dash Pages, code stopped working, and I was not able to find any info (spent like two days). With DiskcacheManager, the code runs as expected. This pull request is showing what I've tried so far:
https://github.com/roar-skinderviken/dash-celery-docker-compose/pull/1

Hence, some doc/examples on how to use background_callback_manager/CeleryManager with Dash Pages would be nice.

**Comment by celia-plotly** [comment]
Hi @roar-skinderviken you can find a description of the issue and a workaround by @AnnMarieW in this minimal example:
https://github.com/AnnMarieW/dash-multi-page-app-demos/blob/main/multi_page_cache_background_callback/app.py

**Comment by roar-skinderviken** [comment]
The example code solved my problem, thanks a lot @celia-lm!

It turned out that the only change I had to do, was to keep the Dash-app in a global var.
