### ISSUE TITLE
Unsubscribe notifications from github to my email

### ISSUE THREAD

**Issue by MGBpy** [plotly/dash#278]
Hi all,

I am recieving mass notifications of thread discussiion and its a lot I dont know how to unsubscribe. When I click mute thread it say it is not apropriate for my account.
Please, help.
Thanks

**Comment by chriddyp** [comment]
See https://help.github.com/articles/subscribing-to-and-unsubscribing-from-notifications/ and https://help.github.com/articles/watching-and-unwatching-repositories/

**Comment by MGBpy** [comment]
Thanks but I ve already read that I did not help me. I am sorry!

**Comment by mchatham-fk** [comment]
Check to make sure that you are not watching the repository. That is most likely why you are receiving so many emails.

**Comment by mchatham-fk** [comment]
Also, if you are logged into a different GitHub account when you click the email link to mute the thread, you'll get the message about the action being invalid for your account.
