### ISSUE TITLE
How could I export an Excel of the data by the interactive model of dash

### ISSUE THREAD

**Issue by vegetable09** [plotly/dash#279]
The interactive of dash is great, however, I want to export an Excel from the webpage

I have read the interactive part in user guide of dash, but have no idea yet

please help me, i don't know how to persuade my boss not to use excel

**Comment by chriddyp** [comment]
See https://community.plot.ly/t/allow-users-to-dowload-an-excel-in-a-click/9410

**Comment by adrienpacifico** [comment]
For any user falling here, there is a section "Download Dataframe as Excel file"
on the dash documentation's Download page: https://dash.plotly.com/dash-core-components/download
