### ISSUE TITLE
GeoJSON

### ISSUE THREAD

**Issue by bsab** [plotly/dash#28]
Hello,
is it possible to add support for the GeoJSON format, used for geocoding including Point, MultiPoint, LineString, MultiLineString, Polygon, MultiPolygon, GeometryCollection, Feature, FeatureCollection.

**Comment by chriddyp** [comment]
@bsab - thanks for reaching out! The `scattermapbox` trace type supports all of these already. Here are examples in `plotly.js`, but the syntax is the same for the `Graph` component:

- `GeometryCollection`: https://codepen.io/chriddyp/pen/ZOgWEb
- `MultiPolygon`: https://codepen.io/chriddyp/pen/OXbEQm
- `Polygon`: https://codepen.io/chriddyp/pen/vKyrpG
- `Point`: https://codepen.io/chriddyp/pen/oLZxNw
- `MultiLineString`: https://codepen.io/chriddyp/pen/vKyryO
- `MultiPoint`: https://codepen.io/chriddyp/pen/JKbLjG
- `LineString`: https://codepen.io/chriddyp/pen/yJVEaK

**Comment by chriddyp** [comment]
Here are some examples in Python: https://plot.ly/python/scattermapbox/
and an example in particular with creating your own shape files: https://plot.ly/python/county-level-choropleth/

**Comment by fillipefeitosa** [comment]
Would be great to have native geoJson Support, as it is more a standard than a object type.

Nice framework. I am looking for a DS viewing

**Comment by chriddyp** [comment]
Brand new first-class geojson choropleths are now available in Dash 1.1.1 :tada: Many thanks to the organization that sponsored this feature :heart:  (more about how to sponsor & fund our open source work: https://plot.ly/products/consulting-and-oem).
Resources:
- Alternative base layers (mapbox token no longer needed): https://plot.ly/python/mapbox-layers/
- `densitymapbox` chart type: [https://plot.ly/python/mapbox-density-heatmaps/ ](https://plot.ly/python/mapbox-density-heatmaps/)
- `choroplethmapbox` - GeoJSON choropleths: [https://plot.ly/python/mapbox-county-choropleth/ ](https://plot.ly/python/mapbox-county-choropleth/)
- All mapping chapters: https://plot.ly/python/maps/
