### ISSUE TITLE
[Feature Request] Global set_props in backend callbacks.

### ISSUE THREAD

**Issue by T4rk1n** [plotly/dash#2803]
Add a global `dash.set_props` to be used in callbacks to set arbitrary props not defined in the callbacks outputs, similar to the clientside `dash_clientside.set_props`.

Example:

```
app.layout =  html.Div([
    html.Div(id="output"),
    html.Div(id="secondary-output"),
    html.Button("click", id="clicker"),
])

@app.callback(
    Output("output", "children"),
    Input("clicker", "n_clicks"),
    prevent_initial_call=True,
)
def on_click(n_clicks):
    set_props("secondary-output", {"children": "secondary"})
    return f"Clicked {n_clicks} times"
```

**Comment by BSd3v** [comment]
Are you thinking this will be implemented and responding back alongside the same callback method? Or will this `set_props` immediately trigger something on the clientside?

**Comment by T4rk1n** [comment]
> Are you thinking this will be implemented and responding back alongside the same callback method? Or will this `set_props` immediately trigger something on the clientside?

For regular callback I am planning on adding the new props to the callback response data, on the renderer side this update the layout at the same as the rest of the outputs.

For background callback, adding a cached set_props value to retrieve on requests and apply as side update like the set_progress, independent of the output response.
