### ISSUE TITLE
How does dash combine with flask jwt?

### ISSUE THREAD

**Issue by jaxonister** [plotly/dash#2813]
My previous project used flask jwt for authentication. After switching to dash, how can I support jwt?

**Comment by Coding-with-Adam** [comment]
hi @jaxonister
Thank you for your question. Can you please ask Dash questions on the [community forum](https://community.plotly.com/). The likelihood of getting an answer there is higher, given the amount of people active on the forum.

This issues tab in this repo is mainly used for reporting bugs or requesting new features. The forum is geared more towards educational questions.

Thank you,
