### ISSUE TITLE
Can callback be set to take effect with the current page or globally

### ISSUE THREAD

**Issue by jaxonister** [plotly/dash#2824]
Can callback be set to take effect with the current page or globally? Is this more reasonable?

**Comment by Coding-with-Adam** [comment]
hi @jaxonister
Thank you for your question. Can you please ask Dash questions on the [community forum](https://community.plotly.com/). The likelihood of getting an answer there is higher, given the amount of people active on the forum. 

This issues tab in this repo is mainly used for reporting bugs or requesting new features. The forum is geared more towards educational questions. 

than you,
