### ISSUE TITLE
[BUG] Using gunicorn to deploy a dash app with plotly-resampler in Linux, and the figure didnt render correctly

### ISSUE THREAD

**Issue by SMOKTEA** [plotly/dash#2825]
**Describe the bug**

details on https://github.com/predict-idlab/plotly-resampler/issues/300#issuecomment-2023043859

OS: Linux
Python environment:
Python version: 3.10.x
plotly-resampler environment: Dash web app (Chrome)
plotly-resampler version: 0.9.2

**Comment by gvwilson** [comment]
It appears this has been closed in another repo (see https://github.com/predict-idlab/plotly-resampler/issues/300#issuecomment-2045407637) - hope that helps.
