### ISSUE TITLE
'return pressed' event missing for Input component

### ISSUE THREAD

**Issue by mguijarr** [plotly/dash#283]
The input component only has 'change' and 'blur' events. However, another very useful event would
be to have the callback executed when [Enter] key is pressed.

There is forum discussion about this issue here:
https://community.plot.ly/t/manange-enter-event-on-button/6689/13

But there is no conclusion and I cannot find anything to know if this feature is being considered or not.

**Comment by chriddyp** [comment]
Closing in preference for the other issue created
