### ISSUE TITLE
[BUG] Use of `dash_duo` hangs Github Action until Timeout 

### ISSUE THREAD

**Issue by 2Ryan09** [plotly/dash#2836]
**Describe your context**
Github Action running on `ubuntu-latest` and unit tests run with:

```bash
pytest --capture=no --headless [package]
```

**Result of `pip list | grep dash`**
```
dash                                             2.15.0
dash_ag_grid                              31.0.1
dash-bootstrap-components     1.6.0
dash-core-components              2.0.0
dash_daq                                     0.5.0
dash-html-components              2.0.0
dash-table                                    5.0.0
dash-testing-stub                        0.0.2
```

**Describe the bug**

When running unit tests in Github Actions that involve the use of `dash_duo` to spin up an instance of the server, the action is left hanging until timeout even after all tests within pass. The final output is the summary from `pytest` saying all tests passed:

<img width="506" alt="image" src="https://github.com/plotly/dash/assets/22386684/8929ff57-90ce-46ae-a724-45b59450dddc">

Assuming this is due to some background/sub process of selenium not terminating correctly.

Have tried using `dash_duo` as a content manager, as below, without success.

```python
with dash_duo:
    do_some_test_with_dash_duo()
```

**Expected behavior**

The GitHub action to proceed once `pytest` has terminated.

**Comment by emilykl** [comment]
Hi @2Ryan09 , thanks for reporting this issue.

I haven't been able to reproduce yet -- [here's a successful workflow which uses `pytest` and `dash_duo`](https://github.com/emilykl/dash-duo-gh-actions/actions/runs/8854827818/job/24318665542).

Could you share a minimal example which triggers the hang?

Also check what `pytest` version you are using and see if you can upgrade — the above uses `pytest==8.1.2`.

**Comment by gvwilson** [comment]
@2Ryan09 hi - we're doing planning for our next work cycle - have you been able to reproduce this one? thanks - @gvwilson
