### ISSUE TITLE
[Feature Request] Is there any way to set the local and global effects of dash's callback?

### ISSUE THREAD

**Issue by jaxonister** [plotly/dash#2849]
Is there any way to set the local and global effects of dash's callback?

**Comment by T4rk1n** [comment]
> Is there any way to set the local and global effects of dash's callback?

What do you mean by global effects?

**Comment by jaxonister** [comment]
The callback only takes effect on the current page, or the entire website.

**Comment by T4rk1n** [comment]
If you want save effects from a callback to the layout of another page or for other users, you can look into integrating a database with your application.

For question such as this, it's better to ask them on the community forums https://community.plotly.com/ so you can more support from the community.
