### ISSUE TITLE
pylint warning in Visual Studio Code: module 'dash_html_components' has no 'Div' member

### ISSUE THREAD

**Issue by 2-5** [plotly/dash#285]
There are `pylint` warnings when using `dash_core_components` or `dash_html_components` objects. This makes working with `dash` in Visual Studio Code a bit annoying, since disabling those warnings is not the best thing either:

```python
import dash_core_components as dcc
import dash_html_components as html

app.layout = html.Div(children=[
    dcc.Graph()
])
```

The warnings:
```
[pylint] E1101:Module 'dash_html_components' has no 'Div' member
[pylint] E1101:Module 'dash_core_components' has no 'Graph' member
```

![2018-07-11_002424](https://user-images.githubusercontent.com/3753822/42542883-dc107b88-84a0-11e8-8bdd-338087cad924.png)

The cause is probably this piece of magic which imports the names, which `pylint` can't handle:

```python
for component in _components:
    setattr(_this_module, component.__name__, component)
    setattr(component, '_js_dist', _js_dist)
    setattr(component, '_css_dist', _css_dist)
```

**Comment by chriddyp** [comment]
Thanks for reporting! This is will be fixed in https://github.com/plotly/dash/pull/271
