### ISSUE TITLE
Dash 2.17.0 prevents some generated App Studio apps from running

### ISSUE THREAD

**Issue by hatched** [plotly/dash#2851]
https://github.com/plotly/notebook-to-app/actions/runs/8974757424/job/24647808759#step:9:1283

We've reverted to 2.16.1 for the time being.

**Comment by gvwilson** [comment]
@hatched is this still a problem?

**Comment by T4rk1n** [comment]
This was caused by the fix for dropdown  #2816, previously bugged but some dropdown in app-studio tests were using invalid value not in their options so with the fix they were getting removed and failing tests.
Tests were updated and app-studio now on version  2.17.1
