### ISSUE TITLE
[BUG] callback dataflow display flickers at certain sizes

### ISSUE THREAD

**Issue by gvwilson** [plotly/dash#2862]
Thank you so much for helping improve the quality of Dash!

We do our best to catch bugs during the release process, but we rely on your help to find the ones that slip through.

**Describe your context**
Please provide us your environment, so we can easily reproduce the issue.

-  replace the result of `pip list | grep dash` below
```
dash                      2.17.0
dash_ag_grid              31.2.0
dash-bootstrap-components 1.6.0
dash-core-components      2.0.0
dash_design_kit           1.10.2
dash-html-components      2.0.0
dash_mantine_components   0.14.3
dash-table                5.0.0
dash-testing-stub         0.0.2
```
-  if frontend related, tell us your Browser, Version and OS

    - MacOS Sonoma 14.4.1
    - Chrome 124.0.6367.158

**Describe the bug**

- Running the World Bank example from Chapter 5 of https://github.com/DashBookProject/plotly-dash
- Opened the dataflow graph showing connections between callbacks
- Display flickered: appears that scrollbars are appearing and disappearing repeatedly.

**Expected behavior**

No flickering.

**Screenshots**

Movie attached

https://github.com/plotly/dash/assets/911566/36f8962e-1722-484b-ad46-764d5ce0f319

**Comment by AnnMarieW** [comment]
@gvwilson  I tried this and can't duplicate the issue.  Can you give any more details about how to reproduce?

**Comment by gvwilson** [comment]
@AnnMarieW it seems to depend on the exact size of the browser window. When I display the world bank app on my large monitor, I can't reproduce the problem. If I drag that tab to my Mac's display, the problem reoccurs. Unfortunately, if I then open Chrome developer tools to get the size of the display port, the problem goes away again. Settings...Display tells me it's an "Apple XDR Display (P3-1600 nits)", but that doesn't give me the vertical size. My code is in the `dash-book-5` folder in https://github.com/gvwilson/dash-feederwatch if that helps.

**Comment by AnnMarieW** [comment]
Well, it works for me on all browser sizes.  Have you tried a different browser?  It works fine on Firefox for me as well.  I'm using Linux so, that might be why I can't reproduce.

**Comment by gvwilson** [comment]
Cannot reproduce with Firefox 125.0.3 on the same computer and display. Resizing the Chrome window slightly makes the problem go away. Happy to have this closed as "cannot reproduce" or "there's a simple workaround".

**Comment by Coding-with-Adam** [comment]
Hi @gvwilson 
I couldn't reproduce this either. It might make sense to close as "cannot reproduce"

**Comment by gvwilson** [comment]
Cannot reproduce on other machines.
