### ISSUE TITLE
Better error when missing dash.layout

### ISSUE THREAD

**Issue by bpostlethwaite** [plotly/dash#287]
You get `AttributeError: 'NoneType' object has no attribute 'traverse'`

see https://github.com/plotly/dash/issues/220 for a case where this has tripped someone up. I just got tripped up on this... 

We should have better error messaging for this case. 

@rmarren1 you are on better Dev support program right? Are you interested in assigning this one and tackling it at some point? Should be relatively simple fix for decent gain!

**Comment by rmarren1** [comment]
Not letting me self-assign for some reason, but I can get to this next week
