### ISSUE TITLE
CSS styling to dash debug button resets on refresh

### ISSUE THREAD

**Issue by matt-sd-watson** [plotly/dash#2875]
**Describe your context**
Please provide us your environment, so we can easily reproduce the issue.

-  replace the result of `pip list | grep dash` below
```
dash                          2.10.2
dash-ag-grid                  2.3.0
dash-auth                     2.0.0
dash-bootstrap-components     1.4.1
dash-canvas                   0.1.0
dash-core-components          2.0.0
dash-daq                      0.5.0
dash-draggable                0.1.2
dash-extensions               1.0.1
dash-google-auth              0.1.2
dash-html-components          2.0.0
dash-mantine-components       0.12.1
dash-table                    5.0.0
dash-testing-stub             0.0.2
dash-tour-component           0.0.2
dash-uploader                 0.7.0a1
jupyter-dash                  0.4.2

```
-  if frontend related, tell us your Browser, Version and OS

    - OS: Ubuntu
    - Browser; chrome
    - Version: 125.0.6422.141 (Official Build) (64-bit)

**Describe the bug**

In my dash app, I have applied CSS styling to the dash debug button so that it appears the same color as the rest of my inputs. However, on refresh, the CSS color styling resets to the default. 

**Expected behavior**

This is the CSS styling used in `assets/styles.css`, which `assets` is in the root directory where the app is: 

```

.dash-debug-menu {
  background-color: #0f4d92;
  //color: #0f4d92;
 }

 .dash-debug-menu--open {
  background-color: #0f4d92;
  //color: #0f4d92;
 }

.dash-debug-menu:hover {
  background-color: #0f4d92;
  //color: #0f4d92;
 }
```

In debug mode, the styles are applied on the fly if changed (see screenshot 1). However, on refresh, the color resets to the default. 
I apply other CSS component stylings in this sheet as well to different buttons, and all of those styles are still retained on refresh.

**Screenshots**

Correct application of CSS
![Screenshot from 2024-06-04 09-57-06](https://github.com/plotly/dash/assets/40243147/a15c3878-d9cd-445a-949a-d2566c8c3736)

On refresh, the style is reset to default

![Screenshot from 2024-06-04 09-57-23](https://github.com/plotly/dash/assets/40243147/8bb2056e-d44a-412f-8990-7fca4c44efd9)

**Comment by CNFeffery** [comment]
@matt-sd-watson Adding `!important` after those CSS rules would be better.
