### ISSUE TITLE
[Feature Request] Add `outputs` and `outputs_list` to `window.dash_clientside.callback_context`

### ISSUE THREAD

**Issue by CNFeffery** [plotly/dash#2877]
For dash's client-side callbacks, adding `outputs` and `outputs_list` for `window.dash_clientside.callback_context` will improve operational freedom in many scenarios. Currently, only the following information can be obtained in the client-side callbacks:
![image](https://github.com/plotly/dash/assets/49147660/a0728038-0b78-4ae8-84e2-1294d557fbdf)

```python
import dash
from dash import html
from dash.dependencies import Input, Output

app = dash.Dash(__name__)

app.layout = html.Div(
    [html.Button("trigger", id="trigger-demo"), html.Pre(id="output-demo")],
    style={"padding": 50},
)

app.clientside_callback(
    """(n_clicks) => {
        return JSON.stringify(Object.keys(window.dash_clientside.callback_context));
    }""",
    Output("output-demo", "children"),
    Input("trigger-demo", "n_clicks"),
    prevent_initial_call=True,
)

if __name__ == '__main__':
    app.run(debug=True)
```

**Comment by T4rk1n** [comment]
The new fields can be added here: https://github.com/plotly/dash/blob/09252f8d2f690480cc468b2e015f9e2417dc90ad/dash/dash-renderer/src/actions/callbacks.ts#L271

The data is available in `payload`.
