### ISSUE TITLE
Application fails when deploying on apache

### ISSUE THREAD

**Issue by drRussClay** [plotly/dash#289]
Hi,

I am building a dash application that I would like to run for my organization, for internal use, behind a secure firewall.  I am able to access the application using 127.0.0.1:<port> in a browser on the Web Server without issue.  However, when I attempt to access the application using a proxy-mapped Web address, the page load fails.  Using developer tools, I can see that the load progresses smoothly through the first dozen or so steps (all of the calls to the rc-slider, react, bundle.js files), but it fails when trying to load _dash-layout and _dash-dependencies.  I should note that I set app.config['routes_pathname_prefix'] = '' because without this, the application load fails even earlier (it never finds the rc-slider, react, bundle.js, etc files).

I'm stumped as to where to go from here in order to get this up and running.  Any suggestions?

Second note - I am not managing the Web Server / apache environment, and I am not super-knowledgeable in that domain.  I'm in contact with our team that manages those systems, but they asked me to dig into the issue.

Thank you.

**Comment by drRussClay** [comment]
Thank you for responding.  I'm getting 404 errors when the application tries to load from those paths (_dash-layout and _dash-dependencies).  I'm attaching a screenshot:
![dash-load_error](https://user-images.githubusercontent.com/17880365/42733784-a32e949a-8805-11e8-8fb7-5a8568834396.jpg)

**Comment by drRussClay** [comment]
I appreciate it.  I think this is going to work.  We're doing some hardware updates, so I need to wait for all of that to be sorted out in order to be 100% sure, but I will let you know. once I can test it.  Thank you!!!

**Comment by drRussClay** [comment]
I am 99% certain that ned2's comment from July 17th resolved this issue.  For unrelated reasons, we ended up switching to an IIE deployment and never fully produced a working example with Apache, but I was getting views in our development environment that led me to believe that the problem was fixed.  Sorry for leaving it open for so long.

**Comment by nidhisingh88** [comment]
> While I'm not too sure what's going on, looking through the community forums I see a post that could be relevant here: https://community.plot.ly/t/hosting-multiple-dash-apps-with-uwsgi-nginx/6758/4
> 
> Perhaps try also setting `app.config['requests_pathname_prefix'] = ''`?

Hi @ned2 ,

After updating to Dash 1.0 , your mentioned solution doesn't work anymore as it is not possible to set `
'requests_pathname_prefix'=''`. It leads to `InvalidConfig` exception
`
dash.exceptions.InvalidConfig: 'requests_pathname_prefix' needs to ends with 'routes_pathname_prefix'.
`

Any suggestions on how to fix the deployment?
Thank you.
