### ISSUE TITLE
[Feature Request] tabIndex of Div should also accept number type

### ISSUE THREAD

**Issue by CNFeffery** [plotly/dash#2891]
In the origin React, parameter `tabIndex` could accept number type:
![image](https://github.com/plotly/dash/assets/49147660/d23f2603-be1e-4109-a09e-8ab0688200e5)

It would be better to add number type support for `tabIndex`:

![image](https://github.com/plotly/dash/assets/49147660/bae3d973-6a7e-4b10-81ab-2e4193e23932)

**Comment by CNFeffery** [comment]
For example, when using other React libraries like react-slick to develop Dash component, its inner logic will change tabIndex to -1, which causes a type check error to be triggered in Dash(2.17.1):

![image](https://github.com/plotly/dash/assets/49147660/98a33382-7edf-4940-81e7-006d7bdcf15a)

**Comment by AnnMarieW** [comment]
It may be possible to fix this just by including `'tabIndex'` here:  https://github.com/plotly/dash/blob/dev/components/dash-html-components/scripts/generate-components.js#L59
