### ISSUE TITLE
React 18 warning defaultProps will be removed from function components

### ISSUE THREAD

**Issue by T4rk1n** [plotly/dash#2919]
Running an app with React 18 emit a warning that defaultProps for functions components are deprecated.

Warning message:
`Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.`

We use the defaultProps for our own components generator in either the generated react-docgen metadata or the typescript transpiler. We do not support newer version of react-docgen (5.4.3 is our last supported version) that may have a fix for this in their code. The typescript transpiler needs to be adapted.

Affected core components:
- All html components.
- dcc
  - Link
  - Loading
  - Location
  - Tab
  - Tooltip

**Comment by AnnMarieW** [comment]
I could help with this if you like.

I verified that our current version of react-docgen works when the default props are defined in the function parameter like this:

```
({ a = '1' }) => <div />;
```

https://react-docgen.dev/docs/reference/handlers/default-props-handler


I started by updating ` dcc.Loading`  and the docstrings were generated correctly.   

I'm not sure how to test this though. I don't see any warnings when I run a dash app with React 18

**Comment by T4rk1n** [comment]
> I could help with this if you like.

I verified that our current version of react-docgen works when the default props are defined in the function parameter like this:

Great, all the core components are still in js, will need to validate if it works with the typescript components or if we need to add more code.

> I'm not sure how to test this though. I don't see any warnings when I run a dash app with React 18

The deprecation starts with version 18.3.0: https://github.com/facebook/react/blob/main/CHANGELOG.md#1830-april-25-2024

That version is not listed here: https://gitkraken.dev/link/dnNjb2RlOi8vZWFtb2Rpby5naXRsZW5zL2xpbmsvci8xYTRhMzVkMWRmOTkyNDk4YmRiOTBiYTJiN2EzZTQyZWU2ZDQ3ZmQ3L2YvZGFzaC9fZGFzaF9yZW5kZXJlci5weT91cmw9Z2l0JTQwZ2l0aHViLmNvbSUzQXBsb3RseSUyRmRhc2guZ2l0JmxpbmVzPTUtNg%3D%3D?origin=gitlens

So just need to add it.
