### ISSUE TITLE
Compiling a Plotly Dash app with Nuitka the Python Compiler [Feature Request]

### ISSUE THREAD

**Issue by dmitrii-erkin** [plotly/dash#2921]
I would like to ask for help regarding the [issue](https://github.com/Nuitka/Nuitka/issues/2988). This issue results in a Plotly Dash app compiled with [Nuitka ](https://nuitka.net/) crushing with "OSError: could not get source code". I got a response from one of the Nuitka maintainers asking for help: [https://github.com/Nuitka/Nuitka/issues/2988#issuecomment-2227426370](url)

Thank you.

**Comment by T4rk1n** [comment]
Duplicate of #1885
