### ISSUE TITLE
Implementing Dual Scrollbars with AG Grid in Dash Application

### ISSUE THREAD

**Issue by jankrans** [plotly/dash#2941]
I'm working on a Dash application that uses AG Grid, and I'm trying to implement a dual scrollbar system - one at the top and one at the bottom of the grid. However, I do not know if it is possible. Is there any guidance available to this? I tried replicating the navbar, and connecting it through clientside callbacks from dash without any success.

**Comment by AnnMarieW** [comment]
Hi @jankrans 

Yes, this should be possible.  Could you please post on the [Dash Community Forum](https://community.plotly.com/) and include a minimal example with what you have tried so far?

**Comment by AnnMarieW** [comment]
Hi @jankrans 

Thanks for posting on the forum.  I'm going to close this for now, but it can be re-opened if it turns out to be a bug in either Dash or Dash AG Grid.
