### ISSUE TITLE
Scroll Appears instead of Full App in View Ouptut for Jupyter Lab - Just want it to take full height space

### ISSUE THREAD

**Issue by firmai** [plotly/dash#2945]
I have this annoying behavior that in jupyter notebook the app doesn't show in full, it always has this scroller, now I have two scrollers, I just want to scroll on the notebook, that is enough for me

![image](https://github.com/user-attachments/assets/fcba6918-b2fa-4efc-b10b-5ecbbaab7e5d)

**Comment by AnnMarieW** [comment]
Hi @firmai 
It looks like you found a workaround or a solution based on your  post in the dash-mantine-components discord.  Can you please confirm?

![image](https://github.com/user-attachments/assets/f62abd50-84a8-4628-9a2f-ac3e5cf8563a)
https://discord.com/channels/932931236882677780/932931237398581310/1271584646890655866
