### ISSUE TITLE
Excel files do not work in the `parse_contents()` function provided in the sample code for dcc.Upload

### ISSUE THREAD

**Issue by lucasprshepherd** [plotly/dash#2948]
Thank you so much for helping improve the quality of Dash!

We do our best to catch bugs during the release process, but we rely on your help to find the ones that slip through.

**Describe the bug**

I noticed this in my own code, then referred to the sample code provided and found the same issue. 

When I click the 'Drag and Drop or Select Files' button in the documentation's sample code for [dcc.Upload](https://dash.plotly.com/dash-core-components/upload) and select an Excel file, I receive the error 'There was an error processing this file.'.

**Expected behavior**

I expect the file to upload, the contents to be parsed, and a table to be generated.

**Screenshots**
![image](https://github.com/user-attachments/assets/4ae6ef47-0362-481a-ab96-769d91a2a5ec)

**Comment by AnnMarieW** [comment]
@lucasprshepherd 
Did you check the error message that's printed to the console?

> Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.

PS - need to update the dash-docs :-)

**Comment by lucasprshepherd** [comment]
@AnnMarieW Thank you for your reply!

I installed openpyxl, then received a new error message:

> Excel file format cannot be determined, you must specify an engine manually.

I edited the code to specify my engine as openpyxl like so
`df = pd.read_excel(io.BytesIO(decoded), engine='openpyxl')`
and then I received a different message:
> File is not a zip file

I haven't been able to find a solution while looking online, but I will dig deeper. I understand this issue may be out of Dash's scope as it appears to be a complication with Pandas reading the bytes object. Regardless, I think fixing the documentation to acknowledge this complication would be helpful.

**Comment by lucasprshepherd** [comment]
It turns out that I was attempting to upload an xls rather than an xlsx file. The code provided in the documentation is working with xlsx.

I apologize for the confusion!

**Comment by AnnMarieW** [comment]
Hi @lucasprshepherd.  Glad you got it working,  Note - to read xls files, be sure to install the `xlrd` library.

I'm going to close this for now.  If you have any more issues uploading a excel files or any other questions about Dash, please feel free to ask for help on the [Dash Community Forum](https://community.plotly.com/)  :-)
