### ISSUE TITLE
error in tutorial

### ISSUE THREAD

**Issue by CinnamonJP** [plotly/dash#296]
In the 3rd chapter of the Dash Tutorial, there is the bug in the content "Multiple Outputs".
https://dash.plot.ly/getting-started-part-2

```{python3}
@app.callback(
    dash.dependencies.Output('cities-dropdown', 'value'),
    [dash.dependencies.Input('cities-dropdown', 'options')])
def set_cities_value(available_options):
    return available_options[0]['value']
```
but ```available_options``` is dictionary, not list.
Probably the following is collect.
```{python3}
@app.callback(
    Output('cities-dropdown', 'value'),
    [Input('countries-dropdown', 'value')])
def set_cities_value(available_options):
    return all_options[available_options][0]
```

**Comment by chriddyp** [comment]
> but `available_options` is dictionary, not list.

I think you are confusing this with the `all_options` variable. `available_options` _is_ a list, it's the input argument of the function and so it is the list of options that the previous callback defined:

```python
@app.callback(
    dash.dependencies.Output('cities-dropdown', 'options'),
    [dash.dependencies.Input('countries-dropdown', 'value')])
def set_cities_options(selected_country):
    return [{'label': i, 'value': i} for i in all_options[selected_country]]
```

**Comment by chriddyp** [comment]
(Thanks for reporting though, appreciate you taking the time!)
