### ISSUE TITLE
performance issues when building custom components using dash-component-boilerplate

### ISSUE THREAD

**Issue by manyuemeiquqi** [plotly/dash#2966]
When using the [dash-component-boilerplate] to build my custom React component, the component becomes very sluggish. This component is related to rendering graphics on a canvas.

React framework show this

![lazy1](https://github.com/user-attachments/assets/46302f02-48bb-47a4-9a51-eeb76901a137)

and when i use in dash, show this
![lazy](https://github.com/user-attachments/assets/00fedd64-8441-4cc0-91e2-c2c9b8c2ebde)

**Comment by CNFeffery** [comment]
@manyuemeiquqi Can you attach your custom component source code

**Comment by manyuemeiquqi** [comment]
> @manyuemeiquqi Can you attach your custom component source code

https://github.com/plotly/dash/issues/2966#issuecomment-2312706349 
You can run this repo

run for dash
```
python usage.py 
```

run for react
```
npm i
npm run start
```

**Comment by CNFeffery** [comment]
@manyuemeiquqi works fine for me:

![demo](https://github.com/user-attachments/assets/417779ad-054b-44b2-8ce9-92b24ec5fe83)
