### ISSUE TITLE
Integration Testing Guide

### ISSUE THREAD

**Issue by rmarren1** [plotly/dash#297]
We should have a guide for adding integration tests to a Dash repo.

Right now the only real resource is reading the previous code and figuring it out.

A few points I think this guide should have, let me know if there are more!

1. Installing Selenium and the Chrome Driver tools. I have a gist of that process [here](https://gist.github.com/rmarren1/31fdd713482f2c697ef805d00b927b7e) that we could modify.
2. Intro to the testing lifecycle methods `setUpClass`, `tearDownClass`, `setUp`, `tearDown` so a user understands what happens before each test, after each test, once before all the tests, and once after all the tests
3. What is percy and how to take percy screenshots
4. Simple example of a test (https://github.com/plotly/dash/blob/f309cc2b8a45644004db98ffcaf0d9a72870c27d/tests/test_integration.py#L24)
5. Links to selenium resources (http://selenium-python.readthedocs.io/), although I really hate these docs and find it more helpful to just read the code (https://github.com/SeleniumHQ/selenium/tree/master/py). Maybe we can 
6. Link to https://docs.python.org/3.6/library/unittest.html#module-unittest, maybe a separate list of the most useful `self.assert...` functions.

**Comment by T4rk1n** [comment]
For the selenium docs, there is also https://seleniumhq.github.io/selenium/docs/api/py/api.html, I find those docs easier to navigate.

**Comment by rmarren1** [comment]
It might also make sense to include commonly used patterns when testing dash apps, are there any common quirks specific to dash apps anyone would like to share here?

For example, I have found it difficult to chain clicks together since after one click, the `_dash-loading-callback` div appears over the entire screen with the highest z-index, so all other elements are 'unclickable' according to Selenium. I made a special click function to deal with this error.

```
    def super_click(self, element):
        try:
            element.click()
        # The loading element is covering the screen
        except exceptions.WebDriverException:
            try:
                loading_callback = self.driver.\
                    find_element_by_css_selector('._dash-loading-callback')
            # The loading element left the screen during the time it took to run the find_element_by_css_selector function
            except exceptions.NoSuchElementException:
                element.click()
                return
            self.wait.until(EC.staleness_of(loading_callback))
            element.click()
```

**Comment by rmarren1** [comment]
forgot to tag @plotly/dash

**Comment by chriddyp** [comment]
Related #390

**Comment by chriddyp** [comment]
This file has some simple assertion and wait examples with the new selenium api: https://github.com/plotly/dash-component-boilerplate/blob/eaceef1c87665ac5bb07701e876654382e603aef/tests/test_render.py

**Comment by rmarren1** [comment]
Maybe these can be useful: https://circleci.com/docs/2.0/creating-orbs/

**Comment by gwdekker** [comment]
Great idea! Would love to have this for `pytest` as well, not only `unitTest`.

**Comment by byronz** [comment]
most of the discussion in this issue is included in  https://dash.plot.ly/testing
