### ISSUE TITLE
[QUESTION] Does Dash have an official logo

### ISSUE THREAD

**Issue by CNFeffery** [plotly/dash#2984]
Does Dash have a purely official logo image that doesn't include the word `plotly`.

**Comment by T4rk1n** [comment]
The default favicon doesn't have the name: https://github.com/plotly/dash/blob/dea1c622dc8cd8949468dc98f81848cf2c4837e6/dash/favicon.ico

**Comment by CNFeffery** [comment]
@T4rk1n Is there a clear version? This one works as a favicon, but it's too vague to be used as an article or video to promote dash.

**Comment by gvwilson** [comment]
cc @ndrezn

**Comment by CNFeffery** [comment]
@gvwilson Is there any new progress on this issue.

**Comment by ndrezn** [comment]
We don't have a Dash logo without Plotly -- primarily we use this logos (light/dark):
![New Plotly_logos-03](https://github.com/user-attachments/assets/c82024d7-2d38-4720-837f-b65c24a47dd7)
![New Plotly_logos-04](https://github.com/user-attachments/assets/decd728c-9c2b-4224-9bc4-a0cd8358a282)

Feel free to use in any of your projects!
