### ISSUE TITLE
[REGRESSION] Number of no_output must match number of outputs in dash==2.18.0

### ISSUE THREAD

**Issue by ndrezn** [plotly/dash#2986]
In `dash==2.18.0`, the number of `no_update ` returned must match the number of outputs. This is not true in earlier versions of Dash.

This can be resolved by making `no_update` match but is a regression.

Consider:
```python
import dash
from dash import html, dcc, Input, Output, no_update

# Initialize the Dash app
app = dash.Dash(__name__)

# Define the layout
app.layout = html.Div(
    [
        dcc.Input(id="input-box", type="text", value=""),
        html.Button("Submit", id="button"),
        html.Div(id="output-1", children="Output 1 will be displayed here"),
        html.Div(id="output-2", children="Output 2 will be displayed here"),
    ]
)


# Callback with two outputs
@app.callback(
    Output("output-1", "children"),
    Output("output-2", "children"),
    Input("button", "n_clicks"),
    Input("input-box", "value"),
)
def update_outputs(n_clicks, value):
    if n_clicks is None:
        return no_update
    return "Hello", "world!"


# Run the app
if __name__ == "__main__":
    app.run_server(debug=True)
```

Dash 2.18
![Screenshot 2024-09-05 at 1 37 26 PM](https://github.com/user-attachments/assets/8a802c4a-9cdf-405b-84d0-af9bcd2759d6)

Dash 2.17
![Screenshot 2024-09-05 at 1 37 44 PM](https://github.com/user-attachments/assets/20c4d4db-8323-42fc-8d9f-2452095dcf8a)

**Comment by johnkangw** [comment]
@ndrezn Thanks for fixing this! I was wondering why in our apps we were receiving errors for this component.

**Comment by leo-smi** [comment]
> @ndrezn Thanks for fixing this! I was wondering why in our apps we were receiving errors for this component.

Does this replace the old sintax "PreventUpdate"?

**Comment by ndrezn** [comment]
@leo-smi no, no relation to `PreventUpdate`.
