### ISSUE TITLE
generated content of parameter comments for `oneOfType` is confusing

### ISSUE THREAD

**Issue by CNFeffery** [plotly/dash#2990]
```
dash                 2.17.1
dash-core-components 2.0.0
dash-html-components 2.0.0
dash-table           5.0.0
```

The format of the component parameter documentation is confusing for complex parameters with the type format set to `oneOfType`, for example:

![image](https://github.com/user-attachments/assets/c5bb20b1-0001-40b7-bd51-b267f7ea422f)

Generate documentation result, The order and structure from the source code are lost:

![image](https://github.com/user-attachments/assets/4fe39912-7f54-4e0e-a477-e8e60aa8610f)

I hope to generate parameter documentation that is consistent with the order and structure in the source code.

**Comment by T4rk1n** [comment]
I think this is sorted here: https://github.com/plotly/dash/blob/a77dec611f8bdf0a3087085c057e58ff1cb1ac25/dash/development/_py_components_generation.py#L560
Code probably predates default ordered dict, so the keys were sorted to have a consistent output. Should be removed and keep the order it was defined in the metadata.json

**Comment by CNFeffery** [comment]
@T4rk1n I noticed that the `dash-generate-components` cli has a parameter named `--keep-prop-order`.
![image](https://github.com/user-attachments/assets/0972aada-72eb-4375-a9fb-6d863cd99717)

should the code below follow this parameter to change?
https://github.com/plotly/dash/blob/a77dec611f8bdf0a3087085c057e58ff1cb1ac25/dash/development/_py_components_generation.py#L560
![image](https://github.com/user-attachments/assets/da6cf4a5-764c-41cb-8186-b8a79994b0f5)

**Comment by T4rk1n** [comment]
> should the code below follow this parameter to change?
No I don't think it should follow that variable is for the main props but the bug here is with the shapes, I think just removing `sorted(list(` part would be enough.
