### ISSUE TITLE
No data displayed in examples

### ISSUE THREAD

**Issue by rthompsonj** [plotly/dash#3]
I cannot get any data to display for any of the examples in either Chrome or Safari on OSX.  The browser comes up, shows the graphs, but they are empty.

![dash](https://cloud.githubusercontent.com/assets/543053/11226571/6fa2ff4c-8d46-11e5-96eb-f759e12b64bb.png)

**Comment by eyadsibai** [comment]
+1

**Comment by danaki** [comment]
+1

**Comment by jonmoore** [comment]
I saw the same and was getting a javascript error "Cannot call method 'onClose' of null".  Updating the version of socket.io in base.html to "//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.7/socket.io.js" got the examples running for me.  

This was on Windows 7, with eventlet installed.

**Comment by rthompsonj** [comment]
@jonmoore 's solution worked for me on OSX, thanks!

**Comment by chriddyp** [comment]
thanks for checking this out @rthompsonj @jonmoore @danaki @eyadsibai ! A new version of Dash is now available, completely rewritten, and it works a lot better than this old prototype :)
