### ISSUE TITLE
dropdowns ignore values when options are not set

### ISSUE THREAD

**Issue by areed145** [plotly/dash#3004]
Thank you so much for helping improve the quality of Dash!

We do our best to catch bugs during the release process, but we rely on your help to find the ones that slip through.

**Describe your context**
dash==2.18.1
dash-bootstrap-components==1.6.0
dash-extensions==1.0.15
dash-cytoscape==1.0.1
plotly==5.24.1

-  replace the result of `pip list | grep dash` below
```
dash                            2.18.1
dash-bootstrap-components       1.6.0
dash-core-components            2.0.0
dash_cytoscape                  1.0.1
dash_dangerously_set_inner_html 0.0.2
dash-extensions                 1.0.15
dash-html-components            2.0.0
dash-leaflet                    1.0.15
dash-mantine-components         0.12.1
dash-quill                      0.0.4
dash-svg                        0.0.12
dash-table                      5.0.0
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: Windows
    - Browser: Edge
    - Version: 128.0.2739.67

**Describe the bug**

On my dashboard I use dropdowns where the options are dynamically updated based on the underlying dataset. In order to facilitate quick links throughout the site, I use URL params to pre-set the dropdowns to certain values.

It has been a very simple solution for me for years now.

Up to dash 2.16.1, this all works fine. On any higher versions the pre-set value is ignored.

**Expected behavior**

I am able to set the value of a dropdown without an options set, and once the options are updated, the pre-set value shows up as selected if it is part of the options set.

**Minimal Example***

```
from dash import Dash, dcc, html, Input, Output, callback

preset_value = 'NYC' # from url params

app = Dash(__name__)
app.layout = html.Div([
    dcc.Store(id='demo-store'),
    dcc.Interval(id='demo-interval', interval=1000, n_intervals=0),
    dcc.Dropdown(
        value=preset_value, 
        options=[], 
        id='demo-dropdown'
    ),
])

@callback(
    Output('demo-store', 'data'),
    Input('demo-interval', 'n_intervals')
)
def update_output(n):
    return [{'label': i, 'value': i} for i in ['NYC', 'MTL', 'LA']]

@callback(
    Output('demo-dropdown', 'options'),
    Input('demo-store', 'data')
)
def update_output(data):
    return data

if __name__ == '__main__':
    app.run(debug=True)
```

**Comment by AnnMarieW** [comment]
I thought this issue was odd, so I did a little investigating...

I could verify that the code posted above works in 2.16.1 but not in dash>=2.17.0  I found this surprising, because I didn't expect it to work in either version.  Typically, with options that are updated dynamically -- like when a country dropdown updates a city dropdown --  the `value` is updated to include only those defined in the options.   So when `options=[]` I would expect the preset value to be changed to None.


Oddly, this works in the current version - when options are undefined:

```python
    dcc.Dropdown(
        value=preset_value, 
     #   options=[], 
        id='demo-dropdown'
    ),
```

I'm not sure if this is a bug or not, but as a workaround, in order to preset a value, recommend defining it like this:

```python
   dcc.Dropdown(
        value=preset_value, 
        options=[preset_value], 
        id='demo-dropdown'
    )
```

**Comment by areed145** [comment]
Thanks for the response. I realized the same thing yesterday. I went ahead and removed out all the options definitions from various dropdowns in my project and it is now functioning as I hoped. I will keep in mind your workaround in case it is a bug and stops working in the future....

**Comment by skloibhofer** [comment]
Thanks a 1000, was stuck with this problem also when syncing the dropdown and the url with a circular callback. Finally working again!
