### ISSUE TITLE
Dynamic local Folder with static server possible?

### ISSUE THREAD

**Issue by charlydwi** [plotly/dash#3013]
Hello chriddyp,

maybe you have a hint for me, how I can use dynamic foldernames with your solution?
I like to choose a folder and Image(name) and open the image.

I try this:
image_directory = 'F:\\Datenbrille\\assets\\'
static_image_route = '/static/'
app = dash.Dash()
app.layout = html.Div([
    dcc.Dropdown(id='Teilnummer', options=[
        {'label': 'A_C_224', 'value': 'A_C_224'},
        {'label': 'A_C_225', 'value': 'A_C_225'},
    ], value='A_C_224'  ),
    dcc.Dropdown(id='Bildname', options=[
        {'label': 'CL_green_BP1_Visu_cropped.jpg', 'value': 'CL_green_BP1_Visu_cropped.jpg'},
        {'label': 'CL_blue_BP4_Visu_cropped.jpg', 'value': 'CL_blue_BP4_Visu_cropped.jpg'},
    ], value='CL_green_BP1_Visu_cropped.jpg'  ),
    html.Img(id='image')  
])
@app.callback(
    Output('image','src'),
    Input('Teilnummer', 'value'),
    Input('Bildname', 'value'),
)
def update_image_src(Teilnummer_value, Bildname_value):
    completePathName=static_image_route + Teilnummer_value +"/SaveData4/"+ Bildname_value
    return completePathName

# Add a static image route that serves images from desktop
@app.server.route('{}<image_path>.jpg'.format(static_image_route))
def serve_image(image_path):
    image_name = '{}.png'.format(image_path)
    return flask.send_from_directory(image_directory, 'CL_green_BP1_Visu_cropped.jpg')
if __name__ == '__main__':
    app.run_server(debug=True)

I try many variations about the path, but it never found the images...
Has anyone a tip?

590     return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
        werkzeug.utils = <module 'werkzeug.utils' from 'C:\\Users\\danie\\anaconda3\\Lib\\site-packages\\werkzeug\\utils.py'>
        directory = 'C:\\Users\\danie\\JupyterOrdner\\static'
        path = 'A_C_224/SaveData4/CL_green_BP1_Visu_cropped.jpg'
        kwargs = {'max_age': None}
    591         directory, path, **_prepare_send_file_kwargs(**kwargs)
    592     )

File ~\anaconda3\Lib\site-packages\werkzeug\utils.py:587, in send_from_directory(
    directory=r'C:\Users\danie\JupyterOrdner\static',
    path=r'C:\Users\danie\JupyterOrdner\static/A_C_224/SaveData4/CL_green_BP1_Visu_cropped.jpg',
    environ={'HTTP_ACCEPT': 'image/avif,image/webp,image/png,image/svg+xml,image/*;q=0.8,*/*;q=0.5', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br, zstd', 'HTTP_ACCEPT_LANGUAGE': 'de,en-US;q=0.7,en;q=0.3', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_DNT': '1', 'HTTP_HOST': '127.0.0.1:8050', 'HTTP_PRIORITY': 'u=5, i', 'HTTP_REFERER': 'http://127.0.0.1:8050/', 'HTTP_SEC_FETCH_DEST': 'image', 'HTTP_SEC_FETCH_MODE': 'no-cors', ...},
    **kwargs={'_root_path': r'C:\Users\danie\JupyterOrdner', 'max_age': <bound method Scaffold.get_send_file_max_age of <Flask '__main__'>>, 'response_class': <class 'flask.wrappers.Response'>, 'use_x_sendfile': False}
)
    585 try:
    586     if not os.path.isfile(path):
--> 587         raise NotFound()
    588 except ValueError:
    589     # path contains null byte on Python < 3.8
    590     raise NotFound() from None

NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

_Originally posted by @chriddyp in https://github.com/plotly/dash/issues/71#issuecomment-313222343_

**Comment by charlydwi** [comment]
I solved it this way with get_asset_url :
app = dash.Dash()

app.layout = html.Div([
    dcc.Dropdown(id='Teilnummer', options=[
        {'label': 'A_C_224', 'value': 'A_C_224'},
        {'label': 'A_C_225', 'value': 'A_C_225'},
    ], value='A_C_224'  ),
    dcc.Dropdown(id='Bildname', options=[
        {'label': 'CL_green_BP1_Visu_cropped.jpg', 'value': 'CL_green_BP1_Visu_cropped.jpg'},
        {'label': 'CL_blue_BP4_Visu_cropped.jpg', 'value': 'CL_blue_BP4_Visu_cropped.jpg'},
    ], value='CL_green_BP1_Visu_cropped.jpg'  ),
    #html.Img(src=app.get_asset_url('A_C_224/SaveData4/CL_green_BP1_Visu_cropped.jpg'))
    html.Img(id="image")

])
@app.callback(
    Output('image','src'),
    Input('Teilnummer', 'value'),
    Input('Bildname', 'value'),
)
def update_image_src(Teilnummer_value, Bildname_value):
    completePathName=Teilnummer_value +"/SaveData4/"+ Bildname_value
    print("completePathName:",completePathName)
    return app.get_asset_url(completePathName)

if __name__ == '__main__':
    app.run_server(debug=True)

**Comment by gvwilson** [comment]
Hi - we are tidying up issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. For tech support and "how-to" questions, please post in our community forum https://community.plotly.com/. Thank you - @gvwilson
