### ISSUE TITLE
[BUG] Make a minor release updating plotly bundle to 2.35.2 or newer to fix maplibre

### ISSUE THREAD

**Issue by pupitetris** [plotly/dash#3016]
I got the pip package of dash, version 2.18.1.

Would it be possible to make a new release that updated plotly from 2.35.0 to 2.35.2? We have an offline application, and the bundled plotly (v2.35.0) is trying to get maplibre-gl.js from some CDN, instead of having it bundled, and they fixed that on plotly 2.35.2, but the latest stable dash release has not been updated accordingly.

Best regards,
Arturo

**Comment by T4rk1n** [comment]
The plotly.js version we serve has been decoupled from dash some time ago, it now resolves to the `plotly.py` version.
It was updated here: https://github.com/plotly/plotly.py/commit/d52f2a263901fcf9734e626aae69228038505359 and should be available in plotly.py 5.24.1

**Comment by pupitetris** [comment]
OMG, perfect! Thanks for the reply, I'll check it then.
