### ISSUE TITLE
output not being updated by callback

### ISSUE THREAD

**Issue by DSAGRO3F** [plotly/dash#3022]
Thank you so much for helping improve the quality of Dash!

We do our best to catch bugs during the release process, but we rely on your help to find the ones that slip through.

**Describe your context**
Google Colab Pro

-  replace the result of `pip list | grep dash` below
```
dash                             2.18.1
dash-bootstrap-components        1.6.0
dash-core-components             2.0.0
dash-html-components             2.0.0
dash-table                       5.0.0
```
-  if frontend related, tell us your Browser, Version and OS

**Describe the bug**

Using app Dash with dcc.Input() callback I noticed output is not updated accordingly. No error message.
If I input "hello" in text box, output should be updated to "hello", instead initial value remains.

**Expected behavior**

If I input "hello" in text box, output should be updated to "hello", instead initial value remains..

**Screenshots**

```
app = JupyterDash(__name__)

port = 8053

"""authenticate using token"""
!ngrok config add-authtoken 2S97GELhJsGO---token---koHb24wsr #Configure authtoken

"""Open a ngrok tunnel to the HTTP server"""
public_url = ngrok.connect(port).public_url
print(f'* ngrok tunnel {public_url} -> http://127.0.0.1:{port}')


"""configure app layout"""
app.layout = html.Div(
    children=[
        html.H5('change value in text box'),
        
        html.Div(["input: ", dcc.Input(id='my-input', value='initial-value', type='text')]),
        
        html.Div(id='my-output'),
    ])


"""define callback"""
@app.callback(
    Output(component_id='my-output', component_property='children'),
    Input(component_id='my-input', component_property='value')
)
def update_input(text_input):
  return print(f'output: {text_input}')

if __name__ == "__main__":
  app.run_server(debug=False, jupyter_server_url=public_url, port=port, mode='external')
```

**Comment by gvwilson** [comment]
@T4rk1n does the example code look good to you?

**Comment by T4rk1n** [comment]
@DSAGRO3F You are returning print from the callback here:
```
def update_input(text_input):
  return print(f'output: {text_input}')
```
print doesn't return anything.

**Comment by DSAGRO3F** [comment]
**Many thanks!**
