### ISSUE TITLE
[Feature Request] The console displays the back-end interface for the actual request

### ISSUE THREAD

**Issue by xiaoxiaoimg** [plotly/dash#3026]
dash Back-end request interface, the browser console does not print the request interface, such as login request, but the browser does not display the login request interface, only such interfaces as update-component, how to display the actual interface in the control?

**Comment by gvwilson** [comment]
Hi - we are tidying up issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. For tech support and "how-to" questions, please post in our community forum https://community.plotly.com/. Thank you - @gvwilson
