### ISSUE TITLE
Error with reserved word pattern in dash-generate-components when converting Ant Design React components

### ISSUE THREAD

**Issue by C0deBeez** [plotly/dash#3079]
Description: When trying to convert Ant Design React components to Dash components using dash-typescript-components-boilerplate, the following errors are triggered:

ERROR: "_internalDisableMenuItemTitleTooltip" matches reserved word pattern: /^_.*$/
ERROR: "_internalRenderMenuItem" matches reserved word pattern: /^_.*$/
ERROR: "_internalRenderSubMenuItem" matches reserved word pattern: /^_.*$/

Details: After investigating, it appears that the error is due to the underlying dependency in Ant Design's menu implementation, which relies on the [rc-menu project](https://github.com/react-component/menu). Specifically, rc-menu has _internalRenderMenuItem and other _internal related methods that match Dash's reserved word pattern /^_.*$/.

Since these methods are part of the rc-menu internals, it appears Dash's reserved word patterns are causing conflicts during the conversion process.

Steps to Reproduce:

Set up a Dash project with dash-generate-components.
Attempt to convert Ant Design components (especially Menu related components) using dash-generate-components.
Observe the errors related to reserved word patterns in the output.
Expected Behavior: The components should be generated without error or provide a way to handle these internal methods without conflicting with Dash’s reserved patterns.

Environment:

Dash version: 2.18.2
Ant Design version: 5.22.0
rc-menu version: 9.16.0

Would it be possible to provide an option to ignore or handle internal methods that start with an underscore (_) to avoid conflicts with Dash's reserved patterns?

Thank you for your assistance!

**Comment by T4rk1n** [comment]
Are you trying to just generate component from existing components?
That is not really supported, a Dash component != react component, you should create wrappers for the component to wrap and only allow json props to be passed around. The `_` is reserved for private usage inside the python components.

For antd components, there is this library already existing: https://github.com/CNFeffery/feffery-antd-components
