### ISSUE TITLE
Clash between Dash and flask_wtf.csrf, possibly a bug.

### ISSUE THREAD

**Issue by Aso1977** [plotly/dash#308]
Dash app fails, when it is created and called through the flask sever. Dash 'Callback’s are not working and gives Post Request 400. Any help appreciated.

A sample code to reproduce the problem is below. I use latest Dash 0.22.0, Dash HTML Components 0.11.0, and Dash Core Components 0.24.1, and Flask 1.0.2:

```
# file 'simple_flask.py'

from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_wtf.csrf import CSRFProtect


# Initialise flask App 
app = Flask(__name__, instance_relative_config=True)
#app.config.from_object('config.Config')

db = SQLAlchemy()         # SQLAlchemy
csrf_protect = CSRFProtect()

def set_app(app):

    # Setup WTForms CSRFProtect
    app.secret_key = 'My super secret key'
    csrf_protect.init_app(app)

    # Setup Flask-SQLAlchemy
    db.init_app(app) 
     
    # run in app context
    with app.test_request_context():
        db.create_all()

        from simple_dash import create_dash
        create_dash(app)


if __name__ == '__main__':
    set_app(app)
    app.run(host='127.0.0.1', port=5002, debug=True) 


## file 'simple_dash.py'

import dash
import dash_html_components as html
import dash_core_components as dcc

def create_dash(app):
    dash_app = dash.Dash(__name__, server=app, 
                        #static_folder='/static',
                        #url_base_pathname='/app/oga/', 
                        # csrf_protect=False
                        )
    dash_app.layout = html.Div([
        dcc.Dropdown(
            id='my-dropdown',
            options=[
                {'label': 'New York City', 'value': 'NYC'},
                {'label': 'Montreal', 'value': 'MTL'},
                {'label': 'San Francisco', 'value': 'SF'}
            ],
            value='NYC'
        ),
        html.Div(id='output-container')
    ])


    @dash_app.callback(
        dash.dependencies.Output('output-container', 'children'),
        [dash.dependencies.Input('my-dropdown', 'value')])
    def update_output(value):
        return 'You have selected "{}"'.format(value)
```

The missing reference after loading the page and any subsequent change in drop-down is: “POST /_dash-update-component HTTP/1.1” 400

**Comment by T4rk1n** [comment]
Just tried the code without the SQLAlchemy stuff, it worked.

**Comment by Aso1977** [comment]
dear @T4rk1n thanks for looking at the issue. 
When you say without sqlalchemy stuff, do you mean commenting out the following lines:
```
#from flask_sqlalchemy import SQLAlchemy
#db = SQLAlchemy()         # SQLAlchemy
       #db.init_app(app) 
           #db.create_all()
```
Sorry, but it didn't work for me even after commenting out those lines.
Do you use the same versions? I included mine in the question.

**Comment by T4rk1n** [comment]
@Aso1977 Yes, But I also commented `csrf_protect = CSRFProtect()` and `csrf_protect.init_app(app)`, uncommenting those lines gives the 400 errors, so the problem is with the `CSRFProtect`.

**Comment by Aso1977** [comment]
It was idneed CSRFProtect stuff not sqlalchemy. I commented out those lines and it worked.
A crash between Dash and CSRFProtect extension of flask, is it something to report as bug?
Thanks for pointing me in the right direction.

**Comment by Aso1977** [comment]
Dash can be excluded from CSRF in flask as following:
`csrf_protect = CSRFProtect()
csrf_protect._exempt_views.add('dash.dash.dispatch')`

**Comment by T4rk1n** [comment]
Closing as a solution was found https://github.com/plotly/dash/issues/308#issuecomment-412653680
