### ISSUE TITLE
[BUG] scrollTo Jumps the Scroll Bar

### ISSUE THREAD

**Issue by georgiossalon** [plotly/dash#3085]
-  `pip list` 
```
dash                 2.18.2
dash_ag_grid         31.2.0
dash-core-components 2.0.0
dash-html-components 2.0.0
dash-table           5.0.0
```
-  Browser, Version and OS

    - OS: win11
    - Browser chrome
    - Version 130.0.6723.119 (Offizieller Build) (64-Bit)

**Describe the bug**

Adjusting the scrollTo and selecting a row makes the scroll bar to jump back to the position set in my callback. The callback is getting triggered only once though in the beginning.

**Expected behavior**

Since the callback is not getting triggered when selecting a row, the scroll bar should stay where I manually scrolled.

**Code**

```
import dash_ag_grid as dag
from dash import Dash, html, Input, Output
import pandas as pd


app = Dash(__name__)

df = pd.read_csv(
    "https://raw.githubusercontent.com/plotly/datasets/master/ag-grid/olympic-winners.csv"
)


columnDefs = [
    {"headerName": "Row", "valueGetter": {"function": "params.node.rowIndex"}}
] + [{"field": c} for c in df.columns]

app.layout = html.Div(
    [
        dag.AgGrid(
            id="grid-scroll-to-start",
            columnDefs=columnDefs,
            rowData=df.to_dict("records"),
            dashGridOptions={'rowSelection': 'single', 'animateRows': False}
        ),
    ]
)

@app.callback(
    Output('grid-scroll-to-start', 'scrollTo'),
    Input('grid-scroll-to-start', 'rowData')
)
def handle_scroll_to(rowData):
    #dummy logic
    row = rowData[100]
    return {'data': row}


if __name__ == "__main__":
    app.run(debug=True)
```

**Comment by AnnMarieW** [comment]
Hi @georgiossalon 

I can't seem to replicate the issue - Your app seems to work fine [on PyCafe](https://py.cafe/snippet/dash/v1?pycafe-app-view=false&pycafe-edit-enable=true#c=H4sIAF4fPWcEA41V227jNhD9FUH74AS1ZMtOnMSAgF6CbvelC7QL9CEKBFqiLK4pkiWpOErgf-8ZSXaaxQZZOXA8M2duhzPUc1jokofrUDRGWx-UzNU52-ZbK8qAOcjbTFVWN70lGFG3-D0Nat_IafBJmdZPg8-tx_9MjQjDFBwogikzRR9mTJD2nmd5rljD8_yc9GUFtSljy1mZF-7hLFMBniysvTduPZtZto-3wtftpnXcFlp5rnxc6GZmpPaym5XMM8e9mzXMeW5nbBtR-TMtu8aIItoLpbh1MYJnYab6rJkqtGwbdcsrh_x3Q9JnZEUZ3P6J-rJwjSr-0vssnOLHA5Mt_8g9MpAF0KpVhRdaDUDDLGtcrEBnbPX-kyr5YxYeDpm6D34K7ggvuCwJXByCStugCIQKygqtUCXunqoCS7FknW49qiKC41txpGQskh4cS_zL9iO6HG3HR5RpFlL3kSusljLyOnKeWY8mXiNf-k9ffn6DQR-3IDdFkV7npSj8WRZaXmhbuiw8_wZNE0IlfTbEikufJ_D_m0veszRZBxMn1FbyyTSYMAwK8xzsOhh-Z9JxMNWHwXOMDEr60_qZaCmYlBtW7MaOh4E7m3yvWcowqL7oyTFYP6hv48deJ0iIv5JXQY0ZljwfsLnXZyPkfD0E_FC2TdMFUm9FMWgAwLGNsLtkPkcDvZ771qrgeUKjin6BQLf0EVVw3IYgTTFGed4wofIcczL4Uuu2VWcl37Tb9Itt-Xk4xSH82wrLG6yCC9chUY-i8R2N05-pYQWB9Z2hDScrJNP5WivIptOlKHn0MI8XqziBaRi8cP0cPmBfcGbheoFUWnucE6nHSBbSNCxqIUvLAbo7WTzbYBNh3IvS1-E6uZxPw0aofwZxOUh_cLGtkYdEUcKtEpL_iqjY79-w3yCA2zcyEDTaDFhADKO4YXi4P0xPmFMV3wsA44sfkWu68LXvi_n_LMf-0b9OY9-n4f3Wx1bea_vY8asCTmnqMWpydfkjOXGFQc3ke0mPOMpKn8O0px8Dd3ePadHFjkSKAoKA_4CVcfU64OzqZsFYdZUUm6LaXCXXyyIpFit-vbqcXyyTTG2kUDtu0zSJb-I5LmNuvahEmi7mi4t4ES-gqplFd5HStmFSPBF6GS97kxTFLk2v4yS-GqYejnFyTTaSjjsAhwTBEL_X4tri-GqMVnSg5DM_GemufdMIoiVP08tBVUnmkH4JaYkNLhUjAZUM7z4pNlHDPaNdpyLhBZN3JVNbbnXbx-6r-irUV7Yg54QiNczuWuNYhVRoJ77M8N5yPmKuU4XQRNaK3FTbmI4krO3Fcc9PQYeXIhULJkH1cc3pdZqm2PVBSZdAhBJ564UkZ5xDbLTzFKLzT1DRUQBLS4Ay-gzgE3ZcZ7YTaks1LKkEnFNrvNYSoNUNOoabE49kT_qSMSCsEB5lURpSdAYBIv4IC900cESyPrp_Gpg75m-tBKVLSt_Xvud298RxF_YnsMrUkzDoDJPRuzsnMxUe_gOk-Cet2QgAAA)
