### ISSUE TITLE
Dash Doesn't Show the graph

### ISSUE THREAD

**Issue by iocohen** [plotly/dash#315]
Thanks so much for your interest in Dash! 
Before you post an issue here, could you quickly search for your 
issue in the Dash community forum? https://community.plot.ly/c/dash
GitHub issues are great for bug reports, the community forum is great for
implementation questions. When in doubt, creating feel free to just post the
issue here :)
Thanks, and welcome to Dash!

Hi there,
I installed dash on my mac. i did all the steps perfectly. the tool is ok and have no errors. My issue is that when i run the server, the charts are not created. I see that is running and when i go to the local host i see only the HTML without any other graph. This is my below code.
This is what i see in my terminal `127.0.0.1 - - [01/Aug/2018 22:01:04] "POST /_dash-update-component HTTP/1.1" 200 -` I have a MacBook Air and is not showing the graphs with all their change.

```


import dash
import dash_core_components as dcc
import dash_html_components as html
import pandas as pd
pd.core.common.is_list_like = pd.api.types.is_list_like

import time
from collections import deque
import plotly.graph_objs as go
import random

app = dash.Dash('vehicle-data')



max_length = 50
times = deque(maxlen=max_length)
oil_temps = deque(maxlen=max_length)
intake_temps = deque(maxlen=max_length)
coolant_temps = deque(maxlen=max_length)
rpms = deque(maxlen=max_length)
speeds = deque(maxlen=max_length)
throttle_pos = deque(maxlen=max_length)

data_dict = {"Oil Temperature":oil_temps,
"Intake Temperature": intake_temps,
"Coolant Temperature": coolant_temps,
"RPM":rpms,
"Speed":speeds,
"Throttle Position":throttle_pos}

def update_obd_values(times, oil_temps, intake_temps, coolant_temps, rpms, speeds, throttle_pos):

    times.append(time.time())
    if len(times) == 1:
        #starting relevant values
        oil_temps.append(random.randrange(180,230))
        intake_temps.append(random.randrange(95,115))
        coolant_temps.append(random.randrange(170,220))
        rpms.append(random.randrange(1000,9500))
        speeds.append(random.randrange(30,140))
        throttle_pos.append(random.randrange(10,90))
    else:
        for data_of_interest in [oil_temps, intake_temps, coolant_temps, rpms, speeds, throttle_pos]:
            data_of_interest.append(data_of_interest[-1]+data_of_interest[-1]*random.uniform(-0.0001,0.0001))

    return times, oil_temps, intake_temps, coolant_temps, rpms, speeds, throttle_pos

times, oil_temps, intake_temps, coolant_temps, rpms, speeds, throttle_pos = update_obd_values(times, oil_temps, intake_temps, coolant_temps, rpms, speeds, throttle_pos)

app.layout = html.Div([
    html.Div([
        html.H2('Vehicle Data',
                style={'float': 'left',
                       }),
        ]),
    dcc.Dropdown(id='vehicle-data-name',
                 options=[{'label': s, 'value': s}
                          for s in data_dict.keys()],
                 value=['Coolant Temperature','Oil Temperature','Intake Temperature'],
                 multi=True
                 ),
    html.Div(children=html.Div(id='graphs'), className='row'),
    dcc.Interval(
        id='graph-update',
        interval=100),
    ], className="container",style={'width':'98%','margin-left':10,'margin-right':10,'max-width':50000})


@app.callback(
    dash.dependencies.Output('graphs','children'),
    [dash.dependencies.Input('vehicle-data-name', 'value')],
    events=[dash.dependencies.Event('graph-update', 'interval')]
    )
def update_graph(data_names):
    graphs = []
    update_obd_values(times, oil_temps, intake_temps, coolant_temps, rpms, speeds, throttle_pos)
    if len(data_names)>2:
        class_choice = 'col s12 m6 l4'
    elif len(data_names) == 2:
        class_choice = 'col s12 m6 l6'
    else:
        class_choice = 'col s12'


    for data_name in data_names:

        data = go.Scatter(
            x=list(times),
            y=list(data_dict[data_name]),
            name='Scatter',
            fill="tozeroy",
            fillcolor="#6897bb"
            )

        graphs.append(html.Div(dcc.Graph(
            id=data_name,
            animate=True,
            figure={'data': [data],'layout' : go.Layout(xaxis=dict(range=[min(times),max(times)]),
                                                        yaxis=dict(range=[min(data_dict[data_name]),max(data_dict[data_name])]),
                                                        margin={'l':50,'r':1,'t':45,'b':1},
                                                        title='{}'.format(data_name))}
            ), className=class_choice))

    return graphs



external_css = ["https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css"]
for css in external_css:
    app.css.append_css({"external_url": css})

external_js = ['https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js']
for js in external_css:
    app.scripts.append_script({'external_url': js})


if __name__ == '__main__':
    app.run_server(debug=True)
```

**Comment by iocohen** [comment]
hi there, the examples work fine. after a waiting period of 10 mins i had the graphs showing, but without any motion in them. They were static and basically that was it. In normal case they should move, change every 1 second or so. Is this due to my laptop?

**Comment by chriddyp** [comment]
> after a waiting period of 10 mins i had the graphs showing, but without any motion in them. They were static and basically that was it. In normal case they should move, change every 1 second or so. Is this due to my laptop?

It's hard to say. If you reduce the code into something more minimal, it might become clearer. Alternatively, start from the ground-up with this example: https://dash.plot.ly/live-updates

**Comment by Jeffrey9130** [comment]
I can reproduce this issue in my dash app as well if I reduce the interval to 100 ms. 

I think it's about the minimum loading/setup time of plotly in live-update applications. If the app update interval is too small, I guess the plotly plot will be stuck in the loading/setup phase always and therefore show nothing eventually.

BTW, I found the following thread in which a kind of syntax trick can improve and loading/setup speed of plotly and therefore allow a much smaller interval period. Works well in my app.
[https://community.plot.ly/t/callback-interval-100-doesnt-work-slow/23338](url)

**Comment by tpt5cu** [comment]
Hey guys, so I encountered a similar error when using Dash on a Raspberry Pi. I was able to fix the problem increasing the interval to 1*10000 ms. Not sure why it worked, but it does.

**Comment by yesdeepakmittal** [comment]
I changed the **Event** with **Input** and removed the square brackets to keep both **Input()** into the same list. Though after that I had not found an error in the code the output is not as same as desired. I am hard trying to find the bug but not getting where the problem is. Someone please look at the above code and tell me where is the bug.

**Comment by alexcjohnson** [comment]
@yesdeepakmittal this is an obsolete issue using old pre-v1 syntax. Anyway github works best for bug reports and feature requests - for usage help I'd recommend posting a complete app to https://community.plotly.com/c/dash/16
