### ISSUE TITLE
Generate_class issue with plotly dahs 0.23.1 and dangerously_set_inner_html

### ISSUE THREAD

**Issue by bnouvelbmll** [plotly/dash#321]
After updating to 0.23.1, the following code importing "dangerously_set_inner_html" does not work anymore. It seems that some field may be missing / not set correctly and that this is field is used in an exec statement. The same import is working with previous release.

Error:
```
In [1]: import dash_dangerously_set_inner_html
Traceback (most recent call last):

  File "/miniconda/envs/.../lib/python3.4/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-8721236f3c51>", line 1, in <module>
    import dash_dangerously_set_inner_html

  File "/miniconda/envs/////lib/python3.4/site-packages/dash_dangerously_set_inner_html/__init__.py", line 10, in <module>
    'dash_dangerously_set_inner_html'

  File "/miniconda/envs/.../lib/python3.4/site-packages/dash/development/component_loader.py", line 51, in load_components
    namespace

  File "/miniconda/envs/...lib/python3.4/site-packages/dash/development/base_component.py", line 441, in generate_class
    exec(string, scope)

  File "<string>", line 27
    def __init__(self, children=None, , **kwargs):
```

**Comment by T4rk1n** [comment]
I think `dash_dangerously_set_inner_html` has to be updated. You can downgrade to dash `0.22.0` in the meantime.

**Comment by chriddyp** [comment]
Hm, did the latest IDE stuff break the existing components? If so, we should make a new release that is backwards compatible, i.e. doesn't break the existing components that are out there.

**Comment by T4rk1n** [comment]
Yes, I think there is some errors in how the classes generates the constructor arguments you can see the invalid part 
`def __init__(self, children=None, , **kwargs):` have an extra comma. I also have problems with `dash_flow_example` #319.

**Comment by chriddyp** [comment]
@rmarren1 - Could you check this out too?

**Comment by T4rk1n** [comment]
I found the issue with `dash_flow_example`

https://github.com/plotly/dash/blob/1f27bac61fc30f0480f585bebbc43c861cb5adb3/dash/development/base_component.py#L376-L381

Should change the `endswith('-*')` with `endswith('*')`, cause the dash_flow_example has `data_*`.

**Comment by T4rk1n** [comment]
For the dangerously set inner html, we have to remove the `,` on this line:
https://github.com/plotly/dash/blob/1f27bac61fc30f0480f585bebbc43c861cb5adb3/dash/development/base_component.py#L369

There is already a ',' before the kwargs at

https://github.com/plotly/dash/blob/1f27bac61fc30f0480f585bebbc43c861cb5adb3/dash/development/base_component.py#L306

**Comment by T4rk1n** [comment]
I got this bit working:

```python
    if 'children' in props:
        prop_keys.remove('children')
        default_argtext = "children=None "
        # pylint: disable=unused-variable
        argtext = 'children=children, **args'
    else:
        default_argtext = ""
        argtext = '**args'
    default_argtext = ", ".join([default_argtext] if default_argtext else [] +
        [('{:s}=Component.REQUIRED'.format(p)
          if props[p]['required'] else
          '{:s}=Component.UNDEFINED'.format(p))
         for p in prop_keys
         if p and not p.endswith("*") and
         p not in ['dashEvents', 'fireEvent', 'setProps']]
    )
```
But it's not pretty.
