### ISSUE TITLE
How can I run Dash automatically?

### ISSUE THREAD

**Issue by fdkssdks** [plotly/dash#329]
Hello,

I am trying to figure out how can I run Dash automatically instead of going to the local server manually.

Is there a parameter like below?

```app.run_server(debug=True, start_browser=True)```

Thanks

**Comment by fdkssdks** [comment]
@T4rk1n Not even if I use Flask or something similar?

**Comment by T4rk1n** [comment]
You can open the browser with just python:

```
if __name__ == '__main__':
    import webbrowser
    webbrowser.register('chrome', None)
    webbrowser.open('http://localhost:5050')
    app.run_server(port=5050, debug=True, threaded=True)
```
