### ISSUE TITLE
Can't override external CSS without !important

### ISSUE THREAD

**Issue by rmarren1** [plotly/dash#331]
Not really a bug, just something I noticed that we should be aware of.

In the new `assets` directory approach to including CSS, [external stylesheets always appear beneath local stylesheets.](https://github.com/plotly/dash/blob/7361db52690810891c5f68501eda1d71043cb777/dash/dash.py#L333-L336)

There doesn't seem to be a way to switch this (at least that I'm aware of), so a user can't override CSS from external libraries without !important since external scripts will always be imported last and thus take precedence. I think this is a very common use case (e.g. import bootstrap, then add your own CSS to customize a small part of bootstrap) and users shouldn't have to manually add !important to all their stylesheets or change the specificity of selectors to get it to work.

**Comment by rmarren1** [comment]
@T4rk1n

**Comment by T4rk1n** [comment]
I'll change the assets to go after external.

**Comment by chriddyp** [comment]
> I'll change the assets to go after external.

Yeah, that seems like it would be the right behaviour.

**Comment by chriddyp** [comment]
And if the user really needs to customize it, then they can override the index
