### ISSUE TITLE
Git tagged releases would help downstream packagers

### ISSUE THREAD

**Issue by moorepants** [plotly/dash#332]
Hi,

I've been packaging dash (and dash related python packages) for conda forge. We currently have to manually check for mismatches in dependencies and other install details wrt to the released packages on PyPi. It would be very helpful for me if git tags were used to tag releases and the tags pushed to github. I can then do diffs between releases to quickly see if any changes warrant updating the conda forge packaging spec.

Would it be possible to encourage dash developers that make releases to tag and push these to github on release? The commands are:

```
$ git tag -a v0.3.9 -m "Tagged v0.3.9"
$ git push --tags
```

Thanks for your consideration.

**Comment by byronz** [comment]
@Marc-Andre-Rivet  is this something that we already put in the release process? I think yes

**Comment by moorepants** [comment]
It does seem like this is now done.
