### ISSUE TITLE
Functions as layout no longer work (_validate_layout throws error)

### ISSUE THREAD

**Issue by phifre** [plotly/dash#334]
Hello,

since the `_validate_layout` method was introduces in dash.py setting functions as layout no longer works, because calling `traverse()` on an function fails. 
Setting a function as layout is necessary to make the app reload the layout on page reload as described in the [documentation](https://dash.plot.ly/live-updates).

Currently the fastest option is to remove the `_validate_layout` call in the `_setup_server` method.

**Comment by phifre** [comment]
Checking if the layout is a function and then calling it once to validated the returned layout would be an appropriate fix.

**Comment by rmarren1** [comment]
Will have a fix for this soon, this was introduced in 0.22.0 via https://github.com/plotly/dash/pull/294 so you can downgrade to 0.21.1 for now or edit as above.

**Comment by phifre** [comment]
Actually it was introduced with version 0.24.2 in commit [https://github.com/plotly/dash/commit/e190768d7ae3db400e744d6d1d594969aacd2bf9](e190768d7ae3db400e744d6d1d594969aacd2bf9) so 0.24.1 works fine.

**Comment by T4rk1n** [comment]
Yes, it's from the disallow duplicate ids of 0.24.2.

@rmarren1  Can fix this with `self._layout_value().traverse()` instead of `self.layout.traverse()` or taking the `self._cached_layout` value.

**Comment by rmarren1** [comment]
Ah right, forgot more was added to validation. Thanks for the detailed report @phifre !

**Comment by rmarren1** [comment]
Fix for this released in `dash==0.26.1` [see changelog](https://github.com/plotly/dash/blob/master/CHANGELOG.md#0261---2018-08-26)
