### ISSUE TITLE
error running in jupyter notebook - SystemExit: 1

### ISSUE THREAD

**Issue by eloiup** [plotly/dash#34]
the current error msg/log at jupyter notebook isnt really helpful

![image](https://user-images.githubusercontent.com/20978596/27486860-4fa2416a-5808-11e7-8c77-7275ea456f22.png)

**Comment by chriddyp** [comment]
Hm... I'm not sure what's going on here or why Jupyter isn't showing the error message.

**Comment by chriddyp** [comment]
I wonder if it's an issue with the interactive debug mode. Perhaps try removing the `debug=True` statement there. Just run `app.run_server(debug=False)`.

**Comment by chriddyp** [comment]
Setting `debug=False` seems to work for me:
![image](https://user-images.githubusercontent.com/1280389/27590930-36748554-5b1e-11e7-805e-d4f2766c3890.png)

**Comment by eloiup** [comment]
ill test it. but running the same code as a .py script instead of a notebook worked fine

**Comment by chriddyp** [comment]
> but running the same code as a .py script instead of a notebook worked fine

Yeah. It seems like Jupyter notebook and the Flask debug mode don't work together. I'd recommend running it as a regular python script with debug mode for now. With `debug=True`, the script will automatically re-run itself when you make changes to the code; you can just refresh the browser without re-starting the script.

**Comment by eloiup** [comment]
if i run it in a jup notebook in aws, it runs, but doesnt print out any msgs with access address.

**Comment by chriddyp** [comment]
Here's a solution from the community for running Dash in Jupyter / Ipython notebooks: https://community.plot.ly/t/can-i-run-dash-app-in-jupyter/5235/2

**Comment by legendkt100** [comment]
It is not running on sypder with the same error and debug = False

**Comment by vasili111** [comment]
Works in Spyder with `debug = False`.

**Comment by Subhamp7** [comment]
if( __name__ == "__main__"):
    app.run(debug=True, use_reloader=False)

try this works perfectly fine for Spyder

**Comment by john101h** [comment]
> I wonder if it's an issue with the interactive debug mode. Perhaps try removing the `debug=True` statement there. Just run `app.run_server(debug=False)`.

OMG! It works. Thank u
