### ISSUE TITLE
API Question: Why was a dict-based API chosen (for things like Div parameters) instead of a Class-based one?

### ISSUE THREAD

**Issue by dougthor42** [plotly/dash#35]
**Note:** this may be more of a `plotly` API question. Please let me know if I should post there instead.

I'm running through the dash tutorial and an API design question popped into my mind: Why are most parameters dictionaries? It seems that many things could be made easier to write via a class.

For example, the `style` item is currently defined like so:

```python
go.Layout(margin={'l': 40, 'b': 40, 't': 10, 'r': 0})
```

Personally I find dicts a pain to write because of all the quotes and alternating between colon and comma. With my naive understanding of the (admittedly awesome) dash package is that it should be possible to do:

```python
go.Layout(margin=Margin(40, 40, 10, 0))
```

Another example are the `axis` values:

```python
go.Layout(xaxis={'type': 'log', 'title': 'GDP Per Capita'})

# vs
go.Layout(xaxis=Axis('GDP Per Capita', 'log'))
```

In my opinion, the primary advantage of doing class-based things is auto-completion and discovery. I find it much harder to determine which keys are available in a dict than it is to find what args a class initializer takes.

Of course, I can always write the `Margin` class and others myself and use that (and I plan to do so), but I was just curious as to why this wasn't a design choice from the beginning.

Thanks,

**Comment by chriddyp** [comment]
Good question @dougthor42 ! You can actually use both. There is a full set of classes in the `plotly.graph_objs` module:

```
go.Layout(xaxis=go.XAxis(type='log', title='GDP Per Capita'))
```

will produce the same thing as:
```
dict(xaxis=dict(type='log', title='GDP Per Capita'))
```

which is also the same as
```
{'xaxis': {'type': 'log', 'title': 'GDP Per Capita'}}
```

**Comment by dougthor42** [comment]
Oh that's awesome! I'll have to really look over `plotly` docs then.

Thanks for the info. I'm really looking forward to using `dash` a bunch.
