### ISSUE TITLE
Allow Dash children lists to be tuples also.

### ISSUE THREAD

**Issue by rmarren1** [plotly/dash#358]
Right now we only accept objects which are instances of `collections.MutableSequence` as lists in Dash.

Is there a reason we are this specific? A tuple will be serialized just fine.

**Comment by chriddyp** [comment]
> we only accept objects which are instances of collections.MutableSequence as lists in Dash.

By 'only accept', do you mean in the `plotly.utils.PlotlyJSONEncoder` or in the `base_component.Component`?

**Comment by rmarren1** [comment]
`PlotlyJSONEncoder` [looks like it allows tuples](https://github.com/plotly/plotly.py/blob/1cd50977e1feb6c2c91fe160b3c6c188dc92e715/plotly/utils.py#L205).

It looks like the problem is just that the base component traversal uses `isinstance(x, collections.MutableSequence)` to check if an object is a list [here](https://github.com/plotly/dash/blob/7219b3d9f827e95bbbace801aa955b8c21ff8ffe/dash/development/base_component.py#L224) and [here](https://github.com/plotly/dash/blob/7219b3d9f827e95bbbace801aa955b8c21ff8ffe/dash/development/base_component.py#L19) and [here](https://github.com/plotly/dash/blob/7219b3d9f827e95bbbace801aa955b8c21ff8ffe/dash/development/base_component.py#L148) and [here](https://github.com/plotly/dash/blob/7219b3d9f827e95bbbace801aa955b8c21ff8ffe/dash/development/base_component.py#L257).

I think if we just change these lines to `collections.Sequence` we should get support for tuples.

**Comment by chriddyp** [comment]
![image](https://user-images.githubusercontent.com/1280389/45005203-107cdc00-afc0-11e8-929e-4c34c66aa325.png)

Yeah, I don't think that we're using any of those extra `MutableSequence` methods (`append`, `reverse`, `extend`, `pop`, `remove`, `__iadd__`), so I think we're good. (https://docs.python.org/2/library/collections.html#collections-abstract-base-classes)

**Comment by rmarren1** [comment]
I'll make a PR and see how it works out

**Comment by rmarren1** [comment]
It turns out making Dash children a tuple instead of a list (e.g. `html.Div(children=(html.P("Hello"), html.P("World"))`) already works, but the `Component.traverse()` method does not work correctly in these instances so some things break like layout validation, JSON serializable error checking, etc

**Comment by rmarren1** [comment]
strings are instances of `collections.Sequence`, so to get the desired behavior I just added `tuple` to the list of accepted types, e.g. `isinstance(x, (tuple, collections.MutableMapping))` instead of `isinstance(x, collections.MutableMapping)`
