### ISSUE TITLE
routes_pathname_prefix needs to end with '/' [Question]

### ISSUE THREAD

**Issue by StephaneKazmierczak** [plotly/dash#359]
Hello, 

First I would like to thank you very much for dash, it is been really usefull to me to create UI around python datascience project. 
However, I recenlty update from dask=0.21.1 to 0.26.3 and my app don't want to run anymore I am getting: 

`dash.exceptions.InvalidConfig: `routes_pathname_prefix` needs to end with `/``

and this is the line which is the problem:

`app_analysis = dash.Dash(name="app_analysis", server=server, url_base_pathname="/analysis.html")`

I have been looking at the updates in the github but I don't really get it

**Comment by StephaneKazmierczak** [comment]
ok I found that putting / at the end of my pathname worked, but it is not a prefix right? and I confused why it is require now

**Comment by T4rk1n** [comment]
You can find the change in the changelog of version 0.25.0:
 
https://github.com/plotly/dash/blob/master/CHANGELOG.md#0250---2018-08-14
