### ISSUE TITLE
Need to update `pexpect>=4.3` in all Dash repos for 3.7 compatibility

### ISSUE THREAD

**Issue by rmarren1** [plotly/dash#360]
See here: https://github.com/plotly/plotly.py/issues/1142

This is an issue in `ipython`, which breaks `plotly`, which in turn breaks `dash` :cry:

**Comment by T4rk1n** [comment]
I don't think it's ipython but the version we have in the requirement that is trouble because I have added tests for 3.7 and I needed to remove the version of some the requirements for it to work.

**Comment by rmarren1** [comment]
It breaks with the latest versions of `plotly` and `ipython`

**Comment by rmarren1** [comment]
Looks like the problem is just that we need `pexpect>=4.3`. We should make changes
* [here](https://github.com/plotly/dash/blob/7219b3d9f827e95bbbace801aa955b8c21ff8ffe/requirements.txt#L28)
* [here](https://github.com/plotly/dash-html-components/blob/22ebfa8f41acb284ab07ec1c5f119ed17679a421/requirements.txt#L33)
* [here](https://github.com/plotly/dash-core-components/blob/557d2fd4987c437265d220f71ee69c2d0616526c/requirements-locked.txt#L38)

**Comment by rmarren1** [comment]
ipython now installs an updated version
