### ISSUE TITLE
assets_url_path is broken.

### ISSUE THREAD

**Issue by T4rk1n** [plotly/dash#373]
Changing the `assets_url_path` breaks the assets includes, they are still requesting `/assets/` instead of the changed `assets_url_path`.

**Comment by gjackson12** [comment]
This still seems like an issue from what I'm seeing.

**Comment by ned2** [comment]
@gjackson12, I can't see any issue. Changing the `assets_url_path` does indeed change the URL of the assets files for me. Maybe check you're on the latest version of Dash? otherwise, can you provide a minimal working example of the issue?
