### ISSUE TITLE
404 not found for meta og:image for  https://plot.ly/

### ISSUE THREAD

**Issue by jbampton** [plotly/dash#376]
Hello everyone wasn't sure where to post this issue.

Using the Facebook Sharing Debugger you can see what websites look like in a preview.

https://developers.facebook.com/tools/debug/sharing

For https://plot.ly/ you have a 404 not found for the meta og:image tag which means you don't get a nice image preview if the link is shared.  From my experience you can have up to 5 different og:image tags which enables you to select from one of the five images when sharing a website link.

http://ogp.me/  - Open Graph protocol

![plotly-404-no-preview](https://user-images.githubusercontent.com/418747/45257105-fb4ee580-b3e3-11e8-8206-0a6ec1a0a921.png)

**Comment by chriddyp** [comment]
Thanks! I'll share this upstream.
