### ISSUE TITLE
Change names of our bundles

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash#384]
Right now, we name all of our bundles `bundle.js`. We should rename these bundles the name of the JS library to make debugging / inspecting errors in the console easier. That is, across:
- [x] In [dash-renderer](https://github.com/plotly/dash-renderer/): `bundle.js` ➡️  `dash_renderer.min.js`
- [x] In [dash-core-components](https://github.com/plotly/dash-core-components/): `bundle.js` ➡️ `dash_core_components.min.js`
- [x] In [dash-html-components](https://github.com/plotly/dash-core-components/): `bundle.js` ➡️  `dash_html_components.min.js`
- [x] In [dash-component-boilerplate](https://github.com/plotly/dash-component-boilerplate): `bundle.js` ➡️ `the_package_name.min.js`

These changes can happen in the individual component libraries, e.g. here: https://github.com/plotly/dash-core-components/blob/29d9f1d366b64a2759fbfc74d184a0561288284d/dash_core_components/__init__.py#L42-L47
we shouldn't need to change anything in `dash` itself. I'm creating this issue in `dash` just to organize things across the repos 😺

**Comment by T4rk1n** [comment]
@chriddyp 

Should I do it in the serve dev bundle PRs while I'm at it ?

**Comment by chriddyp** [comment]
sure!
