### ISSUE TITLE
When using the dash instance as the return value of route in Flask, dash.Dash (server=?)

### ISSUE THREAD

**Issue by cixingzhici** [plotly/dash#386]
When I use the flask app instance current_app, it's error

```
@main.route('/dash1', methods=['GET', 'POST'])

@login_required

def dash1():
    
    dash_app = dash.Dash(__name__, server=current_app)
    
    dash_app.layout = html.Div(‘dash1’)
    
    return dash_app.index()
```

AssertionError: A setup function was called after the first request was handled. This usually indicates a bug in the application where a module was not imported and decorators or other functionality was called too late. To fix this make sure to import all your view modules, database models and everything related at a central place before the application starts serving requests.

**Comment by T4rk1n** [comment]
You cannot do this, dash uses a `before_first_requests` handler, this can only be added before the server has started.
