### ISSUE TITLE
Best python version

### ISSUE THREAD

**Issue by FabianoLothor** [plotly/dash#388]
What is the best python version for use Dash?

**Comment by chriddyp** [comment]
We support and test 2.7, 3.6, 3.7. If you're starting fresh, I recommend starting with Python 3.6 or 3.7.

**Comment by FabianoLothor** [comment]
Great @chriddyp. Exists some test using some ubuntu version and python 3.7?

I'm configuring the server.

**Comment by FabianoLothor** [comment]
> We support and test 2.7, 3.6, 3.7. If you're starting fresh, I recommend starting with Python 3.6 or 3.7.

Great @chriddyp. Exists some test using some ubuntu version and python 3.7?

I'm configuring the server.
