### ISSUE TITLE
Multiple Apps from a single server

### ISSUE THREAD

**Issue by pyenthu** [plotly/dash#40]
Outstanding work Chris. Exploring this still.
One question. Is it possible to launch a routing mechanism with different single page apps from a single server instance?
What I am looking for is different web pages with the same functionality.
Say xxx.yyy.com/dash1, xxx.yyy.com/dash2. xxx.yyy.com/dash3 etc?

**Comment by bmike78** [comment]
pyenthu,

You could front end all of your Flask instances with Apache.  I have some example code here:
https://github.com/bmike78/apache-flask-wsgi

Using SSL and individual virtualenvs are not necessary, but there as examples.

**Comment by chriddyp** [comment]
Good question @pyenthu  and thanks for the reference @bmike78 !

There is unofficial support for routes right now, and I'm using them to render the multi-page dash docs currently at https://plot.ly/dash.

I wrote about this a little bit in the community forum, so I'll just reference that here: https://community.plot.ly/t/dash-on-multi-page-site-app-route-flask-to-dash/4582

In short: multi-page URLs are possible now but the API is going to change. A new solution for URLs that treats the `URLBar` as it's own component will be available soon. I'll keep this issue open to track the progress.

**Comment by Volodymyrk** [comment]
I believe #70 addresses this pretty well

**Comment by chriddyp** [comment]
Support for URLs has been added through the `dcc.Link` and `dcc.Location` components. See https://plot.ly/dash/urls for a tutorial :)

**Comment by nirvana-msu** [comment]
This is really useful. When is it going to be included in PyPI package? I would though that the recent release candidate 0.17.8rc3 should include it, but it doesnt for some reason.
