### ISSUE TITLE
Snap package support (Feature Request)

### ISSUE THREAD

**Issue by Mikerr1111** [plotly/dash#400]
I was thinking the setup and install process for Ubuntu and other Linux distros could be improved by having a [Snap package](https://snapcraft.io/) version. I also wouldn't mind being the one to create the snap too.

[Creating a Snap](https://tutorials.ubuntu.com/tutorial/create-your-first-snap#0)

[Building Snaps with Python](https://docs.snapcraft.io/build-snaps/python)

[Linux distros with Snap support](https://docs.snapcraft.io/core/install)
![snap](https://user-images.githubusercontent.com/18353476/43989596-ec564800-9d01-11e8-89e6-8e0af1434f62.png)

**Comment by chriddyp** [comment]
From Snap's documentation:

> Linux install instructions for Python applications often get complicated. System dependencies, which differ from distribution to distribution, must be separately installed. To prevent modules from different Python applications clashing with each other, developer tools like virtualenv or venv must be used. With snapcraft it’s one command to produce a bundle that works anywhere.

In our case, we don't have any system dependencies. Our code is just Python and so `pip install dash` works easily across all platforms without any additional complexity (both from a maintenance point of view and from an end-user point of view).

So, I don't think that `snap` is a good fit for this particular project, although it seems like it could be useful for other, more complex packages.
