### ISSUE TITLE
Including Local CSS not working when running app as a WSGI server

### ISSUE THREAD

**Issue by timpal0l** [plotly/dash#404]
When adding local css files to the assets folder as instructed here: https://dash.plot.ly/external-resources
it works fine when running as a python3 app. 

When running as as WSGI (tested with gunicorn) it does not load the css.

**Comment by T4rk1n** [comment]
Did you include `dash.Dash(__name__)` when creating the dash app ?

**Comment by ned2** [comment]
I did some experimenting and I think @T4rk1n's suggestion should fix this issue. The relevant factor is that when running as a standalone Python script, the variable `__name__` takes the value `__main__`, whereas, when being run with Gunicorn, the Python script is treated as a module and `__name__` therefore takes the value to be the name of the script. 

Explicitly passing `__name__` as Dash's `name` parameter smooths over this difference.
