### ISSUE TITLE
Allow component suites to be individually loaded locally.

### ISSUE THREAD

**Issue by T4rk1n** [plotly/dash#405]
If you have a custom component that is not on npm, you'll have to set `app.scripts.serve_locally=True` for the whole app. We should allow for a component suite to only have a `relative_package_path`.

**Comment by T4rk1n** [comment]
This is already supported, just need to remove the `external_url` from the `_js_dist`. I'll add an option in the cookiecutter boilerplate so you can have a `private` component.

**Comment by chriddyp** [comment]
If `serve_locally = False`, does it load the `relative_package_path`? It might not, I forget

**Comment by T4rk1n** [comment]
@chriddyp Yes, if there's no `external_url` in the `_js_dist`.
