### ISSUE TITLE
Double click zoom out behaviour

### ISSUE THREAD

**Issue by pfbuxton** [plotly/dash#416]
Hello,

I reported this issue to plotly.js:
https://github.com/plotly/plotly.js/issues/3026

However, the bug still exists in dash. I am using python with the following package versions.

| Package | Version |
| --- | --- |
| dash | 0.28.1 |
| dash-core-components | 0.31.0 |
| dash-html-components | 0.13.2 |
| dash-renderer | 0.14.1 |
| plotly | 3.3.0 |

Thanks,
Peter

**Comment by chriddyp** [comment]
Thanks! Looks like we need to upgrade our plotly.js in dash-core-components. I just made an issue and you can track it's progress in https://github.com/plotly/dash-core-components/issues/317

**Comment by pfbuxton** [comment]
This bug has been fixed in:

| Package | Version |
| --- | --- |
| dash-core-components | 0.33.0 |

Thank you,
Peter
