### ISSUE TITLE
time-series plot can't be cross-filtered on selectedData

### ISSUE THREAD

**Issue by havok2063** [plotly/dash#42]
I'd like to set up multiple time-series plots and cross-filter between and it seems this doesn't work when I set the callback to trigger off selectedData.  When I click and drag to select a subset of the time range, I am selecting data so it should propagate.  clickData seems to work as normal but my guess is that's not really the common usage for time series.

**Comment by chriddyp** [comment]
Discussion has moved to https://community.plot.ly/t/solved-crossfiltering-on-timeseries-plots/4605/2
