### ISSUE TITLE
Callback validation infinite recursion

### ISSUE THREAD

**Issue by Vetinar1** [plotly/dash#425]
I'm writing a modular Dash interface that allows mixing and matching complex components using the `serve_layout` pattern from example 4 [here](https://dash.plot.ly/sharing-data-between-callbacks). I define generator functions that set up both the layout and the callbacks of my modules.

This works if the layout is generated statically with `app.layout = serve_layout()`, but if it is generated dynamically (to make session-ids work), as in `app.layout = serve_layout`, infinite recursion occurs.

This is because every time the layout is calculated, all it's callbacks are verified, but to do so, Dash reconstructs the layout. Which leads to verifying the callbacks again and we're back at the start.

I suggest finding a solution where the layout is cached after creation and have `_validate_callback` use that instead of generating it again.

Here's some sample code that reproduces the error:

```
import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output, State
from uuid import uuid4

app = dash.Dash()

def generate_callback():
    def callback(clicks):
        return clicks
    return callback

def serve_layout():
    id = str(uuid4())
    print("Serving: " + id)

    output = html.Div(
        [
            html.Div(id="counter"),
            html.Button("Click", id="button")
        ]
    )

    app.callback(
        Output("counter", "children"),
        [Input("button", "n_clicks")])(
            generate_callback()
    )

    return output

app.layout = serve_layout


if __name__ == "__main__":
    app.run_server(debug=True)
```

For now you can put your callback definitions in functions, add them to a global list and execute them in order after your layout has been set:
```
import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output, State
from uuid import uuid4

callbacks = []

app = dash.Dash()

def generate_callback():
    def callback(clicks):
        return clicks
    return callback

def serve_layout():
    id = str(uuid4())
    print("Serving: " + id)

    output = html.Div(
        [
            html.Div(id="counter"),
            html.Button("Click", id="button")
        ]
    )

    def submit_callback():
        app.callback(
            Output("counter", "children"),
            [Input("button", "n_clicks")])(
                generate_callback()
        )

    callbacks.append(submit_callback)

    return output

app.layout = serve_layout

for i in callbacks:
    i()

if __name__ == "__main__":
    app.run_server(debug=True)
```

Ultimately, however, this is not a satisfactory solution: Not only do you need to wrap each callback definition in a function, but if you want to create dash components dynamically based on some data at the beginning, then add callbacks to them, you need to write a function factory to create the callback defining functions. Add to that the functions to create the functions that are the actual callbacks and you're already four level of function definitions deep, which leads to confusing code very quickly.

**Comment by T4rk1n** [comment]
I don't see any problem here, you shouldn't generate callbacks when serving layout, only return the layout in there.

**Comment by rmarren1** [comment]
Yeah I do not think you should be able to do the top example. All callbacks should be defined before the app is run. Since the `serve_layout` function is called every time a user requests the initial page, you would be attempting to add callbacks to a currently running app.

What do you want to be different about the `callback` function in subsequent requests?
