### ISSUE TITLE
Can not show any graph in live update demo.

### ISSUE THREAD

**Issue by 2236zml** [plotly/dash#426]
Thanks so much for your interest in Dash! 
Before you post an issue here, could you quickly search for your 
issue in the Dash community forum? https://community.plot.ly/c/dash
GitHub issues are great for bug reports, the community forum is great for
implementation questions. When in doubt, creating feel free to just post the
issue here :)
Thanks, and welcome to Dash!

Hello, I tested ( https://dash.plot.ly/live-updates) demo in my system( ubuntu 16.04 with python3 ).

If I comment     satellite = Orbital('TERRA'), like this:

@app.callback(Output('live-update-graph', 'figure'),
              [Input('interval-component', 'n_intervals')])
def update_graph_live(n):
**#    satellite = Orbital('TERRA')**
    data = {
        'time': [],
        'Latitude': [],
        'Longitude': [],
        'Altitude': []
    }

it work correct.

If uncomment this line。This demo can not show any graph in my browser( chrome and fire ).

The bash version is ( 0.28.1) and plotly is ( 3.3.0), other official demo it work correct.

**Comment by T4rk1n** [comment]
Did you install pyorbital (`pip install pyorbital`) and import `from pyorbital.orbital import Orbital` ?

**Comment by 2236zml** [comment]
yes, I install pyorbital. I tested  satellite = Orbital('TERRA'), satellite can get many data.

**Comment by T4rk1n** [comment]
I just tested the demo on https://dash.plot.ly/live-updates. It took a couple seconds for the graph to show but it worked, did you modify any other part of the code ?

**Comment by 2236zml** [comment]
It like this.
![image](https://user-images.githubusercontent.com/2735992/46751526-6d6d5f80-cced-11e8-8612-f9eca498fdb6.png)
no graph.and then I wait some minites.
I set a breakpoint  satellite = Orbital('TERRA') ,  I can see some data in satellite

**Comment by T4rk1n** [comment]
You got a breakpoint in the callback on your gif, if you don't resume it will never update the graph.

**Comment by 2236zml** [comment]
When this program starting, there is no any breakpoint.
This breakpoint is set after start many minites, just for check data of satelite.

**Comment by 2236zml** [comment]
Maybe that satellite get data too slow( or too heavy) to affect this process . I tested live update database  by manual sql, Its work correct, But I use sqlalchemy, It not working。

**Comment by chriddyp** [comment]
It looks like this is an issue with some of the libraries, not necessarily with Dash, so I'm going to close this one.
