### ISSUE TITLE
urllib3 update broke CI

### ISSUE THREAD

**Issue by rmarren1** [plotly/dash#428]
https://pypi.org/project/urllib3/#history

The most up-to-date version is automatically installed when `selenium` is installed, but `requests` supports the previous version.

I'm working on a fix for https://github.com/plotly/dash/issues/419 right now and I will just fix this as well.

**Comment by T4rk1n** [comment]
I fixed that problem in dcc tuesday plotly/dash-core-components#333, need to pin urllib3<=1.22

**Comment by rmarren1** [comment]
1.23 seems to work, was only <=1.22 working for you?

**Comment by rmarren1** [comment]
Looks like `requests` just fixed it: https://github.com/requests/requests/blob/master/HISTORY.md
