### ISSUE TITLE
Rename `requirements.txt` in this repo to prevent confusion from users vs package devs

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash#434]
Several users have thought that installing  the`requirements.txt` in this project is the correct way to install the necsesary dependencies for `dash` (rather than visiting dash.plot.ly/installation).  See https://github.com/plotly/dash/issues/433#issuecomment-432810843 and some of the issues in https://github.com/plotly/dash/issues?utf8=%E2%9C%93&q=is%3Aissue+requirements.txt. 

Is there any way that we can help prevent these issues? Thoughts:
- Rename `requirements.txt` to something like `contributing_requirements.txt` or place it in a folder like `contributing/requirements.txt`
- Perhaps we can add a "Quickstart" link at the very top of the README.md with a link to https://dash.plot.ly/installation

**Comment by ned2** [comment]
I see dev_requirements.txt used a bit for this purpose. But putting it in a
folder I think would be the safest option. Contributors will be reading the
contributing instructions anyway before they start, so discovery is not an
issue for them.

**Comment by T4rk1n** [comment]
We don't even use the `requirements.txt`, was made with `pip freeze`, the versions are locked and probably out of date.  `pip freeze` never makes good requirements files IMO, it includes dependencies of dependencies so it includes a bunch of packages that should be managed by their dependents instead.  We use the `dev-requirements.txt` and `dev-requirements-37.txt`. So I guess we could delete it and move the other two in a folder like `.circleci/requirements/...`.

**Comment by chriddyp** [comment]
Cool, that sounds good @T4rk1n
