### ISSUE TITLE
dcc.Interval and sharing data between callbacks

### ISSUE THREAD

**Issue by charleyferrari** [plotly/dash#440]
I'm trying to build an app that uses`dcc.Interval` while sharing data between callbacks. I'm getting errors referencing `graph.figure` and `self.callback_map`. Looks to me like there might be some conflict between the interval and components further down the chain...

Here's a reproducible toy app that should show the errors:

```
import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output
import json

app = dash.Dash()

app.layout = html.Div([
    html.Div(id='stock-df', style={'display': 'none'}),
    html.Div(id='stock-show'),
    dcc.Interval(
        id='interval-component',
        interval=1000,  # in milliseconds
        n_intervals=0
    )
])


@app.callback(
    Output('stock-df', 'children'),
    [Input('interval-component', 'n_intervals')]
)
def store_list(n_intervals):
    stocks = ['hello', 'goodbye', 'what']
    return json.dumps(stocks)


@app.callback(
    Output('stock-show', 'children'),
    [Input('stock-df', 'children')]
)
def show_list(stockjson):
    stocks = json.loads(stockjson)
    return [
        html.P([ticker], id=ticker) for ticker in stocks
    ]


if __name__ == '__main__':
    app.run_server(debug=True)
```

**Comment by charleyferrari** [comment]
cc @plotly/dash

**Comment by notatallshaw** [comment]
What versions of dash are you on? Your code executes fine for me with no errors on these vesions:
dash == 0.28.5
dash-core-components == 0.35.1
dash-html-components == 0.13.2
dash-renderer == 0.14.3

**Comment by charleyferrari** [comment]
Looks like I just needed to upgrade. I had:

Dash 0.26.5
dcc 0.29.0
html 0.12.0
dash-renderer 0.13.2

I just upgraded to the latest versions and it's running, so this issue must have already been addressed.
