### ISSUE TITLE
socket.error: [Errno 48] Address already in use

### ISSUE THREAD

**Issue by dpgfoures** [plotly/dash#45]
After a couple of runs, I get this error
`socket.error: [Errno 48] Address already in use`
I'll look into a fix, but simply flagging it out there.

**Comment by dpgfoures** [comment]
For some reason, a process was still running in the background. Had to kill it and restart the server.

**Comment by chriddyp** [comment]
Thanks for reporting @dpgfoures ! I've seen this happen on my machine too. I'm not sure how it happens either.
