### ISSUE TITLE
preserve state in hot reload

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/dash#460]
Hot reloading (#66) is awesome, so here's the next-level feature: state-preserving hot-reloading!

Right now if I'm 50 clicks into an interaction with a Dash app and I modify the code, the frontend reloads and resets back to its initial state. What I'd love to see is for the app to reload with the same state as I was in before, much like react hot reloading works :)

**Comment by nicolaskruchten** [comment]
I've actually built out a little pattern to do this with the state in the URL: https://community.plotly.com/t/boilerplate-starter-app-with-state-in-url-and-state-aware-hot-reloading/71821

**Comment by ndrezn** [comment]
In Dash Enterprise we have deep links integration which also enables this kind of development. @nicolaskruchten's example is pretty wicked as well!
