### ISSUE TITLE
DataTable Client Side Sorting No Callback

### ISSUE THREAD

**Issue by josham** [plotly/dash#465]
Working off the examples from [DataTable Interactivity](https://dash.plot.ly/datatable/interactivity), it seems that if I remove the callback, the sorting no longer works, even though it should take place client side. The table shows up with sortable columns but clicking them does nothing. Is this expected behavior?

```
import dash
import dash_table
import dash_html_components as html
import pandas as pd


df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/gapminder2007.csv')

app = dash.Dash(__name__)

app.layout = html.Div([
    dash_table.DataTable(
        id='datatable-interactivity',
        columns=[
            {"name": i, "id": i} for i in df.columns
        ],
        data=df.to_dict("rows"),
        sorting=True
    )
])


if __name__ == '__main__':
    app.run_server(debug=True)

```

Version info:

- python==3.6.6
- dash==0.30.0
- dash-core-components==0.38.0
- dash-html-components==0.13.2
- dash-renderer==0.15.1
- dash-table==3.1.6

**Comment by T4rk1n** [comment]
See https://github.com/plotly/dash-table/issues/202
