### ISSUE TITLE
provide better docstring support for the components

### ISSUE THREAD

**Issue by T4rk1n** [plotly/dash#467]
A few issue with the components docstring.
- When working in vscode, the components docstring doesn't get applied because there is a filename with the same name as the component name. Solution: use snake_case for the component classes filename.
- The arguments docstring is not in the right place, it should be under init.
- Add type hinting with the typing module (can be used in python 2 docstrings).
- docstring max width should be max 70 chars.

**Comment by T4rk1n** [comment]
Typing should be done with mypy syntax to support a wide range of editors.

ie: `# type: (str, int) -> None`

**Comment by eric-spitler** [comment]
@T4rk1n Does mypy support the Python built-in [`typing`](https://docs.python.org/3/library/typing.html) package introduced in 3.5? If so, I feel like this would provide the most support for IDEs and uses the [PEP 484](https://peps.python.org/pep-0484/) standards.

**Comment by T4rk1n** [comment]
@eric-spitler 
This issue is old, I added typing to the init in this recent PR: https://github.com/plotly/dash/pull/2276
Will work with mypy, but I found mypy has some issues, `pyright` is a better static checker that is used in tests in the PR to check the generated typing. Work with `vscode`/`pycharm`.

**Comment by ndrezn** [comment]
@T4rk1n with https://github.com/plotly/dash/pull/2276 merged can we close this ticket?
