### ISSUE TITLE
Inline CSS Style - Small Suggestion

### ISSUE THREAD

**Issue by carlsonp** [plotly/dash#47]
Most of the gallery examples use HTML divs with a CSS class value set.  However, some parts have inline CSS.  In cases where you have a dash/hyphen in the CSS property name, this won't work:

```
html.Tr([
                    ...
            ], style = dict(font-weight="bold")),
```
It gives an error: `SyntaxError: keyword can't be an expression`.  The hyphen (-) is an operator in Python.  It might be better in the demos to use the following syntax for dictionary creation which would then allow hyphens:

```
html.Tr([
                    ...
            ], style = {'font-weight':'bold'}),
```
Otherwise you have to do something like this:
```
html.Tr([
                    ...
            ], style = dict([('font-weight','bold')])),
```
I don't think this is as easy to read.

As an aside, it would be great to have a little more detail or an example into including local CSS files.

Thank you for all the hard work and this great project!

**Comment by jackwluo** [comment]
Thanks for pointing it out! Updating the example apps stylesheets to {} syntax.
Dash doesn't currently support the inclusion of local CSS files. For now, your best bet would be to upload the stylesheets to Github and link them using Rawgit
