### ISSUE TITLE
Local CSS is overridden by React-generated CSS

### ISSUE THREAD

**Issue by EBoisseauSierra** [plotly/dash#482]
Context
===
I'm trying to style various DCC elements — say multi-value dropdowns. 

Problem
===
I am using Dash v0.31.0.

I add a css file to my project containing:
```
.Select--multi .Select-value {
    background-color:#df0a0b;
}
```
I know the CSS is loaded as other rules (e.g. affecting `h1`) take effect. 
However, for the dropdown, my own styles are overridden by the React select .ccs file — i.e. the file starting with:
```
/**
 * React Select
 * ============
 * Created by Jed Watson and Joss Mackison for KeystoneJS, http://www.keystonejs.com/
 * https://twitter.com/jedwatson https://twitter.com/jossmackison https://twitter.com/keystonejs
 * MIT License: https://github.com/JedWatson/react-select
*/
.Select {
  position: relative;
}
…
.Select--multi .Select-value {
  background-color: #ebf5ff;
  /* Fallback color for IE 8 */
  background-color: rgba(0, 126, 255, 0.08);
  border-radius: 2px;
  border: 1px solid #c2e0ff;
  /* Fallback color for IE 8 */
  border: 1px solid rgba(0, 126, 255, 0.24);
  color: #007eff;
  display: inline-block;
  font-size: 0.9em;
  line-height: 1.4;
  margin-left: 5px;
  margin-top: 5px;
  vertical-align: top;
}
…
```

The latter is indeed passed as "inline":
![screenshot from 2018-12-06 16-50-03](https://user-images.githubusercontent.com/37387755/49599266-79397300-f978-11e8-8f38-23a1ad6f7029.png)

Question
===

➥ **How to enforce _my_ CSS?**

**Comment by EBoisseauSierra** [comment]
Quick and dirty fix: replace all `.Select` with `div.Select` to gain higher priority.

**Comment by valentijnnieman** [comment]
What version of `dash-core-components` are you using? In https://github.com/plotly/dash-core-components/pull/382 we fixed the issue where user supplied styles weren't overriding the React included styles.

**Comment by EBoisseauSierra** [comment]
Indeed, I thought it would be solved. But I'm using v0.39.0…
```
$ pip show dash-core-components
Name: dash-core-components
Version: 0.39.0
```

**Comment by anandcu3** [comment]
Same behavior in v0.42.1

**Comment by mamay13** [comment]
Same behavior in  0.45.0
only with imported dash_table

**Comment by jjaraalm** [comment]
Same here with dash 1.9.1 using `dash_table`. Custom CSS is applied correctly on page load, however I have dropdowns in one tab and tables in another. Switching to the table tab causes custom css to be overridde once I switch back.

**Comment by elastufka** [comment]
I also have this issue. Any solutions yet? I can't find the part in my CSS which controls the dropdown menu colors.

**Comment by AP2008** [comment]
I am having the exact same issue but with `dash_table`. Any solutions yet?

**Comment by Geometrein** [comment]
Same issue with dcc.tabs. 
The actual example that you provide on your website: [Styling the Tabs component with CSS Classes ](https://dash.plotly.com/dash-core-components/tabs) contains this issue. 
Any solutions yet?

**Comment by Xzyon** [comment]
Same behavior with dash-core-components ver. 2.0.0
React override local CSS of dropdown only when a dash_table is present.

**Comment by lance-noel** [comment]
I have the same problem with `.Select--multi .Select-value` being overwritten by react-select

**Comment by Coding-with-Adam** [comment]
@ndretex are you referring to a CSS styling problem related to Dash Core Components or the Dash DataTable?

**Comment by at1047** [comment]
Another quick and dirty fix, add !important to the css property you want to override

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
