### ISSUE TITLE
Pandas table rendering

### ISSUE THREAD

**Issue by jermaine1ronquillo** [plotly/dash#50]
pandas table not rendering properly on firefox browser (linux machine)

![pandas_rendering](https://user-images.githubusercontent.com/15191328/27614077-e52e59a4-5bd1-11e7-8cfd-e096b78e7f12.png)

**Comment by chriddyp** [comment]
Thanks for reporting @jermaine1ronquillo ! Are you running this locally or just viewing the documentation (at https://plot.ly/dash/getting-started).

As far as I can tell, this looks like it is rendering it "properly", it just may note be styled in the way that you would prefer.

**Comment by jermaine1ronquillo** [comment]
I'm running this locally, @chriddyp you are right it doesn't render the way I was expecting it, Is there a fix to this so that it'll be the same as in the documentation? Thank you

**Comment by chriddyp** [comment]
You can add your own CSS to your app to style it the way that you'd like it. There was a note about this in the documentation in https://plot.ly/dash/getting-started:

> 6. The fonts in your application will look a little bit different than what is displayed here. This application is using a custom CSS stylesheet to modify the default styles of the elements. You can learn more in the css tutorial, but for now you can add app.css.append_css({"external_url": "https://codepen.io/chriddyp/pen/bWLwgP.css"}) to your file to get the same look and feel of these examples.

**Comment by jermaine1ronquillo** [comment]
Thanks Chris
