### ISSUE TITLE
Input's disabled option doesn't work.

### ISSUE THREAD

**Issue by thedimlebowski** [plotly/dash#51]
```
app.layout = html.Div(
    [
        dcc.Input(
            disabled=True,
            type='int'
        )
    ]
)
```

produces this hmtl code:

`<input type="int" id="rendering-frequency-input" placeholder="50">`

**Comment by chriddyp** [comment]
Confirmed. Thanks for reporting!

**Comment by bpostlethwaite** [comment]
PR to fix this issue here: https://github.com/plotly/dash-core-components/pull/185

Note that this won't land into Dash until we bump `dash-core-components` in `requirements.txt`

**Comment by avaz** [comment]
The same applies for the ```readonly``` attribute. Besides the ```input``` component declare this as a valid attribute, manipulate it via a callback leads to nothing rendered on the component.
