### ISSUE TITLE
Role of Input's type option?

### ISSUE THREAD

**Issue by thedimlebowski** [plotly/dash#52]
It seems that the `type` option of the Input class is not doing anything.
![image](https://user-images.githubusercontent.com/6419212/27644310-158fe916-5c1b-11e7-9222-740af48522bf.png)

Code:
```
import dash
import dash_core_components as dcc
import dash_html_components as html
app = dash.Dash(__name__)
app.layout = html.Div(
    [
        dcc.Input(id='input', type='int'),
        html.Div(id='output')
    ]
)
@app.callback(
    dash.dependencies.Output('output', 'children'),
    [dash.dependencies.Input('input', 'value')]
)
def callback(value):
    return ['Output is: {} of type {}'.format(value, type(value))]
app.run_server(debug=True)
```

**Comment by chriddyp** [comment]
`type` is rendered in HTML and it's up to the browser to determine what it does. See https://developer.mozilla.org/en/docs/Web/HTML/Element/input#Form_%3Cinput%3E_types for more about types. Note that not all types are supported by all browsers, see: http://caniuse.com/#search=input%20type
