### ISSUE TITLE
Documentation request: Shiny like dashboard 

### ISSUE THREAD

**Issue by iainmwallace** [plotly/dash#53]
Hi,

This looks like an incredible package! 
Coming from the R/Shiny world, I would love if there was a tutorial for dash that showed how to create a dashboard similar to the shiny dashboard examples (https://rstudio.github.io/shinydashboard/examples.html)

For example, a simple app that showed the following 6 boxes would be incredibly useful
Box 1 - Markdown summary of app
Box 2 - upload a csv file
Box 3 - display contents of file in a DT table 
Box 4 - display graph of table
Box 5 - display only rows of table that correspond to selection in graph
Box 6 - download csv file corresponding to table in box 4 

Thanks

Iain

**Comment by chriddyp** [comment]
Thanks for the feedback @iainmwallace ! Uploading CSV isn't possible yet. The rest of the items are covered in the existing gallery (https://plot.ly/dash/gallery) and in the two sections of the docs: https://plot.ly/dash/getting-started and https://plot.ly/dash/gettting-started-part-2.

**Comment by iainmwallace** [comment]
Thanks for the quick reply. The gallery looks very impressive.

To clarify, from my non-python background, it isn't clear to me
1) how to layout a dash app in 2 columns and 3 rows or 3 columns and 2 rows or 6 columns and 1 row
2) use the Data tables library in dash. The R library, DT, https://rstudio.github.io/DT/ is probably one of most commonly used widgets in my Shiny world. 
3) I didn't see a download button listed as a component

Thanks again,

Iain

**Comment by chriddyp** [comment]
> how to layout a dash app in 2 columns and 3 rows or 3 columns and 2 rows or 6 columns and 1 row

This is possible through custom CSS and using `className`. We'll publish a more in depth tutorial about tempaltes and arrangements soon.

> use the Data tables library in dash

Dash doesn't have a rich Table component yet. We will soon. In the meantime, you can just render data from a datafrom using an HTML table as in https://plot.ly/dash/getting-started.

> I didn't see a download button listed as a component

This isn't available yet. Feel free to make a separate issue if this is a component that you would like to see!

**Comment by iainmwallace** [comment]
Great, thanks! I have created a couple of component requests :)

**Comment by ned2** [comment]
I'm currently building a dashboard with dash using Bootstrap to lay the page out by simply passing Bootstrap class names to the HTML constructors in the layout. This approach is working quite successfully so far.

**Comment by chriddyp** [comment]
I'll close this one for now - it looks like it's been broken out into the necessary sub-issues
