### ISSUE TITLE
Why not including components inside dash?

### ISSUE THREAD

**Issue by john-bonachon** [plotly/dash#54]
So right now, usage is,
```
import dash_core_components as dcc
import dash_html_components as html
```
Why not this?
```
import dash.core.components as dcc
import dash.html.components as html
```
And as optional dependencies,
```
pip install dash[core_components]
pip install dash[html_components]
```

**Comment by chriddyp** [comment]
Good question! Mostly to promote modularity:
- the `dash` package is just an implementation of the dash API in Python with Flask. Alternative backends could exist for other servers or other languages and they might want to use the same component libraries. For example, these component libraries are also node modules on NPM. It wouldn't make as much sense to put the entire `dash` package on NPM.
- Modularity allows these packages to be versioned separately, making it easier in the long run for users to do selective upgrades (reducing the surface area of possible changes). They might not want to change the version of `dash` but they would like to get the latest features in the `dash-core-components` library.
- To encourage / remind users that component libraries are modular packages, and that they can write their own component libraries. It makes forking these component libraries easier too. For more on component library plugins, see: https://plot.ly/dash/plugins
