### ISSUE TITLE
"Error loading dependencies" when opening the Dash website

### ISSUE THREAD

**Issue by WI-KIWI** [plotly/dash#541]
Hello,
the dash website 
https://dash.plot.ly/
is possibly down and shows 
"Error loading dependencies".

OS: Windows 10 Pro 
Browser: Google Chrome Version 71.0.3578.98 (Offizieller Build) (64-Bit)

**Comment by alexcjohnson** [comment]
Thanks for the report @WI-KIWI - we've been monitoring for the last couple of hours (though not quite when you posted this report) and everything seems to be OK, but we've seen some possibly related issues recently, eg https://github.com/plotly/dash-docs/issues/359

Does it load for you now, or are you still seeing a problem?

**Comment by WI-KIWI** [comment]
Hi @alexcjohnson , thanks for the quick reply. Now everything works fine, so I will close this ticket.

Cheers
