### ISSUE TITLE
load local html on dash?

### ISSUE THREAD

**Issue by highwindmx** [plotly/dash#546]
Hi,  Dash!

I am trying to create my own app to organize my notes which are saved in html format.
I am wondering if dash can load these contents and display:
1. like in flask I can use {{content|safe}} method
2. Or any other way round by base64 en-decoding?

Thanks

**Comment by highwindmx** [comment]
I think it is dup of #118 Rendering raw HTML

**Comment by highwindmx** [comment]
Or any idea about how to embed a WYSIWYG editor in dash app?

**Comment by ned2** [comment]
As you probably already gathered, for rendering raw HTML, there is the [dash-dangerously-set-inner-html](https://github.com/plotly/dash-dangerously-set-inner-html) component, which as the name implies, can be dangerous.

The best course of action for a WYSIWYG editor would be to find a React component that does what you want and convert it into a Dash component, as discussed in the [Dash Guide](https://dash.plot.ly/plugins). 

Questions like these are better posted over on the [Dash community forum](https://community.plot.ly/c/dash), where you're more likely to get a discussion going.

**Comment by highwindmx** [comment]
@ned2   wow, very quick respond, now I can try to dig it follow your suggestion. thank you so much.

**Comment by ned2** [comment]
No worries :) good luck!
