### ISSUE TITLE
how to change standard port from dash

### ISSUE THREAD

**Issue by eloiup** [plotly/dash#55]
by standard dash is getting uploaded to the port 8050
how can i change the port i am using // is there an easy function/module within the python library?

**Comment by chriddyp** [comment]
The `run_server` function takes `port` as an argument as well as `kwargs` that get passed into the `flask.run` function. See https://github.com/plotly/dash/blob/a8fc53ba880d26e3c131f7849795d173596405ec/dash/dash.py#L604-L609
