### ISSUE TITLE
provide types in __init__ signatures

### ISSUE THREAD

**Issue by notatallshaw** [plotly/dash#554]
Because the children argument of a component can take a single element or a list, e.g.
html.Div(html.Div())
html.Div([html.Div(), html.Div()])

I can easily make the mistake of not putting the children in a list, e.g.:
html.Div(html.Div(), html.Div())

In this case I do not get any kind of error, and instead the 2nd Div is stringified and becomes part of the id for the parent component.

In very large applications this is easy to lose. If type information was provided then IDEs like Pycharm would highlight this issue and tools like MyPy would warn before the code was ever run.

**Comment by notatallshaw** [comment]
@Marc-Andre-Rivet thanks for the update to the issue. I guess this issue would affect all Dash Components, but the Dash HTML Component is definitely the one where its' most pronounced because of the repeated nesting.

As for #452 I could be wrong but I don't see any talk of PEP 484 Type Annotations in that discussion, but instead a run time check of the Dash Callbacks and the Dash Layout.

**Comment by notatallshaw** [comment]
@T4rk1n Thanks for the work and information!

I think you are correct that doctring type annotations are best for such a widely used library as there is no restrictions on Python version and no worries about current type annotations vs. `__future__` type annotations.

I just tested modifying some Dash Components with type annotations as specified in "[Suggested syntax for Python 2.7 and straddling code](https://www.python.org/dev/peps/pep-0484/#suggested-syntax-for-python-2-7-and-straddling-code)" section of PEP 484 and IntelliJ Ultimate + Python Plugin (IDE I use at the office) successfully highlighted when I was passing the Dash Component incorrect types.

**Comment by T4rk1n** [comment]
@notatallshaw Yes

The PEP 484 suggested syntax for python 2.7 is the most supported by IDE and editors, Pycharm/intelliJ will pick them up right away by adding the type comment to the component `__init__` docstring, but `vscode` and other smart editors needs a plugin for mypy linting and proper generated python filename for the components.

You can also run mypy from the cli on the dash application.

**Comment by ndrezn** [comment]
We do provide a runtime error in this situation that helps to debug this issue -- I don't think we need to make further adjustments to help out with this developer experience for now.
