### ISSUE TITLE
[Question] Tornado and Dash

### ISSUE THREAD

**Issue by loretoparisi** [plotly/dash#559]
I'm running a Tornado application (not WSGI server)

```python
tornado.web.Application(handlers, **settings)
```

with a list of `handlers`.

Now a dash app returns a Flask server like

```python
app = dash.Dash(__name__, external_stylesheets=external_stylesheets)
server = app.server
```

Is it possibile to integrate `Dash` as a Tornado handler in some way?

**Comment by ned2** [comment]
According to the Tornado docs, you can use WSGIAdapter to convert a
tornado.web.Application into a WSGI app. You could then combine that WSGI
app with the Flask app driving your Dash app using werkzeug's
DispatcherMiddleware. This seems a bit convoluted though and may not
actually help your use case.


http://www.tornadoweb.org/en/stable/wsgi.html#running-wsgi-apps-on-tornado-servers

http://werkzeug.pocoo.org/docs/0.14/middlewares/

**Comment by loretoparisi** [comment]
@ned2 thank you. Unfortunately I cannot use the `WSGIAdapter` because my application must asynchronous, while the WSGI adapter is a synchronous interface.

**Comment by ned2** [comment]
Ah, well Flask is inherently synchronous, so you might be out of luck.

Although I did once manage to monkey-patch Dash to use Quart (an async
Flask API compatible framework) instead of Flask.

**Comment by loretoparisi** [comment]
@ned2 ok. But is there any way to export the `Dash` handlers only instead of the whole `app.server`? I assume that this Flask server will have its handlers and maybe some WebSocket internally, but externally for the Tornado side it should be enough to have the rendering part...or may I have to start another `localhost` server and then expose it to Tornado.

**Comment by ned2** [comment]
There's no out-of-the-box way to do this. But I did just come across the PythonOnWheels web framework which is based on Tornado and has recently had Dash support added. Looks like it somehow converts Dash in to a Tornado handler, if you dig around the code.

https://github.com/pythononwheels/pow_devel
