### ISSUE TITLE
Last pypi releases breaks the App

### ISSUE THREAD

**Issue by rbardaji** [plotly/dash#560]
I am writing to tell you that I have updated with "pip --upgrade" all the libraries related to dash and all my applications have stopped working. I've tried the basic example of callbacks, and it does not work either.

Reinstalling the previous versions of the libraries, they work again.

So, with:
```
pip install dash == 0.35.1
pip install dash-html-components == 0.13.4
pip install dash-core-components == 0.42.1
pip install dash-table == 3.1.11
```
Everything works well. 

But if I update the libraries, the callbacks stop working and "Error loading dependencies" appears.

**Comment by alexcjohnson** [comment]
@rbardaji can you also upgrade `dash-renderer`? That gets installed automatically with `dash`, so it's not featured in the installation instructions, but it needs an upgrade too for the latest versions where we removed support for `Event` in callbacks.

Sorry about the disruption - please let us know if that fixes your problem!
(we really need to implement version locking https://github.com/plotly/dash-core/issues/24)

**Comment by rbardaji** [comment]
Thanks @alexcjohnson.

I upgrade ```dash-renderer``` and now my apps work well again.
