### ISSUE TITLE
Python 3.8 collections ABC deprecation warning

### ISSUE THREAD

**Issue by T4rk1n** [plotly/dash#562]
`Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working`

The warning comes from the base component class:

https://github.com/plotly/dash/blob/c9b392d2525f33b22dec0e877e62efc38509f4b8/dash/development/base_component.py#L61

**Comment by alexcjohnson** [comment]
Sadly py2 doesn't have `collections.abc`
https://github.com/benjaminp/six/issues/155

**Comment by T4rk1n** [comment]
Yes, what I just found out...

**Comment by T4rk1n** [comment]
Also:

https://github.com/plotly/dash/blob/c9b392d2525f33b22dec0e877e62efc38509f4b8/dash/dash.py#L278

and

https://github.com/plotly/dash/blob/c9b392d2525f33b22dec0e877e62efc38509f4b8/dash/dash.py#L287
