### ISSUE TITLE
Modify R component prefixes to match Python, enforce dependency on dashR package

### ISSUE THREAD

**Issue by rpkyle** [plotly/dash#591]
For increased parity with the Dash for Python calling syntax, the current prefixes for `dash-html-components` and `dash-core-components` should be changed when generating R components:

- ~`html` ➡️ `dhc`~
- `core` ➡️ `dcc`

**Comment by alexcjohnson** [comment]
Our standard usage in Python is `html` for `dash_html_components` - so I think only `core` needs to change to `dcc`.

**Comment by rpkyle** [comment]
The proposed implementation of the `preload_dependency` method, which will be useful for multipage DashR applications, requires that we enforce a dependency on DashR for all component library packages.

**Comment by rpkyle** [comment]
The above goals were achieved when https://github.com/plotly/dash/pull/638 was merged into Dash. Closing this issue.
