### ISSUE TITLE
Feature Request: Color-Syntax Enrichment in dcc.Markdown

### ISSUE THREAD

**Issue by SterlingButters** [plotly/dash#602]
As far as I can tell this is not supported:

<img width="398" alt="screen shot 2019-02-11 at 9 44 27 pm" src="https://user-images.githubusercontent.com/22737286/52607955-4616d280-2e46-11e9-8fcb-7dd32c3a0296.png">

**Comment by byronz** [comment]
@SterlingButters  I'm pretty sure this is done via https://github.com/plotly/dash-core-components/pull/562.  feel free to reopen it if I was wrong.
