### ISSUE TITLE
Call a python variable from within markdown text

### ISSUE THREAD

**Issue by eotp** [plotly/dash#617]
Is there a way to call a variable from within markdown text?

Something similar to something like that would be great!
```
var = 100
md_text = '50 times 2 is {{var}}.'
```
There is a way to do this in Jupyter [here](https://stackoverflow.com/a/43911937) as well as in R [here](https://stackoverflow.com/a/10903654).

**Comment by ned2** [comment]
You pretty much get this for free by using f-strings (which require Python >= 3.6).

    var = 100
    md_text = f'50 times 2 is {var}.'

**Comment by eotp** [comment]
@ned2 Perfect! 
Thanks I wasn't aware of that.
