### ISSUE TITLE
module 'dash' has no attribute 'callback' on 0.38.0

### ISSUE THREAD

**Issue by ale0xb** [plotly/dash#619]
I hurried to install 0.38.0 to get my hands on [this new callback context functionality](https://github.com/plotly/dash/pull/608) 

I set up the example provided in that PR but I'm still getting `AttributeError: module 'dash' has no attribute 'callback'`. 

I made sure I was running 0.38.0 and that I was trying to access dash.callback inside the callback. 

Am I doing anything wrong?

**Comment by alexcjohnson** [comment]
oops, we changed it to `dash.callback_context` but the changelog still shows `dash.callback`. Thanks for pointing this out!

**Comment by ale0xb** [comment]
I can confirm `dash.callback_context` works. 
Thanks to you for the quick response!
