### ISSUE TITLE
AttributeError: 'module' object has no attribute 'development'

### ISSUE THREAD

**Issue by Chris8080** [plotly/dash#62]
Hello,

I just went through the installation and that seemed fine.
https://plot.ly/dash/getting-started

Then I copied the code into a dash.py file and tried to run it (Python 2.7) and I got this:
`python dash.py 
Traceback (most recent call last):
  File "dash.py", line 2, in <module>
    import dash
  File "/home/automater/Dokumente/Work/Projekte/Scrapy/fabrics/data_automate/dash.py", line 3, in <module>
    import dash_core_components as dcc
  File "/usr/local/lib/python2.7/dist-packages/dash_core_components/__init__.py", line 8, in <module>
    _components = _dash.development.component_loader.load_components(
AttributeError: 'module' object has no attribute 'development'
`
Are there any other requirements or similar?

Thanks,
Chris

**Comment by ned2** [comment]
The problem is that you've named your app file 'dash.py', so Python is dutifully importing the very file you're working on rather than the dash module. Rename your file to something else and you should be good. (I just did the exact same thing, which is how I found this issue :P)

**Comment by Chris8080** [comment]
Oh indeed - yes, I made the same mistake with another library months ago and now that you mention it .. of course. Silly me, thank you very much.

**Comment by chriddyp** [comment]
😅  Thanks for documenting @ned2 and @Chris8080 !
