### ISSUE TITLE
Component request: Download button

### ISSUE THREAD

**Issue by iainmwallace** [plotly/dash#63]
Awesome package - based on the suggestion from I am calling out a couple of components that I have found incredibly useful in the Shiny universe. https://github.com/plotly/dash/issues/53

It would be great to have a download button as a core component. In Shiny, it is a very common pattern to display data in a table and then to provide an option to download the contents of the table as a file

**Comment by chriddyp** [comment]
Thanks for reporting @iainmwallace ! Community: please 👍  if you'd like to see this feature.

**Comment by chriddyp** [comment]
Note that there are a few options to pull a particular graph (it's current view) out of a Dash app:

1 - There is a camera button on every graph element which will download the current view of the graph as a PNG. Here's a GIF of this in action: ![](http://imgur.com/a/CAlGN)
2 - There is a floppy disk icon in every graph element that will open up the chart in a chart editor on plot.ly. Inside the chart editor, you can edit every aspect of the chart: the colors, the text, the data, the chart type, even add annotations. You also have access to the underlying data behind the graph in this view. To save the graph, you'll need a plotly account (free for public data, subscription for private data) but you can also just take a screenshot or use the camera icon in this view if you don't want to sign up. Here's a GIF of this in action: ![](http://imgur.com/a/kvddQ). Here's a link to the chart editor too: https://plot.ly/create.

**Comment by chriddyp** [comment]
Here is a solution to download: https://community.plot.ly/t/download-raw-data/4700/8?u=chriddyp
