### ISSUE TITLE
Hot reload only works once

### ISSUE THREAD

**Issue by jleni** [plotly/dash#634]
I am using `dash == 0.39.0` and I have noticed the following:
- hot reload only works once. 
- After the first hot reload, any further changes do not trigger a refresh.
- If I force refresh (F5), hot reload will work once more time.

I have tested with Chrome and Firefox and it seem to be reproducible in both cases.

The issue has also been posted by other people here:
https://community.plot.ly/t/hot-reload-not-working-for-me/20272

**Comment by T4rk1n** [comment]
Can confirm that hot-reload is broken after 1 reload when reloading python files, assets changes reload normally.

**Comment by chriddyp** [comment]
taking a look at this today

**Comment by GearTheWorld** [comment]
Hot Reload only works the first time after a build and then never work again.
Blazor Wasm ASP.NET core server

Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.0.0
