### ISSUE TITLE
Component request: Table 

### ISSUE THREAD

**Issue by iainmwallace** [plotly/dash#64]
Hi,

Based on a suggestion in https://github.com/plotly/dash/issues/53, I am calling out a couple of components that are very useful in the Shiny world.

It would be really useful to have a table component that can take a pandas data frame ( I believe that is the closest to the R data frame concept) or something similar and display its contents in a rich table that allows column filtering and row selection. 

The DT package achieves this in Shiny - https://rstudio.github.io/DT/shiny.html

Perhaps we could wrap this as a component: https://react-table.js.org - the filtering options look great, https://react-table.js.org/#/story/custom-filtering

Thanks

Iain

**Comment by chriddyp** [comment]
Thanks @iainmwallace !

There is a new Table chart type being built as part of plotly.js. See https://github.com/plotly/plotly.js/pull/1834 for more details and discussion.

**Comment by chriddyp** [comment]
Summary of current solutions here: https://community.plot.ly/t/display-tables-in-dash/4707/13?u=chriddyp

**Comment by chriddyp** [comment]
The latest version in [`dash-table-experiments`](https://github.com/plotly/dash-table-experiments) includes filtering, sorting, and row-selection and is populated from Pandas DataFrames. 

![Dash DataTable Component](https://github.com/plotly/dash-table-experiments/raw/master/images/DataTable.gif)

I'd consider this component functional enough to close this issue :) There is still more to come, so stay tuned in https://github.com/plotly/dash-table-experiments or https://community.plot.ly/t/display-tables-in-dash/4707/13?u=chriddyp

**Comment by Shashank-thrymr** [comment]
How to edit on a single cell of any row after editing it fixed on rendered dataframe. After that, it reflects always.

**Comment by chriddyp** [comment]
> How to edit on a single cell of any row after editing it fixed on rendered dataframe. After that, it reflects always.

@Shashank-thrymr - Could you ask this question the community forum? https://community.plot.ly/c/dash I'm happy to help you out there. Thanks :)

**Comment by pthakur4** [comment]
i have a problem, i was working on a table component, with a date time column, and 2 float columns, in this for the float columns i need to have the integer portion on a smaller font size and the decimal portion to be a bit larger? can we do anything like that? i thought of having an HTML table where we can do this, and then parsing to show up in dash, but not sure how it would work. Any help would be highly appreciated. Thanks very much in advance
