### ISSUE TITLE
dash.Dash.dispatch is getting a `dict` (instead of string?) for `output`

### ISSUE THREAD

**Issue by 0zeroth** [plotly/dash#642]
I am seeing a strange error coming from dash internals (`dash.Dash.dispatch`): it is occurring while it is iterating over the callback map - a copy/paste of the relevant code:

`site-packages/dash/dash.py:1034`
```
 def dispatch(self):
        body = flask.request.get_json()
        inputs = body.get('inputs', [])
        state = body.get('state', [])
        output = body['output']
        ... # snip
         for component_registration in self.callback_map[output]['inputs']:  # TypeError: unhashable type: 'dict'
            ... # snip
```

I created a monkey-patched version of `dash.Dash.dispatch`  to add debug logging, it is copy/paste plus some print statements to log the `output` and `callback_map.keys()`. Sample output and error stack trace below. As you can see the `output` is indeed a `dict` - it appears the step of creating the `callback_id` has been missed.

```
--- DEBUG OUTPUT ---
output: {'id': 'new-data', 'property': 'children'}
self.callback_map.keys(): dict_keys(['pnl-detail-graph.figure', 'live-vs-backtest-current-key.children', 'live-vs-backtest-node-dropdown.options', 'live-vs-backtest-df-dropdown.options', 'live-vs-backtest-df-dropdown.value', 'live-vs-backtest-graph.figure', 'new-data.children', 'body.children'])
--- ------------ ---
2019-03-11 03:50:27,010 [ERROR] Thread-5 flask.app: Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/usr/local/envs/production/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/envs/production/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/envs/production/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/envs/production/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/envs/production/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/envs/production/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/alto_repo/lt-alto/lifetrading/monitor/app.py", line 48, in dispatch
    for component_registration in self.callback_map[output]['inputs']:
TypeError: unhashable type: 'dict'
```

Environment (just the `dash` parts):
```
python                    3.6.7
dash                      0.39.0                    <pip>
dash-bootstrap-components 0.3.4                     <pip>
dash-core-components      0.44.0                    <pip>
dash-html-components      0.14.0                    <pip>
dash-renderer             0.20.0                    <pip>
dash-table                3.6.0                     <pip>
```

The part that has me tearing my hair out is this was previously working code - the only change is using the latest packages. Additionally, it runs fine on my dev pc, it runs fine in a docker container on my dev pc, but that same container fails on our production server. As far as I can tell, this part of the dash code is only concerned with the application configuration (ie everything in `@app.callback` decorators) - so it should not be sensitive to deployment environment or the client data.

Can you provide any insight as to why dash may be receiving a `dict` for `output` ? Any hint appreciated, it may help me track down the source of this error.

**Comment by 0zeroth** [comment]
AS PER USUAL - I solved this minutes after posting the above. Thanks, rubber duck!

The issue was a 'bad client' - someone somewhere has the browser open with our dash page. Even though we've bounced the server, it just tries to connect up again. Everything _almost_ works, apart from this error. The solution for us is just to ask everyone to refresh their browsers - or maybe we'll need to clear some caches.

It would be a nice feature if Dash could force a browser refresh on version changes ( I thinkrefusing to re-connect to old clients would be enough, users would notice things had gone stale pretty quick).

**Comment by ned2** [comment]
Yeah, that looks exactly like you're getting a request from an older version of the Dash renderer. 

Glad you worked it out!
