### ISSUE TITLE
DashR transpiler: type and default information in help strings

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/dash#647]
Let's make sure that the R equivalent of docstrings has the same type/default information as the Python docstrings for components.

**Comment by rpkyle** [comment]
@alexcjohnson

**Comment by rpkyle** [comment]
I'm working on this now, as it's blocking @TahiriNadia from addressing https://github.com/plotly/dash-docs/issues/469.

**Comment by TahiriNadia** [comment]
*Reference*
[] https://stackoverflow.com/questions/30587339/how-do-i-store-the-html-or-text-of-a-r-helpfile-into-a-variable/30587705#30587705

**Comment by rpkyle** [comment]
The Python type information appears to be generated in `_py_components_generation.py` here:

https://github.com/plotly/dash/blob/ac10b2df1e49a153de00fc78b07242f439bb0b99/dash/development/_py_components_generation.py#L421-L424

I should write a Python method called `js_to_r_type` whose function is analogous to this one, which also "corrects" the type information when it doesn't line up with something sensible in R, i.e.
- `array` = (nested) `list`
- `dict` = `list`

https://github.com/plotly/dash/blob/ac10b2df1e49a153de00fc78b07242f439bb0b99/dash/development/_py_components_generation.py#L556-L587

The method can then be called when writing the R help pages to insert the language-appropriate type names.
