### ISSUE TITLE
Component request: Upload button

### ISSUE THREAD

**Issue by iainmwallace** [plotly/dash#65]
Hi,

Building from an earlier issue, https://github.com/plotly/dash/issues/53, I am calling out a few components that would be really useful based on the R/Shiny world. 

It would be great to have an upload button component. I find it is a very common workflow to build dashboards that allow a user to upload a csv file and then display the contents in a table.

Thanks

Iaian

**Comment by chriddyp** [comment]
Thanks for reporting @iainmwallace ! Community: please 👍  if you'd like to see this component.

**Comment by Dracula-36** [comment]
The upload button is really important and necessary...Does someone have any other method to make up this issue?

**Comment by lucapinello** [comment]
Yes I believe  this is the only missing feature to make dash a full replacement of shiny. Thanks for considering doing it!

**Comment by chriddyp** [comment]
Thanks for the feedback all! This is being added in https://github.com/plotly/dash-core-components/pull/73

![upload-component](https://user-images.githubusercontent.com/1280389/30351165-196eb61c-97e8-11e7-9048-70bac13c4c7d.gif)

**Comment by iainmwallace** [comment]
Looks great!!

Is there any equivalent python package to rio?
https://cran.r-project.org/web/packages/rio/README.html

Combination of upload button + rio is pretty nice :)

**Comment by chriddyp** [comment]
Docs at https://plot.ly/dash/dash-core-components/upload

**Comment by krishnarevi** [comment]
can we upload text file using upload component?
