### ISSUE TITLE
Feature Request: clickData Timestamp

### ISSUE THREAD

**Issue by SterlingButters** [plotly/dash#650]
Just read this super in-detail Gist on comparing the `clickData` property amongst multiple components: https://gist.github.com/shawkinsl/22a0f4e0bf519330b92b7e99b3cfee8a

I found myself in need of this too so I thought I'd suggest a `timestamp` key in `clickData`

**Comment by alexcjohnson** [comment]
Have you seen `dash.callback_context` #608? We're hoping this alleviates the need for all of these `timestamp` properties.

**Comment by SterlingButters** [comment]
No I hadn't seen that! Checking it out now!

Does 

> Just merged, going into next release.

mean dash 0.40.0?

**Comment by alexcjohnson** [comment]
In fact it's been released since v0.38
https://github.com/plotly/dash/blob/v0.39.0/CHANGELOG.md#added-1

**Comment by SterlingButters** [comment]
Alright! I guess feel free to close the issue, I'll see if I can't get it working

**Comment by alexcjohnson** [comment]
No, the idea of `triggered` is that if you’re using timestamps (or diffing) to determine which input changed, why don’t we just tell you which one changed? If it’s in `triggered`, it’s the reason the callback fired. Did you have a different usage of `timestamp`?

**Comment by SterlingButters** [comment]
Brilliant, it makes perfect sense now that you put it like that. This will work perfectly, indeed, thanks!
