### ISSUE TITLE
Callback with Single Output in Multiple Output list doesn't work

### ISSUE THREAD

**Issue by ONLYstcm** [plotly/dash#651]
A callback function is ignored if a single output is placed in a list of outputs.
For example
`@app.callback([Output('component', 'value')], [Input('input-component', 'value')])
`
The callback above is ignored unless it is written as so.
`@app.callback(Output('component', 'value'),  [Input('input-component', 'value')])
`
Callbacks work fine if multiple outputs are placed in a list of outputs.

**Comment by alexcjohnson** [comment]
Thanks for the report @ONLYstcm - you're absolutely right. We'll get this fixed shortly.
