### ISSUE TITLE
Ordered dict for `callback_context`

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash#657]
from https://community.plot.ly/t/is-the-order-of-dash-callback-context-inputs-states-guaranteed/21103 - maybe we should guarantee the order of these objects by making them ordered dicts.

**Comment by notatallshaw** [comment]
btw, just to follow up, in CPython 3.6 Dictionary Creation / Insertion order is preserved when iterating over the dictionary. In Python 3.7 this became part of the spec: https://mail.python.org/pipermail/python-dev/2017-December/151283.html

**Comment by kenshima4** [comment]
Hi guys. I'm new here. This seems like something I could solve. Can I be assigned here and shown where the necessary files are?

**Comment by T4rk1n** [comment]
@kenshima4 This is an old issue, all the Python version we support now keep dict insertion order I don't think this is relevant anymore.
