### ISSUE TITLE
Property value of dash_core_components.Input is not set by callbacks

### ISSUE THREAD

**Issue by sinsemellan** [plotly/dash#658]
In the following example, the value of the input textbox in the browser page does get updated by the callback update_a_value. I would expect, that the value is set to `'Set by callback'` after the page loaded. The http requests are made correctly as shown in the image, but the new value is not rendered...

```python
import dash
import json
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output, State

external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']
app = dash.Dash(__name__, external_stylesheets=external_stylesheets)

app.layout = html.Div([
    dcc.Input(id='a', type='text', value='Initial value'),
    html.Button('Hello', id='button-1')
])


@app.callback(Output('a', 'value'), [Input('button-1', 'n_clicks')])
def update_a_value(unused_clicks):
    return 'Set by callback'


app.run_server(host='0.0.0.0', port=8080, debug=False)

```

![grafik](https://user-images.githubusercontent.com/40601743/54675578-1f138680-4aff-11e9-807c-fa0a30887159.png)

Versions:
```txt
dash-core-components==0.44.0
dash-html-components==0.14.0
dash-renderer==0.20.0
dash==0.39.0
```

**Comment by alexcjohnson** [comment]
Is it fixed if `a.value` is an input to a different callback? If so, this will be fixed in the next release, by https://github.com/plotly/dash-renderer/pull/126

**Comment by sinsemellan** [comment]
Yes, it is indeed. Sorry for reporting.
