### ISSUE TITLE
Feature Request: Dynamic Serving of Dash App

### ISSUE THREAD

**Issue by notatallshaw** [plotly/dash#662]
By having some way to provide a custom URL, could be an endpoint variable e.g. `/app/<name>` or a url_query string e.g. `/?app=app_name` I would like to serve an existing Dash App or to create a Dash App at request time and then serve it.

I already do this by manipulating the internal state of Flask to provide an app where users can create their own personalized and customizale Dash Boards.. This is a big ask, I don't expect it to be officially supported, but it would make Dash more viable for building applications that allow for customized user pages.

**Comment by alexcjohnson** [comment]
Is `routes_pathname_prefix` what you're looking for?
https://dash.plot.ly/integrating-dash

**Comment by notatallshaw** [comment]
> Is `routes_pathname_prefix` what you're looking for?
> https://dash.plot.ly/integrating-dash

No, I already use this, you have to define them all before you run the Flask server. My use case is:
 1. Start Server
 2. User wants to create new page, this could be "`/<username>/<new_page_name>`" or even "`/existing_endpoint/?username=<username>&page=<new_page_name>`", but the point is the page has custom layout and custom callbacks
 3. In background I create a new `dash.Dash()` app
 4. User goes to their new page and sees the new `dash.Dash()` app I have created

This could be unsupportable and/or the wrong approach, but it achieves to me what seem like 2 important goals over other multi-page approaches:
 1. I never have to enable `app.config.suppress_callback_exceptions = True`
 2. The new page/app can be completely custom, if the user wants 100s of graphs or datatables in the layout with each of them associated with their own callbacks, I don't need to anticipate that before starting the server.

**Comment by alexcjohnson** [comment]
Ah OK, I see what you're after. Yeah, that's a really interesting feature, but it'll probably take a bit of digging into flask to figure out how we should implement it.

If anyone is interested in taking a swing at it we'd gladly review a PR :)

**Comment by notatallshaw** [comment]
Unfortunately my current company has a very strict "no pushing code developed onsite to github" policy. But if that ever changes in the future I will do my best  to help out with some PRs.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson

**Comment by notatallshaw** [comment]
Alas, I no longer get to work with dash in my current job. 

However I believe since this was posted dash has implemented many features which would make this request less likely to still be needed.

Thanks for continued development of this great tool!
