### ISSUE TITLE
Feature Request: Selectable Shapes or Absolute Marker Sizes

### ISSUE THREAD

**Issue by SterlingButters** [plotly/dash#664]
At first I started with shapes since their size can be explicitly defined in the same domain as the data (i.e. not an arbitrary number that doesn't correspond with the data as with marker size attribute). However, the problem that arises is that shapes do not express any visual feedback when selected (in `selectData`) as markers do. 

So, unfortunately, I've run into a limitation with each method (shapes don't provide feedback when selected nor are they selectable [however you could put a transparent marker in the center which I did for awhile] and marker sizes/shapes cannot be defined in the same domain as the data). Alternatively, I think it might be useful to explicitly define the size and shape of a marker in the same "domain" as the data so that if you were to zoom in or out, the dimensions of the marker do not scale but instead maintain the specified dimensions because its size and shape is important relative to the data. 

Additionally, this would provide some more freedom in customizing the marker i.e. the marker could be defined by an aggregate of shape objects. That is, if it is important that a data point be represented by a red square behind a blue circle each of a specific size - it could be done.

**Comment by alexcjohnson** [comment]
These features belong in https://github.com/plotly/plotly.js rather than in dash. I seem to recall data-referenced marker sizes already having an open issue, so please search a bit before opening a new one, but if not, they're definitely features we'd consider adding.
