### ISSUE TITLE
Favicon is being overwritten by Dash

### ISSUE THREAD

**Issue by joseangel-sc** [plotly/dash#665]
![Screen Shot 2019-03-26 at 16 58 16](https://user-images.githubusercontent.com/21244244/55039150-b3428980-4fe8-11e9-81cd-7822fa3cd151.png)

We have a favicon included in our static folder, and we are also routing using 
```
@app.server.route('/favicon.ico')
def favicon():
    return flask.send_from_directory(os.path.join(app.server.root_path, 'static'),
                                     'favicon.ico', mimetype='image/x-icon')

```

on our ```app.py``` 

This was working fine on previous versions, but now Dash adds this '_favicon.ico' in the frontend

**Comment by shengqiangzhang** [comment]
I have the same problem.do you have the suggested way for this problem?
