### ISSUE TITLE
Doesn't render anything on the page

### ISSUE THREAD

**Issue by bakirillov** [plotly/dash#673]
Hello!
Dash doesn't work completely and I have zero ideas why. 
Renders nothing at all. Even minimal example like https://gist.github.com/bakirillov/1c2e838ab70e0248a98b69651760385a doesn't work.
On startup prints out that error:
VisibleDeprecationWarning:
zmq.eventloop.minitornado is deprecated in pyzmq 14.0 and will be removed.
    Install tornado itself to use zmq with the tornado IOLoop.
Tornado 6.0.1. is installed, dash version is 0.39, pyzmq version is 17.01.
Could you please look into that?

**Comment by alexcjohnson** [comment]
Odd, that example works for me.
![Screen Shot 2019-04-01 at 3 30 23 PM](https://user-images.githubusercontent.com/2678795/55354625-386be980-5494-11e9-9141-d7095fe3bf0d.png)
We don't use Tornado or ZMQ but made sure I had them installed just to be sure (got 6.0.2 and 18.0.1) and the app still works, no messages.

So I'm as puzzled as you are 🤔

**Comment by bakirillov** [comment]
Resolved. Just had to purge pyzmq, tornado and dash.
