### ISSUE TITLE
tree widget sidebar

### ISSUE THREAD

**Issue by h5rdly** [plotly/dash#683]
Hi,

First of all, this is an awesome project, cheers.

I started to implement an SQL dashboard with an editor, and got stuck with the sidebar.

Is there some widget I can use, or some other workaround, by which I could present database names, table names, columns etc. on the side in an expandable way using dash?

thanks,
Eli

**Comment by chriddyp** [comment]
There is nothing in our open source offerings that provides this out of the box. You might try doing something with `html.Details` & `html.Summary`, or create your own sidebar wrapper with React.js and the plugin toolchain (https://dash.plot.ly/react-for-python-developers).
