### ISSUE TITLE
Porting dash to work on offline examples

### ISSUE THREAD

**Issue by icaromedeiros** [plotly/dash#7]
I will fork the project and rewrite it using only offline plots.

I am wondering if you want me to merge it somehow here.

**Comment by akapocsi** [comment]
Looking forward to seeing this.

**Comment by icaromedeiros** [comment]
Check out https://github.com/icaromedeiros/dash/tree/dirty

I am beginning to think the best idea is to create a new project and call it plOFFly as plotly members don't seem thrilled I'm working in making plotly more offline-friendly, just check these not answered pull requests / issues: 

https://github.com/plotly/plotly.py/pull/400
https://github.com/plotly/plotly.py/issues/399

**Comment by chriddyp** [comment]
hey @icaromedeiros ! sorry for the radio silence on this one. An offline version of dash would be awesome. This project was originally written before `plotly.js` was open sourced - that's the only reason that the post message embed API was used!

**Comment by icaromedeiros** [comment]
Hello @chriddyp, good to hear from you and thanks for the historical explanations.

Just checked the mentioned pull requests were merged or answered :smile: 

I got the idea about this project being a show-off for plotly.js, python API and server API main features put together in a nice way so you can bootstrap a project using plot.ly's nicest features.

And I know there is some enterprisey reasons to justifiy that ~95% of the examples (and I am including dash as 'code example' here) are online-based. But maybe, IMHO, the overall plotly community will contribute back in a faster way if offline plotting is more user-friendly and quickier to set tup.

And I think dash can play a big role on attracting potential contributors.

Best regards.

**Comment by ispmarin** [comment]
Hey all, 

I believe that a full offline version of `dash` would be awesome for several use cases:

1. Bad or non-existent internet connection
2. Proxies
3. Privacy issues

and so on. So :+1: for this!

**Comment by lucapinello** [comment]
It will be fantastic!  :+1:

**Comment by chriddyp** [comment]
thanks for checking it out @ispmarin @lucapinello @icaromedeiros @akapocsi ! A new version of Dash is now available and it works completely offline ✨

**Comment by akapocsi** [comment]
Awesome. Just saw the blog post on Medium. Looking forward to checking it out in greater detail.

**Comment by akapocsi** [comment]
Looks like a bokeh killer :)
