### ISSUE TITLE
Modify 'transpiler' behaviour when empty string passed as R component prefix

### ISSUE THREAD

**Issue by rpkyle** [plotly/dash#712]
Currently, R components may be generated for Dash using the syntax

`dash-generate-components ./src/components dash_core_components --r-prefix="dcc"`

When `--r-prefix` is blank, the 'transpiler' assumes `dash` is the prefix. This is undesirable for third party components, or libraries such as `dash-canvas`, which already include "dash" in their names.

Alternatively, a better strategy for the 'transpiler' behaviour might be to accept a blank string, e.g.

`dash-generate-components ./src/lib/components dash_canvas --r-prefix=""`

Then, then the 'transpiler' could generate a properly camelCase function name, i.e. `dashCanvas` instead of `DashCanvas`. 

This would maintain parity with existing Plotly component libraries, and further standardize function naming. These details seem minor, but as R is case-sensitive, they remain important.

@alexcjohnson

**Comment by alexcjohnson** [comment]
Yes, `--r-prefix=""` converting to camelCase sounds perfect. Good catch!
