### ISSUE TITLE
Modify 'transpiler' to properly handle 'dev' bundles

### ISSUE THREAD

**Issue by rpkyle** [plotly/dash#716]
The R 'transpiler' does not currently appear to properly create the internal JavaScript metadata function. Dependencies ending in `*.dev.js` should be mapped to their shortnames with `-dev` appended.

In other words, any JavaScript including `dev` in its filename should be tagged as a bundle to be served in developer/debug mode, while all others should not be so labeled.

https://github.com/plotly/dash/blob/ec1576c3652cbb90ffb064abe2753a17e13f3c51/dash/development/_r_components_generation.py#L258-L284

**Comment by rpkyle** [comment]
@alexcjohnson @byronz @Marc-Andre-Rivet We still want to support loading `*.dev.js` bundles when in debug mode, right? 

Even if we're using source maps for some of our libraries, this feature isn't intended to go away anytime soon?

I only ask because of https://github.com/plotly/dash-html-components/pull/113#issue-278468029:
> _the dev build was useful before we used external source maps on the prod build -- prod and dev are now redundant as the source map is always available_

**Comment by Marc-Andre-Rivet** [comment]
The main concern when we created the `dev` files was for debugging / including source-map. I would be in favor of removing them for projects that don't have a different `dev` implementation. My understanding is that only `renderer` has dev-specific implementation details. Do they serve another purpose?

**Comment by rpkyle** [comment]
> _My understanding is that only renderer has dev-specific implementation details. Do they serve another purpose?_

This is a bit of a difficult question for me to answer, since I'm not working as a JS developer of Dash component libraries. I've been told in the past that I should load dev bundles when `debug = TRUE` in DashR, but I asked because I wasn't sure if we were revisiting this conversation.

I'm happy to close this PR without working on it any further, if it's been deemed unnecessary.

**Comment by alexcjohnson** [comment]
Right, AFAIK only renderer currently has any functional difference between dev and prod bundles, but we shouldn't restrict our ability to load dev bundles to just that one. Any component developer should be allowed to provide a dev bundle and have it loaded when `debug=True`, but if not we still load the prod bundle.
