### ISSUE TITLE
Unable to install dash

### ISSUE THREAD

**Issue by sukhadakulkarni** [plotly/dash#73]
While installing dash, I am running into following issue.

```
$ pip install dash==0.17.7
Collecting dash==0.17.7
  Could not fetch URL https://pypi.python.org/simple/dash/: 
  There was a problem confirming the ssl certificate: EOF occurred in violation of protocol (_ssl.c:590) - skipping
  Could not find a version that satisfies the requirement dash==0.17.7 (from versions: )
No matching distribution found for dash==0.17.7
```

**Comment by bmike78** [comment]
When I browsed https://pypi.python.org/simple/dash/ just a couple minutes ago, I did not see 0.17.7, but now I do and it installed for me.

Try again?  If it doesn't work, are you having problems installing other python packages via pip or is there perhaps a proxy in between you and the internet?

**Comment by mostaszewski** [comment]
I think this might be useful for You:
[https://stackoverflow.com/a/29751768](https://stackoverflow.com/a/29751768)

**Comment by jpatel3** [comment]
try `pip install --trusted-host pypi.python.org dash==0.17.7`

**Comment by chriddyp** [comment]
@sukhadakulkarni - are you able to install any other packages from pypi successfully? For example, try:
```
pip install plotly
```

**Comment by sukhadakulkarni** [comment]
Thank you everyone for suggestions here. There was an issue with my SSL due to proxy issue. Interestingly this issue was intermittent, and I could fix it now. I was able to install dash and also created a dashboard!

**Comment by Soheb1716** [comment]
> 
> 
> try `pip install --trusted-host pypi.python.org dash==0.17.7`

Anything id not working
