### ISSUE TITLE
Flask instance, server's name and `None` stuff

### ISSUE THREAD

**Issue by HorlogeSkynet** [plotly/dash#74]
Hello there !

In the `dash.py` (line 50), you'll get an error if you try to create a Dash server using a Flask one, without any specified name in the constructor.
Just a missing case checking, fixable very quickly 😉 

Ciao 👌 

> Traceback (most recent call last):
  File "main.py", line 22, in <module>
    dash = Dash(server=flask)
  File "~/env/lib/python3.5/site-packages/dash/dash.py", line 50, in \_\_init\_\_
    name.replace('.', '_')
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by yunake** [comment]
This is addressed in #32

**Comment by HorlogeSkynet** [comment]
Closing here, as it's addressed in #32...
Hope it'll merged soon 👌

Bye 👋
