### ISSUE TITLE
[Feature Request] Dash-Renderer API

### ISSUE THREAD

**Issue by shyamd** [plotly/dash#747]
Because I'm a curious George, I've been reading the plotly dash code to get an idea of how the core python Dash app works. My understanding at this point is this:
1. It sets up a Flask Server:
  a. basic settings
  b. blueprint for static assets
  c. error handlers
  d. routes for critical capabilities: serving layouts, dependencies, component-suites, updating components
2. Provides the callback decorators that register callbacks into a callback map. This gets translated into dependencies 
3. Provides the layout setter that builds the layout and figures out component-suites,
3. Builds the index HTML and sets up the flask server to serve this. 
4. The HTML renders the dash-renderer with just enough to call back home using the aforementioned routes to get all additional information and do its thing. 

What I don't understand is the dash-renderer, but since I'm very bad with JS, I probably will never fully understand it by just reading the JS code. **What would help a lot is having some sort of API  specification for the dash-render that tells us how Dash Flask server interacts with the dash-renderer: IE what is the sequence of interaction, what routes the dash-rendered interacts with, what data is exchanged, what format this data is and what the corresponding schema is.**

**Comment by byronz** [comment]
@shyamd  thanks for the interest of dash, I had some ideas about this when I joined dash team couple months ago. But we don't have much time slot on this topic now. what I can tell is there is a better chance after the dash 1.0 and our merging of monorepo is more stable. 

For python developers not familiar with js, what you can get right now without waiting for our crafted nice documentation is more than you can imagine:

firstly, you have the powerful dev tools from Chrome and Firefox, where you can easily see the full interaction in live without reading any js code.  the `network` tab is always your friend.

![Screen Shot 2019-05-29 at 11 39 58 AM](https://user-images.githubusercontent.com/1394467/58570789-9011a180-8206-11e9-8d28-8a31164b209d.png)

secondly, if you run your app in debug mode and install the official redux browser [plugin](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en) and react [plugin](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en)
you will find out even more interesting stuff.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
