### ISSUE TITLE
html.Form() syntax

### ISSUE THREAD

**Issue by ibdafna1** [plotly/dash#75]
Great framework. Very good job, Chris!

within dash_html_components we have the Form() method. I'm not seeing a way to set the type in there. Is there something I'm missing? Are we supposed to use dash_core_components as the only source of user inputs? Would like to use a date picker for my app.

Thanks!

EDIT:
I figured this out. 

We can use dcc.Input(type='date) which is rendered in html, and is effectively what I was looking for. 

Good to close!

**Comment by chriddyp** [comment]
Just a little heads up that a highly customizable date-picker with cross-browser support is coming soon: https://github.com/plotly/dash-core-components/pull/49
