### ISSUE TITLE
Calling Dash from Flask App with Parameters

### ISSUE THREAD

**Issue by shril** [plotly/dash#752]
I have a problem statement in which I have to dynamically change the CSVs from which Dash App has to create a Dashboard.

There is an HTML table in my Flask App like this - 

| Media Name | Media Type | View |
| ------------- |:-------------|:-----|
| Tron Legacy    |  mp4              | [Dashboard]() 
| Avengers        |  mp4              | [Dashboard]()
| Iris                   |  jpg                | [Dashboard]()
| Taj Mahal        |  jpg              | [Dashboard]()

Assuming that there is a single dash app which switches views on the basis of the CSV.
How can we pass a parameter, so as to render a dashboard for each record in the table?

**Comment by alexcjohnson** [comment]
`dcc.Link` and `dcc.Location` will do this for you - see https://dash.plot.ly/urls. For more information, examples, and help, check out https://community.plot.ly/c/dash

**Comment by shril** [comment]
@alexcjohnson, thanks that helps.

**Comment by Juggernaut1997** [comment]
Hi shril, can you help me with same. I am trying to put dash url to flask html button but i am getting nothing
Please help me if you can
