### ISSUE TITLE
Dash R package generator should supply useful error if description missing from props

### ISSUE THREAD

**Issue by rpkyle** [plotly/dash#757]
The R package generator currently throws a generic `KeyError` if a `description` field is missing from component properties. A more useful error should be supplied, or a blank `description` inserted with a warning.

@alexcjohnson Not sure which is preferable here, but should do something more helpful than the current behaviour 🙂

**Comment by alexcjohnson** [comment]
As far as the R generator is concerned let's just insert a blank with no warning.

We already have warnings from `extract-meta` when descriptions are missing, and we've talked about making that a fatal error. It'll probably have to be optional and opt-in though, at least in the short term, so each package can upgrade to required descriptions independently.
