### ISSUE TITLE
[BUG] min_date_allowed and max_date_allowed broken for datepickerrange

### ISSUE THREAD

**Issue by PerKjelsvik** [plotly/dash#758]
```
dash                   0.43.0  
dash-core-components   0.48.0  
dash-html-components   0.16.0  
dash-renderer          0.24.0  
dash-table             3.7.0 
```

    - OS: Ubuntu 18.04.2 LTS
    - Browser: chrome / firefox
    - Version: 74.0.3729.169 (Official Build) (64-bit) / Version 67.0 (64-bit)

The properties `min_date_allowed` and `max_date_allowed` does not work. I discovered this issue first in my own code, and I suspected that it might be due to some custom css or version of dash etc. However, if you visit [the user guide for `datepickerrange`](https://dash.plot.ly/dash-core-components/datepickerrange), the bug can be seen in the very first example. Neither constraint works for the calendar. Interestingly, the bug is not present in the `datepickersingle` component, as can be seen in the first example of [the user guide for `datepickersingle`](https://dash.plot.ly/dash-core-components/datepickersingle). 

In addition, the rendering issue that [dash-core-components#549](https://github.com/plotly/dash-core-components/issues/549) reported is still present, in both `datepickerrange` and `datepickersingle`. I have used the css fix that @brolewis provided in my own code without any apparent issues. 

Screenshot of `datepickerrange`:
![datepickerrange](https://user-images.githubusercontent.com/21362776/58813787-ca26dd00-8624-11e9-8e6b-8455122d2046.png)

Screenshot of `datepickersingle`:
![singledatepicker](https://user-images.githubusercontent.com/21362776/58813790-cb580a00-8624-11e9-99f7-a9a0c645cf53.png)

EDIT: Sorry, this should perhaps have been posted as an issue in the [`dash-core-components`](https://github.com/plotly/dash-core-components) repository, feel free to move it there.
EDIT2: I now see that there has already been reported two issues about this in the other repository: [dash-core-components#557](https://github.com/plotly/dash-core-components/issues/557) and [dash-core-components#551](https://github.com/plotly/dash-core-components/issues/551). Only looked for similar open issues in this repo, sorry. Let me know if I should add my error report as a comment to the already opened issues there. You can mark this as a duplicate in that case.

**Comment by byronz** [comment]
@PerKjelsvik  this bug has been fixed by https://github.com/plotly/dash-core-components/pull/561 thanks to @mmartinsky
