### ISSUE TITLE
Any planned support for data* or aria-* options?

### ISSUE THREAD

**Issue by rc1405** [plotly/dash#78]
As the title indicates, any planned support for the above options add they are supported in react?  Main use case would be for using bootstrap within apps.

**Comment by chriddyp** [comment]
Good idea. It seems like we should support this.

It'll be a little bit tricky because `data-*` and `aria-*` are regex properties. Our dynamic component generation code depends on a strict set of properties rather than a pattern of property names (see https://github.com/plotly/dash/blob/master/dash/development/base_component.py#L188-L259).

**Comment by rc1405** [comment]
Full disclosure, I don't have access to my development area but wanted to throw some initial thoughts together.  The catch is you would have to replace the dash (-) with an underscore(_) when initially initiating.  There are some documentation flaws in doing it this way that would need to be corrected, but some thoughts to debate.

`>>> import dash_html_components as html
>>> html.Div("testing", data_test="#testing")
Div(children='testing', data-test='#testing')
>>> 
`

https://github.com/rc1405/dash/blob/bootstrap/dash/development/base_component.py

**Comment by rc1405** [comment]
or even add the available properties for each class of: data_flags=[{"test": "#testing"] and aria_flags[{"key": "value"}], which can be propagated to data-test="#testing" and aria-key="value" in base_component.py

**Comment by rc1405** [comment]
First method of https://github.com/rc1405/dash/blob/bootstrap/dash/development/base_component.py

```import dash
import dash_html_components as html

app = dash.Dash()

app.layout = html.Div([
    html.H1('Hello Dash'),

    html.Div('''
        Dash: A web application framework for Python.
    '''),

], data_stuff='blah')

if __name__ == '__main__':
    app.run_server(host='0.0.0.0', port=8080)```

Provides capability such as:

![image](https://user-images.githubusercontent.com/13261087/28243694-367d114e-699a-11e7-9c9e-3b7948c1579d.png)

**Comment by javValverde** [comment]
I am also really interested in using bootstrap with dash! Are there any plans for implementing it?

**Comment by chriddyp** [comment]
I wrote a guide on how to add support for this in Dash in https://community.plot.ly/t/can-data-attributes-be-created-in-dash/7222/2?u=chriddyp

**Comment by chriddyp** [comment]
Done in https://github.com/plotly/dash/pull/237
