### ISSUE TITLE
[BUG]ModuleNotFoundError: No module named '_plotly_future_'

### ISSUE THREAD

**Issue by tsokadev** [plotly/dash#792]
**Describe your context**
Please provide us your environment so we can easily reproduce the issue.
I am using **Python 3.6.6** from the **Anaconda** rpi repository. I am using **berryconda** to create a **conda** virtual environment.

```
dash                 0.43.0
dash-core-components 0.48.0
dash-daq             0.1.5
dash-html-components 0.16.0
dash-renderer        0.24.0
dash-table           3.7.0
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: [Raspbian Stretch]
    - Browser [Web ]
    - Version [ 3.8.2]

**Describe the bug**

Whenever I run a python script which imports the **Dash** module, a **ModuleNotFoundExceptionError** is thrown:
```
Exception has occurred: ModuleNotFoundError
No module named '_plotly_future_'
  File "/home/pi/tdunit/app.py", line 3, in <module>
    import dash
  File "/home/pi/berryconda3/envs/tdunitenv/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/berryconda3/envs/tdunitenv/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/pi/berryconda3/envs/tdunitenv/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)

```
**Expected behavior**

I expect the program to execute normally. I have even tried the [getting started example for Dash](https://dash.plot.ly/getting-started) and the same error occurs. 

**Screenshots**

![Dash_error](https://user-images.githubusercontent.com/19230635/60115513-6486c600-9776-11e9-84c1-a20c0a5dfee5.PNG)

**Comment by alexcjohnson** [comment]
weird - `_plotly_future_` should have come in with `plotly`. What version of the `plotly` package do you have?
@jonmmease any idea what's going on?

**Comment by jonmmease** [comment]
This kind of thing is usually caused by there being multiple copies of plotly.py installed at the same time. Can you check the output of 

pip list

and 

conda list

to see what versions of the plotly package are installed?

**Comment by tsokadev** [comment]
@alexjohnson, @jonmmease it appears that I have only 1 version of plotly:
```
(tdenv) pi@tdunit:~ $ conda list
# packages in environment at /home/pi/berryconda3/envs/tdenv:
#
# Name                    Version                   Build  Channel
attrs                     19.1.0                    <pip>
ca-certificates           2018.8.24                     0  
certifi                   2018.8.24                py36_1  
chardet                   3.0.4                     <pip>
Click                     7.0                       <pip>
dash                      0.36.0                    <pip>
dash-core-components      0.42.1                    <pip>
dash-daq                  0.1.4                     <pip>
dash-html-components      0.13.4                    <pip>
dash-renderer             1.0.0                     <pip>
DateTime                  4.2                       <pip>
decorator                 4.4.0                     <pip>
Flask                     1.0.3                     <pip>
Flask-Compress            1.4.0                     <pip>
gunicorn                  19.8.1                    <pip>
idna                      2.8                       <pip>
ipython-genutils          0.2.0                     <pip>
itsdangerous              1.1.0                     <pip>
Jinja2                    2.10.1                    <pip>
jsonschema                3.0.1                     <pip>
jupyter-core              4.5.0                     <pip>
libgfortran               3.0.0                         0  
MarkupSafe                1.1.1                     <pip>
nbformat                  4.4.0                     <pip>
ncurses                   6.1                  h4f752ac_1  
numpy                     1.14.0           py36h73aad69_0  
numpy                     1.16.1                    <pip>
openblas                  0.2.19                        0  
openssl                   1.0.2r               hdff2a78_0  
pandas                    0.23.4                    <pip>
pip                       18.0                     py36_1  
plotly                    3.1.0                     <pip>
pyrsistent                0.15.2                    <pip>
python                    3.6.6                hd0568c0_1  
python-dateutil           2.8.0                     <pip>
pytz                      2019.1                    <pip>
readline                  7.0                  hcb560eb_1  
requests                  2.22.0                    <pip>
retrying                  1.3.3                     <pip>
scipy                     1.0.0            py36h741f5fb_0  
setuptools                40.2.0                   py36_0  
six                       1.12.0                    <pip>
sqlite                    3.24.0               hfcb1bcf_1  
tk                        8.6.8                h849d6a0_0  
traitlets                 4.3.2                     <pip>
urllib3                   1.25.3                    <pip>
Werkzeug                  0.15.4                    <pip>
wheel                     0.31.1                   py36_1  
xz                        5.2.4                hdff2a78_1  
zlib                      1.2.11            hdff2a78_1003  
zope.interface            4.6.0                     <pip>
```

I get a segmentation fault if I do `pip list` inside the virtual environment. 
```
(tdenv) pi@tdunit:~ $ pip list
Segmentation fault

```

Outside the virtual environment:
```
pi@tdunit:~ $ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
asn1crypto (0.22.0)
astroid (2.0.2)
certifi (2018.8.24)
cffi (1.10.0)
chardet (3.0.4)
conda (4.5.11)
cryptography (1.9)
idna (2.5)
isort (4.3.4)
lazy-object-proxy (1.3.1)
mccabe (0.6.1)
packaging (16.8)
pip (9.0.1)
pycosat (0.6.3)
pycparser (2.17)
pylint (2.1.1)
pyOpenSSL (16.2.0)
pyparsing (2.2.0)
requests (2.18.1)
ruamel.yaml (0.11.7)
setuptools (36.0.1)
six (1.10.0)
typed-ast (1.1.0)
urllib3 (1.21.1)
wheel (0.29.0)
wrapt (1.10.11)
```
Conda list outside virtual environment:

```
pi@tdunit:~ $ conda list
# packages in environment at /home/pi/berryconda3:
#
# Name                    Version                   Build  Channel
asn1crypto                0.22.0                   py36_0  
astroid                   2.0.2                    py36_0  
ca-certificates           2018.8.24                     0  
certifi                   2018.8.24                py36_1  
cffi                      1.10.0                   py36_0  
chardet                   3.0.4                    py36_0  
conda                     4.5.11                   py36_0  
conda-env                 2.6.0                         1  
cryptography              1.9                      py36_0  
idna                      2.5                      py36_0  
isort                     4.3.4                    py36_0  
lazy-object-proxy         1.3.1                    py36_0  
libffi                    3.2.1                         0  
mccabe                    0.6.1                      py_1  
ncurses                   5.9                           0  
openssl                   1.0.2r               hdff2a78_0  
packaging                 16.8                     py36_0  
pip                       9.0.1                    py36_0  
pycosat                   0.6.3            py36hdff2a78_1  
pycparser                 2.17                     py36_0  
pylint                    2.1.1                    py36_0  
pyopenssl                 16.2.0                   py36_0  
pyparsing                 2.2.0                    py36_0  
python                    3.6.1                         0  
readline                  6.3                           0  
requests                  2.18.1                   py36_0  
ruamel_yaml               0.11.14                  py36_0  
setuptools                36.0.1                   py36_0  
six                       1.10.0                   py36_0  
sqlite                    3.15.0                        0  
tk                        8.6.6                         0  
typed-ast                 1.1.0            py36hdff2a78_0  
urllib3                   1.21.1                   py36_0  
wheel                     0.29.0                   py36_0  
wrapt                     1.10.11          py36hf843537_0  
xz                        5.2.2                         0  
yaml                      0.1.6                         0  
zlib                      1.2.11                        0  
```

**Comment by jonmmease** [comment]
Hi @tsokadev ,

Something odd is going on with the plotly vesions.  The virtual environment reports plotly version 3.1.0, but this version predates the `_plotly_future_` module. So the `plotly.py` file at `site-packages/plotly/__init__.py` somehow came from a different plotly installation.  You could try uninstall plotly using pip and then reinstalling version 3.10.0.

Also, getting a segmentation fault when calling `pip list` from your virtual environment is a bit concerning.  Perhaps there is some inconsistency in the environment that is causing both problems.

**Comment by florencejt** [comment]
Hi, I've got the same problem as @tsokadev 

`(base) Florence:plotly florence.townend$ conda list
# packages in environment at /Users/florence.townend/anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0  
absl-py                   0.7.1                    pypi_0    pypi
alabaster                 0.7.12                   py37_0  
anaconda-client           1.7.2                    py37_0  
anaconda-navigator        1.9.7                    py37_0  
anaconda-project          0.8.2                    py37_0  
appnope                   0.1.0                    py37_0  
appscript                 1.1.0            py37h1de35cc_0  
asn1crypto                0.24.0                   py37_0  
astor                     0.8.0                    pypi_0    pypi
astroid                   2.2.5                    py37_0  
astropy                   3.1.2            py37h1de35cc_0  
atomicwrites              1.3.0                    py37_1  
attrs                     19.1.0                   py37_1  
babel                     2.6.0                    py37_0  
backcall                  0.1.0                    py37_0  
backports                 1.0                      py37_1  
backports.os              0.1.1                    py37_0  
backports.shutil_get_terminal_size 1.0.0                    py37_2  
beautifulsoup4            4.7.1                    py37_1  
bitarray                  0.8.3            py37h1de35cc_0  
bkcharts                  0.2                      py37_0  
blas                      1.0                         mkl  
bleach                    3.1.0                    py37_0  
blosc                     1.15.0               hd9629dc_0  
bokeh                     1.0.4                    py37_0  
boto                      2.49.0                   py37_0  
bottleneck                1.2.1            py37h1d22016_1  
bzip2                     1.0.6                h1de35cc_5  
ca-certificates           2019.5.15                     0  
cairo                     1.14.12              hc4e6be7_4  
certifi                   2019.6.16                py37_0  
cffi                      1.12.2           py37hb5b8e2f_1  
chardet                   3.0.4                    py37_1  
click                     7.0                      py37_0  
cloudpickle               0.8.0                    py37_0  
clyent                    1.2.2                    py37_1  
colorama                  0.4.1                    py37_0  
conda                     4.6.14                   py37_0  
conda-build               3.17.8                   py37_0  
conda-env                 2.6.0                         1  
conda-verify              3.1.1                    py37_0  
contextlib2               0.5.5                    py37_0  
cryptography              2.6.1            py37ha12b0ac_0  
curl                      7.64.0               ha441bb4_2  
cycler                    0.10.0                   py37_0  
cython                    0.29.6           py37h0a44026_0  
cytoolz                   0.9.0.1          py37h1de35cc_1  
dash                      1.0.0                    pypi_0    pypi
dash-core-components      1.0.0                    pypi_0    pypi
dash-daq                  0.1.0                    pypi_0    pypi
dash-html-components      1.0.0                    pypi_0    pypi
dash-renderer             1.0.0                    pypi_0    pypi
dash-table                4.0.0                    pypi_0    pypi
dask                      1.1.4                    py37_1  
dask-core                 1.1.4                    py37_1  
dbus                      1.13.6               h90a0687_0  
decorator                 4.4.0                    py37_1  
defusedxml                0.5.0                    py37_1  
distributed               1.26.0                   py37_1  
docutils                  0.14                     py37_0  
entrypoints               0.3                      py37_0  
et_xmlfile                1.0.1                    py37_0  
expat                     2.2.6                h0a44026_0  
fastcache                 1.0.2            py37h1de35cc_2  
ffmpeg                    4.0                  h01ea3c9_0  
filelock                  3.0.10                   py37_0  
flask                     1.0.2                    py37_1  
flask-compress            1.4.0                    pypi_0    pypi
fontconfig                2.13.0               h5d5b041_1  
freetype                  2.9.1                hb4e5f40_0  
future                    0.17.1                   py37_0  
gast                      0.2.2                    pypi_0    pypi
get_terminal_size         1.0.0                h7520d66_0  
gettext                   0.19.8.1             h15daf44_3  
gevent                    1.4.0            py37h1de35cc_0  
glib                      2.56.2               hd9629dc_0  
glob2                     0.6                      py37_1  
gmp                       6.1.2                hb37e062_1  
gmpy2                     2.0.8            py37h6ef4df4_2  
graphite2                 1.3.13               h2098e52_0  
greenlet                  0.4.15           py37h1de35cc_0  
grpcio                    1.21.1                   pypi_0    pypi
h5py                      2.8.0            py37h878fce3_3  
harfbuzz                  1.8.8                hb8d4a28_0  
hdf5                      1.10.2               hfa1e0ec_1  
heapdict                  1.0.0                    py37_2  
html5lib                  1.0.1                    py37_0  
icu                       58.2                 h4b95b61_1  
idna                      2.8                      py37_0  
imageio                   2.5.0                    py37_0  
imagesize                 1.1.0                    py37_0  
importlib_metadata        0.8                      py37_0  
intel-openmp              2019.3                      199  
ipykernel                 5.1.0            py37h39e3cac_0  
ipython                   7.4.0            py37h39e3cac_0  
ipython_genutils          0.2.0                    py37_0  
ipywidgets                7.4.2                    py37_0  
isort                     4.3.16                   py37_0  
itsdangerous              1.1.0                    py37_0  
jasper                    2.0.14               h636a363_1  
jbig                      2.1                  h4d881f8_0  
jdcal                     1.4                      py37_0  
jedi                      0.13.3                   py37_0  
jinja2                    2.10                     py37_0  
jpeg                      9b                   he5867d9_2  
jsonschema                3.0.1                    py37_0  
jupyter                   1.0.0                    py37_7  
jupyter_client            5.2.4                    py37_0  
jupyter_console           6.0.0                    py37_0  
jupyter_core              4.4.0                    py37_0  
jupyterlab                0.35.4           py37hf63ae98_0  
jupyterlab_server         0.2.0                    py37_0  
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.0                    pypi_0    pypi
keyring                   18.0.0                   py37_0  
kiwisolver                1.0.1            py37h0a44026_0  
krb5                      1.16.1               hddcf347_7  
lazy-object-proxy         1.3.1            py37h1de35cc_2  
libarchive                3.3.3                h786848e_5  
libcurl                   7.64.0               h051b688_2  
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libedit                   3.1.20181209         hb402a30_0  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 hdd342a3_7  
liblief                   0.9.0                h2a1bed3_2  
libopencv                 3.4.2                h7c891bd_1  
libopus                   1.3                  h1de35cc_0  
libpng                    1.6.36               ha441bb4_0  
libsodium                 1.0.16               h3efe00b_0  
libssh2                   1.8.0                ha12b0ac_4  
libtiff                   4.0.10               hcb84e12_2  
libvpx                    1.7.0                h378b8a2_0  
libxml2                   2.9.9                hab757c2_0  
libxslt                   1.1.33               h33a18ac_0  
llvmlite                  0.28.0           py37h8c7ce04_0  
locket                    0.2.0                    py37_1  
lxml                      4.3.2            py37hef8c89e_0  
lz4-c                     1.8.1.2              h1de35cc_0  
lzo                       2.10                 h362108e_2  
markdown                  3.1.1                    pypi_0    pypi
markupsafe                1.1.1            py37h1de35cc_0  
matplotlib                3.0.3            py37h54f8f79_0  
mccabe                    0.6.1                    py37_1  
mistune                   0.8.4            py37h1de35cc_0  
mkl                       2019.3                      199  
mkl-service               1.1.2            py37hfbe908c_5  
mkl_fft                   1.0.10           py37h5e564d8_0  
mkl_random                1.0.2            py37h27c97d8_0  
mock                      3.0.5                    pypi_0    pypi
more-itertools            6.0.0                    py37_0  
mpc                       1.1.0                h6ef4df4_1  
mpfr                      4.0.1                h3018a27_3  
mpmath                    1.1.0                    py37_0  
msgpack-python            0.6.1            py37h04f5b5a_1  
multipledispatch          0.6.0                    py37_0  
mxnet                     1.3.1                    pypi_0    pypi
navigator-updater         0.2.1                    py37_0  
nbconvert                 5.4.1                    py37_3  
nbformat                  4.4.0                    py37_0  
ncurses                   6.1                  h0a44026_1  
networkx                  2.2                      py37_1  
nltk                      3.4                      py37_1  
nose                      1.3.7                    py37_2  
notebook                  5.7.8                    py37_0  
numba                     0.43.1           py37h6440ff4_0  
numexpr                   2.6.9            py37h7413580_0  
numpy                     1.16.2           py37hacdab7b_0  
numpy-base                1.16.2           py37h6575580_0  
numpydoc                  0.8.0                    py37_0  
olefile                   0.46                     py37_0  
onnx                      1.5.0                    pypi_0    pypi
opencv                    3.4.2            py37h6fd60c2_1  
openpyxl                  2.6.1                    py37_1  
openssl                   1.1.1c               h1de35cc_1  
packaging                 19.0                     py37_0  
pandas                    0.24.2           py37h0a44026_0  
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py37_1  
parso                     0.3.4                    py37_0  
partd                     0.3.10                   py37_1  
path.py                   11.5.0                   py37_0  
pathlib2                  2.3.3                    py37_0  
patsy                     0.5.1                    py37_0  
pcre                      8.43                 h0a44026_0  
pep8                      1.7.1                    py37_0  
percy                     2.0.2                    pypi_0    pypi
pexpect                   4.6.0                    py37_0  
pickleshare               0.7.5                    py37_0  
pillow                    5.4.1            py37hb68e598_0  
pip                       19.1.1                   pypi_0    pypi
pixman                    0.38.0               h1de35cc_0  
pkginfo                   1.5.0.1                  py37_0  
plotly                    3.10.0                   pypi_0    pypi
pluggy                    0.9.0                    py37_0  
ply                       3.11                     py37_0  
prometheus_client         0.6.0                    py37_0  
prompt_toolkit            2.0.9                    py37_0  
protobuf                  3.6.1                    pypi_0    pypi
psutil                    5.6.1            py37h1de35cc_0  
ptyprocess                0.6.0                    py37_0  
pvlive-api                0.3                      pypi_0    pypi
py                        1.8.0                    py37_0  
py-lief                   0.9.0            py37h1413db1_2  
py-opencv                 3.4.2            py37h7c891bd_1  
pycodestyle               2.5.0                    py37_0  
pycosat                   0.6.3            py37h1de35cc_0  
pycparser                 2.19                     py37_0  
pycrypto                  2.6.1            py37h1de35cc_9  
pycurl                    7.43.0.2         py37ha12b0ac_0  
pyflakes                  2.1.1                    py37_0  
pygments                  2.3.1                    py37_0  
pylint                    2.3.1                    py37_0  
pyodbc                    4.0.26           py37h0a44026_0  
pyopenssl                 19.0.0                   py37_0  
pyparsing                 2.3.1                    py37_0  
pyqt                      5.9.2            py37h655552a_2  
pyrsistent                0.14.11          py37h1de35cc_0  
pysocks                   1.6.8                    py37_0  
pytables                  3.4.4            py37h13cba08_0  
pytest                    4.3.1                    py37_0  
pytest-arraydiff          0.3              py37h39e3cac_0  
pytest-astropy            0.5.0                    py37_0  
pytest-doctestplus        0.3.0                    py37_0  
pytest-mock               1.10.4                   pypi_0    pypi
pytest-openfiles          0.3.2                    py37_0  
pytest-remotedata         0.3.1                    py37_0  
pytest-sugar              0.9.2                    pypi_0    pypi
python                    3.7.3                h359304d_0  
python-dateutil           2.8.0                    py37_0  
python-graphviz           0.8.4                    pypi_0    pypi
python-libarchive-c       2.8                      py37_6  
python.app                2                        py37_9  
pytz                      2018.9                   py37_0  
pywavelets                1.0.2            py37h1d22016_0  
pyyaml                    5.1              py37h1de35cc_0  
pyzmq                     18.0.0           py37h0a44026_0  
qt                        5.9.7                h468cd18_1  
qtawesome                 0.5.7                    py37_1  
qtconsole                 4.4.3                    py37_0  
qtpy                      1.7.0                    py37_1  
readline                  7.0                  h1de35cc_5  
requests                  2.21.0                   py37_0  
retrying                  1.3.3                    pypi_0    pypi
rope                      0.12.0                   py37_0  
ruamel_yaml               0.15.46          py37h1de35cc_0  
scikit-image              0.14.2           py37h0a44026_0  
scikit-learn              0.20.3           py37h27c97d8_0  
scipy                     1.2.1            py37h1410ff5_0  
seaborn                   0.9.0                    py37_0  
selenium                  3.141.0                  pypi_0    pypi
send2trash                1.5.0                    py37_0  
setuptools                40.8.0                   py37_0  
simplegeneric             0.8.1                    py37_2  
singledispatch            3.4.0.3                  py37_0  
sip                       4.19.8           py37h0a44026_0  
six                       1.12.0                   py37_0  
snappy                    1.1.7                he62c110_3  
snowballstemmer           1.2.1                    py37_0  
sortedcollections         1.1.2                    py37_0  
sortedcontainers          2.1.0                    py37_0  
soupsieve                 1.8                      py37_0  
sphinx                    1.8.5                    py37_0  
sphinxcontrib             1.0                      py37_1  
sphinxcontrib-websupport  1.1.0                    py37_1  
spyder                    3.3.3                    py37_0  
spyder-kernels            0.4.2                    py37_0  
sqlalchemy                1.3.1            py37h1de35cc_0  
sqlite                    3.27.2               ha441bb4_0  
statsmodels               0.9.0            py37h1d22016_0  
sympy                     1.3                      py37_0  
tblib                     1.3.2                    py37_0  
tensorboard               1.13.1                   pypi_0    pypi
tensorflow                1.13.1                   pypi_0    pypi
tensorflow-estimator      1.13.0                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.8.1                    py37_1  
test-generator            0.1.1                    pypi_0    pypi
testpath                  0.4.2                    py37_0  
tk                        8.6.8                ha441bb4_0  
toolz                     0.9.0                    py37_0  
tornado                   6.0.2            py37h1de35cc_0  
tqdm                      4.31.1                   py37_1  
traitlets                 4.3.2                    py37_0  
typing                    3.6.6                    pypi_0    pypi
typing-extensions         3.7.2                    pypi_0    pypi
unicodecsv                0.14.1                   py37_0  
unixodbc                  2.3.7                h1de35cc_0  
urllib3                   1.24.1                   py37_0  
waitress                  1.3.0                    pypi_0    pypi
wcwidth                   0.1.7                    py37_0  
webencodings              0.5.1                    py37_1  
werkzeug                  0.14.1                   py37_0  
wheel                     0.33.1                   py37_0  
widgetsnbextension        3.4.2                    py37_0  
wrapt                     1.11.1           py37h1de35cc_0  
wurlitzer                 1.0.2                    py37_0  
xlrd                      1.2.0                    py37_0  
xlsxwriter                1.1.5                    py37_0  
xlwings                   0.15.4                   py37_0  
xlwt                      1.3.0                    py37_0  
xz                        5.2.4                h1de35cc_4  
yaml                      0.1.7                hc338f04_2  
zeromq                    4.3.1                h0a44026_3  
zict                      0.1.4                    py37_0  
zipp                      0.3.3                    py37_1  
zlib                      1.2.11               h1de35cc_3  
zstd                      1.3.7                h5bba6e5_0  `

And for my pip list:
`(base) Florence:plotly florence.townend$ pip list
Package                            Version  
---------------------------------- ---------
absl-py                            0.7.1    
alabaster                          0.7.12   
anaconda-client                    1.7.2    
anaconda-navigator                 1.9.7    
anaconda-project                   0.8.2    
appnope                            0.1.0    
appscript                          1.0.1    
asn1crypto                         0.24.0   
astor                              0.8.0    
astroid                            2.2.5    
astropy                            3.1.2    
atomicwrites                       1.3.0    
attrs                              19.1.0   
Babel                              2.6.0    
backcall                           0.1.0    
backports.os                       0.1.1    
backports.shutil-get-terminal-size 1.0.0    
beautifulsoup4                     4.7.1    
bitarray                           0.8.3    
bkcharts                           0.2      
bleach                             3.1.0    
bokeh                              1.0.4    
boto                               2.49.0   
Bottleneck                         1.2.1    
certifi                            2019.6.16
cffi                               1.12.2   
chardet                            3.0.4    
Click                              7.0      
cloudpickle                        0.8.0    
clyent                             1.2.2    
colorama                           0.4.1    
conda                              4.6.14   
conda-build                        3.17.8   
conda-verify                       3.1.1    
contextlib2                        0.5.5    
cryptography                       2.6.1    
cycler                             0.10.0   
Cython                             0.29.6   
cytoolz                            0.9.0.1  
dash                               1.0.0    
dash-core-components               1.0.0    
dash-daq                           0.1.0    
dash-html-components               1.0.0    
dash-renderer                      1.0.0    
dash-table                         4.0.0    
dask                               1.1.4    
decorator                          4.4.0    
defusedxml                         0.5.0    
distributed                        1.26.0   
docutils                           0.14     
entrypoints                        0.3      
et-xmlfile                         1.0.1    
fastcache                          1.0.2    
filelock                           3.0.10   
Flask                              1.0.2    
Flask-Compress                     1.4.0    
future                             0.17.1   
gast                               0.2.2    
gevent                             1.4.0    
glob2                              0.6      
gmpy2                              2.0.8    
graphviz                           0.8.4    
greenlet                           0.4.15   
grpcio                             1.21.1   
h5py                               2.8.0    
heapdict                           1.0.0    
html5lib                           1.0.1    
idna                               2.8      
imageio                            2.5.0    
imagesize                          1.1.0    
importlib-metadata                 0.0.0    
ipykernel                          5.1.0    
ipython                            7.4.0    
ipython-genutils                   0.2.0    
ipywidgets                         7.4.2    
isort                              4.3.16   
itsdangerous                       1.1.0    
jdcal                              1.4      
jedi                               0.13.3   
Jinja2                             2.10     
jsonschema                         3.0.1    
jupyter                            1.0.0    
jupyter-client                     5.2.4    
jupyter-console                    6.0.0    
jupyter-core                       4.4.0    
jupyterlab                         0.35.4   
jupyterlab-server                  0.2.0    
Keras-Applications                 1.0.8    
Keras-Preprocessing                1.1.0    
keyring                            18.0.0   
kiwisolver                         1.0.1    
lazy-object-proxy                  1.3.1    
libarchive-c                       2.8      
lief                               0.9.0    
llvmlite                           0.28.0   
locket                             0.2.0    
lxml                               4.3.2    
Markdown                           3.1.1    
MarkupSafe                         1.1.1    
matplotlib                         3.0.3    
mccabe                             0.6.1    
mistune                            0.8.4    
mkl-fft                            1.0.10   
mkl-random                         1.0.2    
mock                               3.0.5    
more-itertools                     6.0.0    
mpmath                             1.1.0    
msgpack                            0.6.1    
multipledispatch                   0.6.0    
mxnet                              1.3.1    
navigator-updater                  0.2.1    
nbconvert                          5.4.1    
nbformat                           4.4.0    
networkx                           2.2      
nltk                               3.4      
nose                               1.3.7    
notebook                           5.7.8    
numba                              0.43.1   
numexpr                            2.6.9    
numpy                              1.16.2   
numpydoc                           0.8.0    
olefile                            0.46     
onnx                               1.5.0    
openpyxl                           2.6.1    
packaging                          19.0     
pandas                             0.24.2   
pandocfilters                      1.4.2    
parso                              0.3.4    
partd                              0.3.10   
path.py                            11.5.0   
pathlib2                           2.3.3    
patsy                              0.5.1    
pep8                               1.7.1    
percy                              2.0.2    
pexpect                            4.6.0    
pickleshare                        0.7.5    
Pillow                             5.4.1    
pip                                19.1.1   
pkginfo                            1.5.0.1  
plotly                             3.10.0   
pluggy                             0.9.0    
ply                                3.11     
prometheus-client                  0.6.0    
prompt-toolkit                     2.0.9    
protobuf                           3.6.1    
psutil                             5.6.1    
ptyprocess                         0.6.0    
pvlive-api                         0.3      
py                                 1.8.0    
pycodestyle                        2.5.0    
pycosat                            0.6.3    
pycparser                          2.19     
pycrypto                           2.6.1    
pycurl                             7.43.0.2 
pyflakes                           2.1.1    
Pygments                           2.3.1    
pylint                             2.3.1    
pyodbc                             4.0.26   
pyOpenSSL                          19.0.0   
pyparsing                          2.3.1    
pyrsistent                         0.14.11  
PySocks                            1.6.8    
pytest                             4.3.1    
pytest-arraydiff                   0.3      
pytest-astropy                     0.5.0    
pytest-doctestplus                 0.3.0    
pytest-mock                        1.10.4   
pytest-openfiles                   0.3.2    
pytest-remotedata                  0.3.1    
pytest-sugar                       0.9.2    
python-dateutil                    2.8.0    
pytz                               2018.9   
PyWavelets                         1.0.2    
PyYAML                             5.1      
pyzmq                              18.0.0   
QtAwesome                          0.5.7    
qtconsole                          4.4.3    
QtPy                               1.7.0    
requests                           2.21.0   
retrying                           1.3.3    
rope                               0.12.0   
ruamel-yaml                        0.15.46  
scikit-image                       0.14.2   
scikit-learn                       0.20.3   
scipy                              1.2.1    
seaborn                            0.9.0    
selenium                           3.141.0  
Send2Trash                         1.5.0    
setuptools                         40.8.0   
simplegeneric                      0.8.1    
singledispatch                     3.4.0.3  
six                                1.12.0   
snowballstemmer                    1.2.1    
sortedcollections                  1.1.2    
sortedcontainers                   2.1.0    
soupsieve                          1.8      
Sphinx                             1.8.5    
sphinxcontrib-websupport           1.1.0    
spyder                             3.3.3    
spyder-kernels                     0.4.2    
SQLAlchemy                         1.3.1    
statsmodels                        0.9.0    
sympy                              1.3      
tables                             3.4.4    
tblib                              1.3.2    
tensorboard                        1.13.1   
tensorflow                         1.13.1   
tensorflow-estimator               1.13.0   
termcolor                          1.1.0    
terminado                          0.8.1    
test-generator                     0.1.1    
testpath                           0.4.2    
toolz                              0.9.0    
tornado                            6.0.2    
tqdm                               4.31.1   
traitlets                          4.3.2    
typing                             3.6.6    
typing-extensions                  3.7.2    
unicodecsv                         0.14.1   
urllib3                            1.24.1   
waitress                           1.3.0    
wcwidth                            0.1.7    
webencodings                       0.5.1    
Werkzeug                           0.14.1   
wheel                              0.33.1   
widgetsnbextension                 3.4.2    
wrapt                              1.11.1   
wurlitzer                          1.0.2    
xlrd                               1.2.0    
XlsxWriter                         1.1.5    
xlwings                            0.15.4   
xlwt                               1.3.0    
zict                               0.1.4    
zipp                               0.3.3    `


I've uninstalled and reinstalled Plotly but the error still persists:
`(base) Florence:dash florence.townend$ python app.py 
Traceback (most recent call last):
  File "app.py", line 2, in <module>
    import dash
  File "/Users/florence.townend/anaconda3/lib/python3.7/site-packages/dash/__init__.py", line 1, in <module>
    from .dash import Dash, no_update  # noqa: F401
  File "/Users/florence.townend/anaconda3/lib/python3.7/site-packages/dash/dash.py", line 22, in <module>
    import plotly
  File "/Users/florence.townend/anaconda3/lib/python3.7/site-packages/plotly/__init__.py", line 30, in <module>
    from _plotly_future_ import _future_flags
ModuleNotFoundError: No module named '_plotly_future_'`

**Comment by jonmmease** [comment]
Hi @florencejt, how did you install plotly in the first place?  Here's the uninstall/install sequence I mean.

```
$ conda uninstall plotly
$ pip uninstall plotly
$ pip install plotly
```
Then if things don't work after running that sequence, add the output of `conda list` and `pip list` here.  Also, check the contents of your `/Users/florence.townend/anaconda3/lib/python3.7/site-packages/` directory to see if there is a `_plotly_future_` directory in there.

**Comment by florencejt** [comment]
When I tired coda uninstall Plotly I got this:

```
(base) Florence:~ florence.townend$ conda uninstall plotly
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are missing from the target environment:
  - plotly
```

But when I did the pip uninstall and install again, for some reason it worked this time even though I think I did the same thing as before?

Well, I'm not getting an error anymore and the demo worked so thank you.

**Comment by alexcjohnson** [comment]
@tsokadev there's also something weird with the dash versions you've got. These ones:
```
dash                      0.36.0                    <pip>
dash-core-components      0.42.1                    <pip>
dash-daq                  0.1.4                     <pip>
dash-html-components      0.13.4                    <pip>
dash-renderer             1.0.0                     <pip>
```
`dash-renderer@1.0` (the latest version, out last week) is only expected to work with `dash@1.0`, but you have much older `dash`, `dash-core-components`, and `dash-html-components`

**Comment by nicolaskruchten** [comment]
The Plotly future flags only showed up in v3.8 or so and I see a v3.1 up there in the list. Best to upgrade to plotly v3.10 no?

**Comment by tsokadev** [comment]
I reinstalled everything in a new environment and the problem has gone away. @alexcjohnson the reason for the weird dash versions is that I installed them [from a requirements.txt file](https://github.com/plotly/dash-daq-omega-pid/blob/5f38c0ff5e931844f9c1705839f265738b17948f/requirements.txt) which had fixed version numbers.
Thanks for all the help.

**Comment by isConic** [comment]
I'm running into the same issue. Can I ask for step by step on a fresh install?  
Assume I'm not using conda.
