### ISSUE TITLE
Missing `layouts/layout_full_screen.html`

### ISSUE THREAD

**Issue by paul-g** [plotly/dash#8]
Hi, thanks for the project seems a nice way to get started with plotly. I ran into some issues with example 5, looks like a missing file? Full stack omitted for privacy purposes, but that file seems to be missing from the repo:

```
    raise TemplateNotFound(template)
TemplateNotFound: layouts/layout_full_screen.html
```

**Comment by chriddyp** [comment]
thanks for checking it out @paul-g  ! a new version of dash is now available and should solve this issue.
