### ISSUE TITLE
[BUG] A local version of css is not available

### ISSUE THREAD

**Issue by chudur-budur** [plotly/dash#802]
**Describe your context**
Please provide us your environment so we can easily reproduce the issue.

-  replace the result of `pip list | grep dash` below
```
dash (1.0.0)
dash-core-components (1.0.0)
dash-daq (0.1.0)
dash-html-components (1.0.0)
dash-renderer (1.0.0)
dash-table (4.0.0)
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: Ubuntu 18.04
    - Browser Chromium
    - Version 75.0.3770.90 (Official Build) snap (64-bit)

**Describe the bug**

I was just trying to run the [dash-tsne](https://github.com/plotly/dash-sample-apps/tree/master/apps/dash-tsne) app from the [dash-sample-apps](https://github.com/plotly/dash-sample-apps) repo. But I am getting these warnings and looks like the app can't load the css from external urls.

```
Running on http://127.0.0.1:8050/
Debugger PIN: 478-608-242
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
Running on http://127.0.0.1:8050/
Debugger PIN: 674-005-297
/home/khaled/.local/lib/python3.6/site-packages/dash/resources.py:44: UserWarning:

A local version of https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css is not available

/home/$USER/.local/lib/python3.6/site-packages/dash/resources.py:44: UserWarning:

A local version of https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css is not available

/home/$USER/.local/lib/python3.6/site-packages/dash/resources.py:44: UserWarning:

A local version of //fonts.googleapis.com/css?family=Raleway:400,300,600 is not available

/home/$USER/.local/lib/python3.6/site-packages/dash/resources.py:44: UserWarning:

A local version of https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css is not available
```

**Expected behavior**

I was expecting to see the app with the exact formatting/framing given in the dash-tsne [screenshots](https://github.com/plotly/dash-sample-apps/tree/master/apps/dash-tsne/screenshots).

**Screenshots**

But I am getting this:
![Screenshot from 2019-06-29 18-40-54](https://user-images.githubusercontent.com/1117795/60390150-19cebc00-9a9e-11e9-866c-9d418aea19ec.png)

**Comment by chudur-budur** [comment]
I think I have found a work around. We need to explicitly say that those resources should not be served locally, like this.

```
app = dash.Dash(
    __name__, meta_tags=[{"name": "viewport", "content": "width=device-width"}]
)

app.css.config.serve_locally = False
app.scripts.config.serve_locally = False
```

**Comment by alexcjohnson** [comment]
Thanks for the report! Cc @shammamah - we have other apps that have external css and don’t need this override, is this just odd usage we should fix or should we consider this a bug, exposed by the shift to default `serve_locally`in 1.0?

**Comment by shammamah** [comment]
@alexcjohnson During the cleanup process for the apps, the CSS should have been moved to within the `assets` folder -- looks like this app in particular got missed. I've opened up an issue in the monorepo. @chudur-budur Thanks for bringing this to our attention!

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
