### ISSUE TITLE
Error: (converted from warning) Error in : (converted from warning) Error in : (converted from warning) 'box' objects don't have these attributes: 'mode' Valid attributes [BUG]

### ISSUE THREAD

**Issue by abbatidanilo** [plotly/dash#803]
Hello,
- I got this kind of error:

Error: (converted from warning) Error in : (converted from warning) Error in : (converted from warning) 'box' objects don't have these attributes: 'mode'
Valid attributes include:
'type', 'visible', 'showlegend', 'legendgroup', 'opacity', 'uid', 'ids', 'customdata', 'selectedpoints', 'hoverinfo', 'hoverlabel', 'stream', 'transforms', 'uirevision', 'y', 'x', 'x0', 'y0', 'name', 'text', 'hovertext', 'hovertemplate', 'whiskerwidth', 'notched', 'notchwidth', 'boxpoints', 'boxmean', 'jitter', 'pointpos', 'orientation', 'width', 'marker', 'line', 'fillcolor', 'offsetgroup', 'alignmentgroup', 'selected', 'unselected', 'hoveron', 'xcalendar', 'ycalendar', 'xaxis', 'yaxis', 'idssrc', 'customdatasrc', 'hoverinfosrc', 'ysrc', 'xsrc', 'textsrc', 'hovertextsrc', 'hovertemplatesrc', 'key', 'set', 'frame', 'transforms', '_isNestedKey', '_isSimpleKey', '_isGraticule', '_bbox'

**The context**
- In shiny using regularly renderPlotly in server.R and plotlyOutput in ui.R. 
Notice that the function below works perfectly in some cases (only with some ggdf dataframe) which are the same in format. 
The problem seems to rise during the rendering with renderPlotly (the *p* object seems produced with any feedback)

```
 p <- ggplot(ggdf, aes(x = expression, color = sample_id, group = sample_id)) +
    geom_freqpoly(stat = "density") + 
    facet_wrap(~ antigen, scales = "free") +
    scale_color_manual(values = sample_color)
  
  p <- ggplotly(p)
```
- It happens with any browser (I'm currently using firexfox and chrome) in Windows 10 with
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          5.3                         
year           2019                        
month          03                          
day            11                          
svn rev        76217                       
language       R                           
version.string R version 3.5.3 (2019-03-11)
nickname       Great Truth                 

with RStudio
Version 1.2.1335

**Comment by alexcjohnson** [comment]
@abbatidanilo this looks like it’s an issue with https://github.com/ropensci/plotly, yes? They should be able to help if you move the issue over there. Thanks!

**Comment by abbatidanilo** [comment]
opened on  https://github.com/ropensci/plotly
