### ISSUE TITLE
Defer `pytest` import?

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash#804]
Looks like `pytest` isn't the safest dependency, causing issues with scikit-learn: https://community.plot.ly/t/pytest-transient-dependency/25383

Could we move the `import pytest` into the testing module/class/function itself and not require it upon install? We could even have a separate install with setup.py's "extras" feature (https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) like `pip install dash[testing]` or something.

**Comment by byronz** [comment]
@chriddyp  in 1.0, we already use the `extras` feature in `setup.py`,  so the `pip install dash[testing]` might be the way to go.
