### ISSUE TITLE
dash > 0.39 has infinite loop

### ISSUE THREAD

**Issue by mbkupfer** [plotly/dash#816]
**Describe your context**
Please provide us your environment so we can easily reproduce the issue.

-  replace the result of `pip list | grep dash` below

**Note: the first output is using a dash 1.0.0 virtual environment and the second is using a 0.39 environment**
```
(dash1-0) $ pip list | grep dash > pbcopy
dash                 1.0.0    
dash-core-components 1.0.0    
dash-html-components 1.0.0    
dash-renderer        1.0.0    
dash-table           4.0.0    

(dash0-39) $ pip list | grep dash > pbcopy
dash                 0.39.0   
dash-core-components 0.44.0   
dash-html-components 0.14.0   
dash-renderer        0.20.0   
dash-table           3.6.0    


```
-  if frontend related, tell us your Browser, Version and OS

    - OS: Windows 7
    - Browser IE11

**Describe the bug**

The dash app keeps reloading in the browser when `dcc.Loation` component's hash is changed. This only occurs in IE. This worked in a previous app I created that uses an older version of dash which means that this must of been introduced after dash 0.39. I can make the app work using 0.39 dash libraries, but this would be a shame since I would not be able to use the latest and greatest version out there.

Looking at my code below, it may seem obvious that the culprit is the `refresh=True` prop for `url` but setting this to `False` fails to trigger a `
window.onhashchange = locationHashChanged;` event which is the main reason for me changing the hash. Also, as stated earlier, using `refresh=True` has worked fine before and can be reproduced in a 0.39 environment.

**Expected behavior**

Web page should not be refreshed on a hash change. 

**Screenshots**

![hash-reload-bug](https://user-images.githubusercontent.com/6313008/60849259-cd226980-a19e-11e9-8a26-3a971478a041.gif)

**Reproducible example**

```python
import dash
from dash.dependencies import Output, Input
import dash_core_components as dcc
import dash_html_components as html

app = dash.Dash(__name__)

app.layout = html.Div([
    dcc.Location(id='url', refresh=True),
    dcc.Tabs(
        id='tabs',
        value='one',
        children=[
            dcc.Tab(
                label='one',
                value='one',
                children=html.Div([html.H1('Tab one')])
            ),
            dcc.Tab(
                label='two',
                value='two',
                children=html.Div([html.H1('Tab two')])
            )
        ]
    )
])

@app.callback(Output('url', 'hash'),
              [Input('tabs', 'value')])
def update_url_hash(tab):
    '''Set hash in the url bar based on current tab'''
    return tab


if __name__ == '__main__':
    app.run_server(debug=True, host='0.0.0.0', port='3001')

```

Here is the javascript onhashchange which I'm trying to connect to my app. Removing this from my 1.0.0 environment still causes the webpage to go in an infinite loop.

```javascript
"use strict";

var locationHashChanged = function locationHashChanged() {
  if (location.hash === '#two') {
    console.log('two');
  }
};

window.onhashchange = locationHashChanged;
```

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
