### ISSUE TITLE
[BUG] mapbox marker size not updating after callback data received

### ISSUE THREAD

**Issue by zouhairm** [plotly/dash#823]
I just upgraded to Dash 1.0.1 from 0.39.0 and I'm seeing a potential regression whereas the marker sizes in mapbox are not updating despite receiving new data from a callback (I used Chrome's network tool to verify that the callback correctly sent back the updated marker sizes). Hover labels are getting updated however.

If I resize the window (which in my application forces a call to `Plotly.Plots.resize(plot)`), the markers get updated. This issue did not occur with dash==0.39.0

Versions
- OS: MacOS Mojave
- Browser:  Google Chrome | 75.0.3770.100 (Official Build) (64-bit)

```
dash==1.0.1
dash-callback-chain==0.0.2
dash-core-components==1.0.0
dash-dangerously-set-inner-html==0.0.2
dash-daq==0.1.4
dash-defer-js-import==0.0.1
dash-html-components==1.0.0
dash-renderer==1.0.0
dash-table==4.0.1
pytest-dash==2.1.2
plotly==3.10.0
```

**Comment by zouhairm** [comment]
I've upgraded to dash==1.1.1 and plotly==4.1.0 and this still seems to be an issue.

Should this bug be filed with Mapbox instead?

**Comment by alexcjohnson** [comment]
Thanks @zouhairm - and sorry for not replying to this earlier. My guess is this is a plotly.js issue. Would you be able to try and replicate this in a codepen - maybe start with https://codepen.io/alexcjohnson/pen/NMdMbE?editors=1010, swap in your own figure and add the right `Plotly.plots.resize` / `Plotly.react` calls - and then post it at https://github.com/plotly/plotly.js/issues if that shows the same problem?

**Comment by zouhairm** [comment]
@alexcjohnson Unfortunately I'm working within dash and setting the right thing in plotly.js only might not be a good proxy as in my experience the way dash handles the callbacks can significantly change the behaviour.

That being said, I've managed to fix my issue. It was frustrating as I've gone down a rabbit hole trying to see if I can add custom js callback code after dash's to force a Plotly.restyle(). However, it turned out that all I had to do was set `animate = False` in the dcc.Graph configuration. It was  set to True and it wasn't an issue with older versions, but it seems that having it set to True causes this obscure bug...

Since `animate` is a dcc.Graph configuration, I'm inclined to leave the bug report within Dash ...

**Comment by alexcjohnson** [comment]
Glad you sorted this out @zouhairm!
For anyone else encountering this issue if you *do* need animation, we're actually discouraging `animate=True` in `dcc.Graph`, as there's a better (and better supported) option now: `layout.transition`.
https://community.plot.ly/t/exploring-a-transitions-api-for-dcc-graph/15468
https://github.com/plotly/dash-core-components/issues/541
