### ISSUE TITLE
plotly.graph_objs Heatmap

### ISSUE THREAD

**Issue by bbleckel** [plotly/dash#83]
go.Heatmap objects don't plot in dash

**Comment by alishobeiri** [comment]
@bbleckel do you mind sharing your code? I wasn't able to recreate your issue. Heatmap plotted on my end.

**Comment by bbleckel** [comment]
@alishobeiri  Sure thing! I was just copying the example heatmap code from the plotly reference. 

```dcc.Graph(
    id = "heatmap",
    figure = go.Figure(
    data = [go.Heatmap(z=[[1, 20, 30],
      [20, 1, 60],
       [30, 60, 1]])]
    )
)```

**Comment by alishobeiri** [comment]
@bbleckel 

That's odd, that line seems to work for me, are you on the latest version of Dash and Plotly?

```
pip install dash==0.17.7  # The core dash backend
pip install dash-renderer==0.7.3  # The dash front-end
pip install dash-html-components==0.6.2  # HTML components
pip install dash-core-components==0.5.3  # Supercharged components
pip install plotly==2.0.12  # Plotly graphing library used in examples
```

I was able to create the following result with the following code: 


```
import dash
import dash_html_components as html
import dash_core_components as dcc
import plotly.graph_objs as go

app = dash.Dash('heatmap test')

app.layout = html.Div([
    dcc.Graph( id = "heatmap", figure = go.Figure( data = [go.Heatmap(z=[[1, 20, 30], [20, 1, 60], [30, 60, 1]])] ) )
])


if __name__ == '__main__':
    app.run_server()
```

![image](https://user-images.githubusercontent.com/18422723/28133142-fc8658a4-670c-11e7-9afb-e2df02ecfd10.png)

**Comment by bbleckel** [comment]
@alishobeiri Thanks so much for your help. Turns out that I had the following line of code
```python
dcc._js_dist[0]['external_url'] = 'https://cdn.plot.ly/plotly-finance-1.28.0.min.js'
```
which made the plot show up weird. I think that I had previously copied it over from an example in the Dash gallery. No matter, commenting it out made it work.

Thanks again for your help!

**Comment by alishobeiri** [comment]
@bbleckel 
Glad you figured it out! That line actually loads a partial plotly.js bundle that is lighter than the default plotly bundle. As such, it doesn't contain all the chart types but can be potentially faster when loading. 

If you want to find out more check out: https://github.com/plotly/plotly.js/blob/master/dist/README.md#partial-bundles

**Comment by ralfcam** [comment]
I had a similar issue, turns out It was because I was using Brave browser, worked all fine in Chromium though...
