### ISSUE TITLE
plotly-dash showing blank web page

### ISSUE THREAD

**Issue by bhaskar4n** [plotly/dash#837]
Thank you so much for helping improve the quality of Dash!

We do our best to catch bugs during the release process, but we rely on your help to find the ones that slip through.

**Describe your context**
Please provide us your environment so we can easily reproduce the issue.

-  replace the result of `pip list | grep dash` below
```
dash                 1.0.2
dash-core-components 1.0.0
dash-html-components 1.0.0
dash-renderer        1.0.0
dash-table           4.0.2
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: ubuntu 16.04 LTS
    - Browser : google chrome Version 74.0.3729.169 (Official Build) (64-bit)
    - Version 74.0.3729.169 (Official Build) (64-bit)

**Describe the bug**
  I have followed the installation procedure mentioned in this website 
  https://dash.plot.ly/installation
  when I try to connect http://127.0.0.1:8050/ in chrome it showing a blank web page and i used this program 
`
      import dash
       import dash_core_components as dcc
        import dash_html_components as html
        external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']

        app = dash.Dash(__name__, external_stylesheets=external_stylesheets)

       app.layout = html.Div(children=[
         html.H1(children='Hello Dash'),

    html.Div(children='''
        Dash: A web application framework for Python.
    '''),

    dcc.Graph(
        id='example-graph',
        figure={
            'data': [
                {'x': [1, 2, 3], 'y': [4, 1, 2], 'type': 'bar', 'name': 'SF'},
                {'x': [1, 2, 3], 'y': [2, 4, 5], 'type': 'bar', 'name': u'Montréal'},
            ],
            'layout': {
                  'title': 'Dash Data Visualization'
              }
           }
      )
    ] )

    if __name__ == '__main__':
      app.run_server(debug=True)
`
   **error message in javascript console**
``TypeError: dependencies.forEach is not a function
    at graphs (dependencyGraph.js:14)
    at combination (combineReducers.js:120)
    at reducer.js:66
    at reducer.js:102
    at dispatch (createStore.js:165)
    at index.js:11
    at UnconnectedContainer.initialization (APIController.react.js:63)
    at UnconnectedContainer.componentWillReceiveProps (APIController.react.js:33)
    at Zf (react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:67)
    at qg (react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:95)
Bg @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:117
c.callback @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:126
Ag @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:116
zg @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:116
qi @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:131
ui @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:133
(anonymous) @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:158
unstable_runWithPriority @ react@16.8.6.min.js?v=1.0.0&m=1564319210:27
Vc @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:158
Sc @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:158
Z @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:156
Kc @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:155
ya @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:153
enqueueSetState @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:202
t.setState @ react@16.8.6.min.js?v=1.0.0&m=1564319210:20
handleChange @ connect.js:302
dispatch @ createStore.js:173
(anonymous) @ index.js:11
dispatch @ applyMiddleware.js:35
(anonymous) @ api.js:53
Promise.then (async)
(anonymous) @ api.js:52
Promise.then (async)
(anonymous) @ api.js:46
(anonymous) @ index.js:8
initialization @ APIController.react.js:58
componentDidMount @ APIController.react.js:29
qi @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:130
ui @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:133
(anonymous) @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:158
unstable_runWithPriority @ react@16.8.6.min.js?v=1.0.0&m=1564319210:27
Vc @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:158
Sc @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:158
Z @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:156
Kc @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:155
ya @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:153
bh @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:160
xe @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:160
nb.render @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:215
(anonymous) @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:164
$g @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:159
Wc @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:164
render @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:217
DashRenderer @ DashRenderer.js:12
(anonymous) @ (index):28
api.js:73 Uncaught (in promise) TypeError: err.text is not a function
    at api.js:73
(anonymous) @ api.js:73
Promise.catch (async)
(anonymous) @ api.js:45
(anonymous) @ index.js:8
initialization @ APIController.react.js:58
componentDidMount @ APIController.react.js:29
qi @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:130
ui @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:133
(anonymous) @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:158
unstable_runWithPriority @ react@16.8.6.min.js?v=1.0.0&m=1564319210:27
Vc @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:158
Sc @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:158
Z @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:156
Kc @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:155
ya @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:153
bh @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:160
xe @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:160
nb.render @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:215
(anonymous) @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:164
$g @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:159
Wc @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:164
render @ react-dom@16.8.6.min.js?v=1.0.0&m=1564319210:217
DashRenderer @ DashRenderer.js:12
(anonymous) @ (index):28

**Expected behavior**
 when i run the above mentioned program. dash showing the blank webpage.  i need to show graphs
**Screenshots**
[blankwebpage](https://i.stack.imgur.com/C3se4.png)
[terminal screen shot](https://i.stack.imgur.com/GiFIq.png)

**Comment by Marc-Andre-Rivet** [comment]
Note to self: Link to equivalent community issue: https://community.plot.ly/t/dash-showing-blank-page/26499/5
