### ISSUE TITLE
[Feature Request] make DocumentTitle changes adjustable

### ISSUE THREAD

**Issue by philipphutterer** [plotly/dash#856]
Hello there,

as already "discussed" [in the community forum](https://community.plot.ly/t/15379) some time ago, I suggest to have a possibility that allows you to disable the annoying change of the Document Title to "Updating..." every time there is a data update - what might happen very often since you can choose any arbitrary small interval.

In my opinion it should be possible to either
- dynamically set the title during the data update in the callback or
- be a static value what can be set up initially

code file: `DocumentTitle.react.js`

Thanks in advance and best regards,
Philipp

**Comment by CaseGuide** [comment]
Do the features described in #286 take care of this? It seems like overwriting the HTML title tag might fix it.

**Comment by philipphutterer** [comment]
I tried to override the HTML title tag as suggested in #286 and it did not work. The updating script is still intercepting this.

**Comment by chriddyp** [comment]
This feature is now available in `dash==1.14.0` and is documented in http://dash.plotly.com/external-resources. Look for the `title=` and `update_title=`. See the "[Customizing Dash's Document or Browser Tab Title]( http://dash.plotly.com/external-resources)", " [Update the Document Title Dynamically based off of the URL or Tab]( http://dash.plotly.com/external-resources)", and "[Customizing or Removing Dash's "Updating..." Message](http://dash.plotly.com/external-resources)" sections.
