### ISSUE TITLE
Empty hovers when using charts and columnCount

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/dash#86]
This is an odd bug but consistently, the hover/tooltip appears empty for line charts in the second (or higher) column when using `columnCount`... Chart `b` below has empty tooltips. If I add a chart `c` with the same definition, and bump `columnCount` to 3 I have the same problem with that chart too. I've seen the same behaviour with histograms but not pie charts.

```python
import dash, dash_core_components as dcc, dash_html_components as html
import plotly.graph_objs as go

app = dash.Dash()
app.layout = html.Div([
        dcc.Graph(id='a', figure=dict(data = [go.Scatter( x = [1,2], y = [3,4] )])),
        dcc.Graph(id='b', figure=dict(data = [go.Scatter( x = [1,2], y = [3,4] )])),
        ], style={'columnCount': 2})

if __name__ == '__main__':
    app.run_server(debug=True)
```

**Comment by chriddyp** [comment]
![colum-count](https://user-images.githubusercontent.com/1280389/28447934-1199eda0-6da2-11e7-9363-eddb77a29104.gif)

Woah, weird.

**Comment by chriddyp** [comment]
I created an issue in `plotly.js` about it: https://github.com/plotly/plotly.js/issues/1902

I'm going to close this issue and watch the other one. When a fix gets merged in a plotly.js release, we'll bump the version in `dash-core-components`.

Thanks for reporting!
