### ISSUE TITLE
Remove unused javascript

### ISSUE THREAD

**Issue by Jeffrey9130** [plotly/dash#861]
Hi,

The background is I'm going to run a dash application on a Raspberry Pi, and therefore want to improve the loading speed of the application by minimizing the loading components.

I noticed that most of the javascript embed along with the dash application have very low running coverage. I use plotly to render some dynamic curves but the overall coverage of plotly.js is only about 30%.

I have no handy experience about javascript before but is there any way to remove those uncovered javascript?

**Comment by alexcjohnson** [comment]
Thanks @Jeffrey9130 - this is discussed in https://github.com/plotly/dash-core-components/issues/462 and #655 - closing this issue, let's continue the discussion in those issues.
