### ISSUE TITLE
[BUG] Safari Preload Top Hit leads to dash.exceptions.DependencyException

### ISSUE THREAD

**Issue by sderuiter** [plotly/dash#876]
Hi,

Running a simple Dash app on Ubuntu 18.04.
I'm accessing the site from three locations:
1. Safari on Mac, typing in the URL or refreshing the current URL --> works as expected
2. Safari on IOS, having saved the URL to the homescreen --> works as expected
3. Safari on IOS, typing in the URL in the URL field --> error

The error is:
```
File "/home/sander/anaconda3/lib/python3.7/site-packages/dash/dash.py", line 669, in serve_component_suites
    package_name, path_in_package_dist, self.registered_paths
dash.exceptions.DependencyException: "dash_renderer" is registered but the path requested is not valid.
The path requested: "dash_renderer.min.js"
List of registered paths: defaultdict(<class 'set'>, {'dash_renderer': {'prop-types@15.7.2.min.js', 'react@16.8.6.min.js', 'react-dom@16.8.6.min.js', 'dash_renderer.dev.js.map', 'dash_renderer.dev.js'}, 'dash_html_components': {'dash_html_components.min.js', 'dash_html_components.min.js.map'}, 'dash_core_components': {'dash_core_components.min.js', 'dash_core_components.min.js.map', 'highlight.pack.js', 'plotly-1.49.1.min.js'}, 'dash_daq': {'bundle.js'}})
``````
I've succesfully reproduced this when the Safari setting Preload Top Hit is ON. When this setting is off, the error does not occur. 
```
dash==1.1.1
dash-core-components==1.1.1
dash-daq==0.1.7
dash-html-components==1.0.0
dash-renderer==1.0.0
dash-table==4.1.0
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: IOS 12.4
    - Browser: Safari
    - Version: from 12.4

**Comment by alexcjohnson** [comment]
Thanks for the report @sderuiter! It looks like somehow "preload top hit" is attempting to load the production version of the app, while you're running the dev (`debug=True`) version on the server. Perhaps Safari has the production version html page cached, then you restarted the app in dev mode?

Does this prevent the app from loading properly, or just generate an error on the server?

**Comment by sderuiter** [comment]
Yes I did at some point change debug to False from True.

The page takes forever to load and loads only half. The console spits out the error message, but doesn’t crash the app.

-sander

**Comment by alexcjohnson** [comment]
OK, interesting - thanks for the details. I can't immediately find any documentation for Preload Top Hit from a developer's standpoint, but perhaps we can find a header to set that would prevent it from caching the page.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
