### ISSUE TITLE
[Feature Request] clean package.json

### ISSUE THREAD

**Issue by byronz** [plotly/dash#882]
while cleaning up the assets in both dcc and dash, we notice the package.json file in both repos might contain some deprecated/unrelated packages.

relates to https://github.com/plotly/dash-core-components/issues/607

**Comment by alexcjohnson** [comment]
the ones that we flagged in this repo as likely obsolete are:

cross-env
json-loader
query-string
redux-logger

**Comment by alexcjohnson** [comment]
Taking care of this as part of #903, as I wanted to upgrade babel to use with jest for unit testing some JS stuff

**Comment by alexcjohnson** [comment]
Done in #903
