### ISSUE TITLE
[BUG] Error loading dependencies - app.callback

### ISSUE THREAD

**Issue by MBertolino** [plotly/dash#906]
**Describe your context**
Small app breaks with @app.callback().

```
dash                 0.39.0
dash-core-components 0.38.0
dash-html-components 0.13.2
dash-renderer        0.15.0
dash-table           4.2.0
```
    - OS: 5.2.9-arch1-1-ARCH
    - Browser: Firefox    | Chromium
    - Version 69.0-1      | 76.0.3809.132-1
Ad blockers disabled.

**Describe the bug**
The following app gives "Error loading dependencies". The error disappears when the callback is commented out.

```
import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output

app = dash.Dash(__name__)

app.layout = html.Div([
    dcc.Input(id='my-id', value='initial value', type='text'),
    html.Div(id='my-div')
])

@app.callback(
    Output(component_id='my-div', component_property='children'),
    [Input(component_id='my-id', component_property='value')]
)
def update_output_div(input_value):
    return 'You\'ve entered "{}"'.format(input_value)

if __name__ == '__main__':
    app.run_server(debug=True)
```

**Expected behavior**
I have seen similar issues, but unfortunately not been able to resolve it.

**Comment by byronz** [comment]
@MBertolino  thanks for the report,  I cannot reproduce this on my local environment. 

Can you first try to upgrade dash to 1.2.x? If the problem still presents, most likely relates to the Arch Linux, then I will try to reproduce it with the exact environment.  

btw, which python version are you on? thanks

**Comment by MBertolino** [comment]
Thank you @byronz for your swift reply. I use python 3.7.4

I have now retried with updating the following
```
dash                 0.39.0
dash-core-components 0.44.0
dash-html-components 0.14.0
dash-renderer        0.20.0
```
and it works. I originally installed dash via Arch User Repository, and bluntly assumed it was up-to-date, but turns out it wasn't. It is not an issue on your side but hopefully some stray Arch users may find this useful.

Thank you!
