### ISSUE TITLE
[Feature Request] Only trigger a callback if (some) property actually changed

### ISSUE THREAD

**Issue by orenbenkiki** [plotly/dash#908]
In general, if one callback writes some property, then any other callback dependent on that property is also invoked, regardless of the written value. In particular, even if the written value is identical to the current value.

This conservative approach is a good default. It is safe, in that in ensures that everything is always up to date no matter what. It is efficient to implement - properties might be "the HTML content of something" or "the data to display in a heatmap" and comparing such properties would be slow.

However, it _does_ impact overall application performance. For example, consider a case where some dropdown specifies which of multiple UI regions to actually display. Inside these regions, there are components that display all sort of data, which may be expensive to compute.

The simple idiom to implement this is a callback depending on the value of the dropdown, which controls the visibility of the UI regions; and a callback for each displayed data, which may depends on multiple parameters, but must also depend on the visibility of the UI region that contains it.

This works, but it means that every time the dropdown changes, the 1st callback is invoked, which only changes the visibility of up to 2 UI regions (the one being hidden and the one being shown). But technically it writes the visibility of all the UI regions. This causes _all_ the callbacks of _all_ the data display components to be invoked. Sure, each callback just sees its UI region is not visible and immediately returns. But there is still an overhead in dispatching the callbacks. This overhead has increased in dash-1.2.0 (see #904).

I found https://community.plot.ly/t/how-to-leave-callback-output-unchanged/7276 which discusses a similar issue. It suggests that raising an exception will inform Dash that the outputs did not change, and avoid triggering the cascade of dependent callbacks. In the above example, create a callback for controlling the visibility of each UI region, have it take as `State` the current visibility, and if the new visibility is the same, raise an exception. 

The down side is that Dash will complain the callback has failed and will add its stack trace to the errors log. So, a minimal feature request is:

Have a specific `dash.OutputsNotChanged` exception that may be thrown by a callback, which will be silently ignored by Dash instead of being reported as an error.

A solution which requires less application boilerplate (and allows having just a single callback to control the visibility of all the UI regions) is to allow writing something like `Output(..., only_trigger_callbacks_if_changed=True)`. This places the burden on Dash to compare the returned value with the current value.

**Comment by orenbenkiki** [comment]
Ugh, searching more I found github issues regarding `dash.exceptions.PreventUpdate`. Even though https://github.com/plotly/dash-docs/issues/495 is marked as closed (3 weeks ago), I can't find any documentation for it. I also found mentions of `dash.no_update` but I can't find any documentation for it either. At any rate, I'm closing this issue...

**Comment by ned2** [comment]
Here's the relevant page of the docs: https://dash.plot.ly/state

**Comment by orenbenkiki** [comment]
Google for dash.no_update, first result is https://community.plot.ly/t/dash-0-41-0-released/22131 and the docs don’t appear in the first page. Add site:dash.plot.ly and it finds one irrelevant result https://dash.plot.ly/dash-core-components/datepickerrange

Seems like google is not indexing the docs?!?!

**Comment by ned2** [comment]
Yep good call, I've noticed this problem of Search Engines not indexing the docs before.
