### ISSUE TITLE
[BUG] dash-generate-components ignore not working

### ISSUE THREAD

**Issue by stevej2608** [plotly/dash#913]
Hi

The ignore argument on `dash-generate-components` is not working correctly, eg files in the
**\_\_test\_\_** sub-folder are not ignored by:

```
dash-generate-components --ignore=.*?__tests__
```
The ignore pattern is failing due to the regex being quoted when passed into `extract-meta.js`

The one-line fix is in: `dash/extract-meta.js:8`

```
const ignorePattern = new RegExp(process.argv[2]);
```
Should be:

```
const ignorePattern = new RegExp(process.argv[2].split('"').join(''));
```

Cheers, Steve

**Comment by alexcjohnson** [comment]
Closed by @stevej2608 in #915
