### ISSUE TITLE
[BUG] Annotations using log axis as reference

### ISSUE THREAD

**Issue by orenbenkiki** [plotly/dash#916]
```
dash (1.1.1)
dash-bootstrap-components (0.7.0)
dash-core-components (1.1.1)
dash-daq (0.1.7)
dash-html-components (1.0.0)
dash-renderer (1.0.0)
dash-table (4.1.0)
```
**Describe the bug**

Writing: `Scattergl(x_array=[value], ..., layout=dict(..., annotations=[dict(x=value, xref='x', ...)])` will place the annotations directly on top of the marker, as expected.

Writing: `Scattergl(x_array=[value], ..., layout=dict(..., xaxis=dict(type='log'), annotations=[dict(x=value, xref='x', ...)])` will **not** place the annotations directly on top of the marker.

**Expected behavior**

Adding `type='log'` to an axis should not require modifying the coordinates of annotations. If an annotation uses this axis as a reference, then the log function should be applied to its coordinate(s), in the same way it is applied to marker coordinate(s).

**Workaround**

Writing: `Scattergl(x_array=[value], ..., layout=dict(..., xaxis=dict(type='log'), annotations=[dict(x=np.log10(value), xref='x', ...)])` will work.

**Comment by orenbenkiki** [comment]
There is an easy way to fix it in a backward-compatible way: add a new value for the `ref` properties that would indicates that the log transformation (and any other axis transformation) will be applied to the annotation coordinate as expected. Say, `xref='X'` or `xref='x!'` or `xref='x_with_all_transformations'`.

This way new code could be written without having to resort to workarounds, while old code would not be impacted. In theory at some point in the future the current `'x'` or `'y'` value could be deprecated, but that would be far into the future and is completely optional.

There is no reason to wait for a v2.0 version.

**Comment by alexcjohnson** [comment]
That's an interesting idea - feel free to propose it over at https://github.com/plotly/plotly.js/issues/1258 though, whatever we do it'll happen over there, not in Dash.

I'll note though that the problem is not just with annotations; the axis range has the same issue, as do image positions, and there may be others. Also we need to consider multiple x or y axes (currently `xref: 'x2'` etc)
