### ISSUE TITLE
Dropdown component throws react error

### ISSUE THREAD

**Issue by NMRobert** [plotly/dash#92]
Hi,

when trying to create a dash_core_component dropdown,  examples taken from the documentation (and others) will malfunction, throwing a react error when the value is changed in the browser. 

Ex:

```
import dash
import dash_core_components as dcc
import dash_html_components as html
app = dash.Dash()
app.layout = html.Div(children=[
                        dcc.Dropdown(
    options=[
        {'label': 'New York City', 'value': 'NYC'},
        {'label': 'Montréal', 'value': 'MTL'},
        {'label': 'San Francisco', 'value': 'SF'}
    ],
    value='MTL'
)
                      ])
if __name__ == '__main__':
    app.run_server(debug=False)
```

When I try to change the value of the dropdown, nothing happens, and this error appears in the console:

```
Uncaught TypeError: i is not a function
    at Object.onChange (bundle.js:13)
    at Object.setValue (bundle.js:11)
    at Object.<anonymous> (bundle.js:11)
    at e.notifyAll (react-dom.min.js:12)
    at o.close (react-dom.min.js:14)
    at o.closeAll (react-dom.min.js:15)
    at o.perform (react-dom.min.js:15)
    at o.perform (react-dom.min.js:14)
    at Object.T [as flushBatchedUpdates] (react-dom.min.js:14)
    at r.closeAll (react-dom.min.js:15)
```

This seems to occur under a number of conditions, although I haven't figured out exactly what causes it. The dropdown examples in the Dash user guide (https://plot.ly/dash/getting-started) also have this behaviour. I'm observing this under Chrome (Version 59.0.3071.115 (Official Build) (64-bit)), and Firefox(54.0 (64-bit)). I have updated to the most current version of Dash on github, but this hasn't helped.

**Comment by RLstat** [comment]
My personal experience is that you won't be able to change a dropdown value if it is not in a callback function.  Checkout the example in part2 of the user guide, where the dropdown actually works.

**Comment by chriddyp** [comment]
> My personal experience is that you won't be able to change a dropdown value if it is not in a callback function. Checkout the example in part2 of the user guide, where the dropdown actually works.

That (was) correct. Originally, these components wouldn't update themselves until a callback was assigned to them.

This was causing a lot of confusion for folks (despite a couple of warnings in the documentation about it) so I updated the behaviour of the `dash_core_components` in v0.6.0. If you upgrade, then they should update without callbacks being assigned to them:

```
$ pip install dash-core-components==0.6.0
```
