### ISSUE TITLE
special handling for _reload-hash in dev tools

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash#920]
when my app crashes, the reload request fails. this causes repeated error message in dash dev tools:
![image](https://user-images.githubusercontent.com/1280389/64645398-d3250880-d3e2-11e9-9364-21ea9f9086d0.png)

It would be nice if we could treat this message with more care:
- Only display the error once or twice
- Update the error message to be something like "The app has likely crashed."

**Comment by alexcjohnson** [comment]
Good call - also if you forget and leave a dash app open in a tab after halting its server... next day the whole browser starts dragging as those thousands of calls clog up the page.

**Comment by raghavendrajain** [comment]
Hi. In my case, even when there is NO error in the code, page displays this error whenever a change is made. I think, it is a problem with hot-reloading feature, as it appears irrespective of whether code is correct or wrong.

**Comment by alexcjohnson** [comment]
@raghavendrajain that's not an issue I've seen, can you say more? Does it happen with any app or just a specific one? What versions of Dash packages do you have? (`pip list | grep dash` if installed by pip)

**Comment by kenhui521** [comment]
@alexcjohnson 
I got the same error as well. It's not to an app specific. My dash version is dash==1.2.0.
I have noticed that this error appeared when there is a long running method executed by dash button.

**Comment by alexcjohnson** [comment]
Thanks @kenhui521 - I've tried creating extremely slow callbacks, clogging the server, and still haven't been able to generate that error. If you're able to find an app simple enough to share that I can use to replicate this error, I'd love to see it!

**Comment by alexcjohnson** [comment]
Perhaps we should convert this situation from an error to a simple status indicator - when the most recent `_reload-hash` request failed, we add a little red light somewhere that has a tooltip saying "the back end is not responding" - and when a request succeeds we remove that indicator.

Also perhaps we should skip these requests entirely - or at least make them much less frequent - when the window is inactive (`document.visibilityState !== 'visible'` is what I used in `dash-notes`) - just means it may have the old state for a couple seconds when you come back to it.
