### ISSUE TITLE
Script() Error

### ISSUE THREAD

**Issue by ajmendez** [plotly/dash#93]
I would like to add a `<script></script>` tag with some dynamic code to incorporate another module that was already created.  Here is some sample code that reproduces this bug:

```python
import dash
import dash_html_components as html

app = dash.Dash()

app.layout = html.Div([
    html.Script('alert(1);', type='text/javascript')
])

if __name__ == '__main__':
    app.run_server()
```

Loading this page in Chrome does not bring up an alert dialog as expected.  Running alert(1); from the console does bring up an alert so it is not related to any adblocker.  I tried adding async=True and defer=True, but the code does not seem to run.

>>> dash.__version__
'0.17.7'
>>> dcc.__version__
'0.6.0'
>>> html.__version__
'0.7.0'

**Comment by chriddyp** [comment]
I believe that this is an underlying issue with React (https://github.com/facebook/react/issues/654).

Could you use `app.scripts.append_script` (as in https://plot.ly/dash/external-resources) instead? That will append the script to the actual HTML that gets served, rather than rendering it after page load through React.

**Comment by ajmendez** [comment]
That does look to be the issue.  

The `app.scripts.append_script` workaround does not work for my application as I am configuring a second JS module with updated data as it is running. Do you have any recommendations on how to  pass some JS variable through dash that does not use the `html.Script()` tag?

**Comment by chriddyp** [comment]
Dash Plugin Components are the recommended way to do this.
