### ISSUE TITLE
Lines seem arbitrarily long in Python components generated from React.

### ISSUE THREAD

**Issue by mkcor** [plotly/dash#931]
I noticed this issue while reviewing a Dash Bio PR (see https://github.com/plotly/dash-bio/pull/411#discussion_r324820104). For reviewing, readability, and maintenance purposes, we would like to wrap lines at, say, 100 characters.

**Comment by alexcjohnson** [comment]
Maybe we should just run black on generated components, no need to reinvent the wheel here.

Let's combine this with my comment on #929:

> I'd actually prefer us to rewrite it just using (potentially nested) indentation, rather than duplicating the keys (so those/these will disappear entirely). Also we need to rewrap lines so the indentation will be preserved in auto-wrapping contexts. To take a simple example, here's the current `active_cell` from the table:
> ```
> - active_cell (dict; optional): The row and column indices and IDs of the currently active cell. active_cell has the following type: dict containing keys 'row', 'column', 'row_id', 'column_id'.
> Those keys have the following types:
>   - row (number; optional)
>   - column (number; optional)
>   - row_id (string | number; optional)
>   - column_id (string; optional)
> ```
> 
> This should be cleaned up to look something like:
> ```
> - active_cell (dict; optional): The row and column indices and IDs of the
>   currently active cell.
>   active_cell is a dict with keys:
>   - row (number; optional)
>   - column (number; optional)
>   - row_id (string | number; optional)
>   - column_id (string; optional)
> ```

**Comment by mkcor** [comment]
> Maybe we should just run black on generated components, no need to reinvent the wheel here.

It definitely sounded like a problem with an already existing solution. And I don't think I knew of [Black](https://black.readthedocs.io), so thanks!

> Let's combine this with my comment on #929:

Agreed. I'll close this issue then, 'including' it into #929.
