### ISSUE TITLE
pytest plugin should not be registered by default

### ISSUE THREAD

**Issue by vfilimonov** [plotly/dash#946]
Hello 

I suggest that the pytest plugin should not be registered by default on dash installation.

A clean install of pytest without any plugins automatically activates `dash-1.3.1` plugin (which increases the time of test suite by unnecessary import of the module and also annoys with the warning).

On a clean virtual environment:
```
$ python3 -m venv venv
$ source venv/bin/activate
$ pip install dash
$ pip install pytest
$ mkdir tests
$ cd tests/
```
an empty run of pytest results in
```
$ pytest
/Users/user/tmp/venv/lib/python3.7/site-packages/dash/testing/plugin.py:17: UserWarning:

run `pip install dash[testing]` if you need dash.testing

===================================================================== test session starts ======================================================================
platform darwin -- Python 3.7.1, pytest-5.2.0, py-1.8.0, pluggy-0.13.0
rootdir: /Users/user/tmp/tests
plugins: dash-1.3.1
collected 0 items                                                                                                                                              

==================================================================== no tests ran in 0.00s =====================================================================
```

Though the `pytest-dash` plugin was never installed:
```
$ pip uninstall pytest-dash
WARNING: Skipping pytest-dash as it is not installed.
```

**Comment by alexcjohnson** [comment]
Good point @vfilimonov - thanks for bringing it up, I think you're right that we only want the pytest plugin installed with `dash[testing]`.

Unfortunately the solution isn't so clear to me. `pytest-dash` isn't used anymore, `dash.testing` is part of the main `dash` package now. So the pytest plugin is registered in the `setup.py` for `dash` itself, and it's not obvious to me how to supply entry points based on requested extras. This question was asked https://stackoverflow.com/questions/36005886/conditional-setuptools-entry-points, with no simple solutions given. Maybe @byronz will have some ideas when he's back from vacation?

**Comment by nylocx** [comment]
Hi,
any news on that or at least way to disable the warning?

**Comment by byronz** [comment]
@nylocx @vfilimonov  I will take a look at the issue, and find out a way for that. sorry for the delay, this was not on my radar before.

**Comment by gatesn** [comment]
Could we move all imports in `dash/testing/plugin.py` inside the fixtures themselves? This might delay the bulk of the imports until the fixtures are actually invoked.

**Comment by jlf-inc** [comment]
Any updates on this issue? We have a monorepo where dash is a dependency and we need to add some seleniumbase tests,  but they have a conflict argument (`--headless`) that prevent us to do that. We are not using the plugin in `dash[testing]`.

**Comment by radusuciu** [comment]
> Any updates on this issue? We have a monorepo where dash is a dependency and we need to add some seleniumbase tests, but they have a conflict argument (`--headless`) that prevent us to do that. We are not using the plugin in `dash[testing]`.

I have the same issue and just work around it like this:

```
sed -i 's/--headless/--headless_/g' /venv/lib/python3.9/site-packages/dash/testing/plugin.py
```

(called during container build time)
