### ISSUE TITLE
Ability to target individual properties in the loading states

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash#951]
e.g. for a `dcc.Graph` - ability to only display the loading state / loading component if `figure` is updating, not if `hoverData` is updating. there might be some more specificity with respect to a component being an "input" component vs an "output" component as well (e.g. `hoverData` will always be an "input" property not an output property, so we might consider omitting the loading state for it.)

More details here https://community.plot.ly/t/disable-dcc-loading-animation-on-chart-with-hoverdata-callback/29466

**Comment by ethanopp** [comment]
@chriddyp thanks!

**Comment by rredburn** [comment]
I think I'm having the same issue with a selectData callback.  It appears this prevents shift-click from working correctly when clickmode='event+select' as selections don't accumulate.  If I remove the graph from dcc.Loading everything works as expected.

**Comment by luggie** [comment]
I'm having the same issue with intervals that in my case should not trigger loading

**Comment by ashraf97it** [comment]
I'm have the same issue my graph still reload on every update

**Comment by MarcoNastasi** [comment]
Ran into this issue with a graph with hover data. I saw that the related issue https://github.com/plotly/dash-core-components/issues/709 was meant to be included with a prior release, but seems that got dropped?
