### ISSUE TITLE
Dash User Guide wrong for python 2.......

### ISSUE THREAD

**Issue by tpt5cu** [plotly/dash#954]
```
dash                                               1.3.0      
dash-core-components               1.2.0      
dash-daq                                        0.2.1      
dash-html-components               1.0.1      
dash-renderer                                1.1.0      
dash-table                                      4.3.0 
```

**Describe the bug**
I do not know if this is the best place to bring this up, but in the [User Guide](https://dash.plot.ly/getting-started) online, the example app.py code should contain a 
`# coding=utf-8` at the start of the code, otherwise it fails.

**Comment by alexcjohnson** [comment]
Most of the examples on that page do have `# -*- coding: utf-8 -*-` up front. I'm not sure how much more we want to cater to Py2 at this point, but if there are specific ones you think need it feel free to make an issue at https://github.com/plotly/dash-docs - or better yet a PR!
