### ISSUE TITLE
[BUG] Tooltip_data doesn't work when using dev tool UI

### ISSUE THREAD

**Issue by nguyenkhacbaoanh** [plotly/dash#965]
**Dash version**
```
dash                 1.1.1
dash-core-components 1.1.1
dash-daq             0.1.7
dash-html-components 1.0.0
dash-renderer        1.0.0
dash-table           4.1.0
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: Redhat 7.0
    - Browser: chrome
    - Version: 70.0.3538.67

**Describe the bug**

When i used tooltip_data in data_table without using dev tool UI, it worked as expected. One day, i make dev tool UI enable via `app.run_server(host='0.0.0.0', port=5000, debug=True, dev_tools_ui=True, dev_tools_props_check=False)`, there're error like `Invalid argument: tooltip_data[0].col_name`.

**Comment by alexcjohnson** [comment]
This probably means `col_name` isn't doing what you expected. When `debug` mode is enabled (which enables `dev_tools_ui` anyway by default).

That said I wasn't able to reproduce your error with a quick guess as to what your code might have looked like. The best way to handle a situation like this would be to start a new discussion at https://community.plot.ly/c/dash and, along with the version info you already provided here, include a complete simplified code sample that someone who has Dash installed could run, and the complete error traceback.

I'll also note dash is up to v1.4, probably worth updating before asking more questions in case your issue has been addressed in the meantime.

I'm going to close this now, we can reopen or open a new issue in the table repo if the discussion in the community forum determines that there really is a bug.
