### ISSUE TITLE
selectedData does not update on deselection

### ISSUE THREAD

**Issue by pmbaumgartner** [plotly/dash#97]
`selectedData` does not update when data that is selected through the lasso or rectangular selection tool is deselected. You can view this behavior from the crossfiltering example in the docs: https://plot.ly/dash/getting-started-part-2#basic-interactions

This has an impact on building dashboards that use crossfiltering to summarize information for a set of points. For example, I have a chart that by default aggregates information for all points in a scatterplot if `selectedData` is empty. Once `selectedData` is not empty, the aggregating charts then summarize info for the selected data. If I deselect points, I want the charts to return to aggregating for all data points. Currently, in order to get this behavior, I would have to reselect all points in the plot with the select tools.

Replication:
1. Select a set of points using lasso or rectangular selection
2. Deselect points by double-clicking elsewhere in the plot

![data-deselect](https://user-images.githubusercontent.com/5107405/28528828-d475992a-705c-11e7-8dab-d583e38291cc.gif)

---
I have also [asked on the community forums](https://community.plot.ly/t/deselect-event-why-is-selecteddata-persisted-after-deselection/5032/1) if this is the expected behavior.

**Comment by chriddyp** [comment]
Seems like this is a bug 👍 . Thanks for reporting! Will work on a fix this week.

**Comment by chriddyp** [comment]
@pmbaumgartner - Returning
```
{
    "points": []
}
```

or

```
None
```

I think that `points: []` makes more sense here. However, it will be impossible to distinguish between the "unselect" case and the "selected no points" case.

**Comment by chriddyp** [comment]
It looks like plotly.js doesn't distinguish between "single-click" and "double-click to remove selection box" in the `selected` event. We'll need `plotly.js` to update this event data before we patch this.

**Comment by chriddyp** [comment]
> I think that `points: []` makes more sense here. 

Actually, I don't think this makes sense. The Dash developer needs to know if there is a persistent selection box or not. If there is a persistent selection box but no data, then the data structure will be `{points: []}`. However, if there is _no_ selection box then the developer needs to know that so they can e.g. redraw all of the original points.

Maybe reset to `None` makes the most sense here then. That's the initial value when there is no selection box.

This is actually sort of related to https://github.com/plotly/plotly.js/issues/1848

**Comment by pmbaumgartner** [comment]
re: return value - I think it depends on what you want the pattern to be for when data is selected to crossfilter.

A change that would be consistent with the pattern of `if selectedData:` or `if selectedData is None:` would be returning `None`. ([ex](https://github.com/plotly/dash-oil-and-gas-demo/blob/master/app.py#L354)), 

The other pattern is `if (selectedData or len(selectedData['points']) == 0):` which would be consistent with returning `points: []` ([ex](https://github.com/plotly/dash-uber-rides-demo/blob/master/app.py#L191))

**Comment by chriddyp** [comment]
Partial fix here: https://github.com/plotly/dash-core-components/pull/40

**Comment by chriddyp** [comment]
Fixed! see plotly/dash-core-components#40. Upgrade with `pip install dash-core-components==0.7.1`

**Comment by pmbaumgartner** [comment]
@chriddyp not sure if this is related to the change, but I'm getting `Error loading dependencies` on my app after the upgrade. It's also happening with the docs @ https://plot.ly/products/dash/

![screen shot 2017-07-24 at 6 12 07 pm](https://user-images.githubusercontent.com/5107405/28547182-b3e4caa2-709b-11e7-8fe8-a8ee7d4180dd.png)

**Comment by pmbaumgartner** [comment]
Guessing the CDN needs to be updated?

![screen shot 2017-07-24 at 6 24 36 pm](https://user-images.githubusercontent.com/5107405/28547590-8ee803ac-709d-11e7-9e5f-f64bebcd5849.png)

**Comment by chriddyp** [comment]
Yeah, forgot to update the CDN :man_facepalming: Updated now, should be good to go. Thanks for reporting!
