### ISSUE TITLE
How to get rid of Callback errors pop up in the top right hand corner of dashboard?

### ISSUE THREAD

**Issue by rdslkfjasdf** [plotly/dash#970]
It's blocking important parts of the dash and I need to get rid of it.
I tried

app.config.suppress_callback_exceptions = True

but it didn't seem to do anything

**Comment by alexcjohnson** [comment]
Open the debug menu `<>` and click the Errors icon, they'll disappear. Or just run the server with `debug=False`.

But it's not a good idea to allow uncaught errors to make it that far, it can leave the app in an inconsistent state that users can't recover from. If you intend for the app to not receive a new result from that callback, use `dash.exceptions.PreventUpdate` or `dash.no_update` instead.
