### ISSUE TITLE
[Feature Request] Organize dash and components in a single namespace

### ISSUE THREAD

**Issue by jjaraalm** [plotly/dash#971]
Right now the standard approach to loading core components is

```python
import dash
import dash_core_components as dcc
import dash_html_components as html
```

but the component namespaces feel very long and un-pythonic to me. It would be nice if we could have everything linked into the `dash` namespace so the imports would be

```python
import dash
import dash.components.core as dcc
import dash.components.html as html
```

Virtual namespaces would be the most elegant but I think it would be a breaking change since `import dash` would have to change to something like `import dash.dash`. Alternatively, we could add a `dash.components` module that tries to load all the component modules from the existing long module names and gracefully ignores missing ones.

**Comment by chriddyp** [comment]
Thanks for the issue! We've talked about this in the past and the main issue was what to do about 3rd party components. 3rd party components are a really central feature of Dash and should be able to be published independently of Dash.

With 3rd party components, then the community would need to learn two different import patterns:
```
import dash.components.core as dcc
```

_and_ e.g.

```
import dash_table
```

With this, I believe it would become difficult for end-users to know _when_ a component is part of the `dash.` namespace vs independent. They might try to do things like:
```
import dash.components.dash_table as data_table
```
which wouldn't work (and is more verbose than the original).

So, in the spirit of uniformity and consistency, I'm still in favor of keeping them separate.

**Comment by jjaraalm** [comment]
That makes sense, but is also another argument for virtual namespaces!

I wonder if you can have only one package have a real `dash` namespace (to
preserve `import dash`) and have the others use dash as a virtual
namespace? I've never tried it but my feeling is it would lead to
install-order issues. That is,

```
pip install dash
pip install dash_core_components
```

would not be the same as

```
pip install dash_core_components
pip install dash
```

If I get a chance I might try experimenting, but my guess is that a
breaking change would be necessary to reorganize everything with virtual
namespaces.
