### ISSUE TITLE
[BUG] Dash 1.5.1, 1.4.1, and 1.4.0 breaks horizontal stacked bar chart from 1.3.1 (missing 2 of the three columns, but the data is visible with hover)

### ISSUE THREAD

**Issue by davidghill** [plotly/dash#972]
**Describe your context**
```
Dash Version 1.4.1
Dash DataTable Version 4.4.1
Dash Core Components Version 1.3.1
Dash HTML Components Version 1.0.1
Pandas Version 0.25.2
Numpy Version 1.16.5
Plotly Version 4.1.0
cx_Oracle Version 18.3.0.0.0

```
-  if frontend related, tell us your Browser, Version and OS

    - OS: [Windows 10 Pro Version 1903 OS Build 18362.418]
    - Browser [Chrome]
    - Version [77.0.3865.120 (Official Build) (64-bit)]

**Describe the bug**

Horizontal stacked bar chart is missing two columns (no changes to the code that generates the chart).  I upgraded to the latest Dash versions to see if that might clear up the issue, but it remains.  Downgrading to 1.3.1 fixes the issue.  The hover data is still available if you hover over where the column should be in 1.4.0 but the bars are invisible.

**Expected behavior**

There should be 3 stacked bars in each section of the chart (6 total)

**Screenshots**
Dash 1.4.0 Screen Shot
![dash 1 4 0](https://user-images.githubusercontent.com/45153878/67432288-05b24b80-f5b4-11e9-961c-5745f66efe14.PNG)

Dash 1.3.1 Screen Shot
![dash 1 3 1](https://user-images.githubusercontent.com/45153878/67432117-a18f8780-f5b3-11e9-8344-b926f5bad26f.PNG)

** Sample Data for code below **

    UFEZONEMETERTYPEMETHOD                      METERTYPEMETHOD  KWH_PERCENT  SPCOUNT_PERCENT     UFEZONE         TOTAL   SPCOUNT  DATAAGGRUNID                     COLOR                                           KWHTEXT                                        COUNTTEXT
    8 | UFE ZONE 1 | Interval | Actual        Interval | Actual     0.813930         0.696212  UFE ZONE 1  5.341270e+07  696212.0             8  rgba( 38,  24,  74, 0.7)    Interval | Actual | kWh<br>81.39% (53,412,700)    Interval | Actual | Count<br>69.62% (696,212)
    8 | UFE ZONE 2 | Interval | Actual        Interval | Actual     0.733376         0.627906  UFE ZONE 2  2.408597e+07  313953.0             8  rgba( 38,  24,  74, 0.7)    Interval | Actual | kWh<br>73.34% (24,085,966)    Interval | Actual | Count<br>62.79% (313,953)
    8 | UFE ZONE 3 | Interval | Actual        Interval | Actual     0.830630         0.709090  UFE ZONE 3  2.720407e+07  354545.0             8  rgba( 38,  24,  74, 0.7)    Interval | Actual | kWh<br>83.06% (27,204,071)    Interval | Actual | Count<br>70.91% (354,545)
    8 | UFE ZONE 1 | Interval | Default      Interval | Default     0.009403         0.010274  UFE ZONE 1  6.170505e+05   10274.0             8  rgba(122, 120, 168, 0.7)       Interval | Default | kWh<br>0.94% (617,051)     Interval | Default | Count<br>1.03% (10,274)
    8 | UFE ZONE 2 | Interval | Default      Interval | Default     0.015948         0.017442  UFE ZONE 2  5.237783e+05    8721.0             8  rgba(122, 120, 168, 0.7)       Interval | Default | kWh<br>1.59% (523,778)      Interval | Default | Count<br>1.74% (8,721)
    8 | UFE ZONE 3 | Interval | Default      Interval | Default     0.011537         0.013636  UFE ZONE 3  3.778442e+05    6818.0             8  rgba(122, 120, 168, 0.7)       Interval | Default | kWh<br>1.15% (377,844)      Interval | Default | Count<br>1.36% (6,818)
    8 | UFE ZONE 1 | Interval | Estimated  Interval | Estimated     0.050852         0.043514  UFE ZONE 1  3.337088e+06   43514.0             8  rgba( 71,  58, 131, 0.7)   Interval | Estimated | kWh<br>5.09% (3,337,088)   Interval | Estimated | Count<br>4.35% (43,514)
    8 | UFE ZONE 2 | Interval | Estimated  Interval | Estimated     0.122295         0.104652  UFE ZONE 2  4.016496e+06   52326.0             8  rgba( 71,  58, 131, 0.7)  Interval | Estimated | kWh<br>12.23% (4,016,496)  Interval | Estimated | Count<br>10.47% (52,326)
    8 | UFE ZONE 3 | Interval | Estimated  Interval | Estimated     0.031962         0.027274  UFE ZONE 3  1.046802e+06   13637.0             8  rgba( 71,  58, 131, 0.7)   Interval | Estimated | kWh<br>3.20% (1,046,802)   Interval | Estimated | Count<br>2.73% (13,637)
    8 | UFE ZONE 1 | Scalar | Actual            Scalar | Actual     0.109009         0.221990  UFE ZONE 1  7.153512e+06  221990.0             8  rgba( 74,  24,  38, 0.7)       Scalar | Actual | kWh<br>10.90% (7,153,512)      Scalar | Actual | Count<br>22.20% (221,990)
    8 | UFE ZONE 2 | Scalar | Actual            Scalar | Actual     0.115099         0.229822  UFE ZONE 2  3.780161e+06  114911.0             8  rgba( 74,  24,  38, 0.7)       Scalar | Actual | kWh<br>11.51% (3,780,161)      Scalar | Actual | Count<br>22.98% (114,911)
    8 | UFE ZONE 3 | Scalar | Actual            Scalar | Actual     0.101945         0.209302  UFE ZONE 3  3.338803e+06  104651.0             8  rgba( 74,  24,  38, 0.7)       Scalar | Actual | kWh<br>10.19% (3,338,803)      Scalar | Actual | Count<br>20.93% (104,651)
    8 | UFE ZONE 1 | Scalar | Default          Scalar | Default     0.005320         0.005813  UFE ZONE 1  3.491353e+05    5813.0             8  rgba(168, 120, 122, 0.7)         Scalar | Default | kWh<br>0.53% (349,135)        Scalar | Default | Count<br>0.58% (5,813)
    8 | UFE ZONE 2 | Scalar | Default          Scalar | Default     0.005316         0.005814  UFE ZONE 2  1.745840e+05    2907.0             8  rgba(168, 120, 122, 0.7)         Scalar | Default | kWh<br>0.53% (174,584)        Scalar | Default | Count<br>0.58% (2,907)
    8 | UFE ZONE 3 | Scalar | Default          Scalar | Default     0.005331         0.005814  UFE ZONE 3  1.745916e+05    2907.0             8  rgba(168, 120, 122, 0.7)         Scalar | Default | kWh<br>0.53% (174,592)        Scalar | Default | Count<br>0.58% (2,907)
    8 | UFE ZONE 1 | Scalar | Estimated      Scalar | Estimated     0.011485         0.022197  UFE ZONE 1  7.537093e+05   22197.0             8  rgba(131,  58,  71, 0.7)       Scalar | Estimated | kWh<br>1.15% (753,709)     Scalar | Estimated | Count<br>2.22% (22,197)
    8 | UFE ZONE 2 | Scalar | Estimated      Scalar | Estimated     0.007966         0.014364  UFE ZONE 2  2.616191e+05    7182.0             8  rgba(131,  58,  71, 0.7)       Scalar | Estimated | kWh<br>0.80% (261,619)      Scalar | Estimated | Count<br>1.44% (7,182)
    8 | UFE ZONE 3 | Scalar | Estimated      Scalar | Estimated     0.018596         0.034884  UFE ZONE 3  6.090361e+05   17442.0             8  rgba(131,  58,  71, 0.7)       Scalar | Estimated | kWh<br>1.86% (609,036)     Scalar | Estimated | Count<br>3.49% (17,442)
** code snippet **

    # <<< stuff to generate data >>>

                    # graph it
                    blank_trace = go.Bar(
                            x=[0, 0,0,0,0,0,],
                            y=['']*6,
                            #ids=metertypemethod['METERTYPEMETHOD'],
                            #text=['Interval | Actual    ','Interval | Default    ','Interval | Estimated    ','Scalar | Actual    ','Scalar | Default    ','Scalar | Estimated    '],
                            #textposition = 'inside',
                            marker=dict(color=list(colors_dic.values()),
                                        line=dict(color='rgb(255, 255, 255)',
                                                  width=1),
                                                 ),
                            orientation = 'h',
                            width = 0.1,
                            hoverinfo = 'none',
                    #        offset = .005,
                            )
                    
                    kwh_trace = go.Bar(
                            x=metertypemethod['KWH_PERCENT'].map('{:,.1%}'.format),
                    #        y='Data Agg Run ID ' + metertypemethod['DATAAGGRUNID'].astype(str) + '<br>' + metertypemethod['UFEZONE'].map(ufe_dic) + '<br>Total kWh',
                            y=metertypemethod['UFEZONE'].map(ufe_dic) + '<br>Total kWh',
                            ids=metertypemethod['METERTYPEMETHOD'],
                            text=metertypemethod['KWHTEXT'],
                            textposition = 'inside',
                            marker=dict(color=metertypemethod['COLOR'],
                                        line=dict(color='rgb(255, 255, 255)',
                                                  width=1)),
                            orientation = 'h',
                            width = 1.0,
                            hoverinfo = 'text',
                            )
                    
                    count_trace = go.Bar(
                            x=metertypemethod['SPCOUNT_PERCENT'].map('{:,.1%}'.format),
                    #        y='Data Agg Run ID ' + metertypemethod['DATAAGGRUNID'].astype(str) + '<br>' + metertypemethod['UFEZONE'].map(ufe_dic) + '<br>Count',
                            y=metertypemethod['UFEZONE'].map(ufe_dic) + '<br>Count',
                            ids=metertypemethod['METERTYPEMETHOD'],
                            text=metertypemethod['COUNTTEXT'],
                            textposition = 'inside',
                            marker=dict(color=metertypemethod['COLOR'],
                                        line=dict(color='rgb(255, 255, 255)',
                                                  width=1)),
                            orientation = 'h',
                            width = 1.0,
                            hoverinfo = 'text',
                            )
                    
                    kwh_layout = go.Layout(
                            barmode='stack',
                            title='Total Kwh and Count by Meter Type and Method',
                            yaxis= dict(side='left',
                                        hoverformat=',.0f',
                                        tickformat=',.3s',
                                        automargin=True,),
                            xaxis = dict(nticks = 10,
                                         tick0 = 0,
                                         dtick = 10,
                                         tickangle = -45),
                            showlegend=False,
                            hovermode = 'closest',
                            hoverlabel = dict(namelength = -1,),
                            height = 500,
                            paper_bgcolor = 'rgba(127, 127, 177, .2)',
                            plot_bgcolor = 'rgba(127, 127, 177, .0)',
                            legend_bgcolor = 'rgba(127, 127, 177, .0)',
                            )

**Comment by alexcjohnson** [comment]
@davidghill thanks for the report. Dash 1.4 brought with it [Plotly.js 1.50](https://github.com/plotly/plotly.js/releases/tag/v1.50.0), which among other things added support for bar transitions. What's happening is you have multiple bars in the same trace with the same value in `ids`. The `ids` field is intended to identify consistent objects, mainly for object constancy during animation / transitions, so when we see duplicates we apparently collapse them into one object. I'll open an issue in Plotly.js to do something less confusing with duplicate `ids`, but I think the solution is clear, either don't use `ids` at all or ensure the values are unique within each trace.

**Comment by davidghill** [comment]
Thanks! I removed the ids and it works again.

David Hill
President
Entegrity LLC
978.239.8020
www.entegrityllc.com
