### ISSUE TITLE
[BUG] Plot name doesn't override pandas series name

### ISSUE THREAD

**Issue by Zylatis** [plotly/dash#975]
**Packages**
```
dash                          1.4.1                 
dash-bootstrap-components     0.6.3                 
dash-core-components          1.3.1                 
dash-html-components          1.0.1                 
dash-renderer                 1.1.2                 
dash-table                    4.4.1 
```

**Describe the bug**

I have the following code to generate a cumulative financial plot from a dataframe 
```python
def cumulative_netpos(subset):
	trace = []
	diff_cs = subset['diff'].cumsum()
	charges_cs = subset['extra_charges_net'].cumsum()
	net_pos_cs = diff_cs - charges_cs

	trace.append(go.Scatter(x=subset["create_date"], y=diff_cs, name='Diff', mode='lines',
                                marker={'size': 8, "opacity": 0.6, "line": {'width': 0.5}} ))
	trace.append(go.Scatter(x=subset["create_date"], y=charges_cs, name='Additional charges', mode='lines',
                                marker={'size': 8, "opacity": 0.6, "line": {'width': 0.5}} ))
	trace.append(go.Scatter(x=subset["create_date"], y=net_pos_cs, name='Net position', mode='lines',
                                marker={'size': 8, "opacity": 0.6, "line": {'width': 0.5}} ))
```

**Expected behavior**

I would expect that because i have given the go.Scatter() the name keyword for Net Position that this would override whatever series name is given in the net_pos_cs (this ends up picking up a meaningless name i would like to override through it's definition as the difference between two series')

I can fix this by instead passing net_pos_cs.values and then it picks up the name from go.Scatter, but I would assume (maybe incorrectly) this should always override the name given in the pandas series?

Thanks,
Z

**Comment by alexcjohnson** [comment]
When you say "this ends up picking up a meaningless name" what do you mean? Can you show a screenshot of the undesirable behavior?

Also, as the issue seems to relate to `plotly.py`, what is the version of that package you're using?

**Comment by Zylatis** [comment]
Apologies, I should have included more information. What i mean is the object ```net_pos_cs``` is a series and it inherits the name of only one of the constituent series' in the difference calculation (i think in this case 'extra_charges_net'). 

Were i presenting this in a table i'd need to either rename it or do something like this
```python
df = pd.DataFrame()
df['Diff'] = subset['diff'].cumsum()
df['Additional charges'] = subset['extra_charges_net'].cumsum()
df['Net position'] = diff_cs - charges_cs
```

and then i could happily feed the df['Net position'] into the plotly plot and it would be fine, but i was hoping to be able to have the final stop on the journey, i.e. the plot itself, override everything that comes before it in terms of names so i don't need to do this. I can just slice and dice however i want and then only worry about enforcing names at the very end. To me this makes sense right: the plot should have complete control over the plot title, it shouldn't care what series was fed into it.

I am using plotly 3.10.0

**Comment by alexcjohnson** [comment]
I'm still not clear where you're seeing this name instead of what you intended. Are you saying `name='Net position'` isn't showing up, and instead you're seeing `extra_charges_net` as the name of this trace, in the legend and hover labels?

If that's what you mean, my guess is this is being done implicitly by plotly.py. We could verify that by doing something like:
```py
trace = go.Scatter(x=subset["create_date"], y=net_pos_cs, name='Net position')
print(json.loads(trace.to_plotly_json())['name'])
```

I would expect the name you provided to win out (`Net position`), but if instead you see `extra_charges_net` we should move this issue over to https://github.com/plotly/plotly.py

If you see `'Net position'` from the code ^^ but on the actual displayed plot there's some other trace name, then we'll have to investigate further.

**Comment by Zylatis** [comment]
Hmm so rather worryingly (because I don't understand why) it now works. I apologise as I was a bit sloppy and have done some package upgrades lately which may have affected it, or possibly i was just being stupid before (I did the grep dash and all those are the same version).

Apologies for wasting time and thanks for the help!

**Comment by alexcjohnson** [comment]
No problem, thanks for the update!
