### ISSUE TITLE
Dash application login support

### ISSUE THREAD

**Issue by crazycodingcat** [plotly/dash#98]
Hi,

I'd like to know if there any plans to support user authentication in a Dash application? 

I'm trying to add a login page for my dash application. After user enters the user name and password and clicks the 'login' button, is it possible to do a page redirect to the main page? I suppose an alternative is to display a link and ask users to click it, but that's not very user-friendly...

**Comment by crazycodingcat** [comment]
Just realized there is another problem.. How do we generate page content dynamically? e.g. if user is not logged in, display certain content, and display something else if user is logged in. 

I tried the following but it does not work:
```python
def require_login(func):
    def func_wrapper():
        if LOGGED_IN:
            return func()
        else:
            return index_page
    return func_wrapper

@require_login
def render_page():
    return html.Div([
        html.H1('This is my amazing page!')
    ])
```
Is it possible to use extensions such as `Flask-Login` together with Dash?

**Comment by chriddyp** [comment]
It's not safe to provide authentication solely through the user interface - the underlying HTTP routes that Dash provides need to be protected as well.

I have written a preliminary version of a Dash Auth package here: https://github.com/plotly/dash-auth. Here are the docs: https://plot.ly/dash/authentication
