### ISSUE TITLE
[BUG] Example of multi-app documentation not working

### ISSUE THREAD

**Issue by arnyeinstein** [plotly/dash#989]
I tried to run the three examples on https://dash.plot.ly/urls for a multi-page dashboard. Eve of them produced a 404 page. 

-  replace the result of `pip list | grep dash` below
```
dash                 1.5.1
dash-core-components 1.4.0
dash-html-components 1.0.1
dash-renderer        1.2.0
dash-table           4.5.0
```
-  if frontend related, tell us your Browser, Version and OS
Chrome/Windows 10 x64

**Describe the bug**

I tried to run the three examples on https://dash.plot.ly/urls for a multi-page dashboard. Eve of them produced a 404 page. 

**Expected behavior**
App1 showing up. 

There is a discussion in 2017 on this topic, but I didn't get the point. However, it is frustrating if you try to run an example from the documentation and it does not as described.

Cheers
Renger

**Comment by ned2** [comment]
Can you describe the method you're using to run the app?

(Eg the development server or with a wsgi server etc)

**Comment by arnyeinstein** [comment]
C:\WPy36\python-3.6.8.amd64\python.exe D:/Projects/2016_Nexus/Trunk/Code/Nexus_Platform/Homepage/dashboard/index.py
Running on http://127.0.0.1:8050/
Debugger PIN: 027-338-446
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
Running on http://127.0.0.1:8050/
Debugger PIN: 788-409-640

**Comment by arnyeinstein** [comment]
I resolved the issue by changing the code of display_page as follows:
`def display_page(pathname):
    if pathname == '/':
        return app1.layout
    elif pathname == '/apps/app2':
        return app2.layout
    elif pathname == '/apps/app1':
        return app1.layout
    else:
        return '404'`
Others suggested just changing the first line as shown and not adding the additional elif, but that solution doesn't allow you to jump back from app2 to app1.

Perhaps this solution might help in finding what is the problem with the example shown in the documentation.

**Comment by jlmarrugom** [comment]
It seems like the layout for the '/' index is missing. You can add one in the layouts page and referencing it like Layout0.

**Comment by T4rk1n** [comment]
We no longer have those multi app examples in the documentation and instead we recommend to now use the builtin multi page support we added.
